### ISSUE TITLE
Installation issue - composer ext-grpc

### ISSUE THREAD

**Issue by willatkinsnikta** [googleads/google-ads-php#10]
I've just started to look at implementing the Google Ads Beta library, came up against a composer issue at step 3 "Run composer install at the command prompt. This will install all dependencies needed for using the library and running examples."

Mac OS X

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-grpc * is missing from your system. Install or enable PHP's grpc extension.

I'm going to follow this - https://cloud.google.com/php/grpc (initially on Mac, then Cent os)

Is this the best way forward, or is there an easier way :) ?

Thanks

**Comment by fiboknacky** [comment]
Hello!

Yep, I think the instructions are pretty much similar to [this page](https://grpc.io/docs/quickstart/php.html).
That's the one you can use to install gRPC for PHP.

Best,
Knack

**Comment by willatkinsnikta** [comment]
Super thanks for that, I managed to get it up and running on my Mac following! Hopefully also relatively straight forward on cent os!

**Comment by chiragvels** [comment]
hi @fiboknacky ,

I am also facing same issue but I am not able to connect to pear.php.net 

 curl -O https://pear.php.net/go-pear.phar
 sudo php -d detect_unicode=0 go-pear.phar

Thanks,

**Comment by fiboknacky** [comment]
Hello Chirag,

> I am also facing same issue but I am not able to connect to pear.php.net

What's the error message you've got?

**Comment by chiragvels** [comment]
Problem 1
    - The requested PHP extension ext-grpc * is missing from your system. Install or enable PHP's grpc extension.

**Comment by fiboknacky** [comment]
I've faced with that error too.
Probably it's a transient error on PEAR site.
Can you wait for some time and try again please?

**Comment by chiragvels** [comment]
I am waiting from last 2 days and I have replied after that only.

But I can still wait for same. I thought if have some other way for Mac OS High Sierra.

Thanks

**Comment by fiboknacky** [comment]
In fact, PEAR server is now down because of the security breach.
Can you try HomeBrew instead like [this post](https://superuser.com/a/1312286)?

**Comment by chiragvels** [comment]
Hello @fiboknacky ,

I have disable csrutil under mac and I can able to install now.
In my case fortunately my system has PECL already installed, which I came to know by this "which -a pecl" 

But this should be simple and should be install without this issue.

Thanks,

**Comment by ajosephjohnson** [comment]
I am still facing this issue. Running php7.1 on docker. 

"which -a pecl" on the same command line returns "/usr/bin/pecl" but seems like composer does not recognize that is installed

**Comment by fiboknacky** [comment]
@ajosephjohnson  Could you post a new issue and describe your issue there please?

**Comment by ajosephjohnson** [comment]
I didn't have the extension in the ini file file turned on, so it's working
now. Thanks for your follow up!
