### ISSUE TITLE
Use of Lib version v16 with Legacy Methods

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#1009]
I am exploring v16 of the library and going to upgrade my code from v14 to v16.
I have question that when I use the following code It is still asking me to use GAPIC2 but i specified not to use GAPIC2.

$googleAdsClient = (new GoogleAdsClientBuilder())
            ->fromFile()
            ->withOAuth2Credential($oAuth2Credential)
            ->usingGapicV2Source(false)
            ->build();

So it is compulsory to use GAPIC2 with v16 of the Library?

`Error:  Google\Ads\GoogleAds\V16\Services\Client\GoogleAdsServiceClient::search(): Argument #1 ($request) must be of type Google\Ads\GoogleAds\V16\Services\SearchGoogleAdsRequest, string given, called in GoogleAdsReportGapicTest.php`

**Comment by fiboknacky** [comment]
Yes, you can refer to [this guide](https://developers.google.com/google-ads/api/docs/client-libs/php/gapic) how to use GAPIC v2.

**Comment by chiragvels** [comment]
Yes, I followed same guide.
I can able to get data using GAPIC v2 using v16, but Not able to use GAPIC v1 with v16 despite usingGapicV2Source to false.

So It is GAPIC v2 only supported?
Thanks,

**Comment by fiboknacky** [comment]
As described in #934, the client library released this year will support only GAPIC v2 now, so you cannot set it back to use GAPIC v1 anymore. For v16, only GAPIC v2 classes are included.

I'm sorry for this confusion, but the [ConfigurationTrait](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/Lib/ConfigurationTrait.php) is shared among versions, so we cannot just remove the `usingGapicV2Source` property immediately until we sunset v15 later this year.

**Comment by fiboknacky** [comment]
I believe this should answer your question, so I'm closing this issue now.
