### ISSUE TITLE
ResourceNames::forCustomerClient function disappeared

### ISSUE THREAD

**Issue by VladymyrKarpov** [googleads/google-ads-php#1015]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
Could you please help me. I'm trying to construct resource name for client customer which is: The resource name of the customer client. CustomerClient resource names have the form: customers/{customer_id}/customerClients/{client_customer_id}. On version 19.2.0 there was a function in ResourceNames.php -  ResourceNames::forCustomerClient($managerAccount->getId(), $clientId);
Now on version 22.1.0 there is no such function. How can I achieve that? Thanks

**Comment by VladymyrKarpov** [comment]
Sure! I use it to search for particular customer assigned to manager account:
```
$googleAdsClient = (new GoogleAdsClientBuilder())
						->fromFile($settingsPass)
						->withOAuth2Credential($oAuth2Credential)
						->withLoginCustomerId($managerAccount->getId())
						->build();
					$customerResourceName = ResourceNames::forCustomerClient($managerAccount->getId(), $clientId);
 					$query = "SELECT customer_client.id, customer_client.currency_code, customer_client.status, customer_client.descriptive_name FROM customer_client WHERE customer_client.resource_name = '$customerResourceName' AND customer_client.status = 'ENABLED'";
					$response = $googleAdsServiceClient->searchStream($googleAdsClient->getLoginCustomerId(), $query);
					$customer = $response->iterateAllElements()->current();
```
At this point only way to get what I want is to glue strings. I was surprised because I used that method previously without any issues. Thanks

**Comment by VladymyrKarpov** [comment]
That is possible thanks. But I wonder why did that helper method just removed without any notifications. Thank you for help

**Comment by fiboknacky** [comment]
Sorry for that. It's due to the new source generation that we rely on. It'll generate the methods that are necessary for sending a mutate request to the API server.
