### ISSUE TITLE
Problem with conversion trackers and pagination

### ISSUE THREAD

**Issue by giorrrgio** [googleads/google-ads-php#102]
I'm working with `ConversionTrackerService`to get a list of the conversion actions associated to a customer. I'm doing the following request:

```
        $service = $this->services->get($this->session, ConversionTrackerService::class);
        $selector = new Selector();
        $selector->setFields([
                'Id',
            ])
            ->setPaging(0, 10));

        if (null !== $sortField) {
            $selector->setOrdering([new OrderBy($sortField, $sortOrder)]);
        }

        $pageResult = $this->statsTracker->tracedRun(function () use ($service, $selector) {
            return $service->get($selector);
        }, 'api', 'ConversionTrackerService.get');
```

With some customers it returns 0 results even if a bunch of conversion actions are configured, but if I remove the pagination it returns the expected number of results. 
With other accounts everything's fine. Do you have any hints to investigate further?
Thanks

**Comment by Raibaz** [comment]
Hi,

Looking at your code, your issue seems to be related to the old AdWords API client library. Can you please open the issue in [its repo](https://github.com/googleads/googleads-php-lib)?

**Comment by giorrrgio** [comment]
Ouch sorry, my fault
