### ISSUE TITLE
big bug!! your example returns error anyway!

### ISSUE THREAD

**Issue by devorel** [googleads/google-ads-php#1029]
https://github.com/googleads/google-ads-php/blob/3b876a88574a44652ad091da9c731267095b97ea/examples/Planning/GenerateForecastMetrics.php#L124

{ "message": "Request contains an invalid argument.", "code": 3, "status": "INVALID_ARGUMENT", "details": [ { "@type": "type.googleapis.com\/google.ads.googleads.v16.errors.GoogleAdsFailure", "errors": [ { "errorCode": { "keywordPlanIdeaError": "INVALID_VALUE" }, "message": "The input has an invalid value." } ], "requestId": "IEDc8kNrlpbKK3l4Xrt15g" } ] }

Client library and Google Ads API versions:

Client library version: v23.0.1
Google Ads API version: V16
Environment:

The PHP-FPM version: 8.3.

**Comment by fiboknacky** [comment]
What are the parameters you passed to the code examples?

**Comment by fiboknacky** [comment]
I cannot reproduce your error. It runs fine on my side. Since it's not a client-library issue, could you post on [the Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead? Thanks.

**Comment by devorel** [comment]
now it's works , i cannot explain why ?! maybe it because the account is new

**Comment by nocturnalfrog** [comment]
This is why: https://ads.google.com/status/publisher/incidents/Dgkp6kgKHeiuDaUXBa5Q
