### ISSUE TITLE
Fatal error: Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found

### ISSUE THREAD

**Issue by Wisoftsolution** [googleads/google-ads-php#103]
Fatal error: Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found in /home1/sajinair/public_html/wisoftsolutions.net/google-nets/examples/AdWords/v201809/BasicOperations/GetCampaigns.php on line 81

**Comment by fiboknacky** [comment]
Looks like you're using the [old library](https://github.com/googleads/googleads-php-lib/issues).
Please post your issue there.
