### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by devorel** [googleads/google-ads-php#1031]
https://github.com/googleads/google-ads-php/blob/7ff9c4685a037e59d15b1774cc972d27d07e7a8c/examples/Planning/GenerateForecastMetrics.php#L130

in the midnight , the system of google return an error. i think i because timezone server not comperable to timezone googleAds.
i think you have add a per test before you send the request.

my server tiime
 0 => 1717710591 //Thu Jun 06 2024 21:49:51 GMT+0000
  1 => "UTC"

**Comment by fiboknacky** [comment]
Could you elaborate more? Do you have request and response logs?
The time zone shouldn't be a problem here and it should be handled by the server. It'll treat your specified dates based on your account's time zone preferences.
