### ISSUE TITLE
bad argument in search method

### ISSUE THREAD

**Issue by psobhanlo** [googleads/google-ads-php#1036]
hi . i am clone form git LARAVEL EXAMPLE project and config ini file and install vendor package.

everything  well ok.
but when i do  report for the specified customer ID  
i exception in my app

```
TypeError
Google\Ads\GoogleAds\V17\Services\Client\GoogleAdsServiceClient::search(): Argument #1 ($request) must be of type Google\Ads\GoogleAds\V17\Services\SearchGoogleAdsRequest, string given, called in /../google-ads-php/examples/LaravelSampleApp/app/Http/Controllers/GoogleAdsApiController.php on line 149
```

**Comment by psobhanlo** [comment]
please change method search . for first params

`      SearchGoogleAdsRequest::build($customerId, $query) 
`
```
     $response = $googleAdsClient->getGoogleAdsServiceClient()->search(
            SearchGoogleAdsRequest::build($customerId, $query)
,
            [
                'pageSize' => $entriesPerPage,
                // Requests to return the total results count. This is necessary to
                // determine how many pages of results exist.
                'returnTotalResultsCount' => true,
                // The page token of the requested page is in the page token list because of the
                // processing done in the previous loop.
                'pageToken' => $pageTokens[$pageNo - 1]
            ]
        );
```

after change code err auth 400 

`Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response: { "error": "invalid_grant", "error_description": "Bad Request" }`

**Comment by fiboknacky** [comment]
Thanks for reporting. Will TAL as soon as I have bandwidth.

**Comment by psobhanlo** [comment]
after clone and install composer package when search camp id. 
![image](https://github.com/user-attachments/assets/5734c24e-ba15-42c7-9c96-59db7bcb92d6)

**Comment by psobhanlo** [comment]
When do you think this problem will be solved?

Can you describe the problem so that I can solve it myself

**Comment by fiboknacky** [comment]
I thought you could resolve this as you closed it already. 
From the error, it looks like you have a problem with configuring the OAuth tokens, could you post on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) and share your request and response logs?

**Comment by psobhanlo** [comment]
can you share google_ads_php.ini with me for test??
such as sandbox.
with test clientid or secret id o...
for test application??

my domin is [link](https://google-api.admoon.agency/)

**Comment by fiboknacky** [comment]
You can find sample `google_ads_php.ini` [here](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/google_ads_php.ini).

Unfortunately, we don't have test client ID and secret for users to test. You can check [this guide for getting started with the Google API console project](https://developers.google.com/google-ads/api/docs/get-started/oauth-cloud-project).
Visit [Test accounts ](https://developers.google.com/google-ads/api/docs/best-practices/test-accounts) for more information about how to create the test accounts.
If you have any questions about the Google Ads API in general, please contact the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
