### ISSUE TITLE
Fatal error: Trait "Google\Auth\MetricsTrait" not found in

### ISSUE THREAD

**Issue by Harshal-Sweply** [googleads/google-ads-php#1038]
The issue being encountered is a "Fatal error: Trait 'Google\Auth\MetricsTrait' not found" in the file /var/www/html/google-ads-api/vendor/google/auth/src/UpdateMetadataTrait.php on line 27. This error suggests that the MetricsTrait is missing or cannot be found within the specified Google Auth library path.
![image](https://github.com/user-attachments/assets/3e136546-224e-4c3b-86c1-78d14e648208)

**Comment by fiboknacky** [comment]
Since this is an issue of `google/auth`, please file [an issue](https://github.com/googleapis/google-auth-library-php/issues) there. Thanks.
