### ISSUE TITLE
Handle curl timeout error

### ISSUE THREAD

**Issue by ershovalexander** [googleads/google-ads-php#1046]
**Problem**
We are running Google Ads API in multiple concurrent threads.
Those threads create batch job requests, one for every account.
Starting recently, we started receiving the following exception
```
An error has occurred: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://googleads.googleapis.com/v16/customers/[customerId]/operations/[HASH]
```

Problem with the network connectivity, happens in only one out of ten threads.

We're using 'rest' transport and Google Ads API v16.
I looked through the documentation and haven't found how to set the curl timeout for the library.
And since it's the batch job creation phase, adding retry pattern (as recommended for some other jobs) is not a good option.

I understand that it's better to address the root cause (probably network connectivity issues) and we're working in this direction, but we need our app to handle all edge cases.

**Requests**

(1) How to better address this question (for example, change curl timeout via passing some additional parameter that isn't in the documentation)?

(2) Per this [link](https://developers.google.com/google-ads/api/docs/batch-processing/flow#error_handling), it's recommended to process the batchJob results. I see that [HASH] in url is base64-decoded string `customers/[customerId]/batchJobs/[batchJobId]`. Should we parse that from URL and try downloading status for batchJobId, and probably try downloading the results?

**Comment by fiboknacky** [comment]
Regarding curl timeout, could you please ask on [this repository](https://github.com/googleapis/gax-php/issues)? This library uses the classes of that repository to send a request, so the maintainer of the repository would probably can answer your question faster. 

As for 2), I'm not entirely sure what URL you mentioned, but to process the results, you should follow [this step](https://developers.google.com/google-ads/api/docs/batch-processing/flow#listresults).

**Comment by ershovalexander** [comment]
> Regarding curl timeout, could you please ask on [this repository](https://github.com/googleapis/gax-php/issues)? This library uses the classes of that repository to send a request, so the maintainer of the repository would probably can answer your question faster.
> 
> As for 2), I'm not entirely sure what URL you mentioned, but to process the results, you should follow [this step](https://developers.google.com/google-ads/api/docs/batch-processing/flow#listresults).

Hello, thank you
(1) I looked through code and it seems the error is coming from this line
https://github.com/guzzle/guzzle/blob/d281ed313b989f213357e3be1a179f02196ac99b/src/Handler/CurlFactory.php#L259

Seems it’s used in the library that you mentioned 
The question was if there is a way to pass the timeout there.
I found in past issues that your library allows to pass proxy, thought you have a way of passing another curl params.
Seems no((

(2) this is a question of how we can handle this error. If we call the library to create the batch job, then from deep down this curl error exception is thrown (example in original post), next step would be to create the BatchJobResult (after parsing batchJobId from error message i mentioned) and download the results.

But this is a very unreliable way to do this (if the error message is changed, for example).

Wanted to know the better way of doing this.

**Comment by fiboknacky** [comment]
> Seems it’s used in the library that you mentioned
The question was if there is a way to pass the timeout there.
I found in past issues that your library allows to pass proxy, thought you have a way of passing another curl params.
Seems no((

We can surely create a feature request to open a setting for that if necessary.
But first, we need to confirm if there is a way to pass the timeout to the classes in that library.

> (2) this is a question of how we can handle this error. If we call the library to create the batch job, then from deep down this curl error exception is thrown (example in original post), next step would be to create the BatchJobResult (after parsing batchJobId from error message i mentioned) and download the results.

I think that's the best way to do. You probably cannot check whether the failed result was caused by the CURL error or something else, but what you could do is to resend the operations whose [`BatchJobResult.status`](https://developers.google.com/google-ads/api/reference/rpc/v17/BatchJobResult#status)  contains errors.

**Comment by ershovalexander** [comment]
Ok, thank you
I think you answered my questions 
Appreciate your time!
