### ISSUE TITLE
mdanowar

### ISSUE THREAD

**Issue by drmdanowar** [googleads/google-ads-php#1053]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your client library and Google Ads API versions:**

* Client library version: `vX.Y.Z`

* Google Ads API version: `VX`

**Your environment:**

**Description of the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by fiboknacky** [comment]
Sounds like this is created by mistake. Please reopen this if you have more information about the reported issue.
