### ISSUE TITLE
Is PHP client library supported PHP8.4?

### ISSUE THREAD

**Issue by hashimoto-AJ** [googleads/google-ads-php#1054]
An error occurred while executing the Google ads API.
Check the attached log file for the error.
No error occurred in PHP 8.3.13.

Is PHP client library supported PHP8.4?

My emviroment
- Usering PHP client library version : 25.0.0(Google Ads API v18)
- Usering PHP version :  PHP8.4-rc3(on Docker Desktop Windows11)

[ERROR_Google_Ads_Lib_on_PHP8.4.txt](https://github.com/user-attachments/files/17639774/ERROR_Google_Ads_Lib_on_PHP8.4.txt)

**Comment by fiboknacky** [comment]
PHP 8.4 is still in RC, so this library (and many other dependencies that this library uses) doesn't support it yet.
