### ISSUE TITLE
Question about Setup

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#112]
Hi,  

How I can use this library with other composer base library? 
 
I am using other git library as well and composer base library like Google API PHP Client 2.0.  
I am asking this because composer.json is in google-ads-php folder which might not be suitable path for other library which will sit under vendor folder.  
This is some basic question but I am not able to do same.  

Thanks,

**Comment by Raibaz** [comment]
You can import this library as a dependency in the composer.json file of your own application by adding a line like this

    "googleads/google-ads-php": "v1.3.0"

In your "require" section.

This way, when you do `composer install` for your application, the google-ads-php library will be installed, along with other dependencies, in the vendor folder.
