### ISSUE TITLE
New audience: Customer list

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleads/google-ads-php#130]
Hello team, I need your help, I try to recreate the functionality of uploading the email list in the audience, but I do not see these options in the API. They can guide me or clarify where to start.

![image](https://user-images.githubusercontent.com/19626181/59709758-db9fe580-91dd-11e9-87cf-aeca2a3591ec.png)

**Comment by fiboknacky** [comment]
As this is a feature-related question, could you please post in [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thanks.
