### ISSUE TITLE
Warning in gax/version - file not found

### ISSUE THREAD

**Issue by dmachehin** [googleads/google-ads-php#136]
Source file:line `/home/xxx/xxx/vendor/google/gax/src/Version.php:59`
Msg: `file_get_contents(/home/xxx/xxx/vendor/googleads/google-ads-php/VERSION): failed to open stream: No such file or directory`

PHP: 7.2.19
googleads/google-ads-php: 1.4.1

**Comment by Raibaz** [comment]
Hi, can you please provide some more information on how to reproduce this?

When is this happening?

How did you install this library?

**Comment by dmachehin** [comment]
@Raibaz 

Use composer.

Example with notice (problem in error_handler):
```
<?php
require_once __DIR__.'/vendor/autoload.php';

set_error_handler(function ($num, $msg, $file, $line, $ctx) {
	echo "Error ({$num}) occurred in {$file}:{$line} - {$msg}"."\n";
}, error_reporting());

$oauth_credential = new \Google\Auth\FetchAuthTokenCache(
	new \Google\Auth\Credentials\UserRefreshCredentials('https://www.googleapis.com/auth/adwords', [
		'client_id' => 123,
		'client_secret' => 123,
		'refresh_token' => 123
	]),
	null,
	new \Google\Auth\Cache\MemoryCacheItemPool
);

$client = (new \Google\Ads\GoogleAds\Lib\V1\GoogleAdsClientBuilder())
	->withDeveloperToken(123)
	->withOAuth2Credential($oauth_credential)
	->build();

$client->getAccountBudgetServiceClient();
```

**Comment by Raibaz** [comment]
This actually looks like a bug in the gax-php library.

Can you please open the issue in [its repo](https://github.com/googleapis/gax-php)?
