### ISSUE TITLE
App Campaign

### ISSUE THREAD

**Issue by sergeykenshoo** [googleads/google-ads-php#137]
Hi,
I can create App Campaign with "app_campaign_setting" (app_id, app_store, bidding_strategy_goal_type), but when I want to receive a list with "campaign.app_campaign_setting.app_id"

```
$query = 'SELECT campaign.id, campaign.app_campaign_setting.app_id FROM campaign WHERE campaign.id = 1532173601';
$response = $googleAdsServiceClient->search($customerId, $query, ['pageSize' => PAGE_SIZE]);
```

Got error:
ERROR 16384 Google\Ads\GoogleAds\V1\Resources\Campaign_AppCampaignSetting is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V1\Resources\Campaign\AppCampaignSetting instead /usr/local/gittst/zelda/module/googleads/src/Google/Ads/GoogleAds/V1/Resources/Campaign_AppCampaignSetting.php at line 15

**Comment by fiboknacky** [comment]
Can you share the whole script including those lines coming after getting a response?

**Comment by sergeykenshoo** [comment]
> Can you share the whole script including those lines coming after getting a response?

Code:

```
...
$googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();

$query = 'SELECT campaign.id, campaign.app_campaign_setting.app_id FROM campaign WHERE campaign.id = 1532173601 ';

$response = $googleAdsServiceClient->search($customerId, $query, ['pageSize' => PAGE_SIZE]);

foreach ($response->iterateAllElements() as $googleAdsRow) {
/** @var GoogleAdsRow $googleAdsRow */
            printf(
                "Campaign with ID %d, name '%s', App id '%s' was found.%s",
                $googleAdsRow->getCampaign()->getId()->getValue(),
                $googleAdsRow->getCampaign()->getName()->getValue(),
                $googleAdsRow->getCampaign()->getAppCampaignSetting()->getAppIdValue(),
                PHP_EOL
            );
}
```

But without foreach same error

**Comment by sergeykenshoo** [comment]
![Selection_026](https://user-images.githubusercontent.com/46655178/60077897-99255e00-9733-11e9-82ae-3dc14d46a427.png)

Call stack

**Comment by sergeykenshoo** [comment]
Same with campaign.selective_optimization.conversion_actions

SELECT campaign.id, campaign.selective_optimization.conversion_action FROM campaign WHERE campaign.id = 1532173601

ERROR 16384 Google\Ads\GoogleAds\V1\Resources\Campaign_SelectiveOptimization is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V1\Resources\Campaign\SelectiveOptimization instead /usr/local/gittst/zelda/module/googleads/src/Google/Ads/GoogleAds/V1/Resources/Campaign_SelectiveOptimization.php at line 15


![Selection_027](https://user-images.githubusercontent.com/46655178/60080332-5ca83100-9738-11e9-864e-f0527bf50fbc.png)

**Comment by fiboknacky** [comment]
Looks like it's somehow deserialized into a deprecated class, instead of the new class.
Do you also have `Google\Ads\GoogleAds\V1\Resources\Campaign\SelectiveOptimization` in your directories?

And what client library version are you using?

**Comment by sergeykenshoo** [comment]
yes i have /src/Google/Ads/GoogleAds/V1/Resources/Campaign/SelectiveOptimization.php

and I can "use Google\Ads\GoogleAds\V1\Resources\Campaign\SelectiveOptimization;" when I create new Campaign.

version 1.4.1

**Comment by fiboknacky** [comment]
I cannot reproduce this issue on my machine. 
Could you please remove any dependencies that this library depends on (like, `google/gax-php`) and try doing `composer update`?

**Comment by sergeykenshoo** [comment]
I fix error by installing php extension:

`sudo pecl install protobuf`

now it works

**Comment by fiboknacky** [comment]
Glad to hear that.
My guess is that your composer definition would rely on the PHP extension version of the protobuf library, but somehow its version wasn't compatible or outdated.
Once you install the native extension of that library, it works.

We're working on fixing this ambiguity in our composer.json file soon.
