### ISSUE TITLE
CampaignError message missing information

### ISSUE THREAD

**Issue by projectyang** [googleads/google-ads-php#140]
The current campaign error message for CANNOT_MODIFY_FOR_TRIAL_CAMPAIGN can be a bit misleading.

Current error message:

> campaignError":"CANNOT_MODIFY_FOR_TRIAL_CAMPAIGN",
> "message":"Cannot modify dates, budget or campaign name of a trial campaign."

I believe the message should also include status, e.g.:

> "Cannot modify status, dates, budget or campaign name of a trial campaign."

Reference: https://developers.google.com/google-ads/api/docs/experiments/campaign-experiments

**Comment by fiboknacky** [comment]
Thanks for reporting this. As this is not related to the client library, would you mind posting on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thank you.

**Comment by projectyang** [comment]
Whoops, of course. Thanks for pointing me in the right direction.
