### ISSUE TITLE
Extension SiteLink 

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleads/google-ads-php#141]
Hi Google Ads,

I am trying to perform SiteLink type extension, but it is becoming impossible due to lack of documentation. Someone to tell me if I'm going well.
`
use Google\Protobuf\StringValue;
use Google\ApiCore\ApiException;
use Google\Ads\GoogleAds\Util\V1\ResourceNames;
use Google\Ads\GoogleAds\V1\Common\AdScheduleInfo;
use Google\Ads\GoogleAds\Lib\V1\GoogleAdsException;
use Google\Ads\GoogleAds\V1\Common\SitelinkFeedItem;
use Google\Ads\GoogleAds\V1\Resources\ExtensionFeedItem;
use Google\Ads\GoogleAds\V1\Resources\AdGroupExtensionSetting;
use Google\Ads\GoogleAds\V1\Enums\ExtensionTypeEnum\ExtensionType;
use Google\Ads\GoogleAds\V1\Services\AdGroupExtensionSettingOperation;
use Google\Ads\GoogleAds\V1\Enums\DayOfWeekEnum\DayOfWeek;
use Google\Ads\GoogleAds\V1\Enums\MinuteOfHourEnum\MinuteOfHour;

 private function newAdScheduleInfo($nameDayOfWeek,$startMinute,$endMinute,$startHour,$endHour){
  
  $adScheduleInfo = new AdScheduleInfo();
  $adScheduleInfo ->setDayOfWeek( (new DayOfWeek)->value($nameDayOfWeek) );
  $adScheduleInfo ->setStartMinute( (new MinuteOfHour)->value($startMinute) );
  $adScheduleInfo ->setEndMinute( (new MinuteOfHour)->value($endMinute) );
  $adScheduleInfo ->setStartHourValue($startHour);
  $adScheduleInfo ->setEndHourValue($endHour);
  return $adScheduleInfo;
 }

 private function newSiteLinkOption($linkUrl,$link_text, $line1, $line2){  
  $sitelink = new SitelinkFeedItem();
  $sitelink->setLinkTextValue($link_text);
  $sitelink->setLine2Value($line2);
  $sitelink->setLine1Value($line1);
  $sitelink->setFinalUrls( [ new StringValue( [ 'value' => $linkUrl ] ) ] );
  return $sitelink;
 }

$operations = [];
   $adGroupResourceName =new StringValue( [ 'value' => ResourceNames::forAdGroup($this->customerId, $groupId) ] );
   $adScheduleInfo = [];
   $days = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY','FRIDAY'];
   foreach ($days  as $day) {
    $adScheduleInfo[] = $this->newAdScheduleInfo($day,'ZERO','ZERO',0,24);
   }
  
   $sitelink_feed_item = $this->newSiteLinkOption('https://localsite.com','Support ', 'Desc 1 ', 'Desc 2' );
   if(!$sitelink_feed_item){
    return false;
   }
  
   $extensionFeedItem = new ExtensionFeedItem([
    'sitelink_feed_item' => $sitelink_feed_item,
    'ad_schedules' => $adScheduleInfo,
    'start_date_time' => "2021-03-05 09:00:00",
    'end_date_time'   => "2024-03-05 08:00:00",
   ]);
   
   $adGroupExtensionSetting = new AdGroupExtensionSetting([
    'ad_group'        => $adGroupResourceName,
    'extension_type'     => ExtensionType::SITELINK,
    'extension_feed_items' => [$extensionFeedItem->getResourceName()]
   ]);
  
   $adGroupExtensionSettingOperation = new AdGroupExtensionSettingOperation();
   $adGroupExtensionSettingOperation->setCreate($adGroupExtensionSetting);
   $operations[] = $adGroupExtensionSettingOperation;

   $adGroupExtensionSettingServiceClient = $this->service->getAdGroupExtensionSettingServiceClient();
   $response = $adGroupExtensionSettingServiceClient->mutateAdGroupExtensionSettings($this->customerId, $operations);
`

`string(1102) "{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": 0,
            "data": "type.googleapis.com\/google.ads.googleads.v1.errors.GoogleAdsFailure"
        },
        {
            "@type": 0,
            "data": [
                {
                    "errorCode": {
                        "requestError": "RESOURCE_NAME_MISSING"
                    },
                    "message": "Resource name is missing.",
                    "location": {
                        "fieldPathElements": [
                            {
                                "fieldName": "operations",
                                "index": "0"
                            },
                            {
                                "fieldName": "create"
                            },
                            {
                                "fieldName": "extension_feed_items"
                            }
                        ]
                    }
                }
            ]
        }
    ]`

**Comment by PierrickVoulet** [comment]
Hi,

It looks good to me. Could you confirm if the gRPC PHP extension you are using is managed by PECL (C implementation) or Composer (PHP native implementation)? The easiest way to check this is to run `php -i | grep protobuf` in a terminal: if it is returning something then you are running with PECL (C implementation).

Thanks,

**Comment by adrianlaraperez88** [comment]
php -i| find "protobuf" => " "

No error in composer :

![image](https://user-images.githubusercontent.com/19626181/60398542-e76d9f00-9b2f-11e9-9dd6-46060fa292e7.png)


![Capture](https://user-images.githubusercontent.com/19626181/60398503-64e4df80-9b2f-11e9-8530-b9bf157205be.PNG)

**Comment by PierrickVoulet** [comment]
I think the line `$extensionFeedItem->getResourceName()` returns empty because `$extensionFeedItem` is created right before and it does not have resource name attribute.

It is not for the exact same purpose but the [AddDynamicPageFeed example](https://github.com/googleads/google-ads-php/blob/214c1d53ea09605b7ae9279dda9694d9f6b738ec/examples/AdvancedOperations/AddDynamicPageFeed.php) uses FeedItem so you might be interested checking how it is done there.

**Comment by adrianlaraperez88** [comment]
After this update I have a new error: 
![image](https://user-images.githubusercontent.com/19626181/60399862-0543ff80-9b42-11e9-86e4-00282d03e3f7.png)

**Comment by adrianlaraperez88** [comment]
What you want to tell me that you must first create a FeedItem (https://github.com/googleads/google-ads-php/issues/141#issuecomment-507047381) ?? The truth if it is like this is to give a backward movement compared with the previous version.

**Comment by adrianlaraperez88** [comment]
https://github.com/googleads/google-ads-php/issues/141#issuecomment-507047381 ok let me check this option.

**Comment by adrianlaraperez88** [comment]
I have a new error after add this:

`$extensionFeedItem = new ExtensionFeedItem([
				'sitelink_feed_item' => $sitelink_feed_item,
				'ad_schedules' => $adScheduleInfo,
				'start_date_time' => "2021-03-05 09:00:00",
				'end_date_time'   => "2024-03-05 08:00:00",
				'extension_type' => ExtensionType::SITELINK,
				'status' => (new FeedItemStatus)->value('ENABLED')
			]);

			**$extensionFeedItemOperation = new ExtensionFeedItemOperation();
			$extensionFeedItemOperation->setCreate($extensionFeedItem);
	        $operations[] = $extensionFeedItemOperation;

	        $adGroupExtensionSettingServiceClient = $this->service->getExtensionFeedItemServiceClient();
	        $response = $adGroupExtensionSettingServiceClient->mutateExtensionFeedItems($this->customerId, $operations);**
        
			$adGroupExtensionSetting = new AdGroupExtensionSetting([
				'ad_group' 		 	   => $adGroupResourceName,
				'extension_type' 	   => ExtensionType::SITELINK,
				'extension_feed_items' => [$response->getResults()[0]->getResourceName()]
			]);
			
			$operations = [];
			$adGroupExtensionSettingOperation = new AdGroupExtensionSettingOperation();
	        $adGroupExtensionSettingOperation->setCreate($adGroupExtensionSetting);
	        $operations[] = $adGroupExtensionSettingOperation;

	        $adGroupExtensionSettingServiceClient = $this->service->getAdGroupExtensionSettingServiceClient();
	        $response = $adGroupExtensionSettingServiceClient->mutateAdGroupExtensionSettings($this->customerId, $operations);`

![image](https://user-images.githubusercontent.com/19626181/60436582-b7cb9f00-9be2-11e9-9d24-588af8f47c17.png)
