### ISSUE TITLE
Protobuf version

### ISSUE THREAD

**Issue by microcat49** [googleads/google-ads-php#142]
I was just wondering it looks like the current version of protobuf used by this library is ^3.4.0 . This is an out of date version so I was just wondering is there any plans to update the version of protobuf used by this library?

**Comment by Raibaz** [comment]
Yep we will likely update it with the next release which is due pretty soon, thanks for noticing.

**Comment by microcat49** [comment]
Hey @Raibaz, thank for responding. Do you know which version it will be updated to? Also when the next release will be? Thanks!

**Comment by Raibaz** [comment]
V2.0.0 has just been released.
