### ISSUE TITLE
SearchAbsoluteTopImpressionShare or SearchTopImpressionShare fields give Invalid Argument

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#148]
Hi,

The Replaced AvgPosition fields gives Invalid Arguments with Google Ads PHP lib.

I am running this GAQL

`
SELECT segments.date, metrics.average_cpc, metrics.clicks, metrics.conversions, metrics.conversions_from_interactions_rate,   metrics.cost_micros, metrics.cost_per_conversion, metrics.ctr, metrics.impressions,       metrics.top_impression_percentage, metrics.view_through_conversions FROM  customer               WHERE segments.date >= 20190624 AND segments.date <= 20190630`

Thanks,

**Comment by fiboknacky** [comment]
I've not seen any avg position field yet, could you please confirm?
Or do you mean `average_cpc`?

**Comment by chiragvels** [comment]
Hi @fiboknacky 

Please see the release note [here](https://developers.google.com/google-ads/api/docs/release-notes)
Under reporting they have removed metrics.average_position.

and blog post [here](https://ads-developers.googleblog.com/2018/11/top-metrics-absolute-top-metrics-and.html).

Thanks,

**Comment by fiboknacky** [comment]
OK. Sorry for misunderstanding. I thought that you're still using `average_position`, and thus tried to find that one in your GAQL. :)

The reason of this is that `metrics.top_impression_percentage` is not compatible with `customer` resource, as reflected by the fact that it's not listed in the `metrics` list of [this page](https://developers.google.com/google-ads/api/fields/v2/customer).

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

Got It, Then it should also be not selectable with customer?
I was checking metrics directly [here](https://developers.google.com/google-ads/api/fields/v2/metrics#metricstop_impression_percentage).

Thanks,

**Comment by fiboknacky** [comment]
No, it shouldn't be selected with customer (at least for now).
It's a bit confusing. Actually that list means that you can select _fields of_ `customer` in the same `SELECT` clause, but not when `customer` is **a main resource you put in `FROM`**
