### ISSUE TITLE
ResponsiveSearchAd pin position conversion

### ISSUE THREAD

**Issue by alex-s** [googleads/google-ads-php#159]
Hi, i'm noticed that i get strange values for RSA descriptions pin positions.
here the debug output, raw values that i downloaded from google
`"adGroupAd":{"resourceName":"customers\/111111111\/adGroupAds\/2222222~333333","status":"PAUSED","ad":{"id":"366564009807","finalUrls":[blablabla"],"type":"RESPONSIVE_SEARCH_AD","responsiveSearchAd":{"headlines":[{"text":"9_"},{"text":"3qwdqwdqwdqwdqwdqwdqwdqwdqwd"},{"text":"fur"},{"text":"68968"}],"descriptions":[{"text":"4"},{"text":"9","pinnedField":"DESCRIPTION_1"},{"text":"5","pinnedField":"DESCRIPTION_2"}],"path1":"2","path2":"3"}},"policySummary":{"reviewStatus":"REVIEWED","approvalStatus":"APPROVED"}}}`

it looks good, but when i try to get values from API objects

`       /** @var AdTextAsset $line */
        foreach ($this->param as $line) {
            var_dump([$line->getTextValue(), $line->getPinnedField()];
        }`

i got

`array(2) {
  [0]=>
  string(1) "4"
  [1]=>
  int(0)
}
array(2) {
  [0]=>
  string(1) "9"
  [1]=>
  int(5)
}
array(2) {
  [0]=>
  string(1) "5"
  [1]=>
  int(6)
}`

as you can see i have three descriptions 
4 - not pinned
9 - pin to 1
5 - pin to 2
but by fact i got 5 and 6 pin position, but in the same time headlines returns correct pin positions.
It looks like "pinnedField":"DESCRIPTION_1" converts to some different int then "pinnedField":"HEADLINE_1", but i cant find proper conversion way in the documentation.

Thanks for you help!

**Comment by Raibaz** [comment]
If you look at the `AdTextAsset` class, you can see that the `pinnedField` field is of type `ServedAssetFieldType`; this means you can find the proper conversions between integer values and pinned field names in the `ServedAssetFieldType` enum.

Additionally, you can get the human-readable values for the enum by doing, in your code, something like this:

```
/** @var AdTextAsset $line */ 
foreach ($this->param as $line) {
    var_dump([$line->getTextValue(), ServedAssetFieldType::name($line->getPinnedField())];
}
```

Let me know if this helps.

**Comment by alex-s** [comment]
You are right, i missed this class, thanks for your help, problem is gone
