### ISSUE TITLE
The CampaignBudget is created as a shared budget by default

### ISSUE THREAD

**Issue by nielsvandermolen** [googleads/google-ads-php#16]
According to the documentation the campaign budget should not be explicitly shared by default. 

https://developers.google.com/google-ads/api/docs/fields/campaign_budget

However, in this PHP library, the field explicitly_shared field is not set when creating a new CampaignBudget. This causes a campaign budget to be shared by default when being created (e.g. the [example](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/AddCampaigns.php) also created a shared budget).  

I had to manually set it to false to get a normal budget.

$budget->setExplicitlyShared(new BoolValue(['value' => false]));

**Comment by fiboknacky** [comment]
Hello,

Thanks for reporting. I'll discuss with the API engineering team and will update this thread.

Cheers,
Knack

**Comment by fiboknacky** [comment]
Hello,

Sorry for your confusion. It turned out that the default behavior for the `CampaignBudget` object in the Google Ads API is to be *explicitly shared*.
We're updating the code comments so it's clearer from now on.

Thank you very much for your report.

Best,
Knack
