### ISSUE TITLE
Unable to make an excluded subdivision

### ISSUE THREAD

**Issue by SvanThuijl** [googleads/google-ads-php#163]
I am succesfully generating a subdivison for my shopping ad with the code below. However I want to exclude the "other" group from being shown. In the normal Ads interface, you can change the cpc to excluded (screenshot). I am unable to find this option in the API documentation. Can you tell me how to accomplish this?

<img width="594" alt="Screen Shot 2019-07-18 at 13 07 21 " src="https://user-images.githubusercontent.com/2386327/61477344-060bcc80-a95d-11e9-8f95-275e2e0252de.png">

    <?php
        // Create "All Products" group
        $listingGroup = new ListingGroupInfo();
        $listingGroup->setType(ListingGroupType::SUBDIVISION);
        $listingGroup->setParentAdGroupCriterionUnwrapped(null);

        $adGroupCriterionRoot = new AdGroupCriterion();
        $adGroupCriterionRoot->setAdGroupUnwrapped($adGroupAdded->getResourceName());
        $adGroupCriterionRoot->setListingGroup($listingGroup);
        $adGroupCriterionRoot->setStatus(AdGroupAdStatus::PAUSED);
        $adGroupCriterionRoot->setResourceName(ResourceNames::forAdGroupCriterion(self::getCustomerId(), $adGroupAddedId, -1));

        $adGroupCriterionOperation =  new AdGroupCriterionOperation();
        $adGroupCriterionOperation->setCreate($adGroupCriterionRoot);
        $adGroupCriterionOperations[] = $adGroupCriterionOperation;

        // Create subdivision group other products
        $productIdInfo = new ProductItemIdInfo();

        $listingDimension = new ListingDimensionInfo();
        $listingDimension->setProductItemId($productIdInfo);

        $listingGroup = new ListingGroupInfo();
        $listingGroup->setCaseValue($listingDimension);
        $listingGroup->setType(ListingGroupType::UNIT);
        $listingGroup->setParentAdGroupCriterionUnwrapped($adGroupCriterionRoot->getResourceName());

        $adGroupCriterion = new AdGroupCriterion();
        $adGroupCriterion->setAdGroupUnwrapped($adGroupAdded->getResourceName());
        $adGroupCriterion->setCpcBidMicrosUnwrapped($cpc*10000);
        $adGroupCriterion->setListingGroup($listingGroup);
        $adGroupCriterion->setStatus(AdGroupCriterionStatus::PAUSED);
        $adGroupCriterion->setType(CriterionType::LISTING_GROUP);

        $adGroupCriterionOperation =  new AdGroupCriterionOperation();
        $adGroupCriterionOperation->setCreate($adGroupCriterion);
        $adGroupCriterionOperations[] = $adGroupCriterionOperation;

        // Create subdivision for product
        $productIdInfo = new ProductItemIdInfo();
        $productIdInfo->setValueUnwrapped($productId);

        $listingDimension = new ListingDimensionInfo();
        $listingDimension->setProductItemId($productIdInfo);

        $listingGroup = new ListingGroupInfo();
        $listingGroup->setCaseValue($listingDimension);
        $listingGroup->setType(ListingGroupType::UNIT);
        $listingGroup->setParentAdGroupCriterionUnwrapped($adGroupCriterionRoot->getResourceName());

        $adGroupCriterion = new AdGroupCriterion();
        $adGroupCriterion->setAdGroupUnwrapped($adGroupAdded->getResourceName());
        $adGroupCriterion->setCpcBidMicrosUnwrapped($cpc*10000);
        $adGroupCriterion->setListingGroup($listingGroup);
        $adGroupCriterion->setStatus(AdGroupCriterionStatus::ENABLED);
        $adGroupCriterion->setType(CriterionType::LISTING_GROUP);
        
        $adGroupCriterionOperation =  new AdGroupCriterionOperation();
        $adGroupCriterionOperation->setCreate($adGroupCriterion);
        $adGroupCriterionOperations[] = $adGroupCriterionOperation;
    ?>

**Comment by Raibaz** [comment]
This looks like an API issue rather than an issue specific to the PHP client library. Can you please contact googleadsapi-support about it?

Thanks,
Mattia
