### ISSUE TITLE
Method for CustomerService.getCustomers()

### ISSUE THREAD

**Issue by donjajo** [googleads/google-ads-php#166]
Hi,
How do I get this method in the PHP library?
https://developers.google.com/adwords/api/docs/reference/v201809/CustomerService#getcustomers

**Comment by fiboknacky** [comment]
The question is not related to this library. I saw you've posted in googleads-php-lib, which I've already posted an answer. So I'm closing this.

**Comment by donjajo** [comment]
Great, thank you for responding.
This is where I am lost, which of the library is the right one? This is the one I am currently using and i mistakenly posted on the other repo thinking it was this one.

**Comment by fiboknacky** [comment]
This one is for the [Google Ads API](https://developers.google.com/google-ads/api/docs/start).
The [googleads-php-lib](https://github.com/googleads/googleads-php-lib) is for the AdWords API (the previous version of API).

**Comment by donjajo** [comment]
Okay, thanks, seems the previous is more stable.
