### ISSUE TITLE
I am getting Error while running GetCampaigns file 

### ISSUE THREAD

**Issue by shubham-nigam** [googleads/google-ads-php#167]
ApiException was thrown with message '{ "message": "Internal error encountered.", "code": 13, "status": "INTERNAL", "details": [] }'.

**Comment by shubham-nigam** [comment]
Now I am getting this error - 
ApiException was thrown with message '{ "message": "Request contains an invalid argument.", "code": 3, "status": "INVALID_ARGUMENT", "details": [ { "@type": 0, "data": "type.googleapis.com\/google.ads.googleads.v2.errors.GoogleAdsFailure" }, { "@type": 0, "data": [ { "errorCode": { "requestError": "INVALID_CUSTOMER_ID" }, "message": "Invalid customer ID '249-801-4556'." } ] } ] }'.

**Comment by shubham-nigam** [comment]
Got success my API runs successfully

**Comment by iamandreadompe** [comment]
@shubham-nigam how did you solve this problem?

**Comment by shubham-nigam** [comment]
Yes my issue was solved and working fine because I am attempting to use customer I’d in wrong format, you just need to use a customer id without hyphens ( “-“ ) that’s it
