### ISSUE TITLE
how to get Ad Group - Cost , Cost / Conv and Conversion

### ISSUE THREAD

**Issue by arunvc** [googleads/google-ads-php#17]
From the api how to get 

**Ad Group - Cost , Cost / Conv and Conversion**

![image](https://user-images.githubusercontent.com/9069988/51839570-9282ee00-232f-11e9-8359-62d8f5fddd58.png)

Which methods should be called.

**Comment by fiboknacky** [comment]
Hello there,

As your question is more related to the Google Ads API, could you please post your question in the [API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?

Thank you for your cooperation.

Best,
Knack
