### ISSUE TITLE
GetTextAdRecommendations Call to a member function getValue() on null in

### ISSUE THREAD

**Issue by Babis86** [googleads/google-ads-php#183]
Hello everybody,

I try to show all text recommendations with the example class GetTextAdRecommendations.php .
Unfortunately I get an empty object back ( $response->iterateAllElements() ).
dump:
`object(Generator)#20 (0) {
}
`
I can connect though.
But all my expanded text ads that have in adwords recommendations return nothing.
I manage several accounts and that's why I use the loginCustomerId variable in the config

Any suggestions what I might have forgotten.

Best regards
babis86

**Comment by fiboknacky** [comment]
It would have to do more with your accounts, campaigns and your ads rather than the client library, so could you please ask in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thank you.
