### ISSUE TITLE
INTERNAL Error

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#184]
Hello @fiboknacky ,

This is related to this bug, as you asked to create new bug. so i am creating same.
https://github.com/googleads/google-ads-php/issues/80#issuecomment-495498662

I again faced the issue with, this time I find out that Where clause is not supported with customer_client view.

This query will give me Internal Server error
```
$query = 'SELECT
                            customer_client.resource_name,
                            customer_client.client_customer,
                            customer_client.hidden,
                            customer_client.level
                       FROM
                           customer_client
                       WHERE customer.test_account != TRUE';
```
and this will work

```
$query = 'SELECT
                            customer_client.resource_name,
                            customer_client.client_customer,
                            customer_client.hidden,
                            customer_client.level
                       FROM
                           customer_client';
```

Error

> An uncaught Exception was encountered Type: Google\ApiCore\ApiException Message: { "message": "Internal error encountered.", "code": 13, "status": "INTERNAL", "details": [ { "@type": "request-id", "data": "infbdRHHH_65NicyXP-fxg" } ] }

**Comment by fiboknacky** [comment]
Hi Chirag,

I've informed the engineering team of this bug and will follow up on my side.
Thanks so much for reporting this.

As this is not exactly related to the library, I'll close it for now.

Best,
Knack
