### ISSUE TITLE
I am not able to accept the invitation of client user in google adsese API

### ISSUE THREAD

**Issue by AnkitNaudiyal15** [googleads/google-ads-php#185]
When I try to accept the invitation of client user  it's show

Google Ads failure details:
	authorization_error: User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#login-customer-id.

 rest of the thing(creating invitation ) working fine only the accept invitation is not working.

**Comment by fiboknacky** [comment]
This issue is more related to the Google Ads API product. 
Please post in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api). Thank you.

**Comment by AnkitNaudiyal15** [comment]
@fiboknacky  Thanks for your Helping...
