### ISSUE TITLE
Account Hierarchy Example

### ISSUE THREAD

**Issue by hackzilla** [googleads/google-ads-php#191]
I'm struggling to query our Account Hierarchy.

It seems to be that I need to query CustomerClient, then CustomerClientLink, then CustomerManagerLink and finally customer.

🤯

You had a great example in the previous library.
https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/AccountManagement/GetAccountHierarchy.php

And I was hoping that the example ListAccessibleCustomers (#95) was the equivalent.

Any chance you could create an example?

**Comment by fiboknacky** [comment]
Hello,

Thanks for your feedback. With the [recent release](https://developers.google.com/google-ads/api/docs/release-notes#account_management) that provides more info for the CustomerClient, the equivalent is now possible.

So, FYI, I'm now writing an example for this in #192. 

Best,
Knack

**Comment by hackzilla** [comment]
I can see that this has been merged now.
