### ISSUE TITLE
Unable exclude subdivision

### ISSUE THREAD

**Issue by eduardoamills** [googleads/google-ads-php#196]
Hi, im trying make "Exclude" a subdivision but I don't have lucky.
Can you guide me or provide some examples? 

I need to create this.

![image](https://user-images.githubusercontent.com/5342828/63782767-46e2f380-c8c2-11e9-9e15-a4289ae9e4bc.png)

But, with my code I get this results

![image](https://user-images.githubusercontent.com/5342828/63784125-8ad6f800-c8c4-11e9-818f-16d3ff6fcdd3.png)

`
public function createHotelGroup(object $options) {
      $googleAdsClient = (new Client)->getClient();
      $operations = [];
      // Creates the root of the tree as a SUBDIVISION node.
      $rootResourceName = self::addRootNode($options->customerId, $options->adGroupId, $operations, $options->cpcBidMicroAmount);
      // Creates child nodes of level 1, partitioned by the hotel class info.
      $otherHotelResourceName = self::addLevel1(
          $options->customerId,
          $options->adGroupId,
          $rootResourceName,
          $operations,
          $options->cpcBidMicroAmount,
          $options->productId
      );
      $adGroupCriterionServiceClient = $googleAdsClient->getAdGroupCriterionServiceClient();
      $response = $adGroupCriterionServiceClient->mutateAdGroupCriteria($options->customerId, $operations);
      //printf("Added %d listing group info entities.%s", count($response->getResults()), PHP_EOL);
      foreach ($response->getResults() as $adGroupCriterion) {
          //print $adGroupCriterion->getResourceName() . PHP_EOL;
          return response()->json($adGroupCriterion->getResourceName());
      }
    }

    /**
     * Creates the root node of the listing group tree and adds its create operation to the
     * operations list.
     *
     * @param int $customerId the customer ID
     * @param int $adGroupId the ad group ID
     * @param AdGroupCriterionOperation[] $operations the operations
     * @param int $percentCpcBidMicroAmount the CPC bid micro amount to set on created ad group
     *     criteria
     * @return string the root node's resource name
     */
    private static function addRootNode($customerId, $adGroupId, array &$operations, $percentCpcBidMicroAmount ) {
        // Creates the root of the tree as a SUBDIVISION node.
        $root = self::createListingGroupInfo(ListingGroupType::SUBDIVISION);
        $rootAdGroupCriterion = self::createAdGroupCriterion($customerId, $adGroupId, $root, $percentCpcBidMicroAmount);
        $operation = self::generateCreateOperation($rootAdGroupCriterion);
        $operations[] = $operation;
        self::$nextTempId--;
        return $rootAdGroupCriterion->getResourceName();
    }
    /**
     * Creates child nodes of level 1, partitioned by the hotel class info.
     *
     * @param int $customerId the customer ID
     * @param int $adGroupId the ad group ID
     * @param string $rootResourceName the resource name of the root node
     * @param AdGroupCriterionOperation[] $operations the operations list
     * @param int $cpcBidMicroAmount the CPC bid micro amount to set on created ad group
     *     criteria
     * @return string the "other hotel classes" node's resource name, which serves as a parent node
     *     for the next level
     */
    // [START addLevel1Nodes]
    private static function addLevel1($customerId, $adGroupId, $rootResourceName, array &$operations, $cpcBidMicroAmount, $productId) {

      // Creates hotel class info and dimension info for 5-star hotels.
      $fiveStarredDimensionInfo = new ListingDimensionInfo([
        'hotel_id' => new HotelIdInfo(['value' => new StringValue(['value' => $productId])])
      ]);
      // Creates listing group info for 5-star hotels as a UNIT node.
      $fiveStarredUnit = self::createListingGroupInfo(
          ListingGroupType::UNIT,
          $rootResourceName,
          $fiveStarredDimensionInfo
      );
      // Creates an ad group criterion for 5-star hotels.
      $fiveStarredAdGroupCriterion = self::createAdGroupCriterion(
        $customerId,
        $adGroupId,
        $fiveStarredUnit,
        $cpcBidMicroAmount
      );
      // Decrements the temp ID for the next ad group criterion.
      self::$nextTempId--;
      $operation = self::generateCreateOperation($fiveStarredAdGroupCriterion);
      $operations[] = $operation;
      // You can also create more UNIT nodes for other hotel classes by copying the above code in
      // this method and modifying the value passed to HotelClassInfo() to the value you want.
      // For instance, passing 4 instead of 5 in the above code will create a UNIT node of 4-star
      // hotels instead.
      // Creates hotel class info and dimension info for other hotel classes by *not* specifying
      // any attributes on those object.
      $othersHotelsDimensionInfo = new ListingDimensionInfo([
        'hotel_id' => new HotelIdInfo()
      ]);
      // Creates listing group info for other hotel classes as a SUBDIVISION node, which will be
      // used as a parent node for children nodes of the next level.
      $otherHotelsSubDivision = self::createListingGroupInfo(
        ListingGroupType::UNIT,
        $rootResourceName,
        $othersHotelsDimensionInfo
      );
      // Creates an ad group criterion for other hotel classes.
      $otherHotelsAdGroupCriterion = self::createAdGroupCriterion(
        $customerId,
        $adGroupId,
        $otherHotelsSubDivision,
        $cpcBidMicroAmount
      );
      $operation = self::generateCreateOperation($otherHotelsAdGroupCriterion);
      $operations[] = $operation;
      // self::$nextTempId--;
      // return $otherHotelsAdGroupCriterion->getResourceName();
    }
    /**
     * Creates the listing group info with the provided parameters.
     *
     * @param int $listingGroupType the listing group type
     * @param string|null $parentCriterionResourceName optional, the resource name of parent
     *     criterion ID of the listing group info
     * @param ListingDimensionInfo|null $caseValue optional, the dimension info for the listing
     *     group
     * @return ListingGroupInfo the created listing group info
     */
    private static function createListingGroupInfo($listingGroupType, $parentCriterionResourceName = null, ListingDimensionInfo $caseValue = null) {
        $listingGroupInfo = new ListingGroupInfo([
          'type' => $listingGroupType
        ]);
        if (!is_null($parentCriterionResourceName)) {
          $listingGroupInfo->setParentAdGroupCriterion(
            new StringValue(['value' => $parentCriterionResourceName])
          );
          $listingGroupInfo->setCaseValue($caseValue);
        }
        return $listingGroupInfo;
    }
    /**
     * Creates an ad group criterion from the provided listing group info.
     * Bid amount will be set on the created ad group criterion when listing group info type is
     * `UNIT`. Setting bid amount for `SUBDIVISION` types is not allowed.
     *
     * @param int $customerId the customer ID
     * @param int $adGroupId the ad group ID
     * @param ListingGroupInfo $listingGroupInfo the listing group info
     * @param int $cpcBidMicroAmount the CPC bid micro amount to set for the ad group
     *     criterion
     * @return AdGroupCriterion the created ad group criterion
     */
    private static function createAdGroupCriterion($customerId, $adGroupId, ListingGroupInfo $listingGroupInfo, $cpcBidMicroAmount, $status='ENABLED') {
        $adGroupCriterion = new AdGroupCriterion([
          'status' => AdGroupStatus::PAUSED,
          'listing_group' => $listingGroupInfo,
          'resource_name' =>
              ResourceNames::forAdGroupCriterion($customerId, $adGroupId, self::$nextTempId)
        ]);
        // Bids are valid only for UNIT nodes.
        if ($listingGroupInfo->getType() == ListingGroupType::UNIT) {
            $adGroupCriterion->setCpcBidMicros(
              new Int64Value(['value' => $cpcBidMicroAmount])
            );
        }

        return $adGroupCriterion;
    }
    /**
     * Creates an operation for creating the specified ad group criterion.
     *
     * @param AdGroupCriterion $adGroupCriterion the ad group criterion to create an operation for
     * @return AdGroupCriterionOperation the created ad group criterion operation
     */
    private static function generateCreateOperation(AdGroupCriterion $adGroupCriterion)    {
        $operation = new AdGroupCriterionOperation();
        $operation->setCreate($adGroupCriterion);
        return $operation;
    }
`

**Comment by fiboknacky** [comment]
You should be able to set [the `negative` field](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#adgroupcriterion) to `new BoolValue(['value' => true])`. That will exclude the ad group criterion instead of including it.

For further question, please post in [the Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api), as the question is more related to the product than this client library.
Thank you.
