### ISSUE TITLE
Regarding the Return to Beta

### ISSUE THREAD

**Issue by rjksn** [googleads/google-ads-php#197]
Hello @fiboknacky,

I was at the San Fran presentation in the spring regarding this new api and was wondering how the return to beta will affect those times. It looks like the previous Soap based API hasn't been updated since 201809 and I was wondering if this is still the correct path for the future? Going to guess the deprecation timeline is out the window. 

Plow forward (on a slow for now api) or tread water?

https://ads-developers.googleblog.com/2019/07/google-ads-api-returning-to-beta.html

Thanks!

**Comment by fiboknacky** [comment]
Hello Ryan,

Thanks for joining us at the workshop last Spring. :)

Regarding this topic, could you please ask in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead, as the question is more related to the product?
Thanks so much for your cooperation.

Best,
Knack
