### ISSUE TITLE
AddBudgetProposal error

### ISSUE THREAD

**Issue by johnyi** [googleads/google-ads-php#203]
I used the API to add account budget proposal. This Monday I got an error message "Request contains an invalid argument", but I didn't change anything. It still worked last Friday. I changed the argument to be the same as the example. The error message is the same.
Here is the log .

google-ads.NOTICE: Request ------- Method Name: /google.ads.googleads.v2.services.AccountBudgetProposalService/MutateAccountBudgetProposal Host: googleads.googleapis.com Headers: {     "x-goog-api-client": "gl-php\/7.2.17 gapic\/ gax\/1.1.1 grpc\/1.22.1",     "x-goog-request-params": "customer_id=6889030599",     "developer-token": "REDACTED",     "login-customer-id": "3779999580" } Request: {"customerId":"6889030599","operation":{"create":{"billingSetup":"customers/6889030599/billingSetups/558259197","proposalType":"CREATE","proposedName":"Account Budget (example)","proposedStartTimeType":"NOW","proposedEndTimeType":"FOREVER","proposedSpendingLimitMicros":"10000"}}}  Response ------- Headers: {     "request-id": "srLcDS0zvea7J_DhqPOzgg",     "date": "Thu, 05 Sep 2019 15:52:24 GMT",     "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"" }  Fault ------- Status code: 3 Details: Request contains an invalid argument. Failure: {} [] []

**Comment by fiboknacky** [comment]
As this probably is related to the API itself, could you please contact our team in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thank you.
