### ISSUE TITLE
Allow developers write their own interceptors

### ISSUE THREAD

**Issue by lezhnev74** [googleads/google-ads-php#207]
The current PHP package has a hidden feature - interceptors for grpc requests. 
As seen here: `\Google\Ads\GoogleAds\Lib\V1\ServiceClientFactoryTrait::getGoogleAdsClientOptions`
One application for them is logging (which is already implemented).

For a regular developer, it is not easy to use them and there is no documentation for it available. I feel there is a HUGE benefit in making them available to the general public. For example, I used them to create a VCR layer which would record and playback of all requests and responses (for purposes of testing).

The problem is that `\Google\Ads\GoogleAds\Lib\V1\GoogleAdsClient` is final and doesn't let you customize interceptors.

What do you think?

**Comment by fiboknacky** [comment]
Thanks for the feedback. We'll review your feedback and come up with a plan.
In the meantime, feel free to propose a specific design that you wish to see that would make you achieve your goal most easily. :)

**Comment by lezhnev74** [comment]
Since we as web developers are used to things like HTTP middlewares, it would be convenient to have a similar set of interfaces here. I think, interceptors are basically the same thing but for GRPC.

Take a look at the interface definition `MiddlewareInterface` here https://www.php-fig.org/psr/psr-15/ for some inspiration.

**Comment by fiboknacky** [comment]
Thanks for your opinion. We're working on the revamping part of the interceptors too, as there are parts of the gax-php extension that is already available directly in the grpc extension.

After we're done with that, we'll prioritize exposing this part for developers.
