### ISSUE TITLE
CustomerClient a cancelled account

### ISSUE THREAD

**Issue by hackzilla** [googleads/google-ads-php#209]
After using #192 to recreate the account importer in my project.
We hit another issue.

It is pulling in all the accounts, including hidden and cancelled.

I have found how to expose hidden as part of the SELECT.
However, I can see no way to understand if an account has been cancelled.

**Comment by PierrickVoulet** [comment]
Hi - have you considered using the [status](https://developers.google.com/google-ads/api/fields/v2/customer_client_link#customer_client_linkstatus) field filtering on customer client links?

**Comment by fiboknacky** [comment]
@hackzilla Could you give an example customer ID of your canceled account?
According to what I've synced with engineering, it seems you should get the reverse--no canceled accounts should be returned by CustomerClientService right now.

@PierrickVoulet  I believe we use the CustomerClient, not CustomerClientLink in our example.

**Comment by hackzilla** [comment]
@fiboknacky an example that has been cancelled is "144-554-6407".
Actually, it might be nice to expose the status.
Then I could update my internal system.

**Comment by fiboknacky** [comment]
Hello,

I can reproduce your described issue now.
It seems I misunderstand a bit. What's not returned as customer_client is actually a test account.
The canceled accounts are returned.

Unfortunately, there is no way to figure out if the accounts are canceled right now.
I'll give feedback to the engineering to consider exposing that attribute in the future.

Best,
Knack
