### ISSUE TITLE
Unable to use with GCP packages

### ISSUE THREAD

**Issue by thecubicle** [googleads/google-ads-php#21]
I cannot install google/cloud and google/cloud-logging packages with this project because:

`  Problem 1
    - Installation request for google/gax (locked at 0.35.0) -> satisfiable by google/gax[0.35.0].
    - google/cloud-logging v1.14.2 requires google/gax ^0.38.0 -> satisfiable by google/gax[0.38.0].
    - google/cloud-logging v1.14.3 requires google/gax ^0.38.0 -> satisfiable by google/gax[0.38.0].
    - Conclusion: don't install google/gax 0.38.0
    - google/cloud-logging v1.14.0 requires google/gax ^0.37 -> satisfiable by google/gax[0.37.0].
    - google/cloud-logging v1.14.1 requires google/gax ^0.37 -> satisfiable by google/gax[0.37.0].
    - Conclusion: don't install google/gax 0.37.0
    - Installation request for google/cloud-logging ^1.14 -> satisfiable by google/cloud-logging[v1.14.0, v1.14.1, v1.14.2, v1.14.3].
`

`  Problem 1
    - Can only install one of: google/gax[0.38.0, 0.35.0].
    - Can only install one of: google/gax[0.38.0, 0.35.0].
    - Can only install one of: google/gax[0.38.0, 0.35.0].
    - google/cloud v0.92.0 requires google/gax ^0.38 -> satisfiable by google/gax[0.38.0].
    - Installation request for google/cloud ^0.92.0 -> satisfiable by google/cloud[v0.92.0].
    - Installation request for google/gax (locked at 0.35.0) -> satisfiable by google/gax[0.35.0].
`

What is the best way to resolve this?

**Comment by fiboknacky** [comment]
I'll check on this soon. Probably we can just upgrade the versions to match google/cloud.

**Comment by mackenziestarr** [comment]
I'm also getting this same error message when attempting to use this package and the latest [google/cloud-bigtable](https://packagist.org/packages/google/cloud-bigtable) package within the same repo.
