### ISSUE TITLE
Query Stopped Running

### ISSUE THREAD

**Issue by kaylined** [googleads/google-ads-php#217]
As of Oct 1st my query has stopped running, getting the same generic error when running the PHP code or when running through the Query Builder:

```
class stdClass#6 (1) {
  public $error =>
  class stdClass#5 (3) {
    public $errors =>
    array(1) {
      [0] =>
      class stdClass#4 (3) {
        public $domain =>
        string(6) "global"
        public $reason =>
        string(15) "validationError"
        public $message =>
        string(37) "The request you submitted is invalid."
      }
    }
    public $code =>
    int(400)
    public $message =>
    string(37) "The request you submitted is invalid."
  }
}
```

Request Body
```
{
  "kind": "doubleclickbidmanager#query",
  "metadata": {
    "dataRange": "CUSTOM_DATES",
    "format": "CSV",
    "title": "Test"
  },
  "queryId": 123456789,
  "params": {
    "filters": [
      {
        "type": "FILTER_ADVERTISER",
        "value": "REDACTED"
      }
    ],
    "groupBys": [
      "FILTER_PAGE_LAYOUT",
      "FILTER_SITE_ID",
      "FILTER_LINE_ITEM"
    ],
    "metrics": [
      "METRIC_IMPRESSIONS",
      "METRIC_CLICKS",
      "METRIC_CLICK_TO_POST_CLICK_CONVERSION_RATE",
      "METRIC_REVENUE_ADVERTISER"
    ],
    "type": "TYPE_GENERAL"
  },
  "reportDataEndTimeMs": 1570345200000,
  "reportDataStartTimeMs": 1570345200000,
  "schedule": {
    "frequency": "ONE_TIME"
  },
  "timezoneCode": "America/Los_Angeles"
}
```

**Comment by fiboknacky** [comment]
Could you please confirm you're using this library or [this one](https://github.com/googleads/googleads-php-lib)?

**Comment by the-five-stones** [comment]
Experienced the same issue and contacted DBM support.
Using FILTER_PAGE_LAYOUT + any line item dimensions (FILTER_LINE_ITEM, FILTER_LINE_ITEM_TYPE, ...) in a single query is now being rejected by API but not offline report in DV360 UI.

**Comment by fiboknacky** [comment]
@the-five-stones  Sorry, but your comment doesn't seem to be related to this library. Could you please confirm you're using the [Google Ads API](https://developers.google.com/google-ads/api/docs/start)?

**Comment by the-five-stones** [comment]
Sorry that the issue is not belongs to this library or Google Ads API. I am referring to DoubleClick Bid Manager API.

**Comment by kaylined** [comment]
@the-five-stones that seems to be correct - the FILTER_PAGE_LAYOUT doesn't work alongside any other filters for some reason, came to the same conclusion.

Sorry @fiboknacky, probably the wrong spot for this.
