### ISSUE TITLE
Issues getting metrics.conversions_value field 

### ISSUE THREAD

**Issue by leandromayor** [googleads/google-ads-php#222]
Hiya! 

I'm using now the API for getting metrics from reports.

All is fine, except when I want to call some metrics (Conversions Value).

A screenshot is attached below:

![image](https://user-images.githubusercontent.com/46829666/67427970-d3e4b900-f5a2-11e9-8763-6eeeec88228c.png)

And this is the result: 
" **Fatal error: Uncaught Error: Call to a member function mergeFrom() on float** "

![image](https://user-images.githubusercontent.com/46829666/67428259-66855800-f5a3-11e9-9559-4981a0807a19.png)

I'm using the last github version for this library.

I'll be happy if anyone could solve this issue.

Thanks in advance. Regards.

**Comment by PierrickVoulet** [comment]
Hi - It looks like it is related to JSON decoding so I believe you are running with REST transport? If it is the case, could you try enabling gRPC following the instruction in the [requirements](https://github.com/googleads/google-ads-php#requirements) session of the getting started documentation and let us  know if it fixes the problem?

**Comment by PierrickVoulet** [comment]
This issue is now discussed in #223
