### ISSUE TITLE
Still having issues with getting metrics.conversions_value

### ISSUE THREAD

**Issue by leandromayor** [googleads/google-ads-php#223]
Hi - It looks like it is related to JSON decoding so I believe you are running with REST transport? If it is the case, could you try enabling gRPC following the instruction in the [requirements](https://github.com/googleads/google-ads-php#requirements) session of the getting started documentation and let us  know if it fixes the problem?

_Originally posted by @PierrickVoulet in https://github.com/googleads/google-ads-php/issues/222#issuecomment-545612709_

I'm still having issues :/ 

<b>Fatal error</b>:  Uncaught Exception: Expect float. in ../vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php:182
Stack trace:
#0 ..vendor/google/protobuf/src/Google/Protobuf/DoubleValue.php(61): Google\Protobuf\Internal\GPBUtil::checkDouble(Object(Google\Protobuf\DoubleValue))
#1 ..vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1009): Google\Protobuf\DoubleValue-&gt;setValue(Object(Google\Protobuf\DoubleValue))
#2 ..vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(79): Google\Protobuf\Internal\Message-&gt;mergeFromArray(Array)
#3 ../vendor/google/protobuf/src/Google/Protobuf/DoubleValue.php(38): Google\Protobuf\Internal\Message-&gt;__construct(Array)
#4 ../src/Google/Ads/GoogleAds/V1/Common/Metrics.php(184 in <b>../vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php</b> on line <b>182</b><br />

**Comment by PierrickVoulet** [comment]
I think you are experiencing the same issue as #105.

You previously said that you use the latest version of the library which is great but I see from the logs that you still use the V1 namespace though.

I advice you to update your code to use the V2 namespace instead as it comes with several improvements and bug fixes including one that should fix the issue you are describing here.

**Comment by fiboknacky** [comment]
Closing because an answer is provided.
