### ISSUE TITLE
Issue #169 - Still not Resolved and giving Segmentation Fault - 11

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#229]
Hi @PierrickVoulet 

I am still facing issue#169 that was closed.

Can we reopen it ?

I can also notice that gRPC version 1.20.0 is giving those error.

Thanks,

**Comment by PierrickVoulet** [comment]
Thanks @chiragvels for verifying and letting us know it is still an issue. I just reopened #169 so we can continue working on this with full history from there. Closing this one.
