### ISSUE TITLE
ListAccessibleCustomers not working in Google Ads PHP Lib V2.2

### ISSUE THREAD

**Issue by ronakprogrammer** [googleads/google-ads-php#234]
Hello,

I just updated the google ads library from "googleads/google-ads-php": "^1.3" to "googleads/google-ads-php": "^2.2" and now the following code is not working at all.

                        
                    $oAuth2Credential = (new OAuth2TokenBuilder())
			->fromFile(config('adwords.ini_path'))
			->withClientId(config("adwords.client_id"))
			->withClientSecret(config("adwords.client_secret"))
			->withRefreshToken($refresh_token)
			->build();

			$googleAdsClient = (new GoogleAdsClientBuilder())
			->fromFile(config('adwords.ini_path'))
			->withOAuth2Credential($oAuth2Credential)
			->build();

			// List Accessible Customers
			$customerServiceClient = $googleAdsClient->getCustomerServiceClient();
			$accessibleCustomers = $customerServiceClient->listAccessibleCustomers();
			pr($accessibleCustomers); die;

It was working fine in version 1.3 but after upgrading to version 2.2 I am not able to retrieve the listAccessibleCustomers at all.

Thanks,
Ronak

**Comment by fiboknacky** [comment]
Could you elaborate how you weren't able to retrieve? Do you mean the list is empty?
If so, this sounds involved with the server issues, rather than client libraries.
Could you please reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) first? Just tell your expected result and what you got there.

**Comment by ronakprogrammer** [comment]
The biggest issue is the code doesn't get though this line

`$customerServiceClient = $googleAdsClient->getCustomerServiceClient();`

so for example 

`                             $customerServiceClient = $googleAdsClient->getCustomerServiceClient();
                               echo "Code Works!";
`

The above example doesn't print "Code Works!", it's just gets thrown out without any error exception.

**Comment by ronakprogrammer** [comment]
Ok so finally I was able to fix this issue using this answer https://github.com/googleads/google-ads-php/issues/229

gRPC version 1.25.0 and Protobuf version 3.10.0 is required in order to get it worked.
