### ISSUE TITLE
Ability to get a row of data in array format

### ISSUE THREAD

**Issue by williamjulianvicary** [googleads/google-ads-php#235]
Is it possible to get a raw output row in array format from a report response?

I can see there is `GoogleAdsRow->serializeToJsonString()` but looking into the method it seems quite heavy, and serializing to JSON, then using `json_decode` to switch it into an array seems excessive. 

The use case is that I'm looking to build, effectively, a keyed array of the dimensions and metrics returned from the report request, so that this can then push into our pipeline and subsequently into BigQuery. 

Is there something equivalent to `$row = (array) $googleAdsRow` (which doesn't work, as the row cannot be cast to an array? Alternatively, is there any "download" endpoints, as with previous API's?

**Comment by fiboknacky** [comment]
Unfortunately, there is no such casting function available in this library.
The new architecture is made flexible so you could customize the returned data in your favorable way. For example, if you would like to convert it to CSV or JSON, you could use other third-party libraries to do so, or implement that logic by yourself.

As all the data are stored in [GoogleAdsRow](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V2/Services/GoogleAdsRow.php#L16), you could freely build an associative array based on any segments and metrics you've requested.

**Comment by williamjulianvicary** [comment]
Thanks @fiboknacky, I am building an associative array based on the segments/dimensions and metrics being requested, but the system I'm building essentially accepts a variable length of dimensions/segments that are then built into the GAQL syntax and a report is ran against the API.

Essentially I then need to take an input dimension format like:
`campaign.name`

And swap this into
`$row->getCampaign()->getName()->getValue();`

With a method like this (where the $keys have already been converted to Pascal Case):
```
    private static function getRowValueByPathKeys(GoogleAdsRow $row, $keys)
    {
        try {
            $data = null;
            foreach ($keys as $key) {
                $data = ($data ?? $row)->{'get' . $key}();
            }
            return is_object($data) ? $data->getValue() : $data;
        } catch (\Throwable $e) {
            return null;
        }
    }
```

This all feels incredibly heavy, but as all of the classes have private properties and/or are initialised as final it seems like the only real method to build the array, albeit a little flimsy.

**Comment by fiboknacky** [comment]
> This all feels incredibly heavy, but as all of the classes have private properties and/or are initialised as final it seems like the only real method to build the array, albeit a little flimsy.

I believe all properties have public getters. Can you provide some examples of those that you cannot find their getters?

**Comment by williamjulianvicary** [comment]
The difficulty is when you don't know the request dimensions/segments/metrics, the row doesn't have any way of getting the entire rows' contents (beyond the serializeToJsonString() - which, when I benched the performance was taking ~0.2 seconds for a couple hundred rows of data).

For example, if I take a (sanitised) user input in GAQL, there is no way of returning the data back to the user in a tabular (or otherwise) form for the columns that have been returned from the GAQL.

The only way would be to parse the GAQL, extract the requested columns, explode into an array, map to PascalCase and then use that to pull the data from the necessary getter on each row - an expensive set of operations and code that is liable to break.

To put that into context, this is what I'm doing to achieve the above (slightly changed from my code-base, but you should be able to get the gist. I'd love to be able to replace the heavy code with `yield $responseRow->toArray()` or similar.
```

    public function runReport($awql, $customerId, $loginCustomerId, ?$dimensions=[], ?$metrics=[])
    {
        $googleAdsServiceClient = $this->getClient($loginCustomerId)->getGoogleAdsServiceClient();
        $response = $googleAdsServiceClient->search($customerId, $awql, ['pageSize' => self::PAGE_SIZE]);


        /**
         * Build a dimension/metric map from the input dimensions
         */
        $dimensionHeaders = self::createHeadersFromInput($dimensions);
        $metricHeaders = self::createHeadersFromInput($metrics, $stripMetricsPrefix ? 'metrics.' : null);

        /**
         * Iterate through the data and yield rows.
         */
        /** @var  GoogleAdsRow $googleAdsRow */
        foreach ($response->iterateAllElements() as $googleAdsRow) {
            $row = [];
            foreach ($dimensionHeaders as $key => $parts) {
                $row[$key] = (string) self::getRowValueByPathKeys($googleAdsRow, $parts);
            }

            foreach ($metricHeaders as $key => $parts) {
                $row[$key] = self::getRowValueByPathKeys($googleAdsRow, $parts);
            }

            yield $row;
        }

    }

    /**
     * @param GoogleAdsRow $row
     * @param $keys
     * @return null|mixed
     */
    private static function getRowValueByPathKeys(GoogleAdsRow $row, $keys)
    {
        try {
            $data = null;
            foreach ($keys as $key) {
                $data = ($data ?? $row)->{'get' . $key}();
            }
            return is_object($data) ? $data->getValue() : $data;
        } catch (\Throwable $e) {
            return null;
        }
    }

    /**
     * Create row headers and parts from dot separated input items.
     * Converts parts to pascal case for use in method calls.
     *
     * @param array|null $input
     * @param string|null $strip
     * @return array
     */
    private static function createHeadersFromInput(?array $input, ?string $strip = null): array
    {
        if ($input === NULL) {
            return [];
        }

        $return = [];
        foreach ($input as $item) {
            $key = str_replace('.', '_', $item);

            if ($strip !== NULL) {
                $key = str_replace($strip, '', $item);
            }

            $parts = explode('.', $item);
            $return[$key] = self::arraySnakeCaseToPascalCase($parts);
        }

        return $return;
    }

    /**
     * Takes an input array and returns a pascal case transformed version (from Snake Case).
     * @param array $parts
     * @return array
     */
    private static function arraySnakeCaseToPascalCase(array $parts): array
    {
        return array_map(static function($part) {
            return str_replace('_', '', ucwords($part, '_'));
        }, $parts);
    }
```

**Comment by fiboknacky** [comment]
I see your point now. However, it's actually the design of the API + this library is based on generated code of [google/gax-php](https://github.com/googleapis/gax-php) and [protobuf](https://github.com/protocolbuffers/protobuf), so I'm afraid that we couldn't change things much without breaking the pipeline of generated source code.
I would recommend filing a bug in the protobuf GitHub repo and discuss with owners there.
It might be possible that they can create a utility function for you to check what's really returned without needing to use the combination of `is_object` and `getValue()`.

**Comment by williamjulianvicary** [comment]
Thanks @fiboknacky - I've added a ticket there, seems like this would be a nice addition to the `Message` class.

**Comment by fiboknacky** [comment]
Thanks for your feedback, anyway. :)
I'll close this issue for now, as we don't have action items that we can do in a short time period here.
