### ISSUE TITLE
How to link a Google Adwords Customer to Google Ads Manager in PHP.

### ISSUE THREAD

**Issue by whyjonii06** [googleads/google-ads-php#24]
Hi,

I would like to know how can i link a current Google Adwords Customer with his own Campaigns and Ad Groups to my Google Ads Manager (MCC) ?

Thank's !

**Comment by fiboknacky** [comment]
As this question is related to the Google Ads API in general, could you reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?

Best,
Knack

**Comment by whyjonii06** [comment]
Hi, i'm sorry for that, but nobody can give me a good answer on the forum.

**Comment by fiboknacky** [comment]
Can you give us the link to that forum question you posted?

**Comment by whyjonii06** [comment]
Yes, thanks for your help :  
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/XwlX2OY3dDg/gi213SoUBAAJ

**Comment by fiboknacky** [comment]
I escalated that. You should be able to get the answer very soon. Sorry for your inconvenience.

**Comment by whyjonii06** [comment]
No worries, thank's a lot !
