### ISSUE TITLE
Update campaign optimization bidding strategy

### ISSUE THREAD

**Issue by RomanKenshoo** [googleads/google-ads-php#241]
Hey,
I'm trying to update the campaign optimization bid strategy:

$campaign_data  = [];
$campaign_data['resource_name'] = ResourceNames::forCampaign($account_id, $camapign_id);
$campaign_data['app_campaign_setting'] = new AppCampaignSetting();

$campaign_setting = new AppCampaignSetting();
$campaign_setting->setBiddingStrategyGoalType(3);

$campaign_data['app_campaign_setting'] = $campaign_setting;

$campaign = new Campaign($campaign_data);
$campaignOperation = new CampaignOperation();
$campaignOperation->setUpdate($campaign);

and getting this error: 

`[{"errorCode":{"requestError":"IMMUTABLE_FIELD"},"message":"Field 'app_campaign_setting.app_id' cannot be modified by 'UPDATE' operation.","location":{"fieldPathElements":[{"fieldName":"operations","index":"0"},{"fieldName":"update"},{"fieldName":"app_campaign_setting"},{"fieldName":"app_id"}]}},{"errorCode":{"requestError":"IMMUTABLE_FIELD"},"message":"Field 'app_campaign_setting.app_store' cannot be modified by 'UPDATE' operation.","location":{"fieldPathElements":[{"fieldName":"operations","index":"0"},{"fieldName":"update"},{"fieldName":"app_campaign_setting"},{"fieldName":"app_store"}]}}]`

I'm not trying to update the store id or ap id - only the optimization bid strategy.
Is it possible to do it through the api?

Thank you.

**Comment by fiboknacky** [comment]
Hello,

As this seems to be more involved with the specifications of the API itself, could you please ask in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Feel free to get back to us if it seems to be more related to the client library itself.
Thanks for your cooperation.

Knack
