### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by 5baddi** [googleads/google-ads-php#243]
Hi Dear,
I'm using PHP version 7.3 and i got this error of `*return value in write context*` at **Google/AdsApi/Common/Util/EnvironmentalVariables.php** line 40 and 47

`Fatal error: Can't use function return value in write context in /usr/home/html/production/main/adwords-demo/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php on line 40`

### I fixed the problem manually
With direct validation for `getenv()` result without using `empty()` function

Thanks

**Comment by thangduo** [comment]
Thanks for reporting this issue to us.

Would you be open to making a pull request for the community?

Thanks,
Thang Duong

**Comment by fiboknacky** [comment]
Hello,

It seems you're using [this library](https://github.com/googleads/googleads-php-lib/issues), not this one.
Our team will handle this internally, but if you have other issues, please feel free to file a new issue there.

Best,
Knack
