### ISSUE TITLE
USER_PERMISSION_DENIED. The loginCustomerId header is not added

### ISSUE THREAD

**Issue by miguelgracia** [googleads/google-ads-php#25]
Hi!

I have a test manager account from which I access the content of the associated accounts. Everything worked fine until, when I try to get the campaigns from one of the accounts, the api returns an error and tells me that I do not have access permissions to that customer. I have configured the loginCustomerId parameter according to the documentation but it is not added to the request header. Instead, I tried to add the following test line in the "modifyUnaryCallable" and everything worked well
```
// GoogleAdsGapicClientTrait.php
protected function modifyUnaryCallable(callable &$callable)
{
    if (!is_null($this->developerToken)) {
        $callable = new FixedHeaderMiddleware($callable, [
            self::$DEVELOPER_TOKEN_KEY => [$this->developerToken],
            "login-customer-id" => ["LOGIN_CUSTOMER_ID_HERE"] // This is the line test
        ]);
    }
    $callable = new GoogleAdsExceptionMiddleware($callable);
    $callable = new GoogleAdsResponseMetadataCallable($callable);
}
```

Thank you!

**Comment by fiboknacky** [comment]
There is [a PR](https://github.com/googleads/google-ads-php/pull/26) for this, which would be committed soon.
Sorry for your inconvenience.

**Comment by miguelgracia** [comment]
Great. No problem! Thank you

**Comment by chiragvels** [comment]
I am facing issue for same. I was trying to get data with RefreshToken which I have for googleads-php-lib. Does this lib required to have oAuth Access again? 

Failure: {"errors":[{"errorCode":{"authorizationError":"USER_PERMISSION_DENIED"},"message":"User doesn't have permission to access customer."}]}  
Request with ID '2caCn8q3KCnN3A7ZHuu7Nw' has failed.
Google Ads failure details:
	authorization_error: User doesn't have permission to access customer.

**Comment by fiboknacky** [comment]
Hi Chirag,

> I am facing issue for same. I was trying to get data with RefreshToken which I have for googleads-php-lib. Does this lib required to have oAuth Access again?

This library does require OAuth credentials. That isn't different from the previous SOAP library.
However, for this issue, it's due to the [recent change](https://ads-developers.googleblog.com/2019/01/new-required-header-for-google-ads-api.html).

The PR #26 should fix this.

**Comment by theresaslee** [comment]
Thanks for merging this in! When can we expect this to change to be released on packagist?

**Comment by fiboknacky** [comment]
Should be around 2-3 weeks from now.

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

Is this issue also related to this?

https://groups.google.com/d/topic/adwords-api/0KbXg5znR_g/discussion

Thanks,

**Comment by fiboknacky** [comment]
Hi Chirag,

No, it's not related at all.
Please see my [previous reply](https://github.com/googleads/google-ads-php/issues/25#issuecomment-464016003) above.

Best,
Knack

**Comment by chiragvels** [comment]
ok,

Then this should also a issue.
When we disable Logging then also API looking to create logger.

Should I need to create different issue over here?


Thanks,
