### ISSUE TITLE
gRPC 1.26.0 issue

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#252]
Hi,

Library not working with gRPC v1.26.0

Giving error PHP Warning:  PHP Startup: Unable to load dynamic library 'grpc.so' (tried: /usr/lib/php/20170718/grpc.so (/usr/lib/php/20170718/grpc.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/grpc.so.so (/usr/lib/php/20170718/grpc.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Any way I can get back to old version? I have updated library as well.

Thanks,

**Comment by chiragvels** [comment]
Hi, 

More info:

An uncaught Exception was encountered

Type:        Error
Message:     Call to undefined method Grpc\ChannelCredentials::isDefaultRootsPemSet()
Filename:    /google-ads-php/vendor/grpc/grpc/src/lib/BaseStub.php
Line Number: 46

Backtrace:
	File: /google-ads-php/vendor/google/gax/src/Transport/GrpcTransport.php
	Line: 88
	Function: __construct

	File: /google-ads-php/vendor/google/gax/src/Transport/GrpcTransport.php
	Line: 138
	Function: __construct

	File: /google-ads-php/vendor/google/gax/src/GapicClientTrait.php
	Line: 377
	Function: build

	File: /google-ads-php/vendor/google/gax/src/GapicClientTrait.php
	Line: 327
	Function: createTransport

	File: /google-ads-php/vendor/google/gax/src/LongRunning/Gapic/OperationsGapicClient.php
	Line: 183
	Function: setClientOptions

	File: /google-ads-php/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsGapicClientTrait.php
	Line: 64
	Function: __construct

	File: /google-ads-php/vendor/google/gax/src/GapicClientTrait.php
	Line: 179
	Function: modifyClientOptions

	File: /google-ads-php/src/Google/Ads/GoogleAds/V2/Services/Gapic/CustomerServiceGapicClient.php
	Line: 255
	Function: buildClientOptions

	File: /google-ads-php/src/Google/Ads/GoogleAds/Lib/V2/ServiceClientFactoryTrait.php
	Line: 560
	Function: __construct

**Comment by PierrickVoulet** [comment]
Thanks for raising the concern. As a workaround, you can downgrade gRPC adding `"grpc/grpc": "1.25.0"` in the `require` section of the `composer.json`.

Once done you could run `composer update` and should see something like `Downgrading grpc/grpc (1.26.0 => 1.25.0): Loading from cache` in the standard output.

In the meantime, we will investigate further.

**Comment by PierrickVoulet** [comment]
FYI - An [issue](https://github.com/grpc/grpc/issues/21535) is already opened on the gRPC repository regarding this.

**Comment by PierrickVoulet** [comment]
@chiragvels this error could happen if the version of the `grpc/grpc` package used by Composer is out of sync with the installed `grpc` extension.

I understand that your Composer uses the `grpc/grpc` package version `1.26.0`, could you confirm that the version of the `grpc` extension you use is the same? If not, could you try upgrading and let us know?

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

Downgrading the grpc version worked as expected. I have downgraded both grpc and composer.json

> I understand that your Composer uses the grpc/grpc package version 1.26.0, could you confirm that the version of the grpc extension you use is the same? If not, could you try upgrading and let us know?

->No, I am using both composer and grpc extension v1.26.0
I have upgraded both 
1) via composer update
2) via pecl install grpc

**Comment by PierrickVoulet** [comment]
@chiragvels thanks for confirming. A new version of gRPC (1.26.1) has been released to fix [the issue](https://github.com/grpc/grpc/issues/21535), could you give it another try and let us know if the issue persists?

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

While doing pecl install grpc I am still seeing latest one as 1.26.0

Maybe not released fully.


Thanks,

**Comment by PierrickVoulet** [comment]
There is no release `1.26.1` in the [GitHub gRPC releases](https://github.com/grpc/grpc/releases) but there is one in [Packagist](https://packagist.org/packages/grpc/grpc#1.26.1).

My understanding from this [gRPC PR](https://github.com/grpc/grpc-php/pull/18) is that upgrading the `grpc` C extension to the latest version `1.26.0` with `[sudo] pecl install grpc` and updating the `grpc/grpc` Composer package to the latest version `1.26.1` with `composer update` should do the trick.

**Comment by chiragvels** [comment]
> My understanding from this gRPC PR is that upgrading the grpc C extension to the latest version 1.26.0 with [sudo] pecl install grpc and updating the grpc/grpc Composer package to the latest version 1.26.1 with composer update should do the trick.

Yes, This will solve issue mentioned.

**Comment by PierrickVoulet** [comment]
Thanks for confirming @chiragvels.

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I would suggest that If we can add gRPC version on composer.json itself would prevent this kind of issue in the future?

I was asking because same issue there with gRPC verison 1.20.0 and now with 1.26.0


Also, same issue was there earlier with protobuf as well.

**Comment by PierrickVoulet** [comment]
Fair suggestion, it would definitely add some stability.

We currently use a more flexible approach though only specifying the [googleapis/gax-php](https://github.com/googleapis/gax-php/blob/master/composer.json) dependency where gRPC and Protobuf version rules are defined. Even if broad, these rules are supposed to be quite safe because of backward compatibility.

The [Google Ads API](https://developers.google.com/google-ads/api/docs/start) is still in Beta as for now so it makes sense to have this flexibility to move faster to latest versions. In the specific case of an application that uses this library to access the Beta Google Ads API for production purpose (not recommended), rules to override this behavior could be added to avoid any instability. We will review this approach when the Google Ads API will be out of Beta and out-of-the-box stability will become a main concern.

Feel free to create a dedicated issue to continue discussing and tracking this important subject.

**Comment by HassanElshazlyEida** [comment]
# modules of php 7.3 (state your correct version)
`sudo apt install php7.3-common php7.3-mysql php7.3-xml php7.3-xmlrpc php7.3-curl php7.3-gd php7.3-imagick php7.3-cli php7.3-dev php7.3-imap php7.3-mbstring php7.3-opcache php7.3-soap php7.3-zip php7.3-intl -y`

# module require
`sudo apt-get install php-pear phpunit`

# if you have previous version of grpc, uninstall it
`pecl uninstall grpc`

# install grpc base on specific version
`pecl -d php_suffix=7.3 install grpc`
