### ISSUE TITLE
segments.date is cause of empty response

### ISSUE THREAD

**Issue by khlystov** [googleads/google-ads-php#267]
Hello I have two queries: 
```
SELECT 
  customer.id, 
  campaign.id, 
  campaign.name, 
  campaign_budget.amount_micros, 
  campaign.advertising_channel_type,
  campaign.advertising_channel_sub_type, 
  campaign.status,
  campaign.serving_status, 
  campaign.start_date, 
  campaign.end_date, 
  metrics.conversions, 
  metrics.clicks, 
  metrics.impressions, 
  metrics.cost_micros 
FROM 
  campaign  
WHERE 
  segments.date DURING LAST_MONTH  
LIMIT 50 
```
and next one the same but with **segments.date** in select statement 
```
SELECT 
  segments.date,
  customer.id, 
  campaign.id, 
  campaign.name, 
  campaign_budget.amount_micros, 
  campaign.advertising_channel_type,
  campaign.advertising_channel_sub_type, 
  campaign.status,
  campaign.serving_status, 
  campaign.start_date, 
  campaign.end_date, 
  metrics.conversions, 
  metrics.clicks, 
  metrics.impressions, 
  metrics.cost_micros 
FROM 
  campaign  
WHERE 
  segments.date DURING LAST_MONTH  
LIMIT 50 
```
First one - works well
Last one - empty response, debug information 

> [2020-01-29T17:39:23.079962+03:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v2.services.GoogleAdsService/Search", ClientCustomerId: *******, RequestId: "6T8N7tmWvCs9wP6Ze0RVkg", IsFault: 0, FaultMessage: "None"  

 I am using v3.0.0

Thank you!

**Comment by fiboknacky** [comment]
As this is related to the query in general, could you post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
