### ISSUE TITLE
Add Protobuf info in the agent header "x-goog-api-client"

### ISSUE THREAD

**Issue by PierrickVoulet** [googleads/google-ads-php#268]
A basic value currently looks like "gl-php/7.2.16-1+ubuntu14.04.1+deb.sury.org+1 gapic/ gax/1.2.0 grpc/1.26.0". Two additional pieces of information would be great to add:

- Version of Protobuf
- Protobuf implementation (C or PHP)

**Comment by PierrickVoulet** [comment]
I did a quick analysis and found that the implementation comes from Gax so I opened a [feature request](https://github.com/googleapis/gax-php/issues/262).

It is technically possible to override the agent header value at client library-level to add the information but it would prefer to avoid.

**Comment by fiboknacky** [comment]
The feature request is already complete, so I close this issue.
