### ISSUE TITLE
LinkManagerToClient problem with ACTIVE status

### ISSUE THREAD

**Issue by konradstrek** [googleads/google-ads-php#272]
There is an issue or I did something not right. private static function `acceptInvitation` (https://github.com/googleads/google-ads-php/blob/master/examples/AccountManagement/LinkManagerToClient.php) doesn't work for me and throwing the following error:

`An invitation has been extended from the manager customer 3191377543 to the client customer 1096465570 with the customer client link resource name 'customers/3191377543/customerClientLinks/1096465570~165200823'. Retrieved the manager link of the customer client link: its ID is 165200823 and its resource name is 'customers/1096465570/customerManagerLinks/3191377543~165200823'. ApiException was thrown with message '{ "message": "The caller does not have permission", "code": 7, "status": "PERMISSION_DENIED", "details": [ { "@type": 0, "data": "type.googleapis.com\/google.ads.googleads.v2.errors.GoogleAdsFailure" }, { "@type": 0, "data": [ { "errorCode": { "authorizationError": "USER_PERMISSION_DENIED" }, "message": "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https:\/\/developers.google.com\/google-ads\/api\/docs\/concepts\/call-structure#login-customer-id" } ] } ] }'.`

**Comment by fiboknacky** [comment]
Could you please reach out to the supporting agents in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)?
They will explain what permissions you should have in order to use this feature of the API correctly.
