### ISSUE TITLE
Issue with LoggerFactory->createLogger() 

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#28]
Hi,

Under LoggerFactory->createLogger();

$stream should be 
`$stream = $stream === null ? fopen('php://stderr', 'w') : $stream; `
Instead 
`$stream = $stream === null ? STDERR : $stream;`

**Comment by fiboknacky** [comment]
It should be equivalent based on [this doc](http://php.net/manual/en/features.commandline.io-streams.php).
What error do you get?

**Comment by chiragvels** [comment]
Yes, You are correct.

I am getting this error `The stream or file "STDERR" could not be opened: failed to open stream: `

Thanks,

**Comment by fiboknacky** [comment]
What PHP version are you using?

**Comment by chiragvels** [comment]
I am using.
PHP 7.1.23 (cli) (built: Nov 27 2018 16:59:25) ( NTS )

Any way I found that I need to define constant because this LIB is intended to support CLI only
```
if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'r'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));
if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w'));
```
And 

PHP's CLI interface defines STDIN, STDOUT, and STDERR, which are constants that refer to file handles capable of reading from (STDIN) or writing to (STDOUT, STDERR) standard I/O streams. Because these are only defined by the CLI interface, I can't use them in a web application unless I define it.

If this is not the case then this might be bug.

Thanks,

**Comment by fiboknacky** [comment]
That's probably right. I'll find more info about that when I have time.

**Comment by fiboknacky** [comment]
It looks like you need to define STDERR by yourself, as you mentioned.
As there is a workaround for this, I'm closing this issue.

**Comment by chiragvels** [comment]
@fiboknacky ,

Has you able to found way?

Might be need to define same legacy library works?

Thanks,

**Comment by fiboknacky** [comment]
Unfortunately, not yet. It looks like you probably need to define the constants by yourself as you mentioned.

**Comment by chiragvels** [comment]
@fiboknacky ,

This should be address now,
At my code it is now giving error like

So In future verisons it will not work

Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP)

Thanks,

**Comment by jpuck** [comment]
This exact same issue was identified as a bug in the old SDK and fixed. https://github.com/googleads/googleads-php-lib/issues/173

I really don't think consumers should be required to define constants to make this package work in a web application.

**Comment by fiboknacky** [comment]
Thanks for the feedback. 
I'm making a change in #194.
