### ISSUE TITLE
AuthenticateInStandaloneApplication.php faulting when run from examples

### ISSUE THREAD

**Issue by BeyondClicks** [googleads/google-ads-php#289]
**Which version of the client library are you using?**
3.1.0

**Which version of PHP are you using?**
PhP 7.4.3

**Which operating system (Linux, Windows, ...) and version?**
Windows 10 - 10.0.18363 Build 18363

**Actions taken**
AuthenticateInStandaloneApplication.php run normally, oauth details provided and authenticated, authorization code provided with no problem.

**Expected result**
Application proceeds as normal to verify my Oauth key

**Actual result**
Process stops, PHP fatal errors provided as below - 

`PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate 
(see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201
Stack trace:
#0 C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHt in C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see 
https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201
Stack trace:
#0 C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHt in C:\Users\Mike\Desktop\Work Data\Code\google-ads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201`

**Comment by fiboknacky** [comment]
Could you try what's suggested in [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues) and see if the issue is gone?

**Comment by BeyondClicks** [comment]
The Curl file mentioned was missing, went through the guide and re-added it but no change was made to the issue.

**Comment by fiboknacky** [comment]
Could you elaborate what "Curl" file is missing? You mean you don't have curl command in your system?

**Comment by BeyondClicks** [comment]
The .crt file was missing. Curl is in and functional now

**Comment by fiboknacky** [comment]
What steps did you do in particular? There are many steps in the wiki, so could you please specify what you did in detail?

And in what line of AuthenticateInStandaloneApplication did it stop?

**Comment by BeyondClicks** [comment]
Went to recreate the steps to get the point in which it stopped, and it seemed to run this time, Wiki fix must have gone though. I re-downladed the curl-ca-bundle.crt and placed it in my home path, then used the first of the three solutions  (explicit connection in PHP.ini)
