### ISSUE TITLE
Fatal error: Uncaught BadMethodCallException: Streaming calls are not supported while using the REST transport.

### ISSUE THREAD

**Issue by sreenumalae** [googleads/google-ads-php#296]
I'm trying to implement the basic example GetCampaign.php.
But i'm getting a error.
![error](https://user-images.githubusercontent.com/38936262/77536954-b059cd80-6eb6-11ea-8313-981deecb17b9.PNG)

**Comment by fiboknacky** [comment]
You need to use gRPC for running the examples using streaming calls.
Please see [this section](https://github.com/googleads/google-ads-php#requirements).

**Comment by sreenumalae** [comment]
Thanks @fiboknacky .
The issues is because of placing the php_grpc.dll with a thread safe version
But for PHP in my machine needs Non Thread Safe(NTS) version

**Comment by sreenumalae** [comment]
Currently i'm developing a web-application
where it uses data from google ads 
1) How can i do this OAUTH2 process in server side?
2)By using google api client library. I can do this OAUTH2 process and i can mention the redirect URI. But in google ads we need refresh token. How can i get that?

**Comment by fiboknacky** [comment]
As your questions are related to the API processes in general, could you post your question in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thanks.

**Comment by ravi0142** [comment]
Hello devs,


![image](https://user-images.githubusercontent.com/81223033/114262208-3e3e2300-99fc-11eb-8a90-1329ef5af977.png)
