### ISSUE TITLE
Confirm compatibility with the Google Ads APIs Client Library for Java (AdWords and DFP)

### ISSUE THREAD

**Issue by fiboknacky** [googleads/google-ads-php#3]
Confirm that a single project can require both this library and the [Google Ads APIs Client Library for PHP (AdWords and DFP)](https://github.com/googleads/googleads-php-lib).

This will ensure that users migrating from the [AdWords API](https://developers.google.com/adwords/api/docs/guides/start) to the [Google Ads API](https://developers.google.com/google-ads/api/docs/start) will be able to use both APIs within the same project.

**Comment by Raibaz** [comment]
As displayed by the Migration example, a single project can require both this library and the legacy AdWords API library.

I think we can close this.

**Comment by fiboknacky** [comment]
Yes, thanks for reminding.
