### ISSUE TITLE
Serialized descriptors should have exactly one file

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#307]
Hi,

I was trying to use V3 for the example of the basic operation

when I tried to run the GetCampaigns.php example getting an error

> PHP Fatal error:  Serialized descriptors should have exactly one file in /google-ads-php/metadata/Google/Ads/GoogleAds/V3/Services/GoogleAdsService.php on line 30

Thanks,

**Comment by PierrickVoulet** [comment]
Could you confirm your version of Protobuf? The minimal version is 3.11.4.

**Comment by chiragvels** [comment]
Ok @PierrickVoulet ,

I am having the version 3.11.2,

After update to 3.11.4 has given data.

Thanks,

**Comment by DhruvAtZomato** [comment]
I am getting this error as well. Already have Protobuf version as 3.11.4

**Comment by PierrickVoulet** [comment]
> I am getting this error as well. Already have Protobuf version as 3.11.4

Do you use the C implementation (see [instructions](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#determine_which_implementation_is_being_used) to determine if it is the case)? If it is the case, please make sure you use the minimum version 3.11.4 running the command `sudo pecl install protobuf`.

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I was facing a new error while assigning Negative Placement List to be shared with campaigns,

An uncaught Exception was encountered

> Type:        Exception
> Message:     Expect Google\Ads\GoogleAds\V3\Services\CampaignSharedSetOperation.
> Filename:    /google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php
> Line Number: 197

No real error message.

I was using like this

```
            $campaignSharedSet = new CampaignSharedSet([
            'campaign' => new StringValue(
                ['value' => ResourceNames::forCampaign($customerId, $campaignId)]
            ),
            'shared_set' => new StringValue(['value' => $sharedSetResourceName])
        ]);

        $campaignSharedSetOperation = new CampaignSharedSetOperation();
        $campaignSharedSetOperation->setCreate($campaignSharedSet);

        $campaignSharedSetServiceClient = $googleAdsClient->getCampaignSharedSetServiceClient();
        $response = $campaignSharedSetServiceClient->mutateCampaignSharedSets(
            $customerId,
            [$campaignSharedSetOperation]
        );

```


Thanks,

**Comment by PierrickVoulet** [comment]
> Hi @PierrickVoulet ,
> 
> I was facing a new error while assigning Negative Placement List to be shared with campaigns,
> 
> An uncaught Exception was encountered
> 
> > Type:        Exception
> > Message:     Expect Google\Ads\GoogleAds\V3\Services\CampaignSharedSetOperation.
> > Filename:    /google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php
> > Line Number: 197
> 
> No real error message.
> 
> I was using like this
> 
> ```
>             $campaignSharedSet = new CampaignSharedSet([
>             'campaign' => new StringValue(
>                 ['value' => ResourceNames::forCampaign($customerId, $campaignId)]
>             ),
>             'shared_set' => new StringValue(['value' => $sharedSetResourceName])
>         ]);
> 
>         $campaignSharedSetOperation = new CampaignSharedSetOperation();
>         $campaignSharedSetOperation->setCreate($campaignSharedSet);
> 
>         $campaignSharedSetServiceClient = $googleAdsClient->getCampaignSharedSetServiceClient();
>         $response = $campaignSharedSetServiceClient->mutateCampaignSharedSets(
>             $customerId,
>             [$campaignSharedSetOperation]
>         );
> ```
> 
> Thanks,

Hi @chiragvels , this seems to be unrelated issue so I created a new one based on your comment: #332 . Let's investigate from there.

**Comment by chiragvels** [comment]
@PierrickVoulet ,
Sorry, Thanks for creating new one.

**Comment by fiboknacky** [comment]
Closing this, as it's already forked.
