### ISSUE TITLE
Segment.device and segments.ad_network_type 

### ISSUE THREAD

**Issue by sreenumalae** [googleads/google-ads-php#312]
'''
$query = 'SELECT campaign.id, ad_group.id,metrics.clicks,metrics.ctr,metrics.impressions,segments.ad_network_type,segments.device, ad_group.name FROM ad_group';

$response =
            $googleAdsServiceClient->search($customerId, $query, ['pageSize' => self::PAGE_SIZE]);
        
        // Iterates over all rows in all pages and prints the requested field values for
        // the ad group in each row.
        foreach ($response->iterateAllElements() as $googleAdsRow) {
        printf(
            $googleAdsRow->getSegments()->getDevice();
            $devic=$googleAdsRow->getSegments()->getAdnetworktype();
            )
        }
'''

For the above code i'm getting Numerical values
Instead of mobile its showing 1
1-> mobile
2->computer
3-> tablet
4->tv screens
Same with networktype also
How can i get names instead of values?

**Comment by fiboknacky** [comment]
Please use the `name` method in each enum class.

For example, for device, you can use [Device::name()](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V3/Enums/DeviceEnum/Device.php#L69) like this:

```php
print Device::name(Device:: MOBILE);
```

The above code will print "MOBILE".
