### ISSUE TITLE
Internal error encountered

### ISSUE THREAD

**Issue by Shortcutz** [googleads/google-ads-php#321]
I received the following result:

`PHP Fatal error:  Uncaught Google\ApiCore\ApiException: {
    "message": "Internal error encountered.",
    "code": 13,
    "status": "INTERNAL",
    "details": []
}

  thrown in /Users/Lisica/Documents/GitHub/api-test/vendor/google/gax/src/ApiException.php on line 139`

This is my code:

`<?php

require dirname(__DIR__, 2) . '/GoogleAdsApi.php';

$googleAds = new \GoogleAdsApi();

// example : '222-333-1111'
$clientIDs = $googleAds->getClientIDs();

foreach ($clientIDs AS $clientID) {
    $googleAds->setOAuth2Credential();
    $googleAds->setGoogleAdsClient();
    $googleAdsClient = $googleAds->getGoogleAdsClient();
    $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
    
    // Creates a query that retrieves all keyword statistics.
    $query =
        "SELECT
            campaign.name,
            metrics.cost_micros
        FROM
            campaign";
    
    $response = $googleAdsServiceClient->search($clientID, $query);
    
    print_r($response);
}`

the authentication process seems to work fine, but I'll get an internal error response when I use search()

**Comment by fiboknacky** [comment]
Could you turn on logging and share what's really sent as a request and its response?
Or just the request ID would be fine too.

BTW, what the API version and client library version are you using?

**Comment by Shortcutz** [comment]
Ah its fine I found the issue, I was just somehow unable to close this thread (Edit: Ah, AdBlock made me unable to edit, comment or close in this issue). 

My mistake was I had both the LoginCustomerId as well as the CustomerID stored as xxx-xxx-xxx instead of xxxxxxxx. 
I was just confused because the error did not call me out on my formatting and referred to an internal error.
