### ISSUE TITLE
Expect Google\Ads\GoogleAds\V3\Services\CampaignSharedSetOperation

### ISSUE THREAD

**Issue by PierrickVoulet** [googleads/google-ads-php#332]
Hi @PierrickVoulet ,

I was facing a new error while assigning Negative Placement List to be shared with campaigns,

An uncaught Exception was encountered

> Type:        Exception
> Message:     Expect Google\Ads\GoogleAds\V3\Services\CampaignSharedSetOperation.
> Filename:    /google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php
> Line Number: 197

No real error message.

I was using like this

```
            $campaignSharedSet = new CampaignSharedSet([
            'campaign' => new StringValue(
                ['value' => ResourceNames::forCampaign($customerId, $campaignId)]
            ),
            'shared_set' => new StringValue(['value' => $sharedSetResourceName])
        ]);

        $campaignSharedSetOperation = new CampaignSharedSetOperation();
        $campaignSharedSetOperation->setCreate($campaignSharedSet);

        $campaignSharedSetServiceClient = $googleAdsClient->getCampaignSharedSetServiceClient();
        $response = $campaignSharedSetServiceClient->mutateCampaignSharedSets(
            $customerId,
            [$campaignSharedSetOperation]
        );

```

Thanks,

_Originally posted by @chiragvels in https://github.com/googleads/google-ads-php/issues/307#issuecomment-623464965_

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

What other details here would be helpful?

Thanks,

**Comment by PierrickVoulet** [comment]
I do not see any trivial link between the error message and the code snippet you provided and I tried but could not reproduce either.

Is there any reference of the specific line that triggers this error in the logs? If not, I would need you to provide a minimal piece of code that we could use to easily reproduce.

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I was trying to add sharedSet placement list between multiple campaigns.
But with one campaign it is working fine.

```
$campaigns = array(123456789, 123456788, 123456787, 123456786);
campaignSharedSetOperations =[];
            foreach ($campaigns as $campaignId) {
                $campaignSharedSet = new CampaignSharedSet([
                    'campaign' => new StringValue(
                            ['value' => ResourceNames::forCampaign($customerId, $campaignId)]
                    ),
                    'shared_set' => new StringValue(['value' => 'customers/XXX/sharedSets/XXX'])
                ]);

                $campaignSharedSetOperation = new CampaignSharedSetOperation();
                $campaignSharedSetOperation->setCreate($campaignSharedSet);
                $campaignSharedSetOperations[] = $campaignSharedSetOperation;
            }

            $campaignSharedSetServiceClient = $googleAdsClient->getCampaignSharedSetServiceClient();
            $response = $campaignSharedSetServiceClient->mutateCampaignSharedSets(
                    $this->customerId,
                    [$campaignSharedSetOperations],
                    ['partialFailure' => false, 'validateOnly' => true]
            );
```
I think error is mutateCampaignSharedSets, where I May be not able to pass multiple campaigns.

**Comment by PierrickVoulet** [comment]
I think I know the issue: `campaignSharedSetOperations ` is already an  array so your `mutateCampaignSharedSets ` call should not use `[]`. It should look like the following:

```php
$response = $campaignSharedSetServiceClient->mutateCampaignSharedSets(
    $this->customerId,
    $campaignSharedSetOperations,
    ['partialFailure' => false, 'validateOnly' => true]
);
```

**Comment by chiragvels** [comment]
Oh, Sorry,

It was just missed.

Thanks

**Comment by PierrickVoulet** [comment]
No problem, I consider this resolved but feel free to reopen if you still experience the issue.
