### ISSUE TITLE
Audience list sharing to client accounts

### ISSUE THREAD

**Issue by DhruvAtZomato** [googleads/google-ads-php#335]
Hi,

Our use case is that we want to share multiple audiences available in our manager account to a few of our clients. These clients can have more managers.

How do we ensure that our clients never enable sharing of audience to their managers in setting? Or if they do, we could run a cron(via API or scripts) every few minutes and identify if they are sharing our audiences and disable sharing audience to them.

1. I couldn't find any API/script that could help me change "Audience manager account" (Inside sub-account settings).
2. I couldn't find any API/script that could get me "Remarketing list access" setting for my child account?

**Comment by fiboknacky** [comment]
As this is related to the Google Ads API directly, could you please reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)?

Thank you.
