### ISSUE TITLE
The comment in HandleExpandedTextAdPolicyViolations is incorrect.

### ISSUE THREAD

**Issue by AnashOommen** [googleads/google-ads-php#337]
https://github.com/googleads/google-ads-php/blob/master/examples/ErrorHandling/HandleExpandedTextAdPolicyViolations.php#L170 talks about GoogleAdsClient, should be GoogleAdsException.

**Comment by AnashOommen** [comment]
This issue also exist in https://github.com/googleads/google-ads-php/blob/master/examples/ErrorHandling/HandleKeywordPolicyViolations.php#L185.

**Comment by PierrickVoulet** [comment]
> https://github.com/googleads/google-ads-php/blob/master/examples/ErrorHandling/HandleKeywordPolicyViolations.php#L185

Fixed in #343
