### ISSUE TITLE
Can we use the OneOfCase enum in HandleExpandedTextAdPolicyViolations?

### ISSUE THREAD

**Issue by AnashOommen** [googleads/google-ads-php#338]
https://github.com/googleads/google-ads-php/blob/master/examples/ErrorHandling/HandleExpandedTextAdPolicyViolations.php#L180

In C# I do  if (error.ErrorCode.ErrorCodeCase != ErrorCode.ErrorCodeOneofCase.PolicyFindingError)

Is there an equivalent construct in PHP so we can avoid the equality comparison to a string? Equality comparison against known enum values are easier to follow than against a seemingly random string value.

**Comment by fiboknacky** [comment]
I don't think there is an easy way of using enums like C# in this case.
This is what's in [the ErrorCode class](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V3/Errors/ErrorCode.php).

**Comment by PierrickVoulet** [comment]
I did not find a better way. @AnashOommen do you know if it is something that we have access to with other client libraries?

**Comment by fiboknacky** [comment]
Let's close this for now, as both library owners don't find a better way, so we're sure that there are no better options in this case.
