### ISSUE TITLE
Refactor HandleKeywordPolicyViolations example?

### ISSUE THREAD

**Issue by AnashOommen** [googleads/google-ads-php#340]
PTAL https://github.com/googleads/google-ads-dotnet/pull/186 where I refactored HandleKeywordPolicyViolations example a bit to 

1) Rethrow exceptions like in HandleExpandedTextAdsPolicyViolations
2) Keep track of non-exemptable errors (instead of making assumptions on error count) to determine if a policy exemption can be requested.

Could you PTAL and see if we can get those improvements in the PHP example?

**Comment by fiboknacky** [comment]
Pierrick, please see if this is valid for the PHP example. If so, could you please update the example and golden example file accordingly?

Anash, once you settle review with Pierrick, could you inform all other library owners as well?
Thanks.

**Comment by PierrickVoulet** [comment]
> Pierrick, please see if this is valid for the PHP example. If so, could you please update the example and golden example file accordingly?
> 
> Anash, once you settle review with Pierrick, could you inform all other library owners as well?
> Thanks.

@AnashOommen thank you for the improvement, I think I did an even leaner implementation in #344 . I let you review it and let me know.
