### ISSUE TITLE
Mock GoogleAdsClient

### ISSUE THREAD

**Issue by vienthuong** [googleads/google-ads-php#347]
HI there,
I got a similar issue like in #294 and the example doesn't help, I wish there is setCredentialsConfig in Google\Ads\GoogleAds\Lib\V3\ServiceClientFactoryTrait so that we can set some mock http client into the client then It won't send the actual request to Google Ads API.

**Comment by fiboknacky** [comment]
Pierrick, could you please confirm if this is the same as [this one](https://github.com/googleads/google-ads-php/issues/164)?

**Comment by PierrickVoulet** [comment]
> Pierrick, could you please confirm if this is the same as [this one](https://github.com/googleads/google-ads-php/issues/164)?

I believe it is strongly related but I do not think it is exactly the same thing:

- #164 : there is a real connection to a fake but real server that returns canned response via HTTP.
- Here: my understanding is that the HTTP Client used under the hood would be mocked to return a canned server response without even opening an HTTP connection. Am I getting this right @vienthuong ?

**Comment by vienthuong** [comment]
@PierrickVoulet P
Yes that's it! Because the GoogleAdsClient is final class so I cant just mock it, I tried using an adapter but it looks ugly and redundant since it only created for testing purpose.

**Comment by 77web** [comment]
Hi, transferred from #639
Why not simply remove "final" keyword from GoogleAdsClient? It solves most of testing problem.

**Comment by PierrickVoulet** [comment]
> Hi, transferred from #639
> Why not simply remove "final" keyword from GoogleAdsClient? It solves most of testing problem.

The reasons are not specific to this library or class, I find them pretty well explained in this [article](https://ocramius.github.io/blog/when-to-declare-classes-final/). Note: We do not implement any interface here because there are no public methods, only a constructor.

We are open to discussion, feel free to propose alternatives. There may be other ways to ease testing while keeping the same level of control.

**Comment by PierrickVoulet** [comment]
It is possible to edit class & method flags with the extension [`uopz`](https://pecl.php.net/package/uopz) using the function [`uopz_flags`](https://www.php.net/manual/en/function.uopz-flags.php).

Here is an example where I remove the `final` flag of the class `GoogleAdsClientBuilder` and test an extended version of the class with `PHPUnit`:

```php
$flags = uopz_flags(GoogleAdsClientBuilder::class, null);
uopz_flags(GoogleAdsClientBuilder::class, null, $flags & ~ZEND_ACC_FINAL);

class GoogleAdsClientBuilderExt extends GoogleAdsClientBuilder {
    public function build() {
        return null;
    }
}

class GoogleAdsClientTest extends TestCase
{
    public function test()
    {
        assertNull((new GoogleAdsClientBuilderExt())->build());
    }
}
```

This can be used to mock `GoogleAdsClient` or `GoogleAdsClientBuilder` if you need:

```php
public function test()
{
    $mock = $this->getMockBuilder(GoogleAdsClientBuilder::class)->getMock();
    // ...
}
```

I am closing this issue but feel free to add comments if you need to follow up.

**Comment by bizurkur** [comment]
> > Hi, transferred from #639
> > Why not simply remove "final" keyword from GoogleAdsClient? It solves most of testing problem.
> 
> The reasons are not specific to this library or class, I find them pretty well explained in this [article](https://ocramius.github.io/blog/when-to-declare-classes-final/). Note: We do not implement any interface here because there are no public methods, only a constructor.

If you read [Marco's article](https://ocramius.github.io/blog/when-to-declare-classes-final/) that you referenced, the very first thing it says is ONLY apply `final` **if they implement an interface**. The Google client does not implement an interface. You're going against best practices and making things more difficult for people who want to write quality code and write tests that need access to a dummy client.

It's mind boggling that Google employees do not know how to apply best practices. The ONLY correct answer to this issue is `final` should be removed or the client should have an interface.

**Comment by UltimateFlex** [comment]
Hi there!
I'm facing the same issue with GoogleAdsClient. I want to mock it but the final class make it impossible to do so. 
Is there any possibility to remove final from this class. I understand the meaning of final but it feels like bad practice to use final in libraries like this if there is no interface provided.

**Comment by fiboknacky** [comment]
Fixed with [v20.1.0](https://github.com/googleads/google-ads-php/releases/tag/v20.1.0)

**Comment by 77web** [comment]
Hi, it seems that "final" has come back for V16 Service Client classes in v22.1.0 unfortunately.
They were not marked as final previous versions like V15.

https://github.com/googleads/google-ads-php/tree/main/src/Google/Ads/GoogleAds/V16/Services/Client

They do not have proper interface to implement, so they should not be marked as final.

**Comment by fiboknacky** [comment]
Thanks for reporting. I'll take a look into this. It's probably due to the GAPIC v2 generation.
