### ISSUE TITLE
Composer Deprecation Warnings for PSR-4 Namespace

### ISSUE THREAD

**Issue by DynamoGeek** [googleads/google-ads-php#353]
Composer reports that a few files in the Testing directory have namespaces that aren't PSR-4 compliant. This can be solved from the user side in the short term in various ways, but the long term fix will need to be making the namespaces PSR-4 compliant.
```
Class Google\Ads\GoogleAds\Util\Testing\TestSuite ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/Testing/Google/Ads/GoogleAds/Util/Testing/TestSuite.php
Class Google\Ads\GoogleAds\Util\Testing\Resource ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/Testing/Google/Ads/GoogleAds/Util/Testing/Resource.php
Class Google\Ads\GoogleAds\Util\Testing\TestCase ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/Testing/Google/Ads/GoogleAds/Util/Testing/TestCase.php
Class Google\Ads\GoogleAds\Util\Testing\Foo ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/Testing/Google/Ads/GoogleAds/Util/Testing/Foo.php
Class Google\Ads\GoogleAds\Util\Testing\Bar ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/Testing/Google/Ads/GoogleAds/Util/Testing/Bar.php
```

**Comment by fiboknacky** [comment]
That file is created to correspond to the test proto files. That's why their directory structures are different from normal. We'll look into this.

**Comment by PierrickVoulet** [comment]
> That file is created to correspond to the test proto files. That's why their directory structures are different from normal. We'll look into this.

These seem to be specific to UTs, I suggest that we relocate them out of the `src` folder.

**Comment by fiboknacky** [comment]
> These seem to be specific to UTs, I suggest that we relocate them out of the src folder.

Our directory structure has all testing files in `Testing` inside `src`.
If we move them out, we should move all other testing files out for consistency.
I do see both libraries having testing files in `Testing` and those having them in `test`.

**Comment by johanwilfer** [comment]
They can also be excluded from the classmap: https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps

That route was taken here: https://github.com/MyAllocator/myallocator-pms-php/issues/7
PR: https://github.com/MyAllocator/myallocator-pms-php/pull/8
