### ISSUE TITLE
How to get Conversion ID and Conversion Label after creating Conversion Action?

### ISSUE THREAD

**Issue by konradstrek** [googleads/google-ads-php#371]
I cannot find how I can get  Conversion ID and Conversion Label after creating Conversion Action (AddConversionAction.php). I found only [this article](https://developers.google.com/google-ads/api/reference/rpc/v3/MutateConversionActionResult). Any solutions?

![ice_screenshot_20200621-204933](https://user-images.githubusercontent.com/37452287/85232838-7ee39600-b402-11ea-8a4c-6da0f33fe72c.png)

**Comment by fiboknacky** [comment]
As your question is more related to how to use the Google Ads API, could you please post your question in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)? 
Thank you.
