### ISSUE TITLE
Getting conversion id and label after creating conversion action

### ISSUE THREAD

**Issue by konradstrek** [googleads/google-ads-php#373]
![ice_screenshot_20200624-131728](https://user-images.githubusercontent.com/37452287/85546405-26d4ab80-b61d-11ea-85b3-08e0ebf1c662.png)

**Comment by PierrickVoulet** [comment]
Your question is related to how to use the Google Ads API, you will get the best support posting in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).

In the meantime, let me try to help. The Google Ads API provide ways to [query](https://developers.google.com/google-ads/api/docs/query/overview) resources. In your case, you will likely be interested by querying [`conversion_action`](https://developers.google.com/google-ads/api/fields/v3/conversion_action) with a filter on [`resource name`](https://developers.google.com/google-ads/api/fields/v3/conversion_action#conversion_action.resource_name) and a selector with the [`id`](https://developers.google.com/google-ads/api/fields/v3/conversion_action#conversion_action.id) field. After a quick look I could not find any label information though. [The forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) should be able to provide you with complete information.

**Comment by konradstrek** [comment]
Yes, I received a reply from the [forum](https://groups.google.com/forum/#!msg/adwords-api/L-6JRWCEJ8E/KE357586BwAJ) that it's currently not possible to get a label. The answer may not be visible because I received it privately by email. ref:_00D1U1174p._5004Q218F9D:ref

**Comment by PierrickVoulet** [comment]
Thank you for the context. If Google Ads API exposes the label information in the future it will be surfaced by our library.
