### ISSUE TITLE
Importing conversions from Google Analytics

### ISSUE THREAD

**Issue by konradstrek** [googleads/google-ads-php#374]
![ice_screenshot_20200624-131624](https://user-images.githubusercontent.com/37452287/85546494-3ce26c00-b61d-11ea-94e9-054c8eb3e674.png)

**Comment by PierrickVoulet** [comment]
Your question is related to features of the Google Ads API not the client library for PHP (this project), please post your question in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) to get the right support.

**Comment by konradstrek** [comment]
Their [response](https://groups.google.com/g/adwords-api/c/WqDLjGcOi_8/m/WBzyvWkJBQAJ).

**Comment by PierrickVoulet** [comment]
Thank you for the context.
