### ISSUE TITLE
Inviting an additional Google Ads manager account to the customer account

### ISSUE THREAD

**Issue by konradstrek** [googleads/google-ads-php#375]
Full conversation on the Google Adwords forum: ref:_00D1U1174p._5004Q218Dpr:ref

**Comment by PierrickVoulet** [comment]
@konradstrek do you happen to have a public URL to the forum post you are referring to? If not, could you describe the enhancement you would like to see that is specific to the client library in PHP (this project)?

**Comment by konradstrek** [comment]
Yes, [link](https://groups.google.com/forum/#!msg/adwords-api/c9jq0CYbYxQ/e8FV1hgvBwAJ). And 2 more responses that aren't visible are replied privately to author.

**Comment by PierrickVoulet** [comment]
This is related to the API itself not the client library for PHP (this project). If it turns out to be an issue specific to the client library for PHP, feel free to reopen the issue with detailed information and we will be happy to help.
