### ISSUE TITLE
How to automatically and automatically refresh your refresh token.

### ISSUE THREAD

**Issue by YuK1Game** [googleads/google-ads-php#389]
Hi.

I need to get view count for my ad every day.
I plan to do it daily with the API.

Right now I'm writing a program to renew tokens.
However, once you have to go through the authentication screen from the browser.

Can this not be automated with the console alone?

Thanks.

**Comment by fiboknacky** [comment]
Hello,

In general, this library refreshes **access token** automatically.
Once you pass refresh token [programmatically](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/OAuth2TokenBuilder.php#L118) or via a [config file](https://github.com/googleads/google-ads-php/blob/master/examples/Authentication/google_ads_php.ini#L28), the library will take care of refreshing access tokens for you.

Note that refresh tokens cannot be automatically renewed. Actually, you wouldn't need to create a new refresh token very often.

Best,
Knack

**Comment by YuK1Game** [comment]
> Note that refresh tokens cannot be automatically renewed. Actually, you wouldn't need to create a new refresh token very often.
understood. Thank you
