### ISSUE TITLE
Find replacement for phpunit-mock-objects

### ISSUE THREAD

**Issue by Raibaz** [googleads/google-ads-php#39]
When running composer install, this message is displayed:

    Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. 
    No replacement was suggested.

Another library to mock objects should be used and phpunit-mock-objects should be removed. Perhaps [Phake](https://phake.readthedocs.io/en/2.1/) would be ok.

**Comment by fiboknacky** [comment]
It's required by the old PHPUnit version, which is out of our control. We should just instead install the latest one that supports PHP 7.1, which seems to be [v7.5](https://github.com/sebastianbergmann/phpunit/tree/7.5).

Could you try install that version and run the tests?
