### ISSUE TITLE
Upgrade Version V2 to v3 and v4 

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleads/google-ads-php#393]
Hi @googleads team, I try to upgrade V2 to v3 and v4 but when making update no working more, we have any big update I use:"

**Which version of the client library are you using?**
At that moment I use V2

**Which version of PHP are you using?**
php 7.2
grpc module version => 1.21.3

**Which operating system (Linux, Windows, ...) and version?**
windows local W10, server W Server 2012

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
`public function getCampaignById($id){
		$query = "SELECT campaign.id, campaign.name, campaign.status,campaign.end_date,campaign.start_date, campaign_budget.amount_micros,campaign_budget.id 
				  FROM campaign  
				  WHERE campaign.id = $id 
				  ORDER BY campaign.id";

		$rtn = array();	
		try {	 		 		
			$response =   $this->service->getGoogleAdsServiceClient()->search($this->customerId, $query, ['pageSize' => self::PAGE_SIZE]);
			$rtn['error']=0;
			foreach ($response->iterateAllElements() as $googleAdsRow) {
			
				$rtn['data']=array(
					'id'   => $googleAdsRow->getCampaign()->getIdUnwrapped(),
					'name' => $googleAdsRow->getCampaign()->getNameUnwrapped(),
					'start' => $googleAdsRow->getCampaign()->getStartDateUnwrapped(),
					'end' => $googleAdsRow->getCampaign()->getEndDateUnwrapped(),
					'budget_id' => $googleAdsRow->getCampaignBudget()->getIdUnwrapped(),					
					'budget_amount' => $googleAdsRow->getCampaignBudget()->getAmountMicrosUnwrapped(),
					'status' => $googleAdsRow->getCampaign()->getStatus()
				);
			}
		} catch (GoogleAdsException $googleAdsException) {
           $rtn['error']=1;
        } catch (ApiException $apiException) {
            $rtn['error']=1;
        }
		return $rtn;
	}
$ads_campaing->getCampaignById('11987xxxxx');`

**Expected result**
array(7) {
    ["id"]=>
    int(11987xxxxx)
    ["name"]=>
    string(35) "Name"
    ["start"]=>
    string(10) "2013-06-11"
    ["end"]=>
    string(10) "2037-12-30"
    ["budget_id"]=>
    int(15631xxxx)
    ["budget_amount"]=>
    int(1xxxxxxxx)
    ["status"]=>
    int(2)
  }

**Actual result**
V3 and V4 empty no give result or error

Make sure you include information that can help us debug (full error message, exception listing, stack trace, [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging)).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by PierrickVoulet** [comment]
Hi @adrianlaraperez88 - Could you provide us with the manager and customer account IDs for us to reproduce?

If you do not feel comfortable doing this and prefer to keep the information private, an alternative is to send the information to googleadsapi-support@google.com which is the official Google support alias.

**Comment by adrianlaraperez88** [comment]
Ready I send to email . Subjet: Issue Github 
body : https://github.com/googleads/google-ads-php/issues/393

**Comment by PierrickVoulet** [comment]
Thank you @adrianlaraperez88. I run tests on my side without the WHERE clause on the campaign ID and I retrieved the same number of campaigns with V2 and V4. This number also matched what I could see from the Google UI.

This may be related to the WHERE clause though, do you mind providing the campaign ID so I can continue investigating?

**Comment by adrianlaraperez88** [comment]
@PierrickVoulet CampaignId : 119878134 only update lib and not working more, i change V2 to V3 and V4 and empty result

**Comment by PierrickVoulet** [comment]
@adrianlaraperez88 I gave it another try filtering on the campaign ID this time and it worked as expected (it always return the campaign).

Could you provide request IDs (one using V2 and one using V4)?

Also, could you elaborate a bit more on how you do make the upgrade of the lib?
- Did you do something similar to `composer update`?
- Did you change your code to use the client `Google\Ads\GoogleAds\Lib\V4\GoogleAdsClient` instead of `Google\Ads\GoogleAds\Lib\V2\GoogleAdsClient`?

**Comment by adrianlaraperez88** [comment]
no i clone GitHub and copy my class  next composer install and try change V2 to V3/V4, no make more

**Comment by PierrickVoulet** [comment]
I see. The best would be to provide us with request IDs that can be found in [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging) so we can take a look at the exact requests you send.

**Comment by adrianlaraperez88** [comment]
this is another problem not give me logs

**Comment by PierrickVoulet** [comment]
Do you have the [grpc](https://grpc.io/docs/languages/php/quickstart/#install-the-grpc-php-extension) and [protobuf](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#use_the_c_implementation) PHP extensions installed? If not, could you install then and try again?

**Comment by adrianlaraperez88** [comment]
@PierrickVoulet i have grpc module version => 1.21.3 but when find protobuf(php -i| find "protobuf") no give result

**Comment by PierrickVoulet** [comment]
Could you try again after running `sudo pecl install grpc` and `sudo pecl install protobuf` and adding the following lines to your `php.ini` file:
```
extension=grpc.so
extension=protobuf.so
```

**Comment by adrianlaraperez88** [comment]
Sorry, PTO, but i back and see this problem :

No releases available for package "pecl.php.net/grpc"

**Comment by adrianlaraperez88** [comment]
@PierrickVoulet hi i install Grpc in production server but now i have other error:
![image](https://user-images.githubusercontent.com/19626181/89820414-fa1c1b00-db1a-11ea-9389-6cdf591ee0c7.png)

**Comment by PierrickVoulet** [comment]
@adrianlaraperez88 It looks like there is an issue at gRPC layer but I am not sure what exactly. Do you use the same code as before? Could you provide more details about your production environment and what commands you used to install and configure the dependencies?

I suggest that you open an issue in the [gRPC repository](https://github.com/grpc/grpc) in parallel because when I look at the related [code](https://github.com/grpc/grpc/blob/ebf1b84e0e45fbe879211ff09a5dd7edb2c2835f/src/php/lib/Grpc/AbstractCall.php#L55) I can see that the value type is being [tested](https://github.com/grpc/grpc/blob/ebf1b84e0e45fbe879211ff09a5dd7edb2c2835f/src/php/lib/Grpc/AbstractCall.php#L52) before it is used.

**Comment by adrianlaraperez88** [comment]
@PierrickVoulet yes is same code we install gRPC and QA in production server and give me this error is exactly in this linea, 
only for test change This: 
`  $now = Timeval::now();
            $delta = new Timeval($timeout);
            $deadline = $now->add($delta);`

To this:
`  $now = Timeval::now();
            $delta = new Timeval('1800000');
            $deadline = $now->add($delta);`

and working perfect but is complicated with I use 32 bits, maybe gRPC has more problem with this. I check in old ticket and Google Ads Library have more issues (https://github.com/googleads/google-ads-php/issues/55) related to this and closed without response.

**Comment by PierrickVoulet** [comment]
Good catch, this is the same issue. @MaksTech explains it pretty well in one [comment](https://github.com/googleads/google-ads-php/issues/55#issuecomment-485881185).

I reported an [issue](https://github.com/grpc/grpc/issues/23790) on the gRPC repository because as far as I know gRPC should work just fine in 32bit.

**Comment by adrianlaraperez88** [comment]
Perfect for now I try use this and waiting  for gRPC Team.

**Comment by PierrickVoulet** [comment]
Quick update: the gRPC team made a fix https://github.com/grpc/grpc/pull/23994, this should be available with next release.

**Comment by PierrickVoulet** [comment]
The gRPC team released a new version that should contain the fix ([1.34.0](https://github.com/grpc/grpc/releases/tag/v1.34.0)).
