### ISSUE TITLE
Remove the hard-coded resource name templating implementation for PaymentsProfile

### ISSUE THREAD

**Issue by PierrickVoulet** [googleads/google-ads-php#394]
**Describe the problem you are trying to solve**
https://github.com/googleads/google-ads-php/pull/382 introduced a hard-coded implementation of the resource name templating for PaymentsProfile. This is a workaround only: it should be automatically generated like it is for any other resources but it is not currently.

The reason why it is not automatically generated is that PaymentsProfiles cannot be mutated like any other resources. The ability to build valid PaymentsProfile resource names like any other resources is especially useful while managing BillingSetups.

**Describe the solution you would like**
Remove the hard-coded implementation done in https://github.com/googleads/google-ads-php/pull/382.

**Describe alternatives you've considered**

**Additional context**
Need to wait for the automatic generation to take care of it.

**Comment by fiboknacky** [comment]
This was done after https://github.com/googleapis/gapic-generator-php/issues/453 was fixed.
