### ISSUE TITLE
Is there a way to link from customer to a merchant account via API?

### ISSUE THREAD

**Issue by marknguyen85** [googleads/google-ads-php#415]
Hi there!
As I see now, we can approve the link between Merchant Account and a customer only when there is a request from the Merchant Account center so Is there a way to make a request via API instead of via the UI or Is there a way to link from customer to a merchant account via API?

Thanks!

**Comment by fiboknacky** [comment]
As this is related to the API in general, could you please post your question in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thanks.
