### ISSUE TITLE
Getting PHP Segmentation Fault in v5 library

### ISSUE THREAD

**Issue by carthegian** [googleads/google-ads-php#416]
Hello,

I've recently upgraded API library in the project I'm working on from v4 to v5. I'm expecting nothing changes when executing basic operations get campaigns, but I'm getting PHP Segmentation Fault error as follows. When I changed library to V4 in the same code examples/BasicOperations/GetCampaigns.php, I did not encounter any error.

Was wondering if someone could shed light on this problem, or if I did something wrong somewhere.

```
[ec2-user@localhost google-ads-php-v5]$ php examples/BasicOperations/GetCampaigns.php
Segmentation fault
```

Note: there's no log produced since the execution just stops.

**Which version of the client library are you using?**
5.0.0

**Which version of PHP are you using?**
PHP 7.4.5 (cli)

**Which operating system (Linux, Windows, ...) and version?**
Amazon Linux 2

**Actions taken**
1. Get library v5 and install as per instruction including composer install
2. Run basic operations example get campaigns

**Expected result**
```
[ec2-user@localhost google-ads-php-v5]$ php examples/BasicOperations/GetCampaigns.php 
Campaign with ID XXX and name 'NAME_1' was found.
Campaign with ID YYY and name 'NAME_2' was found.
```

**Actual result**
```
[ec2-user@localhost google-ads-php-v5]$ php examples/BasicOperations/GetCampaigns.php 
Segmentation fault
```
 
**Anything else we should know about your project / environment**
Local Vagrant running Amazon Linux 2

**Comment by fiboknacky** [comment]
I assume you're using [the C implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf), right?
What's the protobuf version that you're using?

**Comment by carthegian** [comment]
Wow, thanks for the quick reply! Thanks to you I figured out what what I was missing (no error details that's what threw me off).

Apparently I was using an older version of protobuf
```
[ec2-user@localhost google-ads-php-v5]$ pear list -a
Installed packages, channel pecl.php.net:
=========================================
Package  Version State
protobuf 3.12.2  stable
```

After changed to newer version
```
[ec2-user@localhost google-ads-php-v5]$ pear list -a
Installed packages, channel pecl.php.net:
=========================================
Package  Version State
protobuf 3.13.0  stable
```

GetCampaigns.php is working fine.

You may mark this as solved!

**Comment by fiboknacky** [comment]
Glad to hear that. Thanks. :)
