### ISSUE TITLE
Migration to V5 - examples/AddCampaigns.php addCampaignBudget field_error: The required field was not present

### ISSUE THREAD

**Issue by roydidier** [googleads/google-ads-php#418]
Hello

I am migration from V2 to V5. I get an error when I try to create a campaign budget.
I have tried with V5/examples/AddCampaigns.php add get the same issue

**Which version of the client library are you using?**
V5

**Which version of PHP are you using?**
7.2

**Which operating system (Linux, Windows, ...) and version?**
Linux Ubuntu

**Actions taken**
use of V5/examples/AddCampaigns.php 
I just change CUSTOMER_ID 

**Expected result**

creation of campaign budget

**Actual result**
Request with ID xxx has failed.
Google Ads failure details:
        field_error: The required field was not present.

** Log data

(We can see into the log that name is missing from request)

Request: {"customerId":"2081628254","operations":[{"create":{"deliveryMethod":"STANDARD"}}]}

Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"fieldError":"REQUIRED"},"message":"The required field was not present.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":"0"},{"fieldName":"create"},{"fieldName":"amount_micros"}]}},{"errorCode":{"fieldError":"REQUIRED"},"message":"The required field was not present.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":"0"},{"fieldName":"create"},{"fieldName":"name"}]}}]}  

Make sure you include information that can help us debug (full error message, exception listing, stack trace, [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging)).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

thanks
Didier ROY

**Comment by fiboknacky** [comment]
How did you upgrade to V5?
Have you done `composer update` too?
And do you use [the C implementation of protobuf](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#use_the_c_implementation)?

**Comment by roydidier** [comment]
Hello

I have upgraded using
git clone https://github.com/googleads/google-ads-php.git
then composer install
I am not using C implementation of protobuf

*Didier Roy*
Head of Software
[image: WIHP] <http://www.wihphotels.com>
wihphotels.com <http://www.wihphotels.com>
77 rue du Faubourg St-Antoine
75011 Paris, France
+33 1 53 46 10 63 TEL(ext 47)

**Comment by fiboknacky** [comment]
What's your protobuf version installed? Could you try using the C implementation first?

**Comment by roydidier** [comment]
It is working fine with C implementation

thank you for your help

*Didier Roy*
Head of Software
[image: WIHP] <http://www.wihphotels.com>
wihphotels.com <http://www.wihphotels.com>
77 rue du Faubourg St-Antoine
75011 Paris, France
+33 1 53 46 10 63 TEL(ext 47)
