### ISSUE TITLE
How can I turn on the Creating Responsive Display Ads Additional format options ?

### ISSUE THREAD

**Issue by nabejohn** [googleads/google-ads-php#423]
I am using Google Ads client library V5.

Creating Responsive Display Ads
https://developers.google.com/google-ads/api/docs/responsive-display-ads/create-responsive-display-ads
ResponsiveDisplayAdInfo
https://developers.google.com/google-ads/api/reference/rpc/v5/ResponsiveDisplayAdInfo

How can I turn on the following Additional format options from Google Ads client library ?
- Use asset enhancements
- Use auto-generated video

![Screen Shot 2020-09-16 at 12 46 15](https://user-images.githubusercontent.com/8167667/93294498-9f669500-f825-11ea-8331-945486b45ffa.png)

**Comment by fiboknacky** [comment]
I believe this is not supported in the API yet.
As this is product-related question, could you please post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) and request this feature if necessary?
Thank you.
