### ISSUE TITLE
Serialisation issue

### ISSUE THREAD

**Issue by falko189** [googleads/google-ads-php#425]
**Which version of the client library are you using?**
Latest master to date v5.0.0

**Which version of PHP are you using?**
7.4.10

**Which operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04.4 LTS

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
`        $budget = new CampaignBudget([
                                         'name' => 'Interplanetary Cruise Budget #234' ,
                                         'delivery_method' => BudgetDeliveryMethod::STANDARD,
                                         'amount_micros' => 500000
                                     ]);
        // Creates a campaign budget operation.
        $campaignBudgetOperation = new CampaignBudgetOperation();
        $campaignBudgetOperation->setCreate($budget);
        print_r($budget->serializeToJsonString());`
**Expected result**
`"{"name":"Interplanetary Cruise Budget #234","amountMicros":"500000","deliveryMethod":"STANDARD"}"`
**Actual result**
`{"deliveryMethod":"STANDARD"}`

**Anything else we should know about your project / environment**
The reason why I came across the issue was the upgrade from v4 to v5, once I upgrade to the new classes/packages a bunch of tests that were using the `serializeToJsonString` method strarted failing with errors like `Failed asserting that '{"create":{"language":{}}}' contains "languageConstants\/1000"` I am not sure why this is happening.

Let me know if you need more informations about it.

Thanks in advance
Daniele

**Comment by PierrickVoulet** [comment]
I reproduce using the PHP implementation of protobuf but not using the C implementation of protobuf (more detail [here](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf)).

Could you try again with the PHP Extension for protobuf installed and configured?

**Comment by Plytas** [comment]
I have similar issue.
PHP implementation doesn't serialize properly. Can't install v3.13.0 on PHP 7.4.10, created an issue for that protocolbuffers/protobuf#7918. Installing 3.12 gets me a 502.

**Comment by PierrickVoulet** [comment]
@falko189 the issue should be fixed on protobuf's side with the version [v3.13.0.1](https://packagist.org/packages/google/protobuf#v3.13.0.1).

Could you update your dependencies (run `composer update`) and give it another try?

**Comment by Plytas** [comment]
I was able to install C implementation (`pecl install protobuf`) and my issue is fixed now.

**Comment by PierrickVoulet** [comment]
This should be fixed with the current version of Protobuf [3.14.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0).
