### ISSUE TITLE
GetCampgain.php error 

### ISSUE THREAD

**Issue by sharadcodify** [googleads/google-ads-php#426]
php GetCampaigns.php --customerId 8044931884
PHP Fatal error:  Uncaught BadMethodCallException: Streaming calls are not supported while using the REST transport. in /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php:119
Stack trace:
#0 /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php(63): Google\ApiCore\Transport\RestTransport->throwUnsupportedException()
#1 /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/GapicClientTrait.php(498): Google\ApiCore\Transport\RestTransport->startServerStreamingCall()
#2 /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Middleware/CredentialsWrapperMiddleware.php(61): Google\Ads\GoogleAds\V5\Services\Gapic\GoogleAdsServiceGapicClient->Google\ApiCore\{closure}()
#3 /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\ApiCore\Middleware\CredentialsWrapperMiddleware->__invoke()
#4 /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Middleware/Retry in /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php on line 119

Why i am getting this error and how can i resolve this

**Comment by fiboknacky** [comment]
> PHP Fatal error: Uncaught BadMethodCallException: Streaming calls are not supported while using the REST transport. in /var/www/html/adskeywords/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php:119

This is because you're using the REST transport.
Please install gRPC in order to use the streaming call. The steps are in [this section](https://github.com/googleads/google-ads-php#requirements).
