### ISSUE TITLE
Creating a new label using the library

### ISSUE THREAD

**Issue by pittrek** [googleads/google-ads-php#428]
Hi, I have a little problem, apologies if it doesn't belong here but I'm not sure if this is a bug or a feature request or just poor documentation or if I'm just dumb.

I am trying to create a new Campaign label using the API using your library (I am using the current latest version). I didn't find any example for it (just adding an existing label), so I checked the documentation and it says

    Create a TextLabel instance.
    Set the desired background color for this TextLabel.
    Enter text for this TextLabel using the description field.
    Wrap the TextLabel in a LabelOperation and send it to LabelService.MutateLabels.

I have created a new Google\Ads\GoogleAds\V5\Common\TextLabel, set its background color and the description. However when I tried to do 

$labelOperation = new Google\Ads\GoogleAds\V5\Services\LabelOperation();
$labelOperation->setCreate($lbl);

The "setCreate" method throws an exception " Expect Google\Ads\GoogleAds\V5\Resources\Label. " When I checked the method it indeed expects a Label instance and not a TextLabel.

Any idea how I can do it? And apologies if it's a completely "newbie" question or if it doesn't belong here. Thanks for any help.

**Comment by fiboknacky** [comment]
Could you include all your code here? Thanks.

**Comment by pittrek** [comment]
This is how my work in progress method which is supposed to do this looks like right now

public function registerLabel($customerId, $bgColor, $name)
{
        $lbl = new TextLabel();
        $lbl->setBackgroundColorUnwrapped($bgColor);
        $lbl->setDescriptionUnwrapped($name);        
        $labelOperation = new LabelOperation();
        $labelOperation->setCreate($lbl);
        $operations = [$labelOperation];
        $labelServiceClient = new LabelServiceGapicClient();
        try {
            $response = $labelServiceClient->mutateLabels($customerId, $operations);
        } catch (GoogleAdsException $googleAdsException) {
            $error .= $googleAdsException->getRequestId();
            foreach ($googleAdsException->getGoogleAdsFailure()->getErrors() as $error) {
                $error .= $error->getErrorCode()->getErrorCode() . $error->getMessage();
            }
        } catch (ApiException $apiException) {
            $error .= $apiException->getMessage();
        } catch (Exception $ex) {
            $error = $ex->getMessage();
        } finally {
            $labelServiceClient->close();
        }
        if ($response) {            
            $returnedLabels = [];
            foreach ($response->getResults() as $addedCampaignLabel) {
                $returnedLabels[] = $addedCampaignLabel->getResourceName();
            }
            $res = new \stdClass();
            $res->status = 'OK';
            $res->labels = $returnedLabels;
            return $res;
        }
        $res = new \stdClass();
        $res->status = 'error';
        $res->error = $error;
        return $res;
}

Yes, I know it needs a little bit of a "cleanup", but as I said it's "work in progress" right now. Thanks a lot for any help. The exception occurs on "$labelOperation->setCreate($lbl);".

**Comment by pittrek** [comment]
So thanks for your time, I know now what the problem was. The documentation suggests that the TextLabel should be wrapped into a LabelOperation DIRECTLY. 

"Wrap the TextLabel in a LabelOperation and send it to LabelService.MutateLabels."

However the true solution was to wrap the TextLabel into a Google\Ads\GoogleAds\V5\Resources\Label, and the Label should be wrapped into a LabelOperation.

So the documentation is a bit confusing for people who are "newbies", at least for me it was.

So thanks a lot for your time, this can be now closed.
