### ISSUE TITLE
How to prove I am making calls to the API via HTTP/2

### ISSUE THREAD

**Issue by carthegian** [googleads/google-ads-php#431]
Good day!

First thing I would like to apologize if this was already mentioned somewhere as I could not find relevant information anywhere.
(I searched all issues already though) 

**Background**
My organization requires the usage of HTTP/2 whenever possible, including when making calls to third-party APIs. So I looked around Google Ads API documentation to see if there's any tidbits containing the information related to HTTP/2.

I found these bits here:
1. [API Call Structure](https://developers.google.com/google-ads/api/docs/concepts/call-structure). This briefly explains that if we're using protocol buffer as the chosen API call method, automatically requests to server will be using HTTP/2.
2. [Transport](https://developers.google.com/google-ads/api/docs/client-libs/php/transport). This explains that when choosing the mode of transport, if gRPC is used then HTTP/2 is automatically used.

However, the above information gives no detailed sentences regarding HTTP/2.
Furthermore I have already setup gRPC and protocol buffer, as shown below from an excerpt of actual log in my application. I think gRPC is already used here.
```
[2020-10-02 14:33:26] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v5.services.AdGroupAdService/MutateAdGroupAds
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.4.9 gapic\/ gax\/1.3.1 grpc\/1.29.1",
    "x-goog-request-params": "customer_id=XXX",
    "developer-token": "REDACTED",
    "login-customer-id": "YYY"
}
```
**My questions:**
How do I prove that HTTP/2 is already used when making calls to Google Ads API? Is there something in the default log setting from API that shows that HTTP/2 is used in request/response?

I would be grateful if you guys could give me some pointers here. Let me know if I need to provide more details!

Also, please find additional info below
**Which version of the client library are you using?**
5.0.0

**Which version of PHP are you using?**
PHP 7.4.5 (cli)

**Which operating system (Linux, Windows, ...) and version?**
Amazon Linux 2

**Anything else we should know about your project / environment**
Dev environment: AWS EC2 server running Amazon Linux 2

**Comment by PierrickVoulet** [comment]
Hi @carthegian,

Thank you for the question. As you pointed out in # 2, gRPC solely relies on HTTP/2 so one solution is to make sure that only gRPC can be used as transport by the library. As described in the [PHP Transport documentation](https://developers.google.com/google-ads/api/docs/client-libs/php/transport), you can force the library to only use gRPC as transport by adding the following lines in your configuration file:

```properties
[CONNECTION]
transport = "grpc"
```

Please note that adding these lines will make the library fail when the required gRPC PHP Extension for the gRPC transport to be used is not well installed and configured.

**Comment by carthegian** [comment]
@PierrickVoulet 
Thank you for replying. That's very reassuring to know that I can limit transport only to gRPC.

Instead of enforcing transport in config file I did so programmatically as shown below.
```
$this->googleAdsClient = (new GoogleAdsClientBuilder())
            ->withOAuth2Credential($oAuth2Credential)
            ->withDeveloperToken(DEVELOPER_TOKEN)
            ->withLoginCustomerId(LOGIN_CUSTOMER_ID)
            ->withLogger(new Log(CHANNEL_API))
            ->withLogLevel(LOG_LEVEL)
            ->withTransport('grpc')
            ->build();
```

No error encountered as I have installed gRPC PHP Extension properly. I guess this means my application is handling HTTP/2 correctly, right?

**Comment by PierrickVoulet** [comment]
That should be the case as gRPC relies on HTTP/2.

**Comment by carthegian** [comment]
Excellent. Thank you very much.
I think you can close this issue now.
