### ISSUE TITLE
Undefined method named hasOneof

### ISSUE THREAD

**Issue by leongersen** [googleads/google-ads-php#432]
**Which version of the client library are you using?**
V5

**Which version of PHP are you using?**
7.4

In V5, the method `\Google\Ads\GoogleAds\V5\Resources\Ad::hasExpandedTextAd` was added, amongst several other has- methods. These methods would be helpful, but use a `hasOneof` method, which is not defined. Calling these has methods result in an error:

```
Attempted to call an undefined method named "hasOneof" of class "Google\Ads\GoogleAds\V5\Resources\Ad".
```

**Comment by PierrickVoulet** [comment]
Thank you for reporting this, @leongersen. This is one more unfortunate consequence of a known issue on protobuf's side https://github.com/protocolbuffers/protobuf/issues/7926. The [`hasOneOf` method should be defined when using protobuf v3.13.0](https://github.com/protocolbuffers/protobuf/blob/v3.13.0/php/src/Google/Protobuf/Internal/Message.php#L228) but it is currently not.

**Comment by PierrickVoulet** [comment]
@leongersen the issue should be fixed on protobuf's side with the version [v3.13.0.1](https://packagist.org/packages/google/protobuf#v3.13.0.1).

Could you update your dependencies (run `composer update`) and give it another try?

**Comment by leongersen** [comment]
I just updated the `google/protobuf`) to v3.13.0.1, and the PHP code now has the `hasOneOf` method. Unfortunately, I'm using the PECL extension, which I also updated to 3.13.0.1, but there I'm still running into this issue.

**Comment by PierrickVoulet** [comment]
I do not reproduce with the version 3.14.0 of Protobuf (tested with both the PHP and C implementations).
