### ISSUE TITLE
error creating new ad schedule (campaign criterion) after updating to v5

### ISSUE THREAD

**Issue by fruwolt** [googleads/google-ads-php#434]
**Which version of the client library are you using?**
v5
according to composer.json following libraries/versions are in use:
....    
"require": {
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.6.*",
        "vlucas/phpdotenv": "~2.2",
        "googleads/google-ads-php": "5.0.0",
        "google/protobuf": "v3.13.0",
        "google/gax": "1.4.0",
        "ulrichsg/getopt-php": "v3.4.0"
},
...

**Which version of PHP are you using?**
v7.1.3

**Which operating system (Linux, Windows, ...) and version?**
debian 9 (docker)

**Actions taken**
I'm trying to upload new ad schedules (campaign criteria) by creating the necessary campaignCriterionOperation objects.
I tried to follow this example: https://developers.google.com/google-ads/api/docs/samples/add-campaign-targeting-criteria#php for creating new campaign criteria, so my code especially sets the campaign (resource name) for each campaignCriterion.

my code looks like:

($accountId and $campaignId are given as int values, both account and campaign exist. The $googleAdsClient is given too and generally works)

```
use Google\Ads\GoogleAds\Lib\V5\GoogleAdsClient;
use Google\Ads\GoogleAds\Util\V5\ResourceNames;
use Google\Ads\GoogleAds\V5\Common\AdScheduleInfo;
use Google\Ads\GoogleAds\V5\Enums\DayOfWeekEnum\DayOfWeek;
use Google\Ads\GoogleAds\V5\Enums\MinuteOfHourEnum\MinuteOfHour;
use Google\Ads\GoogleAds\V5\Resources\CampaignCriterion;
use Google\Ads\GoogleAds\V5\Services\CampaignCriterionOperation;

...
        
        $adScheduleInfo = new AdScheduleInfo([
            'day_of_week' => DayOfWeek::MONDAY,
            'start_hour' => 18,
            'start_minute' => MinuteOfHour::ZERO,
            'end_hour' => 21,
            'end_minute' => MinuteOfHour::ZERO,
        ]);
        $campaignCriterion = new CampaignCriterion(
            [
                'ad_schedule' => $adScheduleInfo,
                'campaign' => ResourceNames::forCampaign($accountId, $campaignId),
            ]
        );

        $op = new CampaignCriterionOperation(['create' => $campaignCriterion]);
        var_dump($op->getCreate()->getCampaign());
        $operations[] = $op;

        $response = $googleAdsClient->getCampaignCriterionServiceClient()->mutateCampaignCriteria($accountId, $operations);
```

The var_dump() prints: 
....xy.php:90:string 'customers/[myAccountId]/campaigns/[myCampaignId]' (length=41)

**Expected result**
new ad schedule to be created for given campaign in given account

**Actual result**

error message in log file:
```
[2020-10-07 11:11:23] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v5.services.CampaignCriterionService/MutateCampaignCriteria", CustomerId: [accountId], RequestId: "xHQjHpvu1b6UbnIn1TOp6A", IsFault: 1, FaultMessage: "["Field 'campaign' is required for 'CREATE' operation."]"  
[2020-10-07 11:11:23] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v5.services.CampaignCriterionService/MutateCampaignCriteria
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.3.18 gapic\/ gax\/1.4.0 grpc\/1.29.1",
    "x-goog-request-params": "customer_id=[accountId]",
    "developer-token": "REDACTED",
    "login-customer-id": "[loginCustomerId]"
}
Request: {"customerId":"[accountId]","operations":[{"create":{"adSchedule":{"startMinute":"ZERO","endMinute":"ZERO","dayOfWeek":"MONDAY"}}}]}

Response
-------
Headers: {
    "request-id": "xHQjHpvu1b6UbnIn1TOp6A",
    "date": "Wed, 07 Oct 2020 09:11:22 GMT",
    "alt-svc": "h3-Q050=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"requestError":"REQUIRED_FIELD_MISSING"},"message":"Field 'campaign' is required for 'CREATE' operation.","location":{"fieldPathElements":[{"fieldName":"operations","index":"0"},{"fieldName":"create"},{"fieldName":"campaign"}]}}]}  
```

**Anything else we should know about your project / environment**

I can see that according to the error message the campaign is missing (and btw. the start_hour and end_hour are missing too, but probably this has not been checked until now)
The code worked before upgrading the library to v5 (v2-v4 are working).

For the v5 upgrade i replaced e.g.  
'campaign' => new StringValue(['value' => ResourceNames::forCampaign($accountId, $campaignId)]), 
with
'campaign' => ResourceNames::forCampaign($accountId, $campaignId),

(if i try to use StringValue, there's an error saying sth like 'string expected')

I'm still not sure if it is my code or maybe an underlying problem with the libraries/versions in use..

Any help is much appreciated!

Regards
Frank

**Comment by fiboknacky** [comment]
Do you use the [C implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#c_implementation) or [PHP implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#php_implementation) of Protobuf?

If the latter, could you please try the C implementation?
We have a known issue with the PHP implementation right now.

**Comment by fruwolt** [comment]
sorry for the late reply... unfortunately i can't test the protobuf c alternative at the moment
i hope this will be possible again in a few days, i'll check that as soon as possible

(and we're on v4 already - instead of v5 as planned before, so maybe i can just wait for an updated protobuf php implementation, if there's already a known issue)

**Comment by fiboknacky** [comment]
Sure. Please try and let us know. Happy to help. :)

**Comment by PierrickVoulet** [comment]
@fruwolt a new version [3.14.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0) of Protobuf was released with important fixes for PHP, could you give it another try after upgrading?

**Comment by fruwolt** [comment]
hey, just tried again with protobuf v3.14.0 - and it worked like a charm! 
thanks a lot for you help!
