### ISSUE TITLE
Add support of adding members to CrmBasedUserList

### ISSUE THREAD

**Issue by AloneCoder** [googleads/google-ads-php#435]
Hello!

Currently this feature is not supported by new Google Ads API and it blocks our project to upgrade the library, so we need to support both versions. This is not very effective, could you please estimate when this will be added?

#93 is closed and there no info about your plans about this feature

**Comment by fiboknacky** [comment]
Hello there,

As this is a product-level feature request, could you please request it in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)?
Thanks for your understanding.

Best,
Knack
