### ISSUE TITLE
Does the laravel sample support v2 of the framework?

### ISSUE THREAD

**Issue by nwbirnie** [googleads/google-ads-php#438]
https://github.com/googleads/google-ads-php/tree/master/examples/LaravelSampleApp

A partner is asking if we can support v2 of Laravel. I'll send them this thread to follow up directly, rather than having me as the middleman.

**Comment by nwbirnie** [comment]
Also do we have a previous example that shows v2 of Laravel?

**Comment by mk-ryan1988** [comment]
Hi there, partner in question here. Just to follow up on what Nick kindly posted here.

I'm looking to see if there a any Laravel samples using V2 of the Google Ads API

**Comment by nwbirnie** [comment]
Ah sorry my mistake - so v2 is almost at end of life - we'll be sunsetting it in the near future. Can I ask why you need to pin to that version?

**Comment by fiboknacky** [comment]
+1 to what Nick said. Could you please consider using v5 instead?

**Comment by mk-ryan1988** [comment]
Thank you both for you replies. Hopefully in the near future I can be in a position to use V5 however currently, due to php version, I cannot but will look to speed up the upgrade path. Thanks again!

**Comment by fiboknacky** [comment]
Thanks for your understanding. I'll close this issue for now, but let us know if you need any help.
