### ISSUE TITLE
When will the MerchantCenterLinkService be implemented?

### ISSUE THREAD

**Issue by sipplified** [googleads/google-ads-php#44]
Hi there,

My team is looking to use the new MerchantCenterLinkService to connect our ads accounts with merchant center accounts. The service is [available in the docs](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#google.ads.googleads.v1.services.MerchantCenterLinkService) but not yet implemented in this library. Do you have a timeframe on when this service will be available?

Thanks!

**Comment by fiboknacky** [comment]
Hello,

Sorry for your inconvenience. We'll release that service soon probably by next week.

Knack

**Comment by fiboknacky** [comment]
This is now fixed with [v1.1.0](https://github.com/googleads/google-ads-php/releases/tag/v1.1.0)
