### ISSUE TITLE
Not enough memory resources error

### ISSUE THREAD

**Issue by xiaawan** [googleads/google-ads-php#440]
When I try to run this command "composer require googleads/google-ads-php" I am getting following error despite of allocating enough memory to PHP.

[0x00000008] Not enough memory resources are available to process this command
--

**Comment by fiboknacky** [comment]
Do you get this error when trying to install other libraries too?

**Comment by xiaawan** [comment]
No, others are fine. Only when I try to run "composer require googleads/google-ads-php". I reinstalled composer, allocated infinite memory to PHP in php.ini for memory_limit. But still getting this error.

**Comment by fiboknacky** [comment]
I've never got this issue before too. Does [this](https://stackoverflow.com/a/63743593) help?

**Comment by fiboknacky** [comment]
And what is your PHP version and what environment do you develop (32 bit vs 64 bit) (Windows, Mac or Linux)?

**Comment by xiaawan** [comment]
I am on windows 10,  64 bit and using xampp. 
PHP version: 7.2.14
The only thing I suspect is my PHP is 32 bit. Would it be something that causing the problem? By the way, I also faced this problem for the first time and unfortunately only when I try to install this library.

**Comment by fiboknacky** [comment]
From my quick search, it's possible, but I cannot say it for sure.
So far, PHP 32 bit would affect some edge cases, like very large number in objects, but I've never got any report about this before.
Could you please also try asking [here](https://github.com/composer/composer/issues) too?

**Comment by xiaawan** [comment]
okay, thanks.
I will post an issue there as well.

**Comment by xiaawan** [comment]
hey @fiboknacky , thanks for your help early on. I didn't post a question there but went through already posted issues related to "memory resources error". It was suggested to upgrade composer to 2.0. Mine was "1.10.13". After upgrading composer to 2.0 the issue has been fixed. 

Once again thanks for your help :)

**Comment by fiboknacky** [comment]
Sure. Glad to hear that you could resolve your issue. :)
