### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by iammine21** [googleads/google-ads-php#441]
I'm trying to run some reports in the example folder and getting the error below.
Any idea what's missing?

I'm running: PHP 7.3.11 (cli) (built: Jun  5 2020 23:50:40) ( NTS )

Fatal error: Uncaught BadMethodCallException: Streaming calls are not supported while using the REST transport. in xxx/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php:125

Thanks!

**Comment by fiboknacky** [comment]
> Streaming calls are not supported while using the REST transport. in xxx/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php:125

As indicated, you need to [install gRPC](https://grpc.io/docs/languages/php/quickstart/#install-the-grpc-php-extension) in order to use an example that uses the stream call.
Please see [this page](https://developers.google.com/google-ads/api/docs/reporting/streaming) for more information.
