### ISSUE TITLE
Pass custom GuzzleHttpClient to RestTransport

### ISSUE THREAD

**Issue by mrpavlikov** [googleads/google-ads-php#442]
**Describe the problem you are trying to solve**

I have my own `GuzzleHttp\Client` with desired settings like timeouts and middlewires, which do profiling e.t.c. I see `\Google\ApiCore\Transport\RestTransport` seems to be able to get it from config, but I've found no way to pass it when building Google Ads Client like this:

```
$oAuth2Credential = (new OAuth2TokenBuilder())->fromFile($ini)->build();
$googleAdsClient = (new GoogleAdsClientBuilder())
    ->fromFile($ini)
    ->withOAuth2Credential($oAuth2Credential)
    ->withTransport('rest')
    ->build();
```

Is there one?

**Comment by fiboknacky** [comment]
Could you check if this is similar to [this reported issue](https://github.com/googleads/google-ads-php/issues/207)?
I'd like to keep requests in one place so we can track and prioritize properly. :)

**Comment by mrpavlikov** [comment]
That would do, thanks!
