### ISSUE TITLE
Methods on $googleAdsRow

### ISSUE THREAD

**Issue by chrisooo3** [googleads/google-ads-php#453]
I have query `SELECT campaign.name, ad_group_ad.ad.responsive_display_ad.marketing_images, ad_group_ad.ad.id FROM ad_group_ad`

Which method allow me to get `ad_group_ad.ad.responsive_display_ad.marketing_images`?
```php
foreach ($stream->iterateAllElements() as $googleAdsRow) {
                /** @var GoogleAdsRow $googleAdsRow */
                print($googleAdsRow->getAdGroupAd()->getAd()->getResponsiveDisplayAd()->getMarketingImages()<???);
        }
```

**Comment by PierrickVoulet** [comment]
Hi @chrisooo3 - There are multiple marketing images so you need to loop on them. You could do something like the following:

```php
foreach ($googleAdsRow->getAdGroupAd()->getAd()->getResponsiveDisplayAd()->getMarketingImages() as $marketingImage) {
    /** @var AdImageAsset $marketingImage */
    print $marketingImage->getAsset();
}
```

Please note that `$marketingImage->getAsset()` returns [the resource name of the asset](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V5/Common/AdImageAsset.php#L19). You can refer to the code example [GetAllImageAssets](https://github.com/googleads/google-ads-php/blob/master/examples/Misc/GetAllImageAssets.php) to learn how to retrieve information about image assets.
