### ISSUE TITLE
Wrong return value

### ISSUE THREAD

**Issue by chrisooo3** [googleads/google-ads-php#454]
Why this method does not return `\Google\Ads\GoogleAds\V5\Common\ResponsiveDisplayAdInfo` ?
https://github.com/googleads/google-ads-php/blob/4355e2b7c01a57212d09a8905d6b943809f56892/src/Google/Ads/GoogleAds/V5/Resources/Ad.php#L1208

**Comment by PierrickVoulet** [comment]
HI @chrisooo3 - [Ads can be of different types](https://developers.google.com/google-ads/api/docs/ads/ad-types#description_of_each_ad_type), this method only returns a value for the ads that are of the type `ResponsiveDisplayAd`.

When retrieving ads, you can filter on the ad type like it is done in the code example [GetResponsiveSearchAds](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/GetResponsiveSearchAds.php#L125) for the ads of type `ResponsiveSearchAd`.
