### ISSUE TITLE
GetAccountHierarchy example

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#458]
Hi,

I think GetAccountHierarchy example [here](https://github.com/googleads/google-ads-php/blob/8b3de48a65251309e6473528d21dfce3fc0f7ac0/examples/AccountManagement/GetAccountHierarchy.php#L293) should be customer_id instead customer.

It is giving error **Notice: Undefined index: customer** because index is customer_id.

Also there is no way to avoid any accounts which are inactive or in draft.

Thanks,

**Comment by PierrickVoulet** [comment]
Thanks @chiragvels for reporting this!
