### ISSUE TITLE
Undefined method named hasOneof (v6)

### ISSUE THREAD

**Issue by digtyarenko** [googleads/google-ads-php#460]
Call to undefined method Google\Ads\GoogleAds\V6\Resources\Ad::hasOneof()

Library version: v6
PHP version: 7.3
"google/protobuf" version: v3.14.0

Problem is like https://github.com/googleads/google-ads-php/issues/432 but it was solved in v5 package and works well!

But when I use **v6 package** this problem manifests itself for v5 and v6 classes, I am getting the following errors:
`Call to undefined method Google\Ads\GoogleAds\**V6**\Resources\Ad::hasOneof()`
or
`Call to undefined method Google\Ads\GoogleAds\**V5**\Resources\Ad::hasOneof()`

When I do rollback to v5 package all works well.

**Comment by fiboknacky** [comment]
Do you use the version installed using PECL (the C implementation) or the PHP implementation?

**Comment by digtyarenko** [comment]
> Do you use the version installed using PECL (the C implementation) or the PHP implementation?

We use PHP implementation

**Comment by fiboknacky** [comment]
Could you try using the C implementation to see if your issue persists?

**Comment by digtyarenko** [comment]
PECL package
protobuf   3.13.0

`php -i | grep protobuf`

```
/etc/php.d/40-protobuf.ini,
protobuf
protobuf.keep_descriptor_pool_after_request => 0 => 0
```
which means we're using now the C implementation 
https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#determine_which_implementation_is_being_used

The problem still persists

**Comment by fiboknacky** [comment]
Do you use 3.13 or 3.14?

**Comment by digtyarenko** [comment]
> Do you use 3.13 or 3.14?

PECL package
protobuf 3.13.0

**Comment by fiboknacky** [comment]
Could you upgrade to 3.14?
I was a bit confused because you said you use 3.14. :)

**Comment by PierrickVoulet** [comment]
I do not reproduce with the version 3.14.0 of Protobuf (tested with both the PHP and C implementations). Feel free to reopen if you find that the issue persists on your side.
