### ISSUE TITLE
Update campaign budget

### ISSUE THREAD

**Issue by aartDev** [googleads/google-ads-php#462]
sdk version :  "googleads/google-ads-php": "v6.0.0"
php version: 7.2.34
OS : Ubuntu 16.04

**Actions**

<pre>

          $googleAdsClient = (new GoogleAdsClientBuilder())->fromFile()
            ->withOAuth2Credential($oAuth2Credential)
            ->build();

          $campaignBudget = new CampaignBudget(
              [
                  'resource_name' => ResourceNames::forCampaignBudget($customerId, $budgetId),
                  'amount_micros' => $budgetAmount,
              ]
           );

          $operation = new CampaignBudgetOperation();
          $operation->setUpdate($campaignBudget);
          $operation->setUpdateMask(FieldMasks::allSetFieldsOf($campaignBudget));
  

         $campaignBudgetServiceClient = $googleAdsClient->getCampaignBudgetServiceClient();
         $response = $campaignBudgetServiceClient->mutateCampaignBudgets($customerId, [$operation]);

</pre>

**I have got error**

<pre>

Array
(
    [0] => Array
        (
            [0] => NOTICE
            [1] => Request
-------
Method Name: /google.ads.googleads.v6.services.CampaignBudgetService/MutateCampaignBudgets
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.2.34-8+ubuntu16.04.1+deb.sury.org+1 gapic\/ gax\/1.6.0 grpc\/1.25.0",
    "x-goog-request-params": "customer_id=2717202935",
    "developer-token": "REDACTED",
    "login-customer-id": "2717202935"
}
Request:
{"customerId":"2717202935","operations":[{"updateMask":"resourceName,amountMicros","update":{"resourceName":"customers\/2717202935\/campaignBudgets\/7575069810"}}]}

Response
-------
Headers: {
    "request-id": "WvRf0gxVVM7hqj1ifJ9kKg",
    "date": "Thu, 19 Nov 2020 16:08:23 GMT",
    "alt-svc": "h3-Q050=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"requestError":"UNKNOWN"},"message":"The error code is not in this version.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations"},{"fieldName":"update"},{"fieldName":"amount_micros"}]}}]}
            [2] => Array
                (
                )

        )

)

</pre>

**Comment by PierrickVoulet** [comment]
The root cause is that, for some reason, the request did not contain the `amount_micros` value even though the field is in the `updateMask`. See: `{"customerId":"2717202935","operations":[{"updateMask":"resourceName,amountMicros","update":{"resourceName":"customers\/2717202935\/campaignBudgets\/7575069810"}}]}`

I gave it a try on my side with a few different environments but could not reproduce the issue: the `amount_micros` value is always passed in the request and the budget amount is successfully updated by the API call.

Could you double check that your variable `$budgetAmount` is not `null` and not `0`? Also, what [protobuf](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf) and [transport](https://developers.google.com/google-ads/api/docs/client-libs/php/transport) you are using?

**Comment by aartDev** [comment]
So, when I try to send `$budgetAmount` equal `null`, I have mistake from `GPBUtil::checkInt64()`, it's normal.

The value of my `$budgetAmount` variable equal `1770000`
I was set different values, but always have mistake  which I show in my issue.

I use:
<pre>
        "grpc/grpc": "1.25.0",
        "google/protobuf": "3.13.0",
</pre>

**Comment by PierrickVoulet** [comment]
Thank you for the extra information, I was able to narrow it down to the `protobuf` dependency.

This issue only occurs when using the version `3.13.0` of the [PHP implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#php_implementation) of `protobuf`.

I was able to fix this by either:

* Installing and configuring the [C implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#c_implementation). The versions `3.13.0` and `3.14.0` are both OK but I advice you to go with `3.14.0` if you can.
* Keeping the PHP implementation but upgrading to the version `3.14.0` (`"google/protobuf": "3.14.0"`)

**Comment by aartDev** [comment]
@PierrickVoulet, thank you so much!
After I updated `"google/protobuf"` to  `"3.14.0"` it started work
