### ISSUE TITLE
PartialFailureError fails to JSON serialize

### ISSUE THREAD

**Issue by leongersen** [googleads/google-ads-php#469]
**Which version of the client library are you using?**
V5

**Which version of PHP are you using?**
PHP 7.4.4

The response from `\Google\Ads\GoogleAds\V5\Services\Gapic\AdGroupCriterionServiceGapicClient::mutateAdGroupCriteria` fails to serialize with the following error:

```
Error occurred during JSON serialization: Couldn't find Any type: google.ads.googleads.v5.errors.GoogleAdsFailure
```

I've tried this with some different operations, those don't seem to make a difference.
```
{"update":{"resourceName":"<a resource name>","status":"PAUSED"}}
```

To narrow it down, I get the same error when trying to serialize the partial failures:

```
$response->getPartialFailureError()->serializeToJsonString()
```

**Comment by PierrickVoulet** [comment]
Hi @leongersen - Please provide the following information so that we can investigate further:

1. A minimal snippet of code to reproduce the error
1. I understand that you use the version 5 of the API? What [version](https://github.com/googleads/google-ads-php/releases) of the library are you using?
1. What implementation (PHP extension or not) and version of [grpc](https://developers.google.com/google-ads/api/docs/client-libs/php/transport) and [protobuf](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf) are you using?
1. Does it also fail when you use gRPC instead of REST?

**Comment by leongersen** [comment]
1. Minimum reproduction:

```PHP
$adGroupCriterion = new AdGroupCriterion();
$adGroupCriterion->setResourceName(
	ResourceNames::forAdGroupCriterion(
		$remoteAccountId,
		<id for ad group>,
		<id for keyword>
	)
);
$adGroupCriterion->setCpcBidMicros(800); // Too small, trigger partial failure

$operation = new AdGroupCriterionOperation();
$operation->setUpdate($adGroupCriterion);
$operation->setUpdateMask(FieldMasks::allSetFieldsOf($adGroupCriterion));

$response = $client->mutateAdGroupCriteria((string)$remoteAccountId, [$operation], ['partialFailure' => true]);

$response->serializeToJsonString();

// =>  Error occurred during JSON serialization: Couldn't find Any type: google.ads.googleads.v5.errors.GoogleAdsFailure
```

I'm using release V5.0.0, and the PHP extension. I had my packages at `php-pecl-protobuf` 3.13.0.1 and `php-pecl-grpc` 1.32.0. The issue also occurs when updating both to 3.14.0 for protobuf and 1.33.1 for grpc.

**Comment by PierrickVoulet** [comment]
Thanks for the additional information @leongersen .

I had to change the line
```php
$operation->setUpdateMask(FieldMasks::allSetFieldsOf($adGroupCriterion));
```
with
```php
$operation->setUpdateMask(new FieldMask(['paths' => ['resource_name', 'cpc_bid_micros']]));
```
to avoid the `hasOneOf` issue but I was not able to reproduce the issue you are getting using your versions of the dependencies.

Could you try upgrading and let us know if the issue persists?

* Change for the version `v6.0.0` of the library. **Note:** there is no need to migrate to the V6 of the API though, you can still use the version 5 if wanted.
* Run `composer update`
* Run `pecl install protobuf` and configure the `protobuf` extension in your `php.ini`
* Run `pecl install grpc` and configure the `grpc` extension in your `php.ini`

**Comment by leongersen** [comment]
I just updated to V6.0.0; the issue persists. I already have the pecl extensions installed and configured.

Regarding the field mask, the request doesn't actually need to contain any updates to trigger the serialization issue, the following will also trigger it:

```php
$operation = new AdGroupCriterionOperation();
$operation->setUpdate($new AdGroupCriterion());

$response = $client->mutateAdGroupCriteria((string)$remoteAccountId, [$operation], ['partialFailure' => true]);

$response->serializeToJsonString();
```

**Comment by PierrickVoulet** [comment]
Thank you for the clarification and for trying the upgrade. Not sure why but I am still unable to reproduce. Could you go through the following instructions to provide us with more detailed information about your environment?

- The output generated by the script [`scripts/print_php_information.php`](https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php).
- The value of the `transport` [client configuration](https://developers.google.com/google-ads/api/docs/client-libs/php/configuration) setting (if set).

**Comment by leongersen** [comment]
Sure thing, thanks for investigating. 

I do not have the `transport` option set.


The requested output:
```
================= PHP GENERAL INFORMATION
phpinfo()
PHP Version => 7.4.4

System => Linux 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64
Build Date => Mar 17 2020 10:40:21
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc
Loaded Configuration File => /etc/php.ini
Scan this dir for additional .ini files => /etc/php.d
Additional .ini files parsed => 

...

PHP API => 20190902
PHP Extension => 20190902
Zend Extension => 320190902
Zend Extension Build => API320190902,NTS
PHP Extension Build => API20190902,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => available, disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, compress.bzip2, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.2, sslv2
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*, mcrypt.*, mdecrypt.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
    with blackfire v1.34.3~linux-x64-non_zts74, https://blackfire.io, by Blackfire
================= PHP EXTENSION INFORMATION
The PHP Extension grpc is installed: 1.33.1
The PHP Extension protobuf is installed: 3.14.0
```

**Comment by PierrickVoulet** [comment]
I do not reproduce even though I have a quite similar environment as you. The only difference is that I use PHP 7.4.11 instead of 7.4.4 which is minor.

I am suspecting the descriptor pool to not be initialized as it should be. Could you add these lines before sending the request and try again?

```php
\Google\Ads\GoogleAds\Util\V5\GoogleAdsFailures::init();
\Google\Ads\GoogleAds\Util\V6\GoogleAdsFailures::init();
```

**Comment by leongersen** [comment]
Yes, calling those (the V5 version specifically, in my case) resolves the issue, and results in a proper serialization.

**Comment by PierrickVoulet** [comment]
I reproduce the issue after changing the log level from `DEBUG` to `INFO`. I think the `DEBUG` log level somehow makes the initialization because it needs to print the request logs but not the `INFO` log level.

Could you give it another try without the two lines `\Google\Ads\GoogleAds\Util\V...\GoogleAdsFailures::init();` but with `DEBUG` log level to confirm? You can do this editing your [configuration file](https://github.com/googleads/google-ads-php/blob/master/examples/Authentication/google_ads_php.ini#L38) if you use one.

**Comment by leongersen** [comment]
I just tried it again, and I can confirm that the issue does not occur with the log level set to `DEBUG`, but it does when it is set to `INFO`.

**Comment by PierrickVoulet** [comment]
I took a look and this arguably work as intended, I created a feature request #481 to improve this.

To avoid this behavior, the best is to make a preemptive `GoogleAdsFailures::init()` call as previously suggested.
