### ISSUE TITLE
BiddingSource Enum Numbers are not valid for V1 (0,1,2,3,5 vs 0,1,5,6,7) 

### ISSUE THREAD

**Issue by PaoloNardini** [googleads/google-ads-php#47]
BiddingSource Enum seems to be changed in V1, but enum class is not updated.

This bug has already been fixed in the Pyhton library (https://github.com/googleads/google-ads-python/issues/49)

**Comment by fiboknacky** [comment]
Mattia, could you take a look? Perhaps, refer to the protobuf definition to double check

**Comment by fiboknacky** [comment]
@PaoloNardini  Thanks for the feedback.
What version of the client library are you referring to?

**Comment by PaoloNardini** [comment]
I'm using the latest v.1.0.0

**Comment by fiboknacky** [comment]
The [BiddingSource enum](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V1/Enums/BiddingSourceEnum/BiddingSource.php) is like what you said.
Can you confirm again please?

**Comment by Raibaz** [comment]
Looks like this was fixed by V1_1.

Please confirm that we can close the issue.

**Comment by PaoloNardini** [comment]
Thank you, I confirm it's working now on V 1.1
