### ISSUE TITLE
FieldMasks::allSetFieldsOf not setting enhancedCpcEnabled > false

### ISSUE THREAD

**Issue by raalderink** [googleads/google-ads-php#480]
When using the `FieldMasks::allSetFieldsOf` to set a `ManualCpc` on a campaign, it will not update the campaign when `enhancedCpcEnabled` is `false`. However, if this field is `true`, it does. See code below to reproduce. I would expect that if you turn Enhanced CPC off, it would still see it as an update.

**What versions of the client library and Google Ads API are you using?**

v5.0.0 and V5
I checked the `FieldMasks` of V6 and it does the same thing

**What environment are you using?**

- PHP 7.4.12
- Linux 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64
- Protobuf; C version 3.14.0
- gRPC version 1.33.1

**Actions taken**

```
$googleCampaign = new Campaign();
$googleCampaign->setResourceName(ResourceNames::forCampaign($accountId, $campaignId));

$manualCpc = new ManualCpc();
$manualCpc->setEnhancedCpcEnabled($biddingStrategyModel->isEnhancedCpc());

$googleCampaign->setManualCpc($manualCpc);

var_dump(FieldMasks::allSetFieldsOf($googleCampaign)->serializeToJsonString());
```

**Expected result**
```
"resourceName,manualCpc.enhancedCpcEnabled"
```

**Actual result**
```
"resourceName"
```

**Comment by PierrickVoulet** [comment]
I reproduce and believe this is because we do not differentiate whether an object is null or a false boolean. I created a PR that should fix this issue $480.

**Comment by leongersen** [comment]
I'm running into incomplete field masks as well, in my case when using empty arrays or empty strings.

```
$keywordPlanCampaign = (new KeywordPlanCampaign())
	->setResourceName('') // as an example
	->setCpcBidMicrosUnwrapped(1000000)
	->setLanguageConstants([]); // legitimate use case

var_dump(FieldMasks::allSetFieldsOf($keywordPlanCampaign)->serializeToJsonString());
```

**Expected result**

```
"resourceName,languageConstants,cpcBidMicros"
```

**Actual result**

```
"cpcBidMicros"
```

**Comment by PierrickVoulet** [comment]
> I'm running into incomplete field masks as well, in my case when using empty arrays or empty strings.
> 
> ```
> $keywordPlanCampaign = (new KeywordPlanCampaign())
> 	->setResourceName('') // as an example
> 	->setCpcBidMicrosUnwrapped(1000000)
> 	->setLanguageConstants([]); // legitimate use case
> 
> var_dump(FieldMasks::allSetFieldsOf($keywordPlanCampaign)->serializeToJsonString());
> ```
> 
> **Expected result**
> 
> ```
> "resourceName,languageConstants,cpcBidMicros"
> ```
> 
> **Actual result**
> 
> ```
> "cpcBidMicros"
> ```

Hi @leongersen - thank you for flagging this, I created a new issue #487 based on your comment for further investigation.
