### ISSUE TITLE
Lazily init GoogleAdsFailure from gRPC interceptor

### ISSUE THREAD

**Issue by PierrickVoulet** [googleads/google-ads-php#481]
**Describe the problem you are trying to solve**

As originally found in #469 the descriptor pool is lazily initialized with the class `GoogleAdsFailure` at log level `DEBUG` but not at coarser log levels (e.g., `INFO`, `ERROR`): this can lead to unexpected behaviors.

**Describe the solution you would like**

We need to start by identifying all the locations where the class `GoogleAdsFailure` is initialized in the descriptor pool and make sure that it covers all the use cases.

Typically, changing the initialization done in the logger to a gRPC interceptor seems to be a good overall improvement.

**Comment by fiboknacky** [comment]
> at log level DEBUG but not at lower log levels

Do you mean "finer" or "coarser" (e.g., INFO, ERROR)?

**Comment by PierrickVoulet** [comment]
> Do you mean "finer" or "coarser" (e.g., INFO, ERROR)?

I mean "coarser" (e.g., INFO, ERROR).
