### ISSUE TITLE
Why i cant get the AveragePosition? it's very important

### ISSUE THREAD

**Issue by devorel** [googleads/google-ads-php#502]
https://github.com/googleads/google-ads-php/blob/ce3ab484ea4363cd31c55f017ca814c580ba9fc2/examples/Planning/GenerateForecastMetrics.php#L120

in the old api , i can get it 
https://developers.google.com/adwords/api/docs/samples/php/optimization
```
        $meanAveragePosition = self::calculateMean(
            $minEstimate->getAveragePosition(),
            $maxEstimate->getAveragePosition()
        );
```

**Comment by fiboknacky** [comment]
As this is related to the Google Ads API in general, please reach out to the experts on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api). Thank you.
