### ISSUE TITLE
SummaryRowSetting

### ISSUE THREAD

**Issue by chrisooo3** [googleads/google-ads-php#503]
Why summaryRowSetting does not appear when I am dumping the results?
My code:
```php
            // Builds the GAQL query.
            $query = sprintf(
                "SELECT %s FROM %s ",
                join(", ", $selectedFields),
                $reportType
            );

            // Searches the results using streaming.
            /** @var GoogleAdsServerStreamDecorator $stream */
            $stream = $googleAdsClient->getGoogleAdsServiceClient()->searchStream(
                $customerId,
                $query,
                ['returnTotalResultsCount' => true, 'summaryRowSetting' => 3]
            );
            // Fetches all the results.
            $results = [];
            foreach ($stream->iterateAllElements() as $googleAdsRow) {
                /** @var GoogleAdsRow $googleAdsRow */
                // Converts each result as a Plain Old PHP Object (POPO) using JSON.
                $results[] = json_decode($googleAdsRow->serializeToJsonString(), true);
            }
            dump($results);
```
I would like to get this type of summary: 
![image](https://user-images.githubusercontent.com/70841270/102473448-c10b2e80-4057-11eb-881f-eacee1a6d8d5.png)

**Comment by PierrickVoulet** [comment]
Hi @chrisooo3 - Your code looks correct to me, could you provide more information for us to reproduce the issue:

**What versions of the client library and Google Ads API are you using?**

- Client library (format: `vX.Y.Z`): the exhaustive list of all released versions of the client library is in the repository [releases' page](https://github.com/googleads/google-ads-php/releases).
- Google Ads API (format: `VX`): you can find the major version of the Google Ads API used by checking the namespace of your `GoogleAdsClient`, e.g., `Google\Ads\GoogleAds\Lib\V6\GoogleAdsClient`.

**What environment are you using?**

The output generated by the script [`scripts/print_php_information.php`](https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php) can be used. Alternatively, you can provide with the following information:

- The PHP version: run `php -v`.
- The name and version of the operating system: run `php -r 'print php_uname();'`.
- Whether the C implementation of `protobuf` is used or not (see [details](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf)): run `php -r 'print phpversion("protobuf");'`.
- Whether the transport used is gRPC or REST (see [details](https://developers.google.com/google-ads/api/docs/client-libs/php/transport)): run `php -r 'print phpversion("grpc");'` and provide the value of the `transport` [client configuration](https://developers.google.com/google-ads/api/docs/client-libs/php/configuration) setting if set.

**Expected result**

**Actual result**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging)).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by chrisooo3** [comment]
Version v6.1.0
Google\Ads\GoogleAds\Lib\V6\GoogleAdsClient

PHP 7.4.3 
Linux 31c4b23d4031 5.4.0-58-generic #64-Ubuntu SMP
Yes - protobuf - 3.14.0
Yes - gRPC - 1.33.1

Expected result
Get summary results for each fields

Actual Result: 
Nothing

**Comment by PierrickVoulet** [comment]
Thank you, this is helpful! Could you provide us with request and response logs or request IDs of failing requests you are referring to? This will be useful to investigate if there is something wrong with the library and/or the Google Ads API.

**Comment by chrisooo3** [comment]
Where can I find it?

**Comment by chrisooo3** [comment]
Look one more time at my code. Are you sure that summary will be at ‘$results’ variable?

**Comment by PierrickVoulet** [comment]
> Where can I find it?

The use of [logging](https://developers.google.com/google-ads/api/docs/client-libs/php/logging) should be enough. By default, short logs should be printed on the console. You can use `DEBUG` to log more details.

**Comment by chrisooo3** [comment]
So I do not have any logs printed to the console

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I think also I would like to add that Summary data do not give bifurcation like It did in UI.
If I see Audience in UI there is summary rows which bifurcate data
Total: Audiences
Total: Expansion 
Total: Other
Total: Display Campaigns 
Total: Search Campaigns 

Sorry for posting here, I thought its relevant to this.

Thanks,

**Comment by PierrickVoulet** [comment]
I was able to make it work fine on my side using paginated `search`. The following prints the total number of clicks for all the campaigns as expected.:

```php
$query = 'SELECT campaign.id, campaign.name, metrics.clicks FROM campaign ORDER BY campaign.id';
$googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
/** @var PagedListResponse $paged */
$paged = $googleAdsServiceClient->search($customerId, $query, ['returnTotalResultsCount' => true]);

print $paged->getPage()->getResponseObject()->getSummaryRow()->getMetrics()->getClicks();
```

**Note:** make sure to include at least one `metrics` field in the selector or you will reach the error `CANNOT_RETURN_SUMMARY_ROW_FOR_REQUEST_WITHOUT_METRICS`.

Regarding `searchStream` I need more time to check it out, I will keep you posted.
