### ISSUE TITLE
Segmentation fault when trying to send a mutate request on AdGroupAd

### ISSUE THREAD

**Issue by benBidShake** [googleads/google-ads-php#514]
Client library: v5.0.0
Google Ads API: v5.0

running in docker

PHP 7.4.12 (cli) (built: Nov  5 2020 20:24:10) ( NTS )
Zend Engine v3.4.0,
ionCube PHP Loader + ionCube24 v10.4.4
Zend OPcache v7.4.12
protobuff 3.14.0
grpc 1.33.1

I'm trying to create an AdGroupAd using an existing groupAd, and i'm getting a "segmentation fault" error message
I've been at this for more than a day now, but the lack of details on the error just makes this insane to understand whats wrong

my code. Assume `createAdGroupAd()` is called with a valid resource name for an adGroup in the `$adGroup` parameter
and the type is `CreativeType_Asset::TYPE_YOUTUBE` in this case (although i tried with both types and both give out the error)
```
public function createAdGroupAd($adGroup, $data) {
		$service = $this->client->getAdGroupAdServiceClient();

		$ad = $this->createAd($data, $data['asset']->type);

		$adGroupAd = new AdGroupAd([
            'ad' => $ad,
			'status' => AdGroupAdStatus::PAUSED,
			'ad_group' => $adGroup
		]);

		$adGroupAdOperation = new AdGroupAdOperation();
		$adGroupAdOperation->setCreate($adGroupAd);

         //This call causes the fault
        $response = $service->mutateAdGroupAds(
			$this->customerId,
			[$adGroupAdOperation]
		);

		return $response->getResults()->count() > 0 ? $response->getResults()[0]->getResourceName() : null;
	}

	public function createAd($data, $adType = null) {
		$service = $this->client->getAdServiceClient();
		$appAdInfo = new AppAdInfo([
			'headlines' => array_map(function ($headline) {
				new AdTextAsset(['text' => $headline]);
			}, [$data['creative']->title1, $data['creative']->title2]),
			'descriptions' => array_map(function ($description) {
				new AdTextAsset(['text' => $description]);
			}, [$data['creative']->description1, $data['creative']->description2])
		]);

		switch ($adType) {
			case CreativeType_Asset::TYPE_IMAGE:
				$appAdInfo->setImages([new AdImageAsset(['asset' => $data['assetResourceName']])]);
				break;
			case CreativeType_Asset::TYPE_YOUTUBE:
				$appAdInfo->setYoutubeVideos([new AdVideoAsset(['asset' => $data['assetResourceName']])]);
				break;
			default:
				break;
		}

		return new Ad([
			'app_ad' => $appAdInfo,
			'type' => AdType::APP_AD]);
	}
```

**Comment by PierrickVoulet** [comment]
Hi @benBidShake - Could you provide us with request IDs and logs?

**Comment by benBidShake** [comment]
I'm not sure how to get that, theres no other erros outputted and there aren't any exceptions

**Comment by benBidShake** [comment]
Ok the issue was found.
I forgot to write "return" statements on the array_map functions in the AppAdInfo building part.
The segmentation fault is a real headache it gives no information about what is wrong

**Comment by PierrickVoulet** [comment]
Glad you found the issue!

Regarding the `Segmentation fault`, were you using the [C implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#c_implementation) of protobuf? If you were, could you give it another try using the [PHP implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#php_implementation) instead and let us know if more information would have been returned for debugging?

**Comment by benBidShake** [comment]
I wasn't able to install the php version in my project, i followed the steps but the C version was still active
