### ISSUE TITLE
Google\ApiCore\ValidationException: Failed to build request, as the provided path (google.longrunning.Operations/GetOperation) was not found in the configuration

### ISSUE THREAD

**Issue by fitzgeralddoe** [googleads/google-ads-php#522]
Library version: v6
PHP version: 7.3
"google/protobuf" version: v3.14.0 (C implementation)

Hello. Trying to run BatchJobOperation using "Usage flow" https://developers.google.cn/google-ads/api/docs/batch-processing/flow#php but always catch error like this:

`Google\ApiCore\ValidationException: Failed to build request, as the provided path (google.longrunning.Operations/GetOperation) was not found in the configuration. in /vendor/google/gax/src/RequestBuilder.php:80 Stack trace: #0 /vendor/google/gax/src/Transport/RestTransport.php(107)...`

Am I doing something wrong?
Thank you!

**Comment by fiboknacky** [comment]
Looks like you've not installed [gRPC](https://grpc.io/docs/languages/php/quickstart/#install-the-grpc-php-extension). Could you do that and try again?

**Comment by fiboknacky** [comment]
Close due to inactivity.
