### ISSUE TITLE
Fatal Error when requesting MUTATABLE_RESOURCE

### ISSUE THREAD

**Issue by mk-ryan1988** [googleads/google-ads-php#525]
**What versions of the client library and Google Ads API are you using?**

- Client library (format: `vX.Y.Z`): v5.0.0

**What environment are you using?**

- The PHP version: 7.4.12
- The name and version of the operating system: Darwin Marks-MBP.lan 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64% 
- Transport: gRPC

**Actions taken**

  $optionalArguments = [
      'responseContentType' => ResponseContentType::MUTABLE_RESOURCE,
  ];

  // Make the actual Google API request
  $response = $this->googleAdsClient->getGoogleAdsServiceClient()->mutate(
      $customerId,
      Arr::flatten($mutateOperations),
      $optionalArguments
  );

**Expected result**

Response contains MUTABLE_RESOURCEs

**Actual result**

array:1 [
  "request-id" => array:1 [
    0 => "1lva_znvCelT4tt1Y2UeOw"
  ]
]

LOGS:

Response
-------
Headers: {
    "request-id": "1lva_znvCelT4tt1Y2UeOw",
    "date": "Mon, 01 Feb 2021 10:17:59 GMT",
    "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault
-------
Status code: 13
Details: Internal error encountered.
Failure: {}  

 
**Anything else we should know about your project / environment**

My code executes as expected without the optional arguments in the mutate request.

**Comment by fiboknacky** [comment]
Looks like you hit unprecedented errors. I'm contacting engineers who work on this to see what happens.

**Comment by fiboknacky** [comment]
This would be fixed in around 4-5 days. Could you please try and let us know if it still fails?
I'll close this issue for now, as it turns out not related to the client library itself.
Feel free to re-open this later if needed.
