### ISSUE TITLE
How to convert the campaign budget from micros google ads API 

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/google-ads-php#537]
Hi, please explain the conversion of the campaign budget.

for example :
campaign budget is: RS 2000

1 . if I pass a campaign budget parameter is RS 2000, the campaign budget is taking 0.002 (micros) in Google ads campaign

but the actual campaign budget parameter is RS 2000.

$campaignBudget = new CampaignBudget([
'name' => $campaignname . uniqid(),
'campaign_goal' => 'Leads',
'delivery_method' => BudgetDeliveryMethod::STANDARD,
'amount_micros' => 2000
]);

Please tell me the calculation and how to pass it

How to set the campaign goal in the google ads API

**Comment by fiboknacky** [comment]
For the questions related to the Google Ads API, please post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
Feel free to use this issues tracker for this library-related questions or issues.

As for the conversion to and from micro amounts, we have some helper functions in [this file](https://github.com/googleads/google-ads-php/blob/master/examples/Utils/Helper.php#L52).
