### ISSUE TITLE
Changing Version from V0 to V1 cause PERMISSION_DENIED

### ISSUE THREAD

**Issue by whyjonii06** [googleads/google-ads-php#54]
Hi, i'm using the Google Ads API with PHP, i was using V0 and one INTERNAL ERROR came !
So i decide to try with the V1 but i have a PERMISSION_DENIED !

**Comment by fiboknacky** [comment]
Could you please reach out to [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) for help, as this is probably related to the product in general? 
Thanks.

Knack
