### ISSUE TITLE
Video Ad Create not allowing YoutubeVideoAssets

### ISSUE THREAD

**Issue by kevmul0929** [googleads/google-ads-php#554]
**What versions of the client library and Google Ads API are you using?**
V6

**What environment are you using?**
PHP 8.0.1 (I know this library isn't ready for 8.0 but I have what I need working)
Windows NT PC 10.0 build 19042 (Windows 10) AMD64
Transport gRPC v1.35.0

**Actions taken**
Creating new `VideoResponsiveAdInfo` with `YoutubeVideoAsset`

**Expected result**
Ad created with a Youtube Video

**Actual result**
Exception Thrown
`Expect Google\Ads\GoogleAds\V6\Common\AdVideoAsset`

 
**Anything else we should know about your project / environment**
I don't know if this is a bug or not, but seems like it. 
The documentation says that the `VideoResponsiveAdInfo` class accepts an array of YouTube Videos.
[Ad Documentation](https://developers.google.com/google-ads/api/reference/rpc/v6/Ad?hl=en#video_responsive_ad)
[Video Responsive Ad Info Documentation](https://developers.google.com/google-ads/api/reference/rpc/v6/VideoResponsiveAdInfo#videos[]) This says "List of YouTube video assets used for the ad."
Below is the source code from Google\Ads\GoogleAds\V6\Common\VideoResponsiveAdInfo to set videos
```
/**
     * List of YouTube video assets used for the ad.
     * Currently, only a single value for the YouTube video asset is supported.
     *
     * Generated from protobuf field <code>repeated .google.ads.googleads.v6.common.AdVideoAsset videos = 5;</code>
     * @param \Google\Ads\GoogleAds\V6\Common\AdVideoAsset[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVideos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Ads\GoogleAds\V6\Common\AdVideoAsset::class);
        $this->videos = $arr;

        return $this;
    }
```
However, the code only accepts `AdVideoAsset`. I had tried to change this source code to accept a `YoutubeVideoAsset` but 
I get the exception that `Expect repeated field of Google\Ads\GoogleAds\V6\Common\YoutubeVideoAsset.`

**Comment by PierrickVoulet** [comment]
Hi @kevmul0929 - Thank you for all these details.

Could you also provide us with the request and response [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging) of the failure (or a request ID)? I am trying to reproduce the issue.

**Comment by kevmul0929** [comment]
Hey Pierrick. I think the Log file I sent had the request id within it. It
was "request-id": "69c7Yjw3yTr7QpWat29Hsw", Let me know if that works. Let
me know if you need anything else :)

**Comment by PierrickVoulet** [comment]
Sorry but what file are you referring to? The request ID `69c7Yjw3yTr7QpWat29Hsw` is not related to the error you are describing, could you double check that this is the right ID?

**Comment by kevmul0929** [comment]
Hello Pierrick,

Sorry, I thought I had attached a file to a previous email. I have attached
a new error log to this email.

However, it doesn't really apply to the error I am getting. I don't think
the code actually gets far enough to send anything to your servers.
Instead, the code is just telling me that it expects
a Google\Ads\GoogleAds\V6\Common\AdVideoAsset but I am sending in
a Google\Ads\GoogleAds\V6\Common\YoutubeVideoAsset.

I would have thought these would be interchangeable. If not, I want to know
how I can create a video ad using an existing Youtube Video.

Here is some of my PHP code.


$adVideoAsset = new YoutubeVideoAsset([
    'youtube_video_id' => H4Enl6iz3O4
]);

$adInfo = new VideoResponsiveAdInfo([
    'videos' => [$adVideoAsset],
    'headlines' => [new AdTextAsset(['text' => 'Test'])],
    'descriptions' => [new AdTextAsset(['text' => 'My really cool
description'])]
]);

Thank you again for your time and help with this!

(incase the error log doesn't get attached)
[2021-03-13 06:55:48] testing.INFO: Request made: Host: "
googleads.googleapis.com", Method:
"/google.ads.googleads.v6.services.CampaignBudgetService/MutateCampaignBudgets",
CustomerId: 5763579756, RequestId: "YtVNtOVBGbyCGlwyjhTesw", IsFault: 0,
FaultMessage: "None"
[2021-03-13 06:55:48] testing.DEBUG: Request
-------
Method Name:
/google.ads.googleads.v6.services.CampaignBudgetService/MutateCampaignBudgets
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/8.0.1 gapic\/ gax\/1.7.0 grpc\/1.35.0",
    "x-goog-request-params": "customer_id=5763579756",
    "developer-token": "REDACTED",
    "login-customer-id": "5763579756"
}
Request:
{"customerId":"5763579756","operations":[{"create":{"name":"2021_03_13__Kevins
Test Campaign #1615647347 -
Budget","amountMicros":"10000","deliveryMethod":"STANDARD"}}]}

Response
-------
Headers: {
    "content-disposition": "attachment",
    "request-id": "YtVNtOVBGbyCGlwyjhTesw",
    "date": "Sat, 13 Mar 2021 14:55:47 GMT",
    "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\";
ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\";
ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000;
v=\"46,43\""
}
Response:
{"results":[{"resourceName":"customers\/5763579756\/campaignBudgets\/8344505416"}]}

[2021-03-13 06:55:48] testing.INFO: Request made: Host: "
googleads.googleapis.com", Method:
"/google.ads.googleads.v6.services.CampaignService/MutateCampaigns",
CustomerId: 5763579756, RequestId: "iQ4d1WEPCBTz8cVVwObaKg", IsFault: 0,
FaultMessage: "None"
[2021-03-13 06:55:48] testing.DEBUG: Request
-------
Method Name:
/google.ads.googleads.v6.services.CampaignService/MutateCampaigns
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/8.0.1 gapic\/ gax\/1.7.0 grpc\/1.35.0",
    "x-goog-request-params": "customer_id=5763579756",
    "developer-token": "REDACTED",
    "login-customer-id": "5763579756"
}
Request:
{"customerId":"5763579756","operations":[{"create":{"name":"2021_03_13__Kevins
Test Campaign
#1615647347","status":"PAUSED","advertisingChannelType":"SEARCH","networkSettings":{"targetGoogleSearch":true,"targetSearchNetwork":true,"targetContentNetwork":false,"targetPartnerSearchNetwork":false},"campaignBudget":"customers\/5763579756\/campaignBudgets\/8344505416","startDate":"20210314","endDate":"20210413","manualCpc":{}}}]}

Response
-------
Headers: {
    "content-disposition": "attachment",
    "request-id": "iQ4d1WEPCBTz8cVVwObaKg",
    "date": "Sat, 13 Mar 2021 14:55:47 GMT",
    "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\";
ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\";
ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000;
v=\"46,43\""
}
Response:
{"results":[{"resourceName":"customers\/5763579756\/campaigns\/12534031127"}]}

[2021-03-13 06:55:48] testing.INFO: Request made: Host: "
googleads.googleapis.com", Method:
"/google.ads.googleads.v6.services.AdGroupService/MutateAdGroups",
CustomerId: 5763579756, RequestId: "CNRZHJVJ4sAuR8Cy1r-q5A", IsFault: 0,
FaultMessage: "None"
[2021-03-13 06:55:48] testing.DEBUG: Request
-------
Method Name: /google.ads.googleads.v6.services.AdGroupService/MutateAdGroups
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/8.0.1 gapic\/ gax\/1.7.0 grpc\/1.35.0",
    "x-goog-request-params": "customer_id=5763579756",
    "developer-token": "REDACTED",
    "login-customer-id": "5763579756"
}
Request:
{"customerId":"5763579756","operations":[{"create":{"name":"2021_03_13__Kevins
Test Adset
#1615647348","status":"ENABLED","type":"SEARCH_STANDARD","campaign":"customers\/5763579756\/campaigns\/12534031127","cpcBidMicros":"10000"}}]}

Response
-------
Headers: {
    "content-disposition": "attachment",
    "request-id": "CNRZHJVJ4sAuR8Cy1r-q5A",
    "date": "Sat, 13 Mar 2021 14:55:47 GMT",
    "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\";
ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\";
ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000;
v=\"46,43\""
}
Response:
{"results":[{"resourceName":"customers\/5763579756\/adGroups\/122919386801"}]}

**Comment by kevmul0929** [comment]
Hey @PierrickVoulet, I apologize, I have been going back and forth with Google and replied to you through my emails. I didn't realize this was different, until just now. Let me know what else you need, and I can get it to you. Thank you for your help!

**Comment by PierrickVoulet** [comment]
@kevmul0929 No worries.

I do not think that this is a bug. I believe the issue is that you are passing a `YoutubeVideoAsset` object instead of a `AdVideoAsset` when creating the ad object.

You should start by a first API call that creates the video asset using a `YoutubeVideoAsset` object. Once done, you will have a resource name associated to this newly created video asset. You need to use this resource name to create the ad object with a `AdVideoAsset` object and make a second API call. Here is how the video responsive ad object would typically look like:

```php
'video_responsive_ad' => new VideoResponsiveAdInfo([
    'videos' => [new AdVideoAsset([
        'asset' => $assetResourceName
    ])],
    'headlines' => [new AdTextAsset(['text' => 'Test'])],
    'descriptions' => [new AdTextAsset(['text' => 'My really cool description'])]
])
```

We do provide examples that demonstrate how to upload and retrieve image assets, this is really similar for video assets: [UploadImageAsset](https://github.com/googleads/google-ads-php/blob/master/examples/Misc/UploadImageAsset.php) and [GetAllImageAssets](https://github.com/googleads/google-ads-php/blob/master/examples/Misc/GetAllImageAssets.php).

**Comment by kevmul0929** [comment]
@PierrickVoulet OOOHHH! Thank you! 

For anyone coming here later, here is how to create the asset
```
// Create the Asset
$asset = new Asset([
    'type' => AssetType::YOUTUBE_VIDEO,
    // Create the YoutubeVideoAsset
    'youtube_video_asset' => new YoutubeVideoAsset([
        'youtube_video_id' => $params['youtube_video_id']
    ])
]);
// Create the Operation
$assetOperation = new AssetOperation();
$assetOperation->setCreate($asset);
$assetServiceClient = $googleAdsClient->getAssetServiceClient();
// Call the service
$response = $assetServiceClient->mutateAssets(
    $this->customer_id,
    [$assetOperation]
);

// Next we can create the AdInfo
$adInfo = new VideoResponsiveAdInfo([
    'videos' => [new AdVideoAsset([
        'asset' => $response->getResults()[0]->getResourceName() // This is the resource name we get from the above code
    ])],
    'headlines' => [new AdTextAsset(['text' => 'Test'])],
    'long_headlines' => [new AdTextAsset(['text' => 'Long Headline Test'])],
    'descriptions' => [new AdTextAsset(['text' => 'My really cool description'])],
    'call_to_actions' => [new AdTextAsset(['text' => 'Call To Action'])]
]);
```
