### ISSUE TITLE
Return StringValue instead string

### ISSUE THREAD

**Issue by dmachehin** [googleads/google-ads-php#555]
`Google\Ads\GoogleAds\V6\Resources\PaymentsAccount::getPaymentsProfileId`

Return typehint has string but return StringValue

**Comment by PierrickVoulet** [comment]
Hi @dmachehin - It looks like our client library has the right [hint](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V6/Resources/PaymentsAccount.php#L50) (see [V6 API documentation](https://developers.google.com/google-ads/api/reference/rpc/v6/BillingSetup.PaymentsAccountInfo#payments_profile_id)).

Could you confirm what version of our library you are using? The format should be `vX.Y.Z` and the exhaustive list of all released versions of the client library is in the [releases' page](https://github.com/googleads/google-ads-php/releases)

Could you also provide the request and response [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging) (or a request ID)?

**Comment by dmachehin** [comment]
Sorry, my bug (cache results from old version)
