### ISSUE TITLE
Not getting segment device name

### ISSUE THREAD

**Issue by r09031995** [googleads/google-ads-php#556]
I am using to below code for getting segment device name.  But unfortunately getting name as 4,2 etc as a integer. So can you please help me getting device name using library.
$segment = $googleAdsRow->getSegments();
echo "Device Name: ".$segment->getDevice();
Response :
Device Name: 4

Thanks & Regards
Rahul

**Comment by fiboknacky** [comment]
You need to call [`Device::name()`](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V6/Enums/DeviceEnum/Device.php#L69) in order to translate the value into a meaningful string representation.
