### ISSUE TITLE
Can't get past getGoogleAdsServiceClient anymore

### ISSUE THREAD

**Issue by SeriousJ55** [googleads/google-ads-php#557]
I upgraded from google-ads-php-v4.0.0 and V4 API to newest google-ads-php-v7.0.0 and V6 API. I use PHP 7.3.

Now I can't get a simple getGoogleAdsServiceClient() to work.

`$googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();`

The code above gets me the following warning message:

> Warning: Declaration of Google\Ads\GoogleAds\Lib\V6\GoogleAdsFailuresInterceptor::interceptUnaryUnary($method, $argument, $deserialize, array $metadata, array $options, $continuation) should be compatible with Grpc\Interceptor::interceptUnaryUnary($method, $argument, $deserialize, $continuation, array $metadata = Array, array $options = Array) in C:\wamp\www\wonder-legal\Libraries\google-ads-php-master\vendor\googleads\google-ads-php\src\Google\Ads\GoogleAds\Lib\V6\GoogleAdsFailuresInterceptor.php on line 26

What's wrong?

**Comment by PierrickVoulet** [comment]
Hi @SeriousJ55 - This seems similar to #549.

**Comment by SeriousJ55** [comment]
I replied to #549.

**Comment by PierrickVoulet** [comment]
Closing this issue as this is being discussed in #549.
