### ISSUE TITLE
No backward compatibility

### ISSUE THREAD

**Issue by SeriousJ55** [googleads/google-ads-php#558]
I upgraded from google-ads-php-v4.0.0 and V4 API to newest google-ads-php-v7.0.0 and V6 API. I use PHP 7.3.

As per usual with Google SDKs, there's no backward compatibility between versions. For example, `$googleAdsRow->getCampaign()->getName()->getValue()` doesn't work anymore. One has to remove `getValue()` and write `$googleAdsRow->getCampaign()->getName()` instead.

Is there a log somewhere detailing all those changes? Or do we have to just wait for bugs to happen and then fix them?

**Comment by PierrickVoulet** [comment]
Hi @SeriousJ55,

This client library reflects the [Google Ads API](https://developers.google.com/google-ads/api/docs/start). Important changes are communicated from the dedicated [Blog](https://ads-developers.googleblog.com/search/label/adwords_api).

When breaking changes are introduced, we release a major version and we log the changes in the [CHANGELOG.md](https://github.com/googleads/google-ads-php/blob/master/CHANGELOG.md) file. The incompatibility you are referring to is called `field presence` and it was introduced with the [major version 6.0.0](https://github.com/googleads/google-ads-php/blob/master/CHANGELOG.md#600).

**Comment by SeriousJ55** [comment]
I read those files very carefully but I couldn't find the line that says that `$googleAdsRow->getCampaign()->getName()->getValue()` doesn't work anymore. Could you point me to that line?

**Comment by PierrickVoulet** [comment]
This particular change is listed:

* In the client library CHANGELOG.md file under `6.0.0`: Migrated to [field presence](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md).
* In the Google Ads API release notes documentation under `6.0.0 (2020-11-05)` [here](https://developers.google.com/google-ads/api/docs/release-notes#client-v6).

Thank you for the feedback, we will try to better highlight these important changes in the future.

**Comment by SeriousJ55** [comment]
I read both. There's no mention to getValue. Can you point me to the right line?

**Comment by fiboknacky** [comment]
`StringValue`, `DoubleValue`, etc. are the so-called **wrapper types**, as stated in the first bullet of [this section](https://developers.google.com/google-ads/api/docs/release-notes#client-v6).
Previously, `Campaign` has a field named `name` of the `StringValue` type, so you needed to call something like `$campaign->getName()->getValue()`.
`$campaign->getName()` will return you a `StringValue` object. And `getValue()` called on `StringValue` (which has a field named `value` of `string`) will return you a primitive string.

 After the migration to field presence (e.g., `optional string`, which is converted to primitive string in PHP), there is therefore no need to call `getValue()`. `$campaign->getName()` will now return `string`.

I'd recommend also seeing the difference between code examples via https://github.com/googleads/google-ads-php/compare/v4.0.0...v7.0.0.
Searching for a code example that might be related to your use case (like AddCampaigns.php) would help you see the differences between the previous and current versions.

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

So this would also need to change 
from 

```
$adGroupCriterion = new AdGroupCriterion([
                'ad_group' => ResourceNames::forAdGroup($customerId, $adgroupId),
                'bid_modifier' => 1.01,
                'age_range' => new AgeRangeInfo([
                    'type' => AgeRangeType:: value($criteria)])
            ]);
```
To

```
$adGroupCriterion = new AdGroupCriterion([
                'ad_group' => ResourceNames::forAdGroup($customerId, $adgroupId),
                'bid_modifier' => 1.01,
                'age_range' => new AgeRangeInfo([
                    'type' => AgeRangeType:: name($criteria)])
            ]);
```

I was trying to modify bid for demographics.
But somehow I can get the error resource not found on some criteria which was REMOVED by default.
And Not able to set any bid modifier for that criteria.

Thanks,

**Comment by SeriousJ55** [comment]
Hi @fiboknacky and @PierrickVoulet,

This also needs to change: `$adGroup->getIdUnwrapped()` to `$adGroup->getId()`. And many other things.

The problem is that changes are not documented anywhere. You documentation gives API changes but nowhere do we know how those changes affect the PHP SDK. We can't deduce from your API documentation that `$adGroup->getIdUnwrapped()` needs to change to `$adGroup->getId()`.

**Comment by fiboknacky** [comment]
@chiragvels 

The [V4](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V4/Common/GenderInfo.php#L31) and [V6](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V6/Common/GenderInfo.php#L31) source for GenderInfo are pretty much the same, i.e., the value you pass to `type` should be an int.
(By the way, your code doesn't look correct. `age_range` should accept an `AgeRangeInfo` object, not `GenderInfo`. Not sure you've updated your comment but didn't change that part?)

The issue you encountered may be due to other causes. If your issue still persists and it doesn't seem to be related to the client library, feel free to report at [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).

**Comment by chiragvels** [comment]
Hello @fiboknacky ,

Thanks for the confirmation. Oops.. Yes I updated the comment and forgot to change that.
```
$adGroupCriterion = new AdGroupCriterion([
                'ad_group' => ResourceNames::forAdGroup($customerId, $adgroupId),
                'bid_modifier' => 1.01,
                'gender' => new GenderInfo([
                    'type' => GenderType:: value($criteria)])
            ]);
```

Yes, I am following up with the [forum](https://groups.google.com/g/adwords-api/c/BHm7ge4D--U/m/CfAOKilXAgAJ) but not getting understand what I need to do.
For example, I am updating bid_modifier for the first time so I am doing setCreate operation. But somehow it is not updating and giving me Resource Not Found issue. Out of few accounts only 1 or 2 have this issue. So not able to get what I was doing wrong.
