### ISSUE TITLE
Question for set refresh token dynamically and get sub account

### ISSUE THREAD

**Issue by r09031995** [googleads/google-ads-php#559]
Hello team,
I have few question which I have mentioned below Please have a look on this and get me solution.

Que1: 
I have to set refresh token dynamically of each user on the time of permission. How can I set this. Currently in the library I have to set it into google_ads_php.ini file. Can you please provide solution for this.

Que2: How get I get sub account under manager account. For now I am using ListAccessibleCustomers.php file to get all customer id but here I am not able to get sub account under manager. Please suggest how can I get these information.

Thanks & Regards
Rahul

**Comment by PierrickVoulet** [comment]
Hi @r09031995 

1. You could edit the configuration of your clients at runtime, see [here](https://developers.google.com/google-ads/api/docs/client-libs/php/configuration#dynamic_configuration) for documentation.
2. The [GetAccountHierrarchy](https://github.com/googleads/google-ads-php/blob/master/examples/AccountManagement/GetAccountHierarchy.php) code example retrieves and prints the hierarchy of accounts. This should be a great starting point.

**Comment by r09031995** [comment]
Hi  PierrickVoulet,
Thanks for Your prompt support.
In GetAccountHierarchy there is MANAGER_CUSTOMER_ID and LOGIN_CUSTOMER_ID what we need to set here. For now I have set in MANAGER_CUSTOMER_ID the id of manger google ad account and how can I get LOGIN_CUSTOMER_ID. Please suggest what we need to set here to get Sub Account data.

Thanks,

**Comment by PierrickVoulet** [comment]
> Hi PierrickVoulet,
> Thanks for Your prompt support.
> In GetAccountHierarchy there is MANAGER_CUSTOMER_ID and LOGIN_CUSTOMER_ID what we need to set here. For now I have set in MANAGER_CUSTOMER_ID the id of manger google ad account and how can I get LOGIN_CUSTOMER_ID. Please suggest what we need to set here to get Sub Account data.
> 
> Thanks,

* `MANAGER_CUSTOMER_ID`: The account ID that you want to retrieve the hierarchy of.
* `LOGIN_CUSTOMER_ID`: The ID of the authorized customer that you want to use to make the API requests (see [Google Ads API documentation](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid)).

**Comment by r09031995** [comment]
Hi PierrickVoulet,
I am getting below error while running GetAccountHierarchy.php file. Could you please suggest why I am getting this error?

No manager customer ID is specified. The example will print the hierarchies of all accessible customer IDs: 8787942940 6226850201 3368687896 ApiException was thrown with message '{ "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https:\/\/developers.google.com\/identity\/sign-in\/web\/devconsole-project.", "code": 16, "status": "UNAUTHENTICATED", "details": [ { "@type": 0, "data": "type.googleapis.com\/google.ads.googleads.v6.errors.GoogleAdsFailure" }, { "@type": 0, "data": [ { "errorCode": { "authenticationError": "CUSTOMER_NOT_FOUND" }, "message": "No customer found for the provided customer id." } ] } ] }'.

Thanks,

**Comment by PierrickVoulet** [comment]
Hi @r09031995 

This `CUSTOMER_NOT_FOUND` error is returned by the Google Ads API itself, see documentation [here](https://developers.google.com/google-ads/api/docs/best-practices/common-errors?hl=en#customer_not_found). If this error persists, the best would be to contact the [Google Ads API Support](https://developers.google.com/google-ads/api/support) for further investigation.

**Comment by r09031995** [comment]
How can I include Authorization : Bearer YOUR_ACCESS_TOKEN in the header Section.  I got below answer from google ads Team in reference to above error.

"Thanks for reaching out. Based on the error message indicating that there was no access token given, it looks like this request was made without the proper authorization header. If you still need further assistance, please reply privately with the complete request details.".
 
Can you please help here.

Thanks,

**Comment by PierrickVoulet** [comment]
The library does it automatically based on the configuration of the client. Could you provide the request ID (or logs) and the code that you use to create the client and make the request?

**Comment by r09031995** [comment]
Logs:
No manager customer ID is specified. The example will print the hierarchies of all accessible customer IDs: 8787942940 6226850201 3368687896 ApiException was thrown with message '{ "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https:\/\/developers.google.com\/identity\/sign-in\/web\/devconsole-project.", "code": 16, "status": "UNAUTHENTICATED", "details": [ { "@type": 0, "data": "type.googleapis.com\/google.ads.googleads.v6.errors.GoogleAdsFailure" }, { "@type": 0, "data": [ { "errorCode": { "authenticationError": "CUSTOMER_NOT_FOUND" }, "message": "No customer found for the provided customer id." } ] } ] }'.

Also, I have attached the code.

[GetAccountHierarchy.zip](https://github.com/googleads/google-ads-php/files/6187507/GetAccountHierarchy.zip)

**Comment by r09031995** [comment]
GetAccountHierarchy.zip code I am using for getting sub account Under manager account.
Example:  There is a manager account with id 336-868-7896. In this manager account there is 2 sub account (941-584-1068, 302-428-4497) with the help of code I have to get these two sub account.

**Comment by PierrickVoulet** [comment]
Hi @r09031995 Thank you for sharing. I could not find anything that demonstrates that there is something missing or a bug in the library itself. The [Google Ads API Support](https://developers.google.com/google-ads/api/support) can help you with all questions related to the API. If you still believe that there is an issue with the library, feel free to reopen with precise instructions so that we can replicate on our end.
