### ISSUE TITLE
Examples\Utils\ArgumentParser not found

### ISSUE THREAD

**Issue by PierrickVoulet** [googleads/google-ads-php#564]
**Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\Examples\Utils\ArgumentParser' not found**  
i am also facing same issue im already get code from composer still same error .
kindly please help me how to solve this.

_Originally posted by @divyeshgajja in https://github.com/googleads/google-ads-php/issues/286#issuecomment-804815119_

**Comment by divyeshgajja** [comment]
plz check i am already create.
https://github.com/googleads/google-ads-php/issues/563
