### ISSUE TITLE
PLACEHOLDER_FEED_ITEM_REPORT missing placeholderType using PHP Library

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#57]
Hello Team,

I can see that PLACEHOLDER_FEED_ITEM_REPORT is mapped to resources feed_item,feed_item_target.
https://developers.google.com/google-ads/api/docs/migration/reports#reports_to_resources

But when I try to get the 
PlaceholderType as segments.placeholder_type It said not supported.
https://developers.google.com/google-ads/api/docs/migration/reports#placeholder_feed_item

I am using simple query

```
$query =
                "SELECT
                    campaign.id,
                    campaign.name,
                    segments.placeholder_type
                FROM
                    feed_item";
```
Error:
Cannot select or filter on the following segments: 'segments.placeholder_type

I think this should be bug as on migration doc it should be like that only.

Thanks,

**Comment by fiboknacky** [comment]
Hello Chirag,

As you can see from [this page](https://developers.google.com/google-ads/api/docs/fields/segments#segmentsplaceholder_type), `campaign` doesn't appear in `segments.placeholder_type`'s *Selectable With*, meaning that they cannot be used in the same SELECT clause.

However, at least `campaign.id` should be able to appear in the SELECT clause, when `feed_item` is used as a main resource. I've filed a bug internally to track this.
Thanks for reporting.

Knack

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

Thanks for insights.

So mapping of PlaceholderType and campaign not possible at all.

I have used  customer_feed, campaign_feed, ad_group_feed to get the Placeholder details but all have same error.

https://developers.google.com/google-ads/api/docs/fields/feed_placeholder_view

Thanks for reporting bug internally.

**Comment by fiboknacky** [comment]
What are the queries of customer_feed, campaign_feed, ad_group_feed that you used?

**Comment by chiragvels** [comment]
The same that I stat above.


```
$query = "SELECT campaign.id, campaign.name, segments.placeholder_type FROM campaign_feed";

$query1 = "SELECT ad_group.id, campaign.id, campaign.name, segments.placeholder_type FROM
	ad_group_feed";

$query2 = "SELECT segments.placeholder_type FROM customer_feed";
```

> Failure: {"errors":[{"errorCode":{"queryError":"PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE"},"message":"Cannot select or filter on the following segments: 'segments.placeholder_type'(could not support requested resources: 'CAMPAIGN_FEED', 'CAMPAIGN_FEED'), since segment is incompatible with the resource in the FROM clause or other selected segmenting resources."}]} 
> 
> Failure: {"errors":[{"errorCode":{"queryError":"PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE"},"message":"Cannot select or filter on the following segments: 'segments.placeholder_type'(could not support requested resources: 'AD_GROUP_FEED', 'AD_GROUP_FEED'), since segment is incompatible with the resource in the FROM clause or other selected segmenting resources."}]}
> 
> Failure: {"errors":[{"errorCode":{"queryError":"PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE"},"message":"Cannot select or filter on the following segments: 'segments.placeholder_type'(could not support requested resources: 'CUSTOMER_FEED', 'CUSTOMER_FEED'), since segment is incompatible with the resource in the FROM clause or other selected segmenting resources."}]}

**Comment by fiboknacky** [comment]
For [customer_feed](https://developers.google.com/google-ads/api/docs/fields/customer_feed), it's not supported yet, as you can see there are no segment fields listed up.
This works as intended for now. I think the team is working on releasing segments and metrics for this resource in the future.

**Comment by chiragvels** [comment]
Okay,

By the way I have used [GAQL Builder](https://developers.google.com/google-ads/api/docs/query/interactive-gaql-builder) to generate those queries.

Can you help anyway I can map PlaceholdeTypes to campaign or Adgroup?

This is possible using Legacy API, but not there in Google Ads API, Is this intended or BUG?

Thanks,

**Comment by fiboknacky** [comment]
If you mean using the campaign and ad group together with placeholder type, it seems not possible right now, because of the reason I stated in the [above reply](https://github.com/googleads/google-ads-php/issues/57#issuecomment-482472681).

If you wish to request for this feature, please post on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).

Cheers,
Knack
