### ISSUE TITLE
Process to implement ads library in laravel

### ISSUE THREAD

**Issue by r09031995** [googleads/google-ads-php#574]
Hello Team,
How I can Implement this google ads library into Laravel. Please send us a guide so that I can follow same and get done my work.

Thanks in Advance 
Rahul

**Comment by fiboknacky** [comment]
We have a sample app implemented with Laravel [here](https://github.com/googleads/google-ads-php/tree/master/examples/LaravelSampleApp).

**Comment by r09031995** [comment]
Can you please share setup steps. I am trying to implement into a existing project but was unable to do and getting error every time.

**Comment by fiboknacky** [comment]
There is an instruction in [the README.md file](https://github.com/googleads/google-ads-php/tree/master/examples/LaravelSampleApp#laravel-sample-application) of the directory I've shared.
Could you please follow that? If you get an error, please share the error and the step that you've done until getting error here.
Thanks.

**Comment by r09031995** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/43718680/114001710-cd6efd80-9879-11eb-86a1-58e3b094f759.png)
When click on show Report button after filling Customer Id getting this error as attached.
