### ISSUE TITLE
Forecast Curves Are Always Empty

### ISSUE THREAD

**Issue by Infamoustrey** [googleads/google-ads-php#578]
**What versions of the client library and Google Ads API are you using?**

- Client library:  `"googleads/google-ads-php": "^8.1"`
- Google Ads API: `V6`

**What environment are you using?**
 
- The PHP version: 
```
PHP 8.0.3 (cli) (built: Apr 12 2021 00:29:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```
- The name and version of the operating system: 
```
Darwin MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64%
```
- Attempted with both protobuf and grpc enabled and not enabled.

**Actions taken**

Minimum Repro

```php
$config = [
    'clientId' => '*********',
    'clientSecret' => '*********',
    'refreshToken'  => '*********',
    'developerToken'  => '*********',
    'managerId'  => '*********',
    'keywordPlanResourceName' => '*********',
];

$oAuth2Credential = (new OAuth2TokenBuilder())
    ->withClientId($config['clientId'])
    ->withClientSecret($config['clientSecret'])
    ->withRefreshToken($config['refreshToken'])
    ->build();

$googleClient = (new GoogleAdsClientBuilder())
    ->withOAuth2Credential($oAuth2Credential)
    ->withDeveloperToken($config['developerToken'])
    ->withLoginCustomerId($config['managerId'])
    ->build();

$keywordPlanServiceClient = $googleClient->getKeywordPlanServiceClient();

$response = $keywordPlanServiceClient->generateForecastCurve($config['keywordPlanResourceName']);

foreach ($response->getCampaignForecastCurves() as $curve) {
    foreach ($curve->getMaxCpcBidForecastCurve()->getMaxCpcBidForecasts() as $maxCpcBidForecast) {

        $metric = $maxCpcBidForecast->getMaxCpcBidForecast();
        $maxCpc = $maxCpcBidForecast->getMaxCpcBidMicros();

        printf(
            "Max CPC Bid: %s%s",
            is_null($maxCpc) ? 'null'
                : sprintf("%.2f", round($maxCpc / self::ONE_MILLION, 2)),
            PHP_EOL
        );
        printf(
            "Estimated Clicks: %s%s",
            is_null($metric->getClicks()) ? 'null'
                : sprintf("%.2f", $metric->getClicks()),
            PHP_EOL
        );
        printf(
            "Estimated Cost: %s%s",
            is_null($metric->getCostMicros())
                ? 'null' : sprintf("%.2f", round($metric->getCostMicros() / self::ONE_MILLION, 2)),
            PHP_EOL
        );
        printf(
            "Estimated Cpc: %s%s",
            is_null($metric->getAverageCpc())
                ? 'null' : sprintf("%.2f", round($metric->getAverageCpc() / self::ONE_MILLION, 2)),
            PHP_EOL
        );
    }
}

```

**Expected result**

Results from the forecast curves.

**Actual result**

The forecast curve returned is empty. `getCampaignForecastCurves` returns an array with a single curve, but drilling into that `->getMaxCpcBidForecastCurve()->getMaxCpcBidForecasts()` is always empty. This happens whether the keyword plan was created through the api or through the UI. Alternatively the rest of the API works just fine, so it appears to be limited to just this endpoint.

**Comment by Infamoustrey** [comment]
I'd be happy to but I'm not sure which interface would expose the underlying logs or ids. Is there a verbose setting I need to set somewhere to toggle output?

**Comment by PierrickVoulet** [comment]
You will find our documentation about logging [here](https://developers.google.com/google-ads/api/docs/client-libs/php/logging), feel free to let us know if it does not help.

**Comment by Infamoustrey** [comment]
Hmm... So I switched to using a file ini based config. And it appears to give the same result but it doesn't seem to respect my logging config. I've ran it several times but it doesn't seem to want to give me a log file.

```ini
[OAUTH2]
clientId = "*****"
clientSecret ="*****"
refreshToken = "*****"

[GOOGLE_ADS]
developerToken = "*****"
loginCustomerId = "*****"

[LOGGING]
logFilePath = "/absolute/path/to/project/out.log"
logLevel = "INFO"
```

I've also update my code to point at this ini file, I know it's using the file because it will throw a permissions error if I remove the token or secret.

```php
$oAuth2Credential = (new OAuth2TokenBuilder())
            ->fromFile(base_path('google_ads_php.ini'))
            ->build();

$googleClient = (new GoogleAdsClientBuilder())
            ->withOAuth2Credential($oAuth2Credential)
            ->fromFile(base_path('google_ads_php.ini'))
            ->build();
```

**Comment by PierrickVoulet** [comment]
Could you make sure that you are using gRPC (the PHP Extension `grpc` should be enabled)? You will find more documentation [here](https://developers.google.com/google-ads/api/docs/client-libs/php/transport).

**Comment by Infamoustrey** [comment]
Alright enabling `grpc` seemed to fix the logging issue. Below is the output:

```log
[2021-05-12T20:52:33.921917+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v6.services.KeywordPlanService/GenerateForecastCurve", CustomerId: "No customer ID could be extracted from the request", RequestId: "YD9gJcSSP_ibtqMdY_ANXg", IsFault: 0, FaultMessage: "None"  
```

I'm not too sure what that error/message means, guidance is appreciated.

**Comment by PierrickVoulet** [comment]
Thanks! This prints information about the Google Ads API call made by the library and `IsFault: 0, FaultMessage: "None"` means that the Google Ads API returned without any errors.

I was able to confirm that the library behaved as expected: The Google Ads API itself does not return any results. Please contact the [support of the Google Ads API](https://developers.google.com/google-ads/api/support), they will help you.
