### ISSUE TITLE
Custom Audience

### ISSUE THREAD

**Issue by theloomproject** [googleads/google-ads-php#582]
Hi,

I would like to create custom audience dynamically using php 5.6 please let us know the library or directly API for this.

**Comment by PierrickVoulet** [comment]
Hi @theloomproject,

This library [does not support PHP `5.X`](https://github.com/googleads/google-ads-php/blob/master/composer.json#L6). You will find the official Google Ads API documentation for custom audience [here](https://developers.google.com/google-ads/api/docs/remarketing/audience-types/custom-audiences) and a code example that uses this library [here](https://github.com/googleads/google-ads-php/blob/master/examples/Remarketing/AddCustomAudience.php). 

Thanks,
