### ISSUE TITLE
Execute through command line, but not directly using the php file with updated const variables.

### ISSUE THREAD

**Issue by steponafish** [googleads/google-ads-php#584]
Client Library: google-ads-php-v7.0.0
Google Ads API : V6 (clean install May 3, 2021)
PHP version on both local and server: 7.3.27

Hi there, 
I'm having an issue with directly using the GenerateKeywordIdeas.php from examples. When I run the command line (locally and on my server), I can execute: `php examples/Planning/GenerateKeywordIdeas.php --customerId 3835729232 --locationIds 2840 --languageId 1000 --keywordTexts cake` and it creates a list just fine. No errors. Nothing added to the error log.

But when I change the const variables directly in the file, go to the url, I get this response: `Usage: /luck/google-ads-php/examples/Planning/GenerateKeywordIdeas.php [options] [operands] Options: -h, --help Show this help and quit --customerId The customer ID without dashes --locationIds The list of location IDs --languageId The language ID --keywordTexts The list of keyword texts --pageUrl [] The page URL` 

Do I need to change something within GenerateKeywordIdeas.php to use the private const instead of the command line? The command line works, directly going to the file does not. 

I used to have the "fail to push limit" issue, but I have fixed that issue.

**Comment by fiboknacky** [comment]
Hello,

I believe this is the limitation of how we structure the example files. For required arguments, e.g., customer ID, you still need to specify that via the command line in order to pass through the validation of ArgumentParser.
If you really need to use the private const, a quick fix would be removing the key `ArgumentNames::CUSTOMER_ID` from the array passed to `parseCommandArguments`, which will result in this:

```php
        $options = (new ArgumentParser())->parseCommandArguments([
            ArgumentNames::LOCATION_IDS => GetOpt::MULTIPLE_ARGUMENT,
            ArgumentNames::LANGUAGE_ID => GetOpt::REQUIRED_ARGUMENT,
            ArgumentNames::KEYWORD_TEXTS => GetOpt::MULTIPLE_ARGUMENT,
            ArgumentNames::PAGE_URL => GetOpt::OPTIONAL_ARGUMENT,
        ]);
```

**Comment by steponafish** [comment]
@fiboknacky so I want to use all the private consts, CUSTOMER_ID, LOCATION_ID_1, LANGUAGE_ID, KEYWORD_TEXT_1, I can remove them from this array?

**Comment by fiboknacky** [comment]
You can do so if you'd like to use private consts only.

**Comment by steponafish** [comment]
@fiboknacky, when I remove the ArgumentNames lines, I get "This Page isn't working" error when reloading the page. Do I need to do anything else within the example file to get this to work without the command line?

**Comment by fiboknacky** [comment]
To be clear, the code example is meant to be run on the command line.
Do you try to run it on web? If so, you'd need to largely modify the code by yourself. Running the example directly wouldn't work.

**Comment by steponafish** [comment]
I see. Ok. Thank you for your help.
