### ISSUE TITLE
Issues with interceptor for lazy init of GGAFailures

### ISSUE THREAD

**Issue by saintanger** [googleads/google-ads-php#588]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**What versions of the client library and Google Ads API are you using?**
v7.0 library with v6 api (v7 not available yet from what I can see)

**What environment are you using?**

================= PHP GENERAL INFORMATION
phpinfo()
PHP Version => 7.3.28

System => Linux 4ef4510caf62 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64
Build Date => Apr 29 2021 18:51:17
Configure Command =>  './configure'  '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-libdir=lib/x86_64-linux-gnu' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' '--disable-cgi' 'build_alias=x86_64-linux-gnu'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /usr/local/etc/php
Loaded Configuration File => (none)
Scan this dir for additional .ini files => /usr/local/etc/php/conf.d
Additional .ini files parsed => /usr/local/etc/php/conf.d/blackfire.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gmp.ini,
/usr/local/etc/php/conf.d/docker-php-ext-grpc.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini,
/usr/local/etc/php/conf.d/docker-php-ext-memcached.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-soap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
/usr/local/etc/php/conf.d/laravel.ini,
/usr/local/etc/php/conf.d/mongodb.ini,
/usr/local/etc/php/conf.d/xdebug.ini

PHP API => 20180731
PHP Extension => 20180731
Zend Extension => 320180731
Zend Extension Build => API320180731,NTS
PHP Extension Build => API20180731,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.2, sslv3, sslv2
Registered Stream Filters => zlib.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.57.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire
================= PHP EXTENSION INFORMATION
The PHP Extension grpc is installed: 1.37.1
The PHP Extension protobuf is not installed

**Actions taken**

**Expected result**

Return the search results data.

**Actual result**

[object] (ErrorException(code: 0): Declaration of Google\\Ads\\GoogleAds\\Lib\\V6\\GoogleAdsFailuresInterceptor::interceptUnaryUnary($method, $argument, $deserialize, array $metadata, array $options, $continuation) should be compatible with Grpc\\Interceptor::interceptUnaryUnary($method, $argument, $deserialize, $continuation, array $metadata = Array, array $options = Array) at /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/GoogleAdsFailuresInterceptor.php:26)
[stacktrace]
#0 /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/GoogleAdsFailuresInterceptor.php(26): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Declaration of ...', '/var/www/ppc-co...', 26, Array)
#1 /xx/xx/xx/vendor/composer/ClassLoader.php(478): include('/var/www/ppc-co...')
#2 /xx/xx/xx/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile('/var/www/ppc-co...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Google\\\\Ads\\\\Goog...')
#4 /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/ServiceClientFactoryTrait.php(185): spl_autoload_call('Google\\\\Ads\\\\Goog...')
#5 /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/ServiceClientFactoryTrait.php(792): Google\\Ads\\GoogleAds\\Lib\\V6\\GoogleAdsClient->getGoogleAdsClientOptions()
#6 /xx/xx/xx/app/GoogleAdsApi/Gaql.php(933): Google\\Ads\\GoogleAds\\Lib\\V6\\GoogleAdsClient->getGoogleAdsServiceClient()

AND/OR

Argument 4 passed to Google\Ads\GoogleAds\Lib\V6\GoogleAdsLoggingInterceptor::interceptUnaryUnary() must be of the type array, object given, called in /xx/xx/xx/vendor/grpc/grpc/src/lib/BaseStub.php on line 423 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 4 passed to Google\\Ads\\GoogleAds\\Lib\\V6\\GoogleAdsLoggingInterceptor::interceptUnaryUnary() must be of the type array, object given, called in /xx/xx/xx/vendor/grpc/grpc/src/lib/BaseStub.php on line 423 at /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/GoogleAdsLoggingInterceptor.php:53)
[stacktrace]
#0 /xx/xx/xx/vendor/grpc/grpc/src/lib/BaseStub.php(423): Google\\Ads\\GoogleAds\\Lib\\V6\\GoogleAdsLoggingInterceptor->interceptUnaryUnary('/google.ads.goo...', Object(Google\\Ads\\GoogleAds\\V6\\Services\\SearchGoogleAdsRequest), Array, Object(Closure), Array, Array)
#1 /xx/xx/xx/vendor/grpc/grpc/src/lib/BaseStub.php(541): Grpc\\BaseStub->Grpc\\{closure}('/google.ads.goo...', Object(Google\\Ads\\GoogleAds\\V6\\Services\\SearchGoogleAdsRequest), Array, Array, Array)
#2 /xx/xx/xx/vendor/google/gax/src/Transport/GrpcTransport.php(213): Grpc\\BaseStub->_simpleRequest('/google.ads.goo...', Object(Google\\Ads\\GoogleAds\\V6\\Services\\SearchGoogleAdsRequest), Array, Array, Array)
#3 /xx/xx/xx/vendor/google/gax/src/GapicClientTrait.php(521): Google\\ApiCore\\Transport\\GrpcTransport->startUnaryCall(Object(Google\\ApiCore\\Call), Array)
#4 /xx/xx/xx/vendor/google/gax/src/Middleware/CredentialsWrapperMiddleware.php(61): Google\\Ads\\GoogleAds\\V6\\Services\\Gapic\\GoogleAdsServiceGapicClient->Google\\ApiCore\\{closure}(Object(Google\\ApiCore\\Call), Array)
#5 /xx/xx/xx/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\\ApiCore\\Middleware\\CredentialsWrapperMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#6 /xx/xx/xx/vendor/google/gax/src/Middleware/RetryMiddleware.php(88): Google\\ApiCore\\Middleware\\FixedHeaderMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#7 /xx/xx/xx/vendor/google/gax/src/Middleware/OptionsFilterMiddleware.php(63): Google\\ApiCore\\Middleware\\RetryMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#8 /xx/xx/xx/vendor/google/gax/src/Middleware/PagedMiddleware.php(67): Google\\ApiCore\\Middleware\\OptionsFilterMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#9 /xx/xx/xx/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\\ApiCore\\Middleware\\PagedMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#10 /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/UnaryGoogleAdsExceptionMiddleware.php(63): Google\\ApiCore\\Middleware\\FixedHeaderMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#11 /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V6/UnaryGoogleAdsResponseMetadataCallable.php(64): Google\\Ads\\GoogleAds\\Lib\\V6\\UnaryGoogleAdsExceptionMiddleware->__invoke(Object(Google\\ApiCore\\Call), Array)
#12 /xx/xx/xx/vendor/google/gax/src/GapicClientTrait.php(642): Google\\Ads\\GoogleAds\\Lib\\V6\\UnaryGoogleAdsResponseMetadataCallable->__invoke(Object(Google\\ApiCore\\Call), Array)
#13 /xx/xx/xx/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V6/Services/Gapic/GoogleAdsServiceGapicClient.php(286): Google\\Ads\\GoogleAds\\V6\\Services\\Gapic\\GoogleAdsServiceGapicClient->getPagedListResponse('Search', Array, 'Google\\\\Ads\\\\Goog...', Object(Google\\Ads\\GoogleAds\\V6\\Services\\SearchGoogleAdsRequest))
#14 /xx/xx/xx/app/GoogleAdsApi/Gaql.php(1331): Google\\Ads\\GoogleAds\\V6\\Services\\Gapic\\GoogleAdsServiceGapicClient->search(XXXXXXXXXXXX, 'SELECT\
     ad_...', Array)
#15 /xx/xx/xx/app/xxx/Query.php(867): App\\GoogleAdsApi\\Gaql->getAds()

 
**Anything else we should know about your project / environment**

Its still working just fine if I switch to v6.* for googleads/google-ads-php

Probably related to:
https://github.com/googleads/google-ads-php/pull/493
https://github.com/googleads/google-ads-php/pull/474

**Comment by saintanger** [comment]
Hi @PierrickVoulet 

Thanks for that, this part seems to be working now with v8.
I've not tested all of the v8 now but is the v8 client ready to use in production?

Thanks

**Comment by PierrickVoulet** [comment]
> Hi @PierrickVoulet
> 
> Thanks for that, this part seems to be working now with v8.
> I've not tested all of the v8 now but is the v8 client ready to use in production?
> 
> Thanks

Thank you for confirming and yes, it is.

I am closing this issue but feel free to open a new one if you find anything wrong upgrading to `v8.0.0`.
