### ISSUE TITLE
Google Ads API PHP with Laravel: LogicException

### ISSUE THREAD

**Issue by MaksTech** [googleads/google-ads-php#59]
Hello!

I have a website app built on Laravel with latest version of Google Ads API PHP library.
Laravel has a Queue functionality which allows to queue tasks for a server to process on background and I'm trying to integrate few things. 
All I am doing is querying some data about clients with MCC account.
Running this task in synchronous mode, so just simply doing request without queue - has never produced an error with over 2000 requests in the last few days.

Problem occurs when trying to do it asynchronously, meaning launching the queue - produces LogicException:

```
LogicException: Missing stream url, the stream can not be opened. This may be caused by a premature call to close(). in \vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:95
Stack trace:
#0 \vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#1 \vendor\monolog\monolog\src\Monolog\Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 \vendor\monolog\monolog\src\Monolog\Logger.php(609): Monolog\Logger->addRecord(200, 'Request made: H...', Array)
#3 \vendor\googleads\google-ads-php\src\Google\Ads\GoogleAds\Lib\V1\GoogleAdsUnaryCallLogger.php(74): Monolog\Logger->log(200, 'Request made: H...', Array)
#4 \vendor\googleads\google-ads-php\src\Google\Ads\GoogleAds\Lib\V1\GoogleAdsLoggingUnaryCall.php(56): Google\Ads\GoogleAds\Lib\V1\GoogleAdsUnaryCallLogger->logSummary(Array, Array)
#5 \vendor\google\gax\src\Transport\GrpcTransport.php(242): Google\Ads\GoogleAds\Lib\V1\GoogleAdsLoggingUnaryCall->wait()
```

If needed, I can send the rest of the exception stack trace.

Also, not related to this, but pretty often getting ServerException...
```
ServerException
Server error: `POST https://oauth2.googleapis.com/token` resulted in a `503 Service Unavailable` response:
"error": {
"code": 503,
"message": "The service is currently unavailable.",
"status": "UNAVAILABLE"
}
...
```
Why is this happening?

Your help would be much appreciated!

**Comment by fiboknacky** [comment]
Mike, can using the Google API library in an asynchronous cause a stream problem like this?

**Comment by michaelbausor** [comment]
Hmm, I'm not sure - I'm not aware of any reason it should. @MaksTech can you provide some code that I could use to try to reproduce the issue?

Also, it looks like the error is coming from Monolog, not from the client library call itself. Is it possible to disable logging (or change the logging framework) and see if that fixes the issue?

**Comment by MaksTech** [comment]
Hmm, yes indeed it comes from Monolog. But I'm not quite sure how to disable that one. 
In terms of my code, it's really simple:
```
$query = "
SELECT
    segments.ad_network_type,
    metrics.clicks,
    metrics.cost_micros,
    metrics.conversions
FROM
    customer
WHERE
    customer.manager != TRUE AND
    segments.date DURING TODAY
ORDER BY
    segments.ad_network_type ASC
LIMIT
    100";

try {
    $response = $this->googleAdsClient->getGoogleAdsServiceClient()->search(MCC_ACOUNT_ID, $query);
    foreach ($response->iterateAllElements() as $googleAdsRow) {
        $segments = $googleAdsRow->getSegments();
        $metrics = $googleAdsRow->getMetrics();
        $data[$segments->getAdNetworkType()] = [
            'clicks' => $metrics->getClicks()->getValue(),
            'cost' => $metrics->getCostMicros()->getValue(),
            'conversions' => $metrics->getConversions()->getValue(),
        ];
    }
    $stat->data = $data;
    $stat->save();
} catch (GoogleAdsException $e) {
    report($e);
} catch (ApiException $e) {
    report($e);
} catch (\ServerException $e) {
    report($e);
} catch (\Exception $e) {
    report($e);
}
return;
```
It is being run in Laravel Job wrapper simply saying, and right now we have to launch it in synchronous way by calling it with [dispatchNow()](https://laravel.com/api/5.5/Illuminate/Contracts/Bus/Dispatcher.html#method_dispatchNow)  method. But really want to know why it wouldn't work in asynchronous method. 

Thanks

**Comment by fiboknacky** [comment]
As it seems the issues are in Monolog and Laravel, could you please ask around in the Laravel and Monolog support forum or issue trackers?
Thank you.

Knack

**Comment by dpereiraegoi** [comment]
Hi.

Any solution?

**Comment by surya-alive** [comment]
Hi,,
I've got this problem exactly in asynchronous process (Queue Job)
here is a solution

```
use Log;
..............
$session = (new AdWordsSessionBuilder())
        ->fromFile($adsapiFilePath)
        ->withOAuth2Credential($oAuth2Credential)
	->withClientCustomerId($accountId)
	->withSoapLogger(Log::getLogger())
	->withReportDownloaderLogger(Log::getLogger())
	->withBatchJobsUtilLogger(Log::getLogger())
	->build();
```
Please take a look on building session.
We have to set Logger instance from application explicitly

**Comment by will621** [comment]
In case this helps anyone else I had this same issue/error with Laravel 8 (Using Jobs and Queues) + Google Ads API v13.0.0

surya_alive's solution of changing the Logger worked for me but needs to be updated for Google Ads API to be used in the Client builder.
   ```
   use Illuminate\Support\Facades\Log;
...
     $this->googleAdsClient = (new GoogleAdsClientBuilder())
            ->fromFile(config('app.google_ads_php_path'))
            ->withLogger(Log::getLogger())
            ->withOAuth2Credential((new OAuth2TokenBuilder())
                ->fromFile(config('app.google_ads_php_path'))
                ->build())
            ->build();
```
