### ISSUE TITLE
get invoice error

### ISSUE THREAD

**Issue by webidoo** [googleads/google-ads-php#594]
**What versions of the client library and Google Ads API are you using?**

Client Library : Google Ads API Client Library for PHP v9.0.0
Google Ads API V7

**What environment are you using?**
PHP 7.3
Debian 10
gRPC

**Actions taken**

Just run the getInvoice example with this command:

```bash
php7.3 GetInvoices.php --customerId=XXXXX --billingSetupId=YYYYYY
```

**Expected result**
All the invoices related to the account.

**Actual result**

```
Method Name: /google.ads.googleads.v7.services.InvoiceService/ListInvoices
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.3.28-1+0~20210503.84+debian10~1.gbp6819da gapic\/ gax\/1.7.1 grpc\/1.37.1",
    "x-goog-request-params": "customer_id=XXXXX",
    "developer-token": "REDACTED",
    "login-customer-id": "XXXXXXX"
}
Request:
{"customerId":"XXXXXXXXX","billingSetup":"customers\/XXXXXXXXXXXX\/billingSetups\/XXXXXXXXXXXXXXX","issueYear":"2021","issueMonth":"APRIL"}

Response
-------
Headers: {
    "request-id": "25Y0Ww7141tqWpHB_-vbpA",
    "date": "Tue, 18 May 2021 13:30:23 GMT",
    "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault
-------
Status code: 13
Details: Internal error encountered.
Failure: {"errors":[{"errorCode":{"internalError":"INTERNAL_ERROR"},"message":"An internal error has occurred."}],"requestId":"25Y0Ww7141tqWpHB_-vbpA"}
Request with ID '25Y0Ww7141tqWpHB_-vbpA' has failed.
Google Ads failure details:
        internal_error: An internal error has occurred.

```

 
**Anything else we should know about your project / environment**
The account used for the test is the highest account in the hierarchy. We are trying to retrieve the monthly invoice for an account in the hierarchy

**Comment by fiboknacky** [comment]
For the API-related issues, could you please create a new post on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)?
Thank you.

**Comment by webidoo** [comment]
we don't have permissions, we have tried with all google accounts

**Comment by fiboknacky** [comment]
Do you mean you cannot access the forum?

**Comment by webidoo** [comment]
yes
[image: image.png]

Il giorno mer 19 mag 2021 alle ore 11:37 Thanet Knack Praneenararat <
***@***.***> ha scritto:

**Comment by fiboknacky** [comment]
I can access without the need of logging in.
Could you try in the Incognito mode? If you cannot access, please attach the screenshot showing the error messages.

**Comment by webidoo** [comment]
I tried with my personal gmail and it works, while the corporate gsuite gives an error.
