### ISSUE TITLE
How to update AdGroupAd?

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#596]
Hello everyone,
i need help to update adgroup headline and descriptions but i dont khnow how to do Please help.

$adGroupAd = new AdGroupAd([
            'status' => AdGroupAdStatus::ENABLED,
            'ad_group' => $adGroupResourceName,
            'ad' => new Ad([
                'app_ad' => new AppAdInfo([
                    'headlines' => [
                        new AdTextAsset(['text' => 'A cool puzzle game']),
                        new AdTextAsset(['text' => 'Remove connected blocks'])
                    ],
                    'descriptions' => [
                        new AdTextAsset(['text' => '3 difficulty levels']),
                        new AdTextAsset(['text' => '4 colorful fun skins'])
                    ]
                ])
            ])
        ]);

i need update:
 **'headlines' => [
                        new AdTextAsset(['text' => 'A cool puzzle game']),
                        new AdTextAsset(['text' => 'Remove connected blocks'])
                    ]**
Please help how to update this using PHP code.

**Comment by fiboknacky** [comment]
Please refer to [this example](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/UpdateExpandedTextAd.php#L112).  It shows how to update an ad group ad.

**Comment by divyeshgajja** [comment]
i am facing error.

Given value is not an instance of Google\Ads\GoogleAds\V7\Resources\Ad.

Please tell me how to solve this.
MY CODE:
  $ad = new Ad([
             'resource_name' => ResourceNames::forAd($customerId, $adId),
             'app_ad' => new AppAdInfo([
                 'headlines' => [
                     new AdTextAsset(['text' => 'Divyesh']),
                     new AdTextAsset(['text' => 'Gajjar'])
                 ],
                 'descriptions' => [
                     new AdTextAsset(['text' => 'Gakjjar']),
                     new AdTextAsset(['text' => 'Divesh gajjar'])
                 ]
             ])
         ]);

         // Constructs an operation that will update the ad, using the FieldMasks to derive the
         // update mask. This mask tells the Google Ads API which attributes of the ad you want to
         // change.
         $adOperation = new AdOperation();
         $adOperation->setUpdate($ad);
         $adOperation->setUpdateMask(FieldMasks::allSetFieldsOf($ad));

         // Issues a mutate request to update the ad.
        $adServiceClient = $googleAdsClient->getAdServiceClient();
        $response = $adServiceClient->mutateAds($customerId, [$adOperation]);

        // Prints the resource name of the updated ad.
        /** @var Ad $updatedAd */
        $updatedAd = $response->getResults()[0];
        printf(
            "Updated ad with resource name: '%s'.%s",
            $updatedAd->getResourceName(),
            PHP_EOL
        );

**Comment by fiboknacky** [comment]
Could you share your whole code? Looks like you've not imported the AdGroupAd class properly.
