### ISSUE TITLE
How to update AdGroupAd?

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#597]
i am facing error.

**Given value is not an instance of Google\Ads\GoogleAds\V7\Resources\Ad.**

I need example for Update AdGroup in app_ad.

My Code 👍

  **$ad = new Ad([
             'resource_name' => ResourceNames::forAd($customerId, $adId),
             'app_ad' => new AppAdInfo([
                 'headlines' => [
                     new AdTextAsset(['text' => 'Divyesh']),
                     new AdTextAsset(['text' => 'Gajjar'])
                 ],
                 'descriptions' => [
                     new AdTextAsset(['text' => 'Gakjjar']),
                     new AdTextAsset(['text' => 'Divesh gajjar'])
                 ]
             ])
         ]);

         $adOperation = new AdOperation();
         $adOperation->setUpdate($ad);
         $adOperation->setUpdateMask(FieldMasks::allSetFieldsOf($ad));

        $adServiceClient = $googleAdsClient->getAdServiceClient();
        $response = $adServiceClient->mutateAds($customerId, [$adOperation]);

        $updatedAd = $response->getResults()[0];
        printf(
            "Updated ad with resource name: '%s'.%s",
            $updatedAd->getResourceName(),
            PHP_EOL
        );**

**Comment by fiboknacky** [comment]
Please continue discussing in the existing issue.
