### ISSUE TITLE
INVALID_ARGUMENT Campaign and Adgroup

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#598]
I am facing Error like this:

{ "message": "Request contains an invalid argument.", "code": 3, "status": "INVALID_ARGUMENT", "details": [ { "@type": "google.ads.googleads.v6.errors.googleadsfailure-bin", "data": "<Unknown Binary Data>" }, { "@type": "grpc-status-details-bin", "data": "<Unknown Binary Data>" }, { "@type": "request-id", "data": "_t8X1kPYNjnnqewg4OX62g" } ] }

I don’t know why.

Kindly please tell me how to solve this.

This error is show when I am created Adgroup or campaign using PHP.

Please tell me how to solve this

**Comment by PierrickVoulet** [comment]
Hi @divyeshgajja - This seems to be an API-related issue, please create a new post on this [forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) for investigation.
