### ISSUE TITLE
Google Ads failure details: collection_size_error: Too few.

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#599]
Hello everyone,
i am facing some error when i am trying to create adgroup .

ERROR:
**Google Ads failure details: collection_size_error: Too few.**

i dont know why?
can you guys please tell me how to solve this.

**Comment by fiboknacky** [comment]
Could you please ask in [this forum](https://groups.google.com/g/adwords-api)? Chances are you've specified something wrong in the request. Experts on the forum will help you identify what's wrong based on your log. Thanks.

**Comment by divyeshgajja** [comment]
I am facing some warning .

proto descriptor was previously loaded (included in multiple metadata bundles?): google/ads/googleads/v6/common/custom_parameter.proto [ROOT/plugins/googleads/metadata/Google/Ads/GoogleAds/V6/Resources/AdGroup.php, line 180]

How to solve this warning.

Please tell me.

Thanks,
Divyesh

**Comment by PierrickVoulet** [comment]
Hi @divyeshgajja - An issue is already opened for this particular problem, see #540.

**Comment by adamgen** [comment]
I had a similar problem when I was sending this request:

```
{
    "status": "ENABLED",
    "resource_name": "customers/1310914546/adGroupAds/138411489117~-1",
    "ad": {
         // ... ad data...
    }
}
```

I got thie error:

```
{
  "errors": [
    {
      "error_code": {
        "collection_size_error": "TOO_FEW"
      },
      "message": "Too few.",
      "location": {
        "field_path_elements": [
          {
            "field_name": "operations",
            "index": 0
          },
          {
            "field_name": "create"
          },
          {
            "field_name": "ad"
          },
          {
            "field_name": "responsive_display_ad"
          }
        ]
      }
    }
  ],
  "request_id": "mgwfdaAiCjDqvtX71qFfSQ"
}
```

I've contacted the [adwords forum](https://groups.google.com/g/adwords-api) as @fiboknacky recommanded and they were fast and helpful.

In my case, it was because my `resource_name` ended with a `-1` and such endings were saved for mutations and batch requests. Replacing the `resource_name` with an `ad_group` with a correct path resolved it for me.
