### ISSUE TITLE
Keyword_type ignored on negative keywords

### ISSUE THREAD

**Issue by cappadaan** [googleads/google-ads-php#600]
google-ads-php-v9.0.0
Google Ads API: V7
php: 8.0.6
REST api

code:

		$adGroupCriterion = new AdGroupCriterion([
			'ad_group' => 'resource-url',
			'status' => 1,
			'negative' => true, 
			'keyword' => new KeywordInfo([
				'text' => 'keyword',
				'match_type' => KeywordMatchType::EXACT
			])
		]);

results in broad negative keyword.

- match_type has no effect
- using "+keyword" or "[keyword]" has no effect, they are being ignored

**Comment by fiboknacky** [comment]
As this is the product question, could you please ask in [this forum](https://groups.google.com/g/adwords-api)? Thanks.
