### ISSUE TITLE
proto descriptor was previously loaded (included in multiple metadata bundles?)

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#601]
Hey guys,
i am facing this Warning every time when my code is run can you guys please tell me how to solve this .
**i am already use latest version of Protobuf.**
**and i am using latest v7 version.**

**proto descriptor was previously loaded (included in multiple metadata bundles?): google/ads/googleads/v7/common/custom_parameter.proto [ROOT/plugins/googleads/metadata/Google/Ads/GoogleAds/V7/Resources/AdGroup.php, line 180]**

i am searching every where but still nobody have solution.
Please help

**Comment by fiboknacky** [comment]
Could you please checked [this reply](https://github.com/googleads/google-ads-php/issues/599#issuecomment-847084240) in the issue you previously created?

**Comment by PierrickVoulet** [comment]
This is a duplicate, please follow #540 for updates.
