### ISSUE TITLE
GoogleAdsLoggingInterceptor Issue V6.1

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleads/google-ads-php#602]
Hi Google Team, I have an issue with version 6.1,

Php: PHP 7.2.34
GRPC: 1.38.0

**Error**: 
`Fatal error: Uncaught TypeError: Argument 4 passed to Google\Ads\GoogleAds\Lib\V
6\GoogleAdsLoggingInterceptor::interceptUnaryUnary() must be of the type array,
object given, called in D:\site\htdocs\google_ads_v
6\google-ads-php-6.1.0\vendor\grpc\grpc\src\lib\BaseStub.php on line 428 and def
ined in D:\site\google_ads_v6\google-ads-php
-6.1.0\src\Google\Ads\GoogleAds\Lib\V6\GoogleAdsLoggingInterceptor.php:53
Stack trace:
#0 D:\site\google_ads_v6\google-ads-php-6.1.
0\vendor\grpc\grpc\src\lib\BaseStub.php(428): Google\Ads\GoogleAds\Lib\V6\Google
AdsLoggingInterceptor->interceptUnaryUnary('/google.ads.goo...', Object(Google\A
ds\GoogleAds\V6\Services\SearchGoogleAdsRequest), Array, Object(Closure), Array,
 Array)
#1D:\site\htdocs\google_ads_v6\google-ads-php-6.1.
0\vendor\grpc\grpc\src\lib\BaseStub.php(541): Grpc\BaseStub->Grpc\{closure}('/go
ogle.ads.goo...', Object(Google\Ads\GoogleAds\V6\Services\Sear in D:\sites\google_ads_v6\google-ads-php-6.1.0\src\Google\Ads\
GoogleAds\Lib\V6\GoogleAdsLoggingInterceptor.php on line 53`

**Comment by fiboknacky** [comment]
What's your installed [`google/gax`](https://github.com/googleads/google-ads-php/blob/v7.0.0/composer.json#L8) version? Is it 1.5.0?

**Comment by Eksilente** [comment]
I got the same issue 

Exception: Argument 4 passed to Google\Ads\GoogleAds\Lib\V5\GoogleAdsLoggingInterceptor::interceptUnaryStream() must be of the type array, object given, called in /srv/projects/contology/vendor/grpc/grpc/src/lib/BaseStub.php on line 452 /srv/projects/contology/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V5/GoogleAdsLoggingInterceptor.php 83

Hoping for a fix please.

**Comment by fiboknacky** [comment]
@Eksilente 
Could you update your `google/gax` to 1.5.0?

**Comment by Eksilente** [comment]
> @Eksilente
> Could you update your `google/gax` to 1.5.0?

Thank you for the quck response. But I still got the same error even though I have run composer update on vendor/googleads/google-ads-php with file composer.json below
{
  "name": "googleads/google-ads-php",
  "author": "Google LLC",
  "url": "https://github.com/googleads/google-ads-php",
  "description": "Google Ads API client for PHP",
  "require": {
    "php": ">=7.2",
    "google/gax": "1.5.0",
    "google/protobuf": "^3.13.0",
    "ulrichsg/getopt-php": "^3.4",
    "monolog/monolog": "^1.23.0 || ^2.0"
  },
  
This is the error details

  ERROR - 2021-06-01 10:44:34 --> Severity: error --> Exception: Argument 4 passed to Google\Ads\GoogleAds\Lib\V5\GoogleAdsLoggingInterceptor::interceptUnaryStream() must be of the type array, object given, called in /srv/projects/projectname/vendor/grpc/grpc/src/lib/BaseStub.php on line 452 /srv/projects/projectname/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V5/GoogleAdsLoggingInterceptor.php 83

**Comment by fiboknacky** [comment]
I'm sorry I missed this for a long time.
Could you please upgrade to the latest version and let us know if you still face this issue. Thanks!

**Comment by fiboknacky** [comment]
Close due to inactivity.

**Comment by adrianlaraperez88** [comment]
@fiboknacky your team never reply about it, we waiting for the Google team to give us information.

**Comment by fiboknacky** [comment]
I'm sorry for the delay once again. Did you happen to do what I suggested in [this comment](https://github.com/googleads/google-ads-php/issues/602#issuecomment-968657375)?

**Comment by adrianlaraperez88** [comment]
@fiboknacky I use the last version, i will check soon if this issue not fixed, can you please closed and we open if we need please
