### ISSUE TITLE
AdGroup Status not Found

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#604]
Hello everyone i need help,

i need AdGroup Status in Text Format but Google Api is response me 1,2 Format.

**My Function : $googleAdsRow->getAdGroup()->getStatus();**

How can i get Status in text Format like ex: ENABLED, PAUSED etc etc.

Please help.

**Comment by fiboknacky** [comment]
You need to convert it by yourself, using an enum-like class.
Please take a look at [this line](https://github.com/googleads/google-ads-php/blob/master/examples/Reporting/GetKeywordStats.php#L150) as an example.

**Comment by divyeshgajja** [comment]
Hello sir,
I need help for create billing setup but my code is stock 

$stream = $googleAdsClient->getGoogleAdsServiceClient()->searchStream($customerId, $query);
/** @var <https://github.com/var> GoogleAdsRow $googleAdsRow */
$googleAdsRow = $stream->iterateAllElements()->current();

How can I solve this..

**Comment by fiboknacky** [comment]
Please create a new issue for this.
