### ISSUE TITLE
[Automation] 3. Delete Merged Branch

### ISSUE THREAD

**Issue by laurachevalier4** [googleads/google-ads-php#608]
Automatically delete branches after merge to maintain repository cleanliness and avoid branches that were leftover “just in case”.

**Comment by PierrickVoulet** [comment]
@laurachevalier4 Could you provide precise instruction on how to this right?

**Comment by laurachevalier4** [comment]
Instructions are linked on the mirrored internal bug

**Comment by PierrickVoulet** [comment]
> Instructions are linked on the mirrored internal bug

Thanks!

**Comment by PierrickVoulet** [comment]
Done.
