### ISSUE TITLE
Hide Customer Client returns error

### ISSUE THREAD

**Issue by fredlovine** [googleads/google-ads-php#611]
**What versions of the client library and Google Ads API are you using?**
v9.0.0 and V7

**What environment are you using?**
================= PHP GENERAL INFORMATION
phpinfo()
PHP Version => 7.4.16

System => Windows NT XPS8700-2 10.0 build 19042 (Windows 10) AMD64
Build Date => Mar  2 2021 13:58:29
Compiler => Visual C++ 2017
Architecture => x64
Configure Command => cscript /nologo /e:jscript configure.js  "--enable-snapshot-build" "--enable-debug-pack" "--with-pdo-oci=c:\php-snap-build\deps_aux\oracle\x64\instantclient_12_1\sdk,shared" "--with-oci8-12c=c:\php-snap-build\deps_aux\oracle\x64\instantclient_12_1\sdk,shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--without-analyzer" "--with-pgo"
Server API => Command Line Interface
Virtual Directory Support => enabled
Configuration File (php.ini) Path =>  
Loaded Configuration File => C:\xampp\php\php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
PHP API => 20190902
PHP Extension => 20190902
Zend Extension => 320190902
Zend Extension Build => API320190902,TS,VC15
PHP Extension Build => API20190902,TS,VC15
Debug Build => no
Thread Safety => enabled
Thread API => Windows Threads
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => disabled

Registered PHP Streams => php, file, glob, data, http, ftp, zip, compress.zlib, compress.bzip2, https, ftps, phar
Registered Stream Socket Transports => tcp, udp, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters => convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, zlib.*, bzip2.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans
================= PHP EXTENSION INFORMATION
The PHP Extension grpc is not installed  ***same issue occurs with grpc installed***
The PHP Extension protobuf is not installed

**Actions taken**
	public function hideCustomerClient($resourceName)
	{
		$customerClientLink = new CustomerClientLink();
		$customerClientLink->setResourceName($resourceName);
		$customerClientLink->setHidden(true);

		$customerClientLinkOperation = new CustomerClientLinkOperation();
		$customerClientLinkOperation->setUpdate($customerClientLink);
		$customerClientLinkOperation->setUpdateMask(FieldMasks::allSetFieldsOf($customerClientLink));

		$customerClientLinkServiceClient = $this->client->getCustomerClientLinkServiceClient();
		$customerClientLinkServiceClient->mutateCustomerClientLink(
			$this->managerCustomerId,
			$customerClientLinkOperation
		);

	}

**Expected result**
- expecting no error, customer client set to hidden

**Actual result**
Google\ApiCore\ApiException : {
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": 0,
            "data": "type.googleapis.com\/google.ads.googleads.v7.errors.GoogleAdsFailure"
        },
        {
            "@type": 0,
            "data": [
                {
                    "errorCode": {
                        "managerLinkError": "INVALID_STATUS_CHANGE"
                    },
                    "message": "The changed status for mutate link is invalid.",
                    "location": {
                        "fieldPathElements": [
                            {
                                "fieldName": "operation"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "@type": 0,
            "data": "89hOxPbOClSIe8-Gx28Tfg"
        }
    ]
}
 C:\99calls\server\lib\vendor\google\gax\src\ApiException.php:139
 C:\99calls\server\lib\vendor\google\gax\src\ApiException.php:109
 C:\99calls\server\lib\vendor\google\gax\src\Transport\RestTransport.php:167
 C:\99calls\server\lib\vendor\google\gax\src\Transport\RestTransport.php:131
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:204
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:153
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\TaskQueue.php:48
 C:\99calls\server\lib\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php:118
 C:\99calls\server\lib\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php:145
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:248
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:224
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:269
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:226
 C:\99calls\server\lib\vendor\guzzlehttp\promises\src\Promise.php:62
 C:\99calls\server\lib\vendor\googleads\google-ads-php\src\Google\Ads\GoogleAds\V7\Services\Gapic\CustomerClientLinkServiceGapicClient.php:366
 C:\99calls\server\lib\GoogleAds\GoogleAdsApiLib.php:297
 C:\99calls\server\tests\integration\lib\GoogleAds\GoogleAdsApiLibTest.php:102

 

**Anything else we should know about your project / environment**
The API is working except for this action. I've tried as a Google Ads admin user. I've tried many other things as well.

**Comment by PierrickVoulet** [comment]
Hi @fredlovine,

The request sent by the library did not try to change the status so it is not clear why you are receiving this error (`INVALID_STATUS_CHANGE `). The issue is specific to the Google Ads API, please contact their [support](https://developers.google.com/google-ads/api/support) for further investigation.
