### ISSUE TITLE
Billing Setup issue 

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#617]
Hello Everyone 
i am trying to create billing setup but after run this code in my browser i am not geting any responce 
can you guys tell me how to solve this.

$response = $billingSetupServiceClient->mutateBillingSetup(
            $customerId,
            $billingSetupOperation
        );
          echo $response->getResult()->getResourceName();
          exit;

My all code are proper but when i am try to print responce i am geting this error.
Please tell me how to solve this.
<img width="1440" alt="Screenshot 2021-06-14 at 9 30 28 PM" src="https://user-images.githubusercontent.com/73573948/121993481-2fd80300-cdc1-11eb-806e-bd4ec7c889a0.png">

**Comment by fiboknacky** [comment]
Please stop creating a new issue for the issue you've already created.
