### ISSUE TITLE
The V7 release does not include the V7 classes

### ISSUE THREAD

**Issue by yoosefi** [googleads/google-ads-php#618]
**Your client library and Google Ads API versions:**

* Client library version: `7.0.0`
* Google Ads API version: `V7`

**Your environment:**
N/A

**Description of the bug:**
The `v7.0.0` release tag points to a commit that does not have the V7 classes.

**Steps to reproduce:**
```
git clone git@github.com:googleads/google-ads-php.git
cd google-ads-php
git checkout tags/v7.0.0 -b v7
find -type d -name 'V7'
```

**Expected behavior:**
The V7 namespace should be present.

**Comment by PierrickVoulet** [comment]
Hi @yoosefi,

This works as intended, let me clarify:

1. The version of the client library is incremented independently from the version of the Google Ads API.
2. Any version of the client library typically supports multiple versions of the Google Ads API.
2. You can check the [`CHANGELOG.md`](https://github.com/googleads/google-ads-php/blob/master/CHANGELOG.md) file to know what versions of the client library added and removed the support for a specific version of the Google Ads API. For example, the support for the version `V7` of the Google Ads API was added in the version `v9.0.0` of the client library (see [here](https://github.com/googleads/google-ads-php/blob/master/CHANGELOG.md#900)).

**Comment by yoosefi** [comment]
@PierrickVoulet is this "intended behavior" documented somewhere, because i seem to have missed it.

**Comment by PierrickVoulet** [comment]
> @PierrickVoulet is this "intended behavior" documented somewhere, because i seem to have missed it.

It was not explicitly documented so I created #619, thank you for the feedback!
