### ISSUE TITLE
proto descriptor was previously loaded (included in multiple metadata bundles?):

### ISSUE THREAD

**Issue by Ljiayi** [googleads/google-ads-php#621]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your client library and Google Ads API versions:**

* Client library version: `v10.0.0`

* Google Ads API version: `V8`

**Your environment:**
linux
php:7.4
grpc:1.38.0
protobuf :3.17.3

**Description of the bug:**
proto descriptor was previously loaded (included in multiple metadata bundles?):
**Steps to reproduce:**
$response = $googleAdsServiceClient->search($customerId, $query, ['pageSize' => self::PAGE_SIZE]);
**Expected behavior:**

**Request/Response Logs:**
proto descriptor was previously loaded (included in multiple metadata bundles?):

 
**Anything else we should know about your project / environment:**

help help.....................

**Comment by PierrickVoulet** [comment]
Hi @Ljiayi - This is a duplicate, please refer to #540.
