### ISSUE TITLE
historicalMetricsOptions in KeywordIdeas doesn't work

### ISSUE THREAD

**Issue by andre-startup** [googleads/google-ads-php#627]
**Your client library and Google Ads API versions:**

* Client library version: `v10.1.0`

* Google Ads API version: `V8`

**Description of the bug:**

I'm trying set the date range for KeywordIdeas as stated in the documentation
https://developers.google.com/google-ads/api/rest/reference/rest/v8/HistoricalMetricsOptions:

```
$requestOptionalArgs['historicalMetricsOptions'] = new HistoricalMetricsOptions([
	'yearMonthRange' => new YearMonthRange([
		'start' => new YearMonth([
			"year" => 2020,
			"month" => Month::FEBRUARY
		]),
		'end' => new YearMonth([
			"year" => 2020,
			"month" => Month::APRIL
		])
	])
]);
```

it doesn't work, returns an error: 
`Invalid message property: yearMonthRange`

but it is set according to the documentation and based on the code inside, I cannot set it otherwise

**Comment by fiboknacky** [comment]
The properties in the generated class are in the snake_case form. So in your case, you need to use 'year_month_range'.
