### ISSUE TITLE
PHPUnit Unable to Mock GoogleAdsRow:class

### ISSUE THREAD

**Issue by andjelboskovic** [googleads/google-ads-php#630]
"googleads/google-ads-php": "^10.0

* Google Ads API version: 8

**Your environment:**

* The PHP version: php 7.4
* The name and version of the operating system: Linux 54f0049bf57f 5.10.25-linuxkit
* Whether the PHP Extension `protobuf` is used or not: 3.17.3
* Whether the PHP Extension `grpc` is used or not: 1.38.0
* The type of transport being used (`grpc` or `rest`): grps

phpunit 8.5

**Description of the bug:**

While trying to mock GoogleAdsRow::class I'm getting an error.

```
<?php
namespace GoogleAds;
use Google\Ads\GoogleAds\V8\Services\GoogleAdsRow;
use PHPUnit\Framework\TestCase;
class GoogleAdsBugTest extends TestCase {
  public function testBug(): void
  {
    $googleAdsRow = $this->createMock(GoogleAdsRow::class);
  }
}
```

I've also tried building as:
```
$googleAdsRow = new GoogleAdsRow();
$googleAdsRow->setAdGroup($adGroup);
$googleAdsRow->setMetrics($metrics);
$googleAdsRow->setSegments($segments);
```

But is also resolves as an error.

**Steps to reproduce:**

Provided above

**Expected behavior:**

The class should be mocked and available for testing

**Request/Response Logs:**

Let me know if there is a way to make this work, or if you need any more details.

Thank you in advance,
Andjel

**Comment by fiboknacky** [comment]
```php
$googleAdsRow = new GoogleAdsRow();
$googleAdsRow->setAdGroup($adGroup);
$googleAdsRow->setMetrics($metrics);
$googleAdsRow->setSegments($segments);
```

Do you mean if the above resolves your issue?

**Comment by andjelboskovic** [comment]
Hi and thank you for responding.

This is not the best example from my side.
`$googleAdsRow = new GoogleAdsRow();
$googleAdsRow->setAdGroup($adGroup);
$googleAdsRow->setMetrics($metrics);
$googleAdsRow->setSegments($segments);`

I can create GoogleAdsRow() in this way but when I use it in the testing context and compare to the returning result of a mocked class an error occurs.

This is a good and reproducible example of the error I'm being faced with, so it may be best to focus on it:

`<?php
namespace GoogleAds;
use Google\Ads\GoogleAds\V8\Services\GoogleAdsRow;
use PHPUnit\Framework\TestCase;
class GoogleAdsBugTest extends TestCase {
  public function testBug(): void
  {
    $googleAdsRow = $this->createMock(GoogleAdsRow::class);
  }
}`

Thank you

**Comment by fiboknacky** [comment]
The classes generated by the [protobuf](https://github.com/protocolbuffers/protobuf) library cannot be created using a mock like that. You can create a new class like you showed.

If you have a valid use case why mocking is better, please feel free to file a feature request on the [library repository](https://github.com/protocolbuffers/protobuf/issues).
