### ISSUE TITLE
AuthenticateInWebApplication stuck at authorized redirect URI

### ISSUE THREAD

**Issue by steponafish** [googleads/google-ads-php#631]
Hello. I found the closed issue on this topic and followed all the steps for [OAuth Web Application Flow ](https://developers.google.com/google-ads/api/docs/client-libs/php/oauth-web) and I get to the "Choose an account" and then I run into "Site Can't be reached 127.0.0.1 refused to connect." I'm not redirected to the authorization succeeded message and the terminal messaging did not update either. 

This is on a web server with LiquidWeb. I have registered http://127.0.0.1:8080/oauth2callback (advice from the other thread) and http://localhost/oauth2callback. I have ensured that the port is open. Am I doing anything wrong?

**Comment by fiboknacky** [comment]
> Site Can't be reached 127.0.0.1 refused to connect.

This looks like your web server still rejects your request.

To be clear, you create you own web server, correct?
Note that the steps in [OAuth Web Application Flow](https://developers.google.com/google-ads/api/docs/client-libs/php/oauth-web) are for our [AuthenticateInWebApplication](https://github.com/googleads/google-ads-php/blob/master/examples/Authentication/AuthenticateInWebApplication.php) example.
Although they're similar, there might be some difference.

You'd need to ensure that you set 127.0.0.1 as **redirect URIs** in your [Google Cloud console](https://support.google.com/cloud/answer/6158849?hl=en#zippy=%2Cuser-consent%2Cweb-applications) as well.

**Comment by steponafish** [comment]
Hi @fiboknacky,

I am on a shared server. Would I need to have my own server then?

When I authenticated way back with Google Adwords API, I had no issue with the setup and authentication process and everything is working just fine with the old API.

**Comment by fiboknacky** [comment]
> I am on a shared server. Would I need to have my own server then?

Shared severs should work fine as long as the configuration is correct.
Unfortunately, I don't have visibility of how your shared severs are configured, so I cannot provide much more insight.
I actually don't expect the authentication flow would be much different between AdWords API and Google Ads API, though.

**Comment by steponafish** [comment]
That's what I thought. Thank you. I had set up the AdWords API with no
issue. So I'm not really sure why I'm having such an issue with the
authentication for Ads API. Since I didn't have any issues with setting up
the AdWords API, I think it might be the new files themselves. Is there a
way where I can authenticate and get the refreshtoken without using the
command line to the shared server?

**Comment by fiboknacky** [comment]
If you wish to just get a refresh token and re-use it for a long time, you can just run [this example](https://github.com/googleads/google-ads-php/blob/master/examples/Authentication/AuthenticateInDesktopApplication.php) on your computer.

Feel free to reach out to [this forum](https://groups.google.com/g/adwords-api) to get help about the OAuth process in general.
Agent monitoring the forum will respond to your question in a timely manner.
