### ISSUE TITLE
don't mark GoogleAdsClient class as final

### ISSUE THREAD

**Issue by 77web** [googleads/google-ads-php#639]
**Problem you are trying to solve:**

Can't write unit tests for our classes to interact with GoogleAdsClient.

**Solution you'd like:**

Don't mark GoogleAdsClient class as final so that we can mock it in our unit tests.

**Alternatives you've considered:**

Define GoogleAdsClientInterface and implement it to GoogleAdsClient.

**Additional context:**

none

**Comment by PierrickVoulet** [comment]
Hi @77web - Thank you for the feedback! This is a known improvement, you can refer to https://github.com/googleads/google-ads-php/issues/347.
