### ISSUE TITLE
Failed to parse binary descriptor

### ISSUE THREAD

**Issue by rpmgr** [googleads/google-ads-php#640]
Hi,

My code is working fine on Dev server but throws Error on Production server, am I missing anything on Production?

`Error: Fatal Error (1): Failed to parse binary descriptor in [../app/Vendor/googleads/google-ads-php/metadata/Google/Ads/GoogleAds/V8/Services/ConversionUploadService.php, line 124]`

Thanks in advance.

**Comment by PierrickVoulet** [comment]
Hi @rpmgr,

I tried to reproduce this issue without success so far. Could you provide the following information?

**Your environment:**

_You can paste the output generated by our complementary script: https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php._

_Alternatively, please provide with the following pieces of information:_

* _The PHP version: Run `php -v`._
* _The name and version of the operating system: Run `php -r 'print php_uname();'`._
* _Whether the PHP Extension `protobuf` is used or not: Run `php -r 'print phpversion("protobuf");'`._
* _Whether the PHP Extension `grpc` is used or not: Run `php -r 'print phpversion("grpc");'`._
* _The type of transport being used (`grpc` or `rest`): See https://developers.google.com/google-ads/api/docs/client-libs/php/transport._

**Steps to reproduce:**

_You can paste the piece of code that fails here._

**Comment by rpmgr** [comment]
**Environment:**
<html>
<body>
<span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 237, 231); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">================= PHP GENERAL INFORMATION</span><div class="center" style="box-sizing: border-box; text-align: center; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

PHP Version 7.4.22
--


</div><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 237, 231); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">================= PHP EXTENSION INFORMATION<br /> The PHP Extension grpc is installed: 1.39.0.<br /> The PHP Extension protobuf is installed: 3.17.3.<br />Since, I've installed the gRPC PHP extension, I think the client library is using `grpc` as a transport.</span>
</body>
</html>


Additional information:
=================================
FYI: PHP Version and gRPC version in my dev is 7.4.21 and 1.38.0 respectively.
OS in dev is Ubuntu 18.04.3 LTS and Debian 4.19.194-3 in production.

=================================
**Steps to reproduce:**
While trying to upload conversion I get the error.

**Piece of code that fails:**

`namespace GPBMetadata\Google\Ads\GoogleAds\V8\Services;

class ConversionUploadService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Http::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Google\Rpc\Status::initOnce();
        $pool->internalAddGeneratedFile(
            '
�
@google/ads/googleads/v8/services/conversion_upload_service.proto google.ads.googleads.v8.servicesgoogle/api/client.protogoogle/api/field_behavior.protogoogle/api/resource.protogoogle/rpc/status.proto"�
UploadClickConversionsRequest
customer_id (	B�AK
conversions (21.google.ads.googleads.v8.services.ClickConversionB�A
partial_failure (B�A

validate_only ("�
UploadClickConversionsResponse1
partial_failure_error (2.google.rpc.StatusH
results (27.google.ads.googleads.v8.services.ClickConversionResult"�
UploadCallConversionsRequest
customer_id (	B�AJ
conversions (20.google.ads.googleads.v8.services.CallConversionB�A
partial_failure (B�A

validate_only ("�
UploadCallConversionsResponse1
partial_failure_error (2.google.rpc.StatusG
results (26.google.ads.googleads.v8.services.CallConversionResult"�
ClickConversion
gclid	 (	H �
conversion_action
 (	H�!
conversion_date_time (	H�
conversion_value (H�

currency_code
 (	H�
order_id (	H�\\
external_attribution_data (29.google.ads.googleads.v8.services.ExternalAttributionDataJ
custom_variables (20.google.ads.googleads.v8.services.CustomVariable=
	cart_data (2*.google.ads.googleads.v8.services.CartDataB
_gclidB
_conversion_actionB
_conversion_date_timeB
_conversion_valueB
_currency_codeB
	_order_id"�
CallConversion
	caller_id (	H �!
call_start_date_time (	H�
conversion_action	 (	H�!
conversion_date_time
 (	H�
conversion_value (H�

currency_code (	H�J
custom_variables
 (20.google.ads.googleads.v8.services.CustomVariableB

_caller_idB
_call_start_date_timeB
_conversion_actionB
_conversion_date_timeB
_conversion_valueB
_currency_code"�
ExternalAttributionData(
external_attribution_credit (H �\'
external_attribution_model (	H�B
_external_attribution_creditB
_external_attribution_model"�
ClickConversionResult
gclid (	H �
conversion_action (	H�!
conversion_date_time (	H�B
_gclidB
_conversion_actionB
_conversion_date_time"�
CallConversionResult
	caller_id (	H �!
call_start_date_time (	H�
conversion_action (	H�!
conversion_date_time (	H�B

_caller_idB
_call_start_date_timeB
_conversion_actionB
_conversion_date_time"{
CustomVariableZ
conversion_custom_variable (	B6�A3
1googleads.googleapis.com/ConversionCustomVariable
value (	"�
CartData
merchant_id (	
feed_country_code (	
feed_language_code (	
local_transaction_cost (>
items (2/.google.ads.googleads.v8.services.CartData.Item@
Item

product_id (	
quantity (

unit_price (2�
ConversionUploadService�
UploadClickConversions?.google.ads.googleads.v8.services.UploadClickConversionsRequest@.google.ads.googleads.v8.services.UploadClickConversionsResponse"i���9"4/v8/customers/{customer_id=*}:uploadClickConversions:*�A\'customer_id,conversions,partial_failure�
UploadCallConversions>.google.ads.googleads.v8.services.UploadCallConversionsRequest?.google.ads.googleads.v8.services.UploadCallConversionsResponse"h���8"3/v8/customers/{customer_id=*}:uploadCallConversions:*�A\'customer_id,conversions,partial_failureE�Agoogleads.googleapis.com�A\'https://www.googleapis.com/auth/adwordsB�
$com.google.ads.googleads.v8.servicesBConversionUploadServiceProtoPZHgoogle.golang.org/genproto/googleapis/ads/googleads/v8/services;services�GAA� Google.Ads.GoogleAds.V8.Services� Google\\Ads\\GoogleAds\\V8\\Services�$Google::Ads::GoogleAds::V8::Servicesbproto3'
        , true);
        static::$is_initialized = true;
    }
`

**Comment by rpmgr** [comment]
Hi @PierrickVoulet,

**Some background:**
I've installed C implementation of grpc and protobuf using PECL. I've installed the client library using `composer install` and I think, it might have installed the PHP version of grpc and protobuf as well to use with `rest`?

**To reproduce the error:**
When I specify the transport as `rest` in the code using following line:
`->withTransport('rest')`
I get the error.

Also, could it be that my git command line is changing `LF` to `CRLF` while pushing the file to repo. I get following warning while pushing all the libs files:
`The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ...`

Thanks,

**Comment by PierrickVoulet** [comment]
@rpmgr Thank you for the additional information, this is helpful!

If you have installed the C implementation of grpc and protobuf using PECL then you can use the `grpc` transport, no need to set it up to `rest`.

Could you provide us with the actual code that you execute and that fails, and the error logs when it fails using `grpc` as a transport? I tried to change the end of line to CRLF on my side but, as far as I can tell, it does not make it fail on my end.

**Comment by rpmgr** [comment]
Hi @PierrickVoulet, thank you for your quick response. 

The codes are separated into different class files as a method. I'll paste the methods involved below:
`public function testGoogleAdsLib()
    {
        echo 'Test Upload Conversion';
        $this->getComponent('GoogleAdsApi');
        $data = [
            'id' => 1,
            'related_id' => 18948,
            'related_table' => 'policies',
            'product_type' => 'warranty',
            'gclid' => 'test1',
            'conversion_action_id' => 758401197,
            'created' => '2021-08-26 18:50:21',
        ];
        try {
            $response = $this->GoogleAdsApi->handleOfflineConversion($data);
            echo 'Response status: ' . $response;
        }  catch (Exception $e) {
            echo '<pre>';
            print_r($e->getTraceAsString());
            echo '</pre>';
            echo 'Error: ' . $e->getMessage();
        }

        if ($this->GoogleAdsApi->hasError()) {
            echo '<pre>';
            print_r($this->GoogleAdsApi->getErrors());
            echo '</pre>';
        }

        exit();
    }

    /*================================================================================*/

    public function handleOfflineConversion(array $data = []): bool
    {
        if(empty($data)) {
            return false;
        }

        $this->resetError();
        $errors = [];

        try {
            $this->uploadOfflineConversion(
                $this->googleAdsClient,
                $this->getCustomerId($data['product_type']),
                $data['conversion_action_id'],
                $data['gclid'],
                $this->getConversionDateTime($data['created'])
            );
        } catch (GoogleAdsException $googleAdsException) {
            $errors[] = sprintf(
                "Request with ID '%s' has failed.%sGoogle Ads failure details:%s",
                $googleAdsException->getRequestId(),
                PHP_EOL,
                PHP_EOL
            );

            foreach ($googleAdsException->getGoogleAdsFailure()->getErrors() as $error) {
                /** @var GoogleAdsError $error */
                $errors[] = sprintf(
                    "\t%s: %s%s",
                    $error->getErrorCode()->getErrorCode(),
                    $error->getMessage(),
                    PHP_EOL
                );
            }

            $this->addErrors($errors);
        } catch (ApiException $apiException) {
            $errors[] = sprintf(
                "ApiException was thrown with message '%s'.%s",
                $apiException->getMessage(),
                PHP_EOL
            );

            $this->addErrors($errors);
        }

        if ($this->hasError()) {
            $this->addLog(
                [
                    'action' => 'upload',
                    'data' => $data,
                ],
                $data['related_table'],
                $data['related_id']
            );

            return false;
        }

        return true;
    }

    /*================================================================================*/

    private function uploadOfflineConversion(
        GoogleAdsClient $googleAdsClient,
        int $customerId,
        int $conversionActionId,
        string $gclid,
        string $conversionDateTime,
        string $conversionCustomVariableId = null,
        string $conversionCustomVariableValue = null
    ): void {
        // Creates a click conversion by specifying currency as GBP.
        $clickConversion = new ClickConversion([
            'conversion_action' => ResourceNames::forConversionAction($customerId, $conversionActionId),
            'gclid' => $gclid,
            'conversion_value' => self::CONVERSION_VALUE,
            'conversion_date_time' => $conversionDateTime,
            'currency_code' => self::CURRENCY_CODE
        ]);

        if (!is_null($conversionCustomVariableId) && !is_null($conversionCustomVariableValue)) {
            $clickConversion->setCustomVariables([
                new CustomVariable([
                    'conversion_custom_variable' => ResourceNames::forConversionCustomVariable(
                        $customerId,
                        $conversionCustomVariableId
                    ),
                    'value' => $conversionCustomVariableValue
                ])
            ]);
        }

        // Issues a request to upload the click conversion.
        $conversionUploadServiceClient = $googleAdsClient->getConversionUploadServiceClient();
        $response = $conversionUploadServiceClient->uploadClickConversions(
            $customerId,
            [$clickConversion],
            true
        );

        if (!is_null($response->getPartialFailureError())) {
            $this->addError(
                sprintf(
                    "Partial failures occurred: '%s'.%s",
                    $response->getPartialFailureError()->getMessage(),
                    PHP_EOL
                )
            );
        }
    }`

I don't have the server access so, I would have to print the `grpc` error log when I run the test through browser. Is there any information as how I can do that or you could point me to right direction?

Thanks,

**Comment by rpmgr** [comment]
Thank you @PierrickVoulet for taking time to look into this.

I've fixed this now.

Thanks,

**Comment by PierrickVoulet** [comment]
I am glad you found the issue and thank you for sharing the resolution.

I was able to reproduce the issue related to REST on my end as well, I created a new issue for it https://github.com/googleads/google-ads-php/issues/640.
