### ISSUE TITLE
How do I get the campaign budget?

### ISSUE THREAD

**Issue by Winchester37** [googleads/google-ads-php#642]
When I try to get the campaign budget, I get a URL-like response. How can I get the campaign budget?

`SELECT campaign.id, 
                         campaign.name, 
                         campaign.status,            
                         campaign.advertising_channel_type,
                         campaign.advertising_channel_sub_type, 
                         campaign.campaign_budget,
                         metrics.average_page_views,
                         metrics.impressions,
                         metrics.clicks,
                         metrics.ctr,
                         metrics.average_cpc,
                         metrics.cost_micros,
                         metrics.all_conversions, 
                         metrics.engagements,
                         metrics.search_budget_lost_impression_share,
                         metrics.content_budget_lost_impression_share,
                         metrics.search_rank_lost_impression_share,
                         metrics.content_rank_lost_impression_share,
                         metrics.video_quartile_p25_rate,
                         metrics.video_quartile_p50_rate,
                         metrics.video_quartile_p75_rate,
                         metrics.video_quartile_p100_rate, 
                         metrics.video_view_rate,
                         metrics.video_views                          
                FROM campaign
                WHERE segments.date DURING LAST_30_DAYS`

Query result;

`
<html>
<body>

[campaign_id] => 14314107263
--
  | [campaign_name] => XXXXX
  | [campaign_status] => 3
  | [advertising_channel_type] => 2
  | [advertising_channel_sub_type] => 0
  | [campaign_budget] => customers/3449XXX5/campaignBudgets/93XXXX949
  | [metrics_average_page_views] => 0
  | [metrics_impressions] => 78
  | [metrics_clicks] => 3
  | [metrics_ctr] => 0.038461538461538
  | [metrics_average_cpc] => 3800000
  | [metrics_cost_micros] => 11400000
  | [metrics_all_conversions] => 0
  | [metrics_engagements] => 0
  | [metrics_search_budget_lost_impression_share] => 0.87818181818182
  | [metrics_content_budget_lost_impression_share] => 0
  | [metrics_search_rank_lost_impression_share] => 0.07
  | [metrics_content_rank_lost_impression_share] => 0
  | [metrics_video_quartile_p25_rate] => 0
  | [metrics_video_quartile_p50_rate] => 0
  | [metrics_video_quartile_p75_rate] => 0
  | [metrics_video_quartile_p100_rate] => 0
  | [metrics_video_view_rate] => 0
  | [metrics_video_views] => 0

</body>
</html>`

**Comment by PierrickVoulet** [comment]
Hi @Winchester37 - Could you provide the code that your are executing for further investigation?

In the meantime, please check this [code example](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/GetCampaigns.php). It retrieves campaigns instead of campaign budgets but it is really similar to what you are trying to achieve.

**Comment by Winchester37** [comment]
I also need to query to get the campaign budget.

SELECT
    campaign_budget.name,
    campaign_budget.amount_micros,
    campaign_budget.status,
    campaign_budget.total_amount_micros
FROM campaign_budget
WHERE
    campaign_budget.id = XXXXXXXXXXX

**Comment by PierrickVoulet** [comment]
I misunderstood the question, I thought it was an issue with our library but your questions is about how to use [Google Ads API reporting](https://developers.google.com/google-ads/api/docs/reporting/overview).

In your GAQL query, you select `campaign_budget` so its resource name is returned as expected (the URL-like field value you are referring to). If you want to return specific fields of the `campaign_budget` associated to each campaign, you need to add them in the select clause. For example you could use `SELECT campaign.name, campaign_budget.name FROM campaign` to return their names.

For questions that are related to the usage of Google Ads API, please contact the [dedicated support](https://developers.google.com/google-ads/api/support).
