### ISSUE TITLE
'year_month_range' in Generating Historical Metrics

### ISSUE THREAD

**Issue by andre-startup** [googleads/google-ads-php#646]
Hello, Please tell me how I can set the 'year_month_range' range in
**Generating Historical Metrics** https://developers.google.com/google-ads/api/docs/keyword-planning/generate-historical-metrics ?
it is indicated in the section "Mapping to the UI", but there are no examples, and it is unclear how to do it.
**KeywordPlanCampaign** does not have such a method, and **KeywordPlanForecastPeriod** sets the **DateRange**, but has comment: "The custom date range used for forecasting. The start and end dates must be in the future." and this is clearly not the same.

**Comment by PierrickVoulet** [comment]
Hi @andre-startup

The [`KeywordPlanService.GenerateHistoricalMetrics`](https://developers.google.com/google-ads/api/reference/rpc/latest/KeywordPlanService#generatehistoricalmetrics) method takes a [`GenerateHistoricalMetricsRequest`](https://developers.google.com/google-ads/api/reference/rpc/latest/GenerateHistoricalMetricsRequest) instance as an input. The field `historical_metrics_options` of this instance can be set with a [`HistoricalMetricsOptions`](https://developers.google.com/google-ads/api/reference/rpc/latest/HistoricalMetricsOptions) instance. The field `year_month_range` of this instance can be set with a [`YearMonthRange`](https://developers.google.com/google-ads/api/reference/rpc/latest/YearMonthRange) instance.

For any further questions related to the Google Ads API (not this library), please contact the [official Google Ads API support](https://developers.google.com/google-ads/api/support) instead.
