### ISSUE TITLE
bug in Keyword Planning -> historicalMetricsOptions

### ISSUE THREAD

**Issue by andre-startup** [googleads/google-ads-php#647]
Hello, seems I found a bug in the AdsAPI. If trying to set the month of JANUARY in **KeywordPlanService.GenerateHistoricalMetrics**  and **KeywordPlanIdeaService.GenerateKeywordIdeass** in the format:
```
"year_month_range" => new YearMonthRange([
	"start" => new YearMonth([
		"year" => 2019,
		"month" => Month::value("JANUARY")
	]),
	"end" => new YearMonth([
		"year" => 2021,
		"month" => Month::value("JUNE")
	])
])
```
	
date range works, but you can't specify start with "JANUARY", for example:

```
"start" => new YearMonth([
	"year" => 2019,
	"month" => Month::value("JANUARY")
```
		
tried on all years (2018, 2019, 2020, 2021), it doesn't work, returns an error:

```
"message": "Internal error encountered.",
"code": 13,
"status": "INTERNAL",
```
	
At the same time, if you set the month "JANUARY" in 'year_month_range' -> 'end' - it works correctly.

**Comment by fiboknacky** [comment]
As this is a server error, could you please post in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)? Thank you.
