### ISSUE TITLE
historicalMetricsOptions is not working

### ISSUE THREAD

**Issue by aayushb051** [googleads/google-ads-php#648]
I am passing these parameters and its not working. its gives me error 

```
 $response = $keywordPlanIdeaServiceClient->generateKeywordIdeas(
            [
                // Set the language resource using the provided language ID.
                'language' => ResourceNames::forLanguageConstant($languageId),
                'customerId' => $customerId,
			'historicalMetricsOptions' => array (
    'yearMonthRange' => 
    array (
      'start' => 
      array (
        'year' => '2021',
        'month' => 'JUNE',
      ),
      'end' => 
      array (
        'year' => '2021',
        'month' => 'JUNE',
      ),
    ),
  ),
                // Add the resource name of each location ID to the request.
                'geoTargetConstants' => $geoTargetConstants,
                // Set the network. To restrict to only Google Search, change the parameter below to
                // KeywordPlanNetwork::GOOGLE_SEARCH.
                'keywordPlanNetwork' => KeywordPlanNetwork::GOOGLE_SEARCH
            ] + $requestOptionalArgs
        );
```

Can you please confirm

**Comment by PierrickVoulet** [comment]
Hi @aayushb051,

Could you provide the error logs?

In the meantime, I noticed that you wrote `'yearMonthRange' => ` but it should be `'year_month_range' => `. You can find the documentation of this field [here](https://developers.google.com/google-ads/api/reference/rpc/v8/HistoricalMetricsOptions).

**Comment by aayushb051** [comment]
I tried with year_month_range and i am getting same error 
year_month_range
Fatal error: Uncaught Exception: Expect Google\Ads\GoogleAds\V8\Common\HistoricalMetricsOptions

**Comment by aayushb051** [comment]
[Wed Sep 08 20:11:16.873531 2021] [php7:error] [pid 11576:tid 1812] [client ::1:64244] PHP Fatal error:  Uncaught Exception: Expect Google\\Ads\\GoogleAds\\V8\\Common\\HistoricalMetricsOptions. in C:\\xampp\\htdocs\\google-ads-php\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\GPBUtil.php:197\nStack trace:\n#0 C:\\xampp\\htdocs\\google-ads-php\\src\\Google\\Ads\\GoogleAds\\V8\\Services\\GenerateKeywordIdeasRequest.php(454): Google\\Protobuf\\Internal\\GPBUtil::checkMessage(Array, 'Google\\\\Ads\\\\Goog...')\n#1 C:\\xampp\\htdocs\\google-ads-php\\src\\Google\\Ads\\GoogleAds\\V8\\Services\\Gapic\\KeywordPlanIdeaServiceGapicClient.php(314): Google\\Ads\\GoogleAds\\V8\\Services\\GenerateKeywordIdeasRequest->setHistoricalMetricsOptions(Array)\n#2 C:\\xampp\\htdocs\\google-ads-php\\examples\\Planning\\keyword.php(194): Google\\Ads\\GoogleAds\\V8\\Services\\Gapic\\KeywordPlanIdeaServiceGapicClient->generateKeywordIdeas(Array)\n#3 C:\\xampp\\htdocs\\google-ads-php\\examples\\Planning\\keyword.php(89): Google\\Ads\\GoogleAds\\Examples\\Planning\\GenerateKeywordIdeas::runExample(Object(Google\\Ads\\GoogleAds\\Lib\\V8\\GoogleAdsClient), 58945666, Array, 1000, Array, NULL)\n#4 C:\\xampp\\htdo in C:\\xampp\\htdocs\\google-ads-php\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\GPBUtil.php on line 197

58945666  is different

**Comment by PierrickVoulet** [comment]
Thanks for the extra details. The error is that you need to set the field `historicalMetricsOptions` with an instance of `HistoricalMetricsOptions` instead of an array.

In other words, `'historicalMetricsOptions' => array (...)` should be `'historicalMetricsOptions' => new HistoricalMetricsOptions([...])`. Please note that you will have to do similar editions with other fields.

**Comment by aayushb051** [comment]
Thanks for suggestions. 
i have added this one 

```
'historicalMetricsOptions' => new HistoricalMetricsOptions([
					'year_month_range' => new YearMonthRange([
						'start' => new YearMonth([
							"year" => 2021,
							"month" => Month::value("July")
						]),
						'end' => new YearMonth([
							"year" => 2021,
							"month" => Month::value("July")
						])
					])
			]),
```

and i am still getting results for one year..

**Comment by PierrickVoulet** [comment]
Could you share the latest error logs?

**Comment by aayushb051** [comment]
I am not getting any error. i am seeing the results, but results is showing for one year instead of one month

**Comment by PierrickVoulet** [comment]
> I am not getting any error. i am seeing the results, but results is showing for one year instead of one month

Thank you for confirming @aayushb051. It does not seem to be an issue with the library but the Google Ads API, please reach out to the dedicated [support](https://developers.google.com/google-ads/api/support) for further investigation.
