### ISSUE TITLE
Bug for create a campaign shopping

### ISSUE THREAD

**Issue by hujian8241** [googleads/google-ads-php#654]
Client library version: 11
Google Ads API version: 8
My environment: php / laravel
PHP version: 7.4
System: Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_6415:48
grpc:1.25.015:50

Description bug:
I want to create a new campaign **shopping standard** with your example:
https://developers.google.com/google-ads/api/docs/shopping-ads/create-campaign

It doesn't work, and it return an error:

Google\Ads\GoogleAds\Lib\V8\GoogleAdsException 

  {
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": "google.ads.googleads.v8.errors.googleadsfailure-bin",
            "data": "Unknown Binary Data"
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "Unknown Binary Data"
        },
        {
            "@type": "request-id",
            "data": "Zqm7_UbKemvE7TxzKWDMnA"
        }
    ]
}

  at vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V8/GoogleAdsExceptionTrait.php:75
     71▕             'previous' => $exception->getPrevious(),
     72▕             'metadata' => $exception->getMetadata(),
     73▕             'basicMessage' => $exception->getBasicMessage()
     74▕         ];
  ➜  75▕         return new GoogleAdsException($exception, $googleAdsFailure, $optionalArgs);
     76▕     }
     77▕ }
     78▕ 

_**but if I want to create a campaign with AdvertisingChannelType::SERACH, it works very will, could you look this problem ?**_

Thanks very much

**Comment by PierrickVoulet** [comment]
Hi @hujian8241 - This issue seems to be related to the Google Ads API (not this library), could you please reach out to their dedicated [support](https://developers.google.com/google-ads/api/support) instead? They will be able to investigate why this error is returned by the Google Ads API.
