### ISSUE TITLE
"AddCampaignBidModifier" not working / laravel

### ISSUE THREAD

**Issue by hujian8241** [googleads/google-ads-php#655]
Client library version: 11
Google Ads API version: 8
My environment: php / laravel
PHP version: 7.4
System: Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_6415:48
grpc:1.25.015:50

Description bug: "AddCampaignBidModifier" not working on my side

Hello,

I have a question for your example "create a campaign bid modifier", url ->
https://github.com/googleads/google-ads-php/blob/8aa3692d8fc53810e8b73023851947dc1555dbb8/examples/CampaignManagement/AddCampaignBidModifier.php

I try to test this file(with a campaign shopping), but it always return an error:
**Request with ID 'J2Bw0HormaO3wGoSzRsIJQ' has failed.
Google Ads failure details: context_error: The operation is not allowed for the given context.**

Do you have any idea for this problem ? 

Thanks

Best Regard

**Comment by PierrickVoulet** [comment]
Hi @hujian8241 - This issue seems to be related to the Google Ads API (not this library), could you please reach out to their dedicated [support](https://developers.google.com/google-ads/api/support) instead? They will be able to investigate why this error is returned by the Google Ads API.
