### ISSUE TITLE
Update Campaign Target Location

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#657]
Hello everyone, 
I need help to update campaign target locations using API.

Hear is my small code please tell me how to do it in API.

    **$languageIds = [
                    1000
                ];
               // foreach ($languageIds as $languageId) {
               //     $campaignCriterion = new CampaignCriterion([
               //         'campaign' => $campaignResourceName,
               //         'type' => CriterionType::LANGUAGE,
               //         'language' => new LanguageInfo([
               //             'language_constant' => ResourceNames::forLanguageConstant($languageId)
               //         ])
               //     ]);
               //     $campaignCriterionOperation = new CampaignCriterionOperation();
               //    // $campaignCriterionOperation->setCreate($campaignCriterion);
               //
               //     $campaignCriterionOperation->setUpdate($campaignCriterion);
               //     $campaignCriterionOperation->setUpdateMask(FieldMasks::allSetFieldsOf($campaignCriterion));
               //
               //     $campaignCriterionOperations[] = $campaignCriterionOperation;
               // }

               $campaignCriterionServiceClient = $googleAdsClient->getCampaignCriterionServiceClient();
               $response = $campaignCriterionServiceClient->mutateCampaignCriteria(
                   $customerId,
                   $campaignCriterionOperations
               );**

My requirement is update campaign target location.

Please replay as soon possible.

**Comment by fiboknacky** [comment]
The closest example that you can refer to would be [this one](https://github.com/googleads/google-ads-php/blob/main/examples/CampaignManagement/UpdateCampaignCriterionBidModifier.php).

**Comment by divyeshgajja** [comment]
i am trying this code

**$criterionId = '2524';
               $campaignCriterion = new CampaignCriterion([
                   'resource_name' => ResourceNames::forCampaignCriterion(
                       $customerId,
                       $campaignId,
                       $criterionId
                   )
               ]);

               // Creates the campaign criterion operation.
               $campaignCriterionOperation = new CampaignCriterionOperation();
               $campaignCriterionOperation->setUpdate($campaignCriterion);
               $campaignCriterionOperation->setUpdateMask(FieldMasks::allSetFieldsOf($campaignCriterion));

               // Issues a mutate request to update the bid modifier of campaign criterion.
               $campaignCriterionServiceClient = $googleAdsClient->getCampaignCriterionServiceClient();
               $response = $campaignCriterionServiceClient->mutateCampaignCriteria(
                   $customerId,
                   [$campaignCriterionOperation]
               );

               $updatedCampaignCriterion = $response->getResults()[0];
               printf(
                   "Campaign criterion with resource name '%s' was modified.%s",
                   $updatedCampaignCriterion->getResourceName(),
                   PHP_EOL
               );**

but still not working please tell me where i am wrong?

**Comment by divyeshgajja** [comment]
i am trying this code

**$criterionId = '2524';
$campaignCriterion = new CampaignCriterion([
'resource_name' => ResourceNames::forCampaignCriterion(
$customerId,
$campaignId,
$criterionId
)
]);

           // Creates the campaign criterion operation.
           $campaignCriterionOperation = new CampaignCriterionOperation();
           $campaignCriterionOperation->setUpdate($campaignCriterion);
           $campaignCriterionOperation->setUpdateMask(FieldMasks::allSetFieldsOf($campaignCriterion));

           // Issues a mutate request to update the bid modifier of campaign criterion.
           $campaignCriterionServiceClient = $googleAdsClient->getCampaignCriterionServiceClient();
           $response = $campaignCriterionServiceClient->mutateCampaignCriteria(
               $customerId,
               [$campaignCriterionOperation]
           );

           $updatedCampaignCriterion = $response->getResults()[0];
           printf(
               "Campaign criterion with resource name '%s' was modified.%s",
               $updatedCampaignCriterion->getResourceName(),
               PHP_EOL
           );**
but still not working please tell me where i am wrong?

**Comment by fiboknacky** [comment]
> but still not working please tell me where i am wrong?

Could you tell what's not working, e.g., any error messages thrown?

**Comment by divyeshgajja** [comment]
I need a simple and only campaign target location update because i am already updated bid & budget.
this example for update bid in already added target location in campaign.

please give me another example for update campaign target location.

**Comment by fiboknacky** [comment]
To be clear, you want to update the location targeting like described in [this guide](https://developers.google.com/google-ads/api/docs/targeting/location-targeting?hl=en#update_geo_targets), correct?
If so, you would need to remove the old one first and create a new one that you want.
You can follow [this example](https://github.com/googleads/google-ads-php/blob/main/examples/Targeting/AddCampaignTargetingCriteria.php) for creating a new campaign targeting.

The removal of the old targeting is relatively easy. You can mimic [RemoveCampaign](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/RemoveCampaign.php), but change the object to `CampaignCriterion`. Let me know if you have a problem with removing the old target.

**Comment by divyeshgajja** [comment]
right now i am facing this error:

**Call to undefined method Google\Ads\GoogleAds\V8\Resources\CampaignCriterion::setRemove()**

**Comment by divyeshgajja** [comment]
in this example is remove my campaign from google ads but i need this campaign and i need only update location in this campaign if i remove this campaign then how can i update location?

please tell me.

how to update location in existing campaing using API?

**Comment by fiboknacky** [comment]
> Call to undefined method Google\Ads\GoogleAds\V8\Resources\CampaignCriterion::setRemove()

You use the method on a wrong object. `setRemove()` is for the `XXXOperation` like [`CampaignCriterionOperation`](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V7/Services/CampaignCriterionOperation.php#L177), not `CampaignCriterion`.

> in this example is remove my campaign from google ads but i need this campaign and i need only update location in this campaign if i remove this campaign then how can i update location?

As I mentioned above, you need to change all occurrences of `Campaign` in that example to `CampaignCriterion`.
That example is not meant to be used as is. We don't have examples for _all operations_ of _all resource types_, since that would be limitless and will make this repository too large.
Could you try changing the example like I mentioned and paste your code here if you still hit an error?

BTW, it looks like you might need help about the usage of Google Ads API in general.
Please also consider contacting our team on [the Google Ads API forum](https://groups.google.com/g/adwords-api). They'll guide you through all the steps you might need and answer all your questions.
