### ISSUE TITLE
I want to clear the value of 'cpc_bid_ceiling_micros'.

### ISSUE THREAD

**Issue by yasuo1001** [googleads/google-ads-php#658]
Hi.

I want to set null to clear the value of 'cpc_bid_ceiling_micros' in my campaign, but I get an error "PHP Fatal error: Uncaught Exception: Expect integer".

$campaign = new Campaign([
  'resource_name' => ResourceNames::forCampaign('customer_id', 'campaign_id'),
  'target_spend' => new TargetSpend(['cpc_bid_ceiling_micros' => null])
]);

How can I clear the value of 'cpc_bid_ceiling_micros'?

Please help me.

**Comment by PierrickVoulet** [comment]
Hi @yasuo1001,

You can achieve this by keeping the `target_spend` unset in your updated campaign instance and setting the path `target_spend.cpc_bid_ceiling_micros` instead of relying on the `FieldMasks::allSetFieldsOf` method.

Here is how it looks like:

```
$campaign = new Campaign([
    'resource_name' => ResourceNames::forCampaign($customerId, $campaignId),
]);

$campaignOperation = new CampaignOperation();
$campaignOperation->setUpdate($campaign);
$campaignOperation->setUpdateMask(new FieldMask(['paths' => ['target_spend.cpc_bid_ceiling_micros']]));
```

Thanks,

**Comment by yasuo1001** [comment]
Thank you for your quick reply. It was very helpful.
