### ISSUE TITLE
Same method names in Common\Metrics cause PHP Fatal error

### ISSUE THREAD

**Issue by MaksTech** [googleads/google-ads-php#66]
Lines [3980](https://github.com/googleads/google-ads-php/blob/863a555465ad7f2d4cf29e4dbda628560575bc86/src/Google/Ads/GoogleAds/V1/Common/Metrics.php#L3980) and [3781](https://github.com/googleads/google-ads-php/blob/863a555465ad7f2d4cf29e4dbda628560575bc86/src/Google/Ads/GoogleAds/V1/Common/Metrics.php#L3781) (and not only those) have the same method names since v1.2 release with getNameValue methods introduction. 
And this causes PHP Fatal error "Cannot redeclare..."

**Comment by Raibaz** [comment]
Hi, sorry for the inconvenience. 

The duplicate methods have been manually removed and the v1.2.0 release has been updated.

**Comment by chiragvels** [comment]
Hi,

I think same issue with Common\BidModifierSimulationPoint::getBiddableConversionsValue()

Thanks,

**Comment by Raibaz** [comment]
Right, thanks for spotting.

These have been fixed as well and the release has been updated.

Sorry for the inconvenience.
