### ISSUE TITLE
Why are some Money fields in micros, others float and not really documented in comments?

### ISSUE THREAD

**Issue by madsem** [googleads/google-ads-php#660]
I'm having a hard time figuring out what data type will be returned for reports.

For example the documentation clearly states that all Money related fields, are in micros.
https://developers.google.com/adwords/api/docs/guides/reporting#money_fields_in_reports

So I wrote my code in a way that converts spend/revenue fields using a `micros` helper.
Then when testing, I realized that some `Money` related fields are not in micros, but looking at the code comments there's no mention of that.

The method names already give a hint that we're not dealing with micros, but why does the documentation then state everything is in micros?

For example:
```sql
SELECT
                campaign.id,
                campaign.name,
                campaign.status,
                metrics.cost_micros,
                metrics.all_conversions_value,
...
...
```

```php
// not in micros, but float/double
'revenue_in_original_currency' => $metrics->getAllConversionsValue(),

// micros
'spend_in_original_currency' => $metrics->getCostMicros(),

// again, in micros
'average_cpc_in_original_currency' => $metrics->getAverageCpc(),
```

Maybe I misunderstood something basic, but to me this all is highly confusing...

Can you guys elaborate and shed some light for me?

PS:
And looking at the method signature for average cpc for example, it even says it is float
```php
/**
     * The total cost of all clicks divided by the total number of clicks
     * received.
     *
     * Generated from protobuf field <code>double average_cpc = 204;</code>
     * @return float
     */
    public function getAverageCpc()
    {
        return isset($this->average_cpc) ? $this->average_cpc : 0.0;
    }
```

Documentation also says it is float/double: https://developers.google.com/google-ads/api/fields/v7/campaign_budget#metrics.average_cpc

But it is returned in micros... So I'm really, really confused.

**Comment by PierrickVoulet** [comment]
Hi @madsem - Thank you for the feedback. This library is generated based on how the Google Ads API is defined (e.g. types, comments). The best is to raise this concern to the [support dedicated to the Google Ads API itself](https://developers.google.com/google-ads/api/support), they will clarify the behavior and improve the documentation if necessary.
