### ISSUE TITLE
Google Ads API error -- Fatal error: Uncaught Error: Class 'Google\Auth\OAuth2' not found in /var/www/html/google-ads-php/examples/Authentication/AuthenticateInDesktopApplication.php:71

### ISSUE THREAD

**Issue by rinkisub** [googleads/google-ads-php#661]
OS : linux
Technology : PHP

I have follow all steps, but still facing error.

![image](https://user-images.githubusercontent.com/90371446/136006555-a550e145-caf1-4c72-bc55-e134c87aabba.png)

Please help...

**Comment by fiboknacky** [comment]
Could you list all the steps you follow? It looks like the composer cannot find the necessary classes.

**Comment by rinkisub** [comment]
1. install PECL 
2. sudo pecl install grpc
3. add line in php.ini  extension=grpc.so
4. php -i | grep grpc
5. sudo pecl install protobuf
6. extension=protobuf.so add line into php.ini
7. php -i | grep protobuf
8. git clone https://github.com/googleads/google-ads-php.git
9. cd google-ads-php
10. composer install
11. google_ads_php.ini this move on my home dir and change all requied details
12.  AuthenticateInDesktopApplication.php file add token, customer ID , client Id and secret key
13. run on localhost server http://localhost/google-ads-php/examples/Authentication/AuthenticateInDesktopApplication.php

**Comment by rinkisub** [comment]
when run Get Campaigns. 


http://localhost/google-ads-php/examples/BasicOperations/GetCampaigns.php

![image](https://user-images.githubusercontent.com/90371446/136008392-80e986c9-563b-4992-aab4-e955a931b6be.png)

**Comment by fiboknacky** [comment]
As stated in Step 5 of [the guide](https://github.com/googleads/google-ads-php#getting-started), the code examples including `AuthenticateInDesktopApplication.php` and `GetCampaigns.php` should be run from _command prompt, not via the web browsers_.

**Comment by rinkisub** [comment]
when use **php examples/BasicOperations/GetCampaigns.php --customerId XXX-XXX-XXXX** command 

![image](https://user-images.githubusercontent.com/90371446/136010222-df11dfc9-231c-413d-b3b3-2b978aced9d5.png)

still its coming :(

**Comment by fiboknacky** [comment]
Could you share your directory structure as well?
(And `--customerId XXX-XXX-XXXX` shouldn't have a dash)

**Comment by rinkisub** [comment]
Hi @fiboknacky,

I have run **php examples/BasicOperations/GetCampaigns.php --customerId XXXXXXXXXX**

![image](https://user-images.githubusercontent.com/90371446/136013251-87e7e0d7-7ee9-49cb-a756-23034b172914.png)

![image](https://user-images.githubusercontent.com/90371446/136013465-2ab2864a-a9a0-421d-b345-1ea7c244728b.png)
