### ISSUE TITLE
INVALID_ARGUMENT error

### ISSUE THREAD

**Issue by manishkvaish** [googleads/google-ads-php#663]
I need to call GenerateKeywordIdeas() call of Google Ads API
Am using this library https://github.com/googleads/google-ads-php, which is
working by calling on command prompt (not working on browser)

Passing it as:

php GenerateKeywordIdeas.php --customerId 9435690315 --locationIds
20009,20009 --languageId 1003 --keywordTexts "amazon,amazon" --pageUrl null

OR

php GenerateKeywordIdeas.php --customerId 9435690315 --geoTargetConstants
geoTargetConstants/20009 --languageId 1003 --keywordPlanNetwork
GOOGLE_SEARCH_AND_PARTNERS --keywordTexts "amazon" --pageUrl null

But getting this error:

ApiException was thrown with message '{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            ***@***.***": 0,
            "data": "type.googleapis.com
\/google.ads.googleads.v8.errors.GoogleAdsFailure"
        },
        {
            ***@***.***": 0,
            "data": [
                {
                    "errorCode": {
                        "keywordPlanIdeaError": "INVALID_VALUE"
                    },
                    "message": "The input has an invalid value.",
                    "location": {
                        "fieldPathElements": [
                            {
                                "fieldName": "keyword_seed"
                            },
                            {
 "fieldName": "keywords",
                                "index": 1
                            }
                        ]
                    }
                },
                {
                    "errorCode": {
                        "keywordPlanIdeaError": "INVALID_VALUE"
                    },
                    "message": "The input has an invalid value.",
                    "location": {
                        "fieldPathElements": [
                            {
                                "fieldName": "geo_target_constants",
                                "index": 1
                            }
                        ]
                    }
                }
            ]
        },
        {
            ***@***.***": 0,
            "data": "24hvgMA1XYdAdljb3ZPcUw"
        }
    ]
}'.

Please guide me through the right way to call this function.

Thank You

**Comment by manishkvaish** [comment]
I have set the file.log server path into google_ads_php,ini , and removed the initial semicolon to apply it, but file.log is not filling with any values.like this:

logFilePath = "https://backoffice.imp-multimedia.com/reports/Google/Ads/GoogleAds/ads-code/file.log"
 logLevel = "DEBUG"

**Comment by manishkvaish** [comment]
Tried --locationIds 20009 --locationIds YOU_OTHER_ID, but same error

also I tried with  logFilePath = "/var/www/server/backoffice/reports/Google/Ads/GoogleAds/ads-code/file.log", but still nothing being loaded into file.log

**Comment by fiboknacky** [comment]
> _root@imp128 /var/www/server/backoffice/reports/Google/Ads/GoogleAds/ads-code/examples/Planning # php GenerateKeywordIdeas.php --customerId 9435690315 --locationIds [ 20009,20009] --languageId 1003 --keywordTexts  ["amazon,amazon"] --pageUrl null_

It looks like the format you pass here is not the same one I recommended yet.
Could you please fix? And why do you need to specify two same texts and location IDs?

Apart from that, if you specify them in the command line, you don't need to specify them in the code.
Just keep `GenerateKeywordIdeas` untouched.
Please try and let me know the result. Thanks.

**Comment by fiboknacky** [comment]
Close due to inactivity.
