### ISSUE TITLE
IpBlockInfo - Object of class Google\\Protobuf\\StringValue could not be converted to string

### ISSUE THREAD

**Issue by avptechnocrats** [googleads/google-ads-php#675]
I am working to implement the functionality to block the IP address using GAds V8 API however it is throwing error as:
## message: "Object of class Google\\Protobuf\\StringValue could not be converted to string"

/adwords/google-ads-php/src/Google/Ads/GoogleAds/V8/Common/IpBlockInfo.php(41): Google\\Protobuf\\Internal\\Message->__construct(Array)"

Here is the piece of code that I am using:
```php
$campaignResourceName = ResourceNames::forCampaign($adwords_user_id, $adwords_campaign_id);
$campaignCriterion = new CampaignCriterion([
// Sets the campaign criterion as a negative criterion.
//'negative' => new BoolValue(['value' => true]),
'campaign' => new StringValue(['value' => $campaignResourceName]),
'type' => CriterionType::IP_BLOCK,
'ip_block' => new IpBlockInfo(['ip_address' => new StringValue(['value' => $ipAddress2])])
//'ip_block' => new IpBlockInfo(['ip_address' => (string)$ipAddress])
]);

$operation = new CampaignCriterionOperation(['create' => $campaignCriterion]); 
$operations[] = $operation; 
// Issues a mutate request to add the campaign criterion.
$campaignCriterionServiceClient = $googleAdsClient->getCampaignCriterionServiceClient();
$response = $campaignCriterionServiceClient->mutateCampaignCriteria($adwords_user_id, $operations);
```

I tried by setting negative criterion to true but the same error always comes up.

## Can you please look into this issue and suggest me if I am doing something wrong here?  I am stuck at this point and your help is highly appreciated. 

Thanks!

**Comment by PierrickVoulet** [comment]
Hi @avptechnocrats,

`'campaign' => new StringValue(['value' => $campaignResourceName])` is based on an old spec that we migrated from since v5. You should now use PHP native types, in this case the code becomes `'campaign' => $campaignResourceName`.

Please refer to this [example](https://github.com/googleads/google-ads-php/blob/main/examples/Targeting/AddCampaignTargetingCriteria.php) for details.

Feel free to let us know if you have any further questions about this.

Thanks,

**Comment by avptechnocrats** [comment]
Hi @PierrickVoulet ,
Thanks for your prompt response.

As per you suggestion, I changed the line 'campaign' => $campaignResourceName, however the error still shows. 
It seems the error is related to 'ip_block' index and I changed it to pass the simple variable without converting it to String, but it does not work either. It throws the same error.

Thanks!

**Comment by PierrickVoulet** [comment]
> Hi @PierrickVoulet , Thanks for your prompt response.
> 
> As per you suggestion, I changed the line 'campaign' => $campaignResourceName, however the error still shows. It seems the error is related to 'ip_block' index and I changed it to pass the simple variable without converting it to String, but it does not work either. It throws the same error.
> 
> Thanks!

Did you also change the line `'ip_block' => new IpBlockInfo(['ip_address' => new StringValue(['value' => $ipAddress2])])` to `'ip_block' => new IpBlockInfo(['ip_address' => $ipAddress2])`?

**Comment by avptechnocrats** [comment]
Yes, I tried changing that too without any luck.

**Comment by PierrickVoulet** [comment]
The following code runs just fine on my end, could you give it a try and provide logs if any failures?

```php
$campaignCriterion = new CampaignCriterion([
    'negative' => true,
    'campaign' => ResourceNames::forCampaign(123, 456),
    'type' => CriterionType::IP_BLOCK,
    'ip_block' => new IpBlockInfo(['ip_address' => ''])
]);
```

Also, could you confirm the information about your environment?

> You can paste the output generated by our complementary script: https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php.
>
> Alternatively, please provide with the following pieces of information:
 
> * The PHP version: Run `php -v`.
> * The name and version of the operating system: Run `php -r 'print php_uname();'`.
> * Whether the PHP Extension `protobuf` is used or not: Run `php -r 'print phpversion("protobuf");'`.
> * Whether the PHP Extension `grpc` is used or not: Run `php -r 'print phpversion("grpc");'`.
> * The type of transport being used (`grpc` or `rest`): See https://developers.google.com/google-ads/api/docs/client-libs/php/transport.

**Comment by avptechnocrats** [comment]
HI @PierrickVoulet 
The provided code format does not work and gives a different error of 'Invalid Argument'. Here is the error:
![image](https://user-images.githubusercontent.com/5183515/141056723-4cbbd413-98b5-4cab-97f2-5e8d6de967ac.png)


Below are the info you asked for:

Command >> php -v 
Output >> PHP 7.3.32 (cli) (built: Oct 28 2021 15:24:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.32, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.32, Copyright (c) 1999-2018, by Zend Technologies


Command >> php -r 'print php_uname();'
Output >> Linux host.theclicksaver.com 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64

Command >> php -r 'print phpversion("protobuf");'
Output >> 3.19.1

Command >> php -r 'print phpversion("grpc");'
No any output.

Thanks!

**Comment by PierrickVoulet** [comment]
Thank you for the extra information, this is helpful. The `INVALID_ARGUMENT` error is coming back from the server, the library woks as intended. Please contact the [Google Ads API Support team](https://developers.google.com/google-ads/api/support), they will be able to investigate why you are getting this error.

**Comment by avptechnocrats** [comment]
Hi @PierrickVoulet 
I contacted GAds team but they are asking me for the logs of GAds API. However, the logs are not generated in GAds log file, which means that the plugin is not calling the GAds API and throwing error before calling the API.
Could you please take a look again to look into my issue?

**Comment by PierrickVoulet** [comment]
@avptechnocrats The screenshot you provided in https://github.com/googleads/google-ads-php/issues/675#issuecomment-964807228 contains some Google Ads API logs and the actual error message coming from the server. Could this be an issue with your configuration (see [documentation](https://developers.google.com/google-ads/api/docs/client-libs/php/logging))?

**Comment by PierrickVoulet** [comment]
> @PierrickVoulet The configuration for logs is correct at our end however the logs are not created in the log file. The error does not seem to return from the GAds API. It is throwing error from library file of the plugin I think. Can you please make sure this is not issue at plugin end?

I think you are using the REST [transport](https://developers.google.com/google-ads/api/docs/client-libs/php/transport) which comes with some limitations, could you try switching to gRPC by any chance?

You will need to install the PHP Extension (run `sudo pecl install grpc`), enable it (add `extension=grpc.so` in your `php.ini` file) and make sure the Google Ads API client configuration setting `transport` is set to `grpc` as described [here](https://developers.google.com/google-ads/api/docs/client-libs/php/transport).
