### ISSUE TITLE
Unknown pipeline failed

### ISSUE THREAD

**Issue by ujwaldhakal** [googleads/google-ads-php#679]
https://github.com/googleads/google-ads-php/commit/82a8ce7cc6bcc49db6f0f434199abf7ea7d1778d after merging this PR there is pipeline failure. @PierrickVoulet i cannot see the build logs can you help me if i  miss anything ?

![image](https://user-images.githubusercontent.com/11195862/140966718-ed00d158-2ecf-4bd5-882e-d5aadda6b0d4.png)

**Comment by PierrickVoulet** [comment]
@ujwaldhakal No worries, this is failing due to unrelated issues. I was able to run all tests successfully on my end.
