### ISSUE TITLE
Planning GenerateKeywordIdeas

### ISSUE THREAD

**Issue by ViktorShchepkin** [googleads/google-ads-php#683]
Hello!

Client library version: v12.0.0

Google Ads API version:  v8

PHP Version => 7.3.31-2+ubuntu20.04.1+deb.sury.org+1

System => Linux dadicc 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64
Build Date => Oct 22 2021 12:34:45
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php/7.3/cli
Loaded Configuration File => /etc/php/7.3/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.3/cli/conf.d
Additional .ini files parsed => /etc/php/7.3/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.3/cli/conf.d/10-opcache.ini,
/etc/php/7.3/cli/conf.d/10-pdo.ini,
/etc/php/7.3/cli/conf.d/15-psr.ini,
/etc/php/7.3/cli/conf.d/15-xml.ini,
/etc/php/7.3/cli/conf.d/20-amqp.ini,
/etc/php/7.3/cli/conf.d/20-apcu.ini,
/etc/php/7.3/cli/conf.d/20-ast.ini,
/etc/php/7.3/cli/conf.d/20-bcmath.ini,
/etc/php/7.3/cli/conf.d/20-bz2.ini,
/etc/php/7.3/cli/conf.d/20-calendar.ini,
/etc/php/7.3/cli/conf.d/20-ctype.ini,
/etc/php/7.3/cli/conf.d/20-curl.ini,
/etc/php/7.3/cli/conf.d/20-dba.ini,
/etc/php/7.3/cli/conf.d/20-dom.ini,
/etc/php/7.3/cli/conf.d/20-enchant.ini,
/etc/php/7.3/cli/conf.d/20-exif.ini,
/etc/php/7.3/cli/conf.d/20-fileinfo.ini,
/etc/php/7.3/cli/conf.d/20-ftp.ini,
/etc/php/7.3/cli/conf.d/20-gd.ini,
/etc/php/7.3/cli/conf.d/20-gearman.ini,
/etc/php/7.3/cli/conf.d/20-geoip.ini,
/etc/php/7.3/cli/conf.d/20-gettext.ini,
/etc/php/7.3/cli/conf.d/20-gmp.ini,
/etc/php/7.3/cli/conf.d/20-gnupg.ini,
/etc/php/7.3/cli/conf.d/20-iconv.ini,
/etc/php/7.3/cli/conf.d/20-igbinary.ini,
/etc/php/7.3/cli/conf.d/20-imagick.ini,
/etc/php/7.3/cli/conf.d/20-imap.ini,
/etc/php/7.3/cli/conf.d/20-interbase.ini,
/etc/php/7.3/cli/conf.d/20-intl.ini,
/etc/php/7.3/cli/conf.d/20-json.ini,
/etc/php/7.3/cli/conf.d/20-ldap.ini,
/etc/php/7.3/cli/conf.d/20-lua.ini,
/etc/php/7.3/cli/conf.d/20-lz4.ini,
/etc/php/7.3/cli/conf.d/20-mbstring.ini,
/etc/php/7.3/cli/conf.d/20-mcrypt.ini,
/etc/php/7.3/cli/conf.d/20-memcache.ini,
/etc/php/7.3/cli/conf.d/20-mongodb.ini,
/etc/php/7.3/cli/conf.d/20-msgpack.ini,
/etc/php/7.3/cli/conf.d/20-mysqli.ini,
/etc/php/7.3/cli/conf.d/20-oauth.ini,
/etc/php/7.3/cli/conf.d/20-odbc.ini,
/etc/php/7.3/cli/conf.d/20-pcov.ini,
/etc/php/7.3/cli/conf.d/20-pdo_dblib.ini,
/etc/php/7.3/cli/conf.d/20-pdo_firebird.ini,
/etc/php/7.3/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.3/cli/conf.d/20-pdo_odbc.ini,
/etc/php/7.3/cli/conf.d/20-pdo_pgsql.ini,
/etc/php/7.3/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/7.3/cli/conf.d/20-pgsql.ini,
/etc/php/7.3/cli/conf.d/20-phalcon.ini,
/etc/php/7.3/cli/conf.d/20-phar.ini,
/etc/php/7.3/cli/conf.d/20-pinba.ini,
/etc/php/7.3/cli/conf.d/20-posix.ini,
/etc/php/7.3/cli/conf.d/20-propro.ini,
/etc/php/7.3/cli/conf.d/20-ps.ini,
/etc/php/7.3/cli/conf.d/20-pspell.ini,
/etc/php/7.3/cli/conf.d/20-radius.ini,
/etc/php/7.3/cli/conf.d/20-raphf.ini,
/etc/php/7.3/cli/conf.d/20-readline.ini,
/etc/php/7.3/cli/conf.d/20-recode.ini,
/etc/php/7.3/cli/conf.d/20-redis.ini,
/etc/php/7.3/cli/conf.d/20-rrd.ini,
/etc/php/7.3/cli/conf.d/20-shmop.ini,
/etc/php/7.3/cli/conf.d/20-simplexml.ini,
/etc/php/7.3/cli/conf.d/20-smbclient.ini,
/etc/php/7.3/cli/conf.d/20-soap.ini,
/etc/php/7.3/cli/conf.d/20-sockets.ini,
/etc/php/7.3/cli/conf.d/20-solr.ini,
/etc/php/7.3/cli/conf.d/20-sqlite3.ini,
/etc/php/7.3/cli/conf.d/20-ssh2.ini,
/etc/php/7.3/cli/conf.d/20-stomp.ini,
/etc/php/7.3/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.3/cli/conf.d/20-sysvsem.ini,
/etc/php/7.3/cli/conf.d/20-sysvshm.ini,
/etc/php/7.3/cli/conf.d/20-tideways.ini,
/etc/php/7.3/cli/conf.d/20-tidy.ini,
/etc/php/7.3/cli/conf.d/20-tokenizer.ini,
/etc/php/7.3/cli/conf.d/20-uopz.ini,
/etc/php/7.3/cli/conf.d/20-uploadprogress.ini,
/etc/php/7.3/cli/conf.d/20-uuid.ini,
/etc/php/7.3/cli/conf.d/20-wddx.ini,
/etc/php/7.3/cli/conf.d/20-xdebug.ini,
/etc/php/7.3/cli/conf.d/20-xhprof.ini,
/etc/php/7.3/cli/conf.d/20-xmlreader.ini,
/etc/php/7.3/cli/conf.d/20-xmlrpc.ini,
/etc/php/7.3/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.3/cli/conf.d/20-xsl.ini,
/etc/php/7.3/cli/conf.d/20-yaml.ini,
/etc/php/7.3/cli/conf.d/20-zip.ini,
/etc/php/7.3/cli/conf.d/20-zmq.ini,
/etc/php/7.3/cli/conf.d/25-apcu_bc.ini,
/etc/php/7.3/cli/conf.d/25-http.ini,
/etc/php/7.3/cli/conf.d/25-mailparse.ini,
/etc/php/7.3/cli/conf.d/25-memcached.ini,
/etc/php/7.3/cli/conf.d/25-swoole.ini,
/etc/php/7.3/cli/conf.d/30-decimal.ini,
/etc/php/7.3/cli/conf.d/30-ds.ini,
/etc/php/7.3/cli/conf.d/30-grpc.ini,
/etc/php/7.3/cli/conf.d/30-inotify.ini,
/etc/php/7.3/cli/conf.d/30-maxminddb.ini,
/etc/php/7.3/cli/conf.d/30-protobuf.ini,
/etc/php/7.3/cli/conf.d/30-vips.ini,
/etc/php/7.3/cli/conf.d/30-zstd.ini

PHP API => 20180731
PHP Extension => 20180731
Zend Extension => 320180731
Zend Extension Build => API320180731,NTS
PHP Extension Build => API20180731,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => available, disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, compress.bzip2, smb, ssh2.shell, ssh2.exec, ssh2.tunnel, ssh2.scp, ssh2.sftp, zip, phar, compress.zstd
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*, mcrypt.*, mdecrypt.*, http.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.3.31, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.31-2+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans

The PHP Extension grpc is installed: 1.41.0
The PHP Extension protobuf is installed: 3.18.0

===========================================================

PROBLEM

I have some problem with method google-ads-php/examples/Planning/GenerateKeywordIdeas.php. 
The method works only if you pass parameters when called in the console. 
I am basing my code on the example code and cannot call the method in the console. Perhaps there is a bug.

CODE
https://i.imgur.com/b7Krto9.png

I call method with params and all work good https://i.imgur.com/gKlVBIk.png
I call without params and have error https://i.imgur.com/0FFnIaN.png

Thanks!

**Comment by PierrickVoulet** [comment]
Hi @ViktorShchepkin - The examples we provide are only designed to be executed from a console. If you want to replicate some logic used in the code examples, you will need to copy the code and adapt it for your own application. For example, you could replace the part that grabs parameter(s) from command line using `GetOpt` to something else.

**Comment by PierrickVoulet** [comment]
It fails calling `ArgumentParser->parseCommandArguments(Array)` even though it should never be called based on your editions, could you make sure that you are actually running the edited version of your code?

**Comment by ViktorShchepkin** [comment]
Good day!

I call method with params and all work good https://i.imgur.com/gKlVBIk.png
I call without params and have error https://i.imgur.com/0FFnIaN.png

I checked it again. I give the complete example code below. (google-ads-php/examples/Planning/GenerateKeywordIdeas.php):

<?php

namespace Google\Ads\GoogleAds\Examples\Planning;

require __DIR__ . '/../../vendor/autoload.php';

use GetOpt\GetOpt;
use Google\Ads\GoogleAds\Examples\Utils\ArgumentNames;
use Google\Ads\GoogleAds\Examples\Utils\ArgumentParser;
use Google\Ads\GoogleAds\Lib\OAuth2TokenBuilder;
use Google\Ads\GoogleAds\Lib\V8\GoogleAdsClient;
use Google\Ads\GoogleAds\Lib\V8\GoogleAdsClientBuilder;
use Google\Ads\GoogleAds\Lib\V8\GoogleAdsException;
use Google\Ads\GoogleAds\Util\V8\ResourceNames;
use Google\Ads\GoogleAds\V8\Enums\KeywordPlanNetworkEnum\KeywordPlanNetwork;
use Google\Ads\GoogleAds\V8\Errors\GoogleAdsError;
use Google\Ads\GoogleAds\V8\Services\GenerateKeywordIdeaResult;
use Google\Ads\GoogleAds\V8\Services\KeywordAndUrlSeed;
use Google\Ads\GoogleAds\V8\Services\KeywordSeed;
use Google\Ads\GoogleAds\V8\Services\UrlSeed;
use Google\ApiCore\ApiException;

/** This example generates keyword ideas from a list of seed keywords or a seed page URL. */
class GenerateKeywordIdeas
{
    private const CUSTOMER_ID = '2735337931';
    // Location criteria IDs. For example, specify 21167 for New York. For more information
    // on determining this value, see
    // https://developers.google.com/adwords/api/docs/appendix/geotargeting.
    private const LOCATION_ID_1 = '20949';
    private const LOCATION_ID_2 = 'INSERT_LOCATION_ID_2_HERE';

    // A language criterion ID. For example, specify 1000 for English. For more information
    // on determining this value, see
    // https://developers.google.com/adwords/api/docs/appendix/codes-formats#languages.
    private const LANGUAGE_ID = '1031';

    private const KEYWORD_TEXT_1 = 'абдоминопластика';
    private const KEYWORD_TEXT_2 = 'абдоминопластика живота';

    // Optional: Specify a URL string related to your business to generate ideas.
    private const PAGE_URL = null;

    public static function main()
    {
       
        // Generate a refreshable OAuth2 credential for authentication.
        $oAuth2Credential = (new OAuth2TokenBuilder())->
        //fromFile()->
        withClientId('123')->
        withClientSecret('123')->
        withRefreshToken('123')->
        withImpersonatedEmail('123')->
        build();

        // Construct a Google Ads client configured from a properties file and the
        // OAuth2 credentials above.
        $googleAdsClient = (new GoogleAdsClientBuilder())->
        //fromFile()->
        withLoginCustomerId('9279005797')->
        withDeveloperToken('123')->
        withTransport("grpc")->
        withOAuth2Credential($oAuth2Credential)->
        build();

        try {
           
            self::runExample(
                $googleAdsClient,
                self::CUSTOMER_ID,
                [self::LOCATION_ID_1],
                self::LANGUAGE_ID,
                [self::KEYWORD_TEXT_1, self::KEYWORD_TEXT_2],
                self::PAGE_URL
            );
        } catch (GoogleAdsException $googleAdsException) {
            printf(
                "Request with ID '%s' has failed.%sGoogle Ads failure details:%s",
                $googleAdsException->getRequestId(),
                PHP_EOL,
                PHP_EOL
            );
            foreach ($googleAdsException->getGoogleAdsFailure()->getErrors() as $error) {
                /** @var GoogleAdsError $error */
                printf(
                    "\t%s: %s%s",
                    $error->getErrorCode()->getErrorCode(),
                    $error->getMessage(),
                    PHP_EOL
                );
            }
            exit(1);
        } catch (ApiException $apiException) {
            printf(
                "ApiException was thrown with message '%s'.%s",
                $apiException->getMessage(),
                PHP_EOL
            );
            exit(1);
        }
    }

    /**
     * Runs the example.
     *
     * @param GoogleAdsClient $googleAdsClient the Google Ads API client
     * @param int $customerId the customer ID
     * @param int[] $locationIds the location IDs
     * @param int $languageId the language ID
     * @param string[] $keywords the list of keywords to use as a seed for ideas
     * @param string|null $pageUrl optional URL related to your business to use as a seed for ideas
     */
    // [START generate_keyword_ideas]
    public static function runExample(
        GoogleAdsClient $googleAdsClient,
        int $customerId,
        array $locationIds,
        int $languageId,
        array $keywords,
        ?string $pageUrl
    ) {
        $keywordPlanIdeaServiceClient = $googleAdsClient->getKeywordPlanIdeaServiceClient();

        // Make sure that keywords and/or page URL were specified. The request must have exactly one
        // of urlSeed, keywordSeed, or keywordAndUrlSeed set.
        if (empty($keywords) && is_null($pageUrl)) {
            throw new \InvalidArgumentException(
                'At least one of keywords or page URL is required, but neither was specified.'
            );
        }

        // Specify the optional arguments of the request as a keywordSeed, urlSeed,
        // or keywordAndUrlSeed.
        $requestOptionalArgs = [];
        if (empty($keywords)) {
            // Only page URL was specified, so use a UrlSeed.
            $requestOptionalArgs['urlSeed'] = new UrlSeed(['url' => $pageUrl]);
        } elseif (is_null($pageUrl)) {
            // Only keywords were specified, so use a KeywordSeed.
            $requestOptionalArgs['keywordSeed'] = new KeywordSeed(['keywords' => $keywords]);
        } else {
            // Both page URL and keywords were specified, so use a KeywordAndUrlSeed.
            $requestOptionalArgs['keywordAndUrlSeed'] =
                new KeywordAndUrlSeed(['url' => $pageUrl, 'keywords' => $keywords]);
        }

        // Create a list of geo target constants based on the resource name of specified location
        // IDs.
        $geoTargetConstants =  array_map(function ($locationId) {
            return ResourceNames::forGeoTargetConstant($locationId);
        }, $locationIds);

        // Generate keyword ideas based on the specified parameters.
        $response = $keywordPlanIdeaServiceClient->generateKeywordIdeas(
            [
                // Set the language resource using the provided language ID.
                'language' => ResourceNames::forLanguageConstant($languageId),
                'customerId' => $customerId,
                // Add the resource name of each location ID to the request.
                'geoTargetConstants' => $geoTargetConstants,
                // Set the network. To restrict to only Google Search, change the parameter below to
                // KeywordPlanNetwork::GOOGLE_SEARCH.
                'keywordPlanNetwork' => KeywordPlanNetwork::GOOGLE_SEARCH_AND_PARTNERS
            ] + $requestOptionalArgs
        );

        // Iterate over the results and print its detail.
        foreach ($response->iterateAllElements() as $result) {
            /** @var GenerateKeywordIdeaResult $result */
            // Note that the competition printed below is enum value.
            // For example, a value of 2 will be returned when the competition is 'LOW'.
            // A mapping of enum names to values can be found at KeywordPlanCompetitionLevel.php.
            printf(
                "Keyword idea text '%s' has %d average monthly searches and competition as %d.%s",
                $result->getText(),
                is_null($result->getKeywordIdeaMetrics()) ?
                    0 : $result->getKeywordIdeaMetrics()->getAvgMonthlySearches(),
                is_null($result->getKeywordIdeaMetrics()) ?
                    0 : $result->getKeywordIdeaMetrics()->getCompetition(),
                PHP_EOL
            );
        }
    }
    // [END generate_keyword_ideas]
}

GenerateKeywordIdeas::main();


Thanks!

**Comment by PierrickVoulet** [comment]
Thank you for posting the entire code. I tried it and it ran successfully on my end:

```
/bin/php /usr/local/google/home/pierrick/git/google-ads-php/examples/Planning/GenerateKeywordIdeas.php
Keyword idea text 'мужская абдоминопластика' has 10 average monthly searches and competition as 0.
...
Keyword idea text 'абдоминопластика акция' has 10 average monthly searches and competition as 4.
[2021-11-23T13:24:56.832094+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com:443", Method: "/google.ads.googleads.v8.services.KeywordPlanIdeaService/GenerateKeywordIdeas", CustomerId: REDACTED, RequestId: "REDACTED", IsFault: 0, FaultMessage: "None"  

Process finished with exit code 0
```

I believe this issue is specific to your environment. The editions you made do not seem to be taken into account when you run the file, may be because you use some sort of [cache](https://www.php.net/manual/en/book.opcache.php)? An easy way to confirm is to add an instruction similar to `print "Hello";` before `GenerateKeywordIdeas::main();` and check if it is printed in the console when you run, could you give it a try?

**Comment by ViktorShchepkin** [comment]
Thanks for answer! I try

**Comment by ViktorShchepkin** [comment]
Resolved! I did not understand what is the reason, maybe cache
Thanks very much!
