### ISSUE TITLE
serializeToJsonString method returns invalid JSON when locale with comma decimals separator is set

### ISSUE THREAD

**Issue by finwe** [googleads/google-ads-php#692]
**Your client library and Google Ads API versions:**

* Client library version: `v12.1.0`

* Google Ads API version: `V9`

**Your environment:**

* The PHP version: `7.4.26`
* The name and version of the operating system: Linux Mint 19.3 (`Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64`).
* Whether the PHP Extension `protobuf` is used or not: No
* Whether the PHP Extension `grpc` is used or not: Run `1.41.0`.
* The type of transport being used (`grpc` or `rest`): `grpc`

**Description of the bug:**

serializeToJsonString method returns invalid JSON when locale with comma decimals separator is set.

JSON contains float fields with a comma as a decimal separator, which cannot be decoded by PHP.

Example resulting JSON (formatted for better readability):

```
{
    "metrics": {
        "allConversions": 181,674599,
        "conversions": 113,674599,
        "costPerConversion": 212185273,47521147
    }
}
```

**Steps to reproduce:**

Run `setlocale(LC_ALL, 'cs_CZ')` and call `serializeToJsonString` on an instance of `\Google\Ads\GoogleAds\V9\Services\GoogleAdsRow` class containing a float field.

**Expected behavior:**

Resulting JSON is valid, float fields contain a period as a decimal separator.

```
{
    "metrics": {
        "allConversions": 181.674599,
        "conversions": 113.674599,
        "costPerConversion": 212185273.47521147
    }
}
```

**Request/Response Logs:**

    [2021-12-01 13:08:53] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v9.services.GoogleAdsService/SearchStream", CustomerId: [redacted] RequestId: "R1OEhPwKrMex3Fo3VBeT1A", IsFault: 0, FaultMessage: "None"

**Comment by finwe** [comment]
This is caused by using a sprintf `g` specifier in the protobuf library, which is locale-aware.

https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/GPBJsonWire.php#L194

**Comment by fiboknacky** [comment]
As this is an issue on the protobuf library, could you please file the bug on that repo instead? Thank you.

**Comment by finwe** [comment]
It seems it was already reported. https://github.com/protocolbuffers/protobuf/issues/8179
