### ISSUE TITLE
ListAccessibleCustomers.php giving error for test developer token with Test account , same credentials working fine with production token

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/google-ads-php#693]
I am using google ads app php V8 lib. I am trying to run bellow example after creating refresh token for test adwords account with test developer token.

https://github.com/googleads/google-ads-php/blob/main/examples/AccountManagement/ListAccessibleCustomers.php

Its working fine if I use production developer token but same is not working with test developer token.

please find attached error log file as well which I generated using test developer token.

Could you please confirm is it developer token issue or something from library side.

I tried with python lib as well , same way there also for production developer token I am getting response but for test developer token I am getting error.

[changes.log](https://github.com/googleads/google-ads-php/files/7634013/changes.log)

**Comment by fiboknacky** [comment]
This sounds like non-client-library issues. Could you please contact people in [this forum](https://groups.google.com/g/adwords-api)?
Thanks.

**Comment by Vijaysinh** [comment]
I have already checked with api forum, using Test Developer Token 
https://googleads.googleapis.com/v9/customers:listAccessibleCustomers 
This api call not working for test manager account , same is working with production developer token.

**Comment by fiboknacky** [comment]
Thanks for update. Feel free to provide the update on the forum.
