### ISSUE TITLE
Update Account Budget Using Google Ads API

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/google-ads-php#697]
Hello Everyone,

Please tell me how to update my Account Budget With Google Ads API.

I am trying this example but still this is not working. And not getting any error.
So how to Update.

Hear is my Code:

 **$accountBudgetProposal = new AccountBudgetProposal([
            'billing_setup' => $billname,
            'proposal_type' => AccountBudgetProposalType::UPDATE,
            'proposed_name' => 'Dec budget',
            'proposed_start_date_time' => '2021-12-01',
            'proposed_end_date_time' => '2021-12-10',
            'proposed_spending_limit_micros' => 1000000000
          ]);
        $accountBudgetProposalOperation = new AccountBudgetProposalOperation();
        $accountBudgetProposalOperation->setCreate($accountBudgetProposal);
        $accountBudgetProposalOperation->setUpdateMask(
          FieldMasks::allSetFieldsOf($accountBudgetProposal)
        );**

Please Tell me How to Update this code is not working on my Problem.

I need to update Account Budget using Customer ID.
Give me Some Direct Example For Doing This.

Thanks,
Divyesh.

**Comment by fiboknacky** [comment]
```php
$accountBudgetProposalOperation->setCreate($accountBudgetProposal);
```

If you wish to update, you need to use `setUpdate`, not `setCreate`.

**Comment by divyeshgajja** [comment]
Call to undefined method Google\Ads\GoogleAds\V9\Services\AccountBudgetProposalOperation::setUpdate().

Now I am Facing this Error.

**Comment by divyeshgajja** [comment]
approved spending limit 'INFINITE' (proposed 'INFINITE', adjusted 'INFINITE')

How can i change this Spending Limit using API?

**Comment by fiboknacky** [comment]
Sorry for my last reply. That applies to general cases, but not the account budget proposal, as [its operation](https://developers.google.com/google-ads/api/reference/rpc/v9/AccountBudgetProposalOperation) doesn't support update.
See [this guide](https://developers.google.com/google-ads/api/docs/billing/account-budgets) for details of how to modify the current account budget.

As for your question, please take a look at [this guide](https://developers.google.com/google-ads/api/docs/billing/account-budgets#update).

**Comment by divyeshgajja** [comment]
I am already trying this example but still not working.

$accountBudgetProposal = new AccountBudgetProposal([
  'proposal_type' => AccountBudgetProposalType::UPDATE,
  'account_budget' => $accountBudget->getResourceName(),
  'proposed_spending_limit_micros' =>
    $accountBudget->getProposedSpendingLimitMicros() + $increaseAmount])

$accountBudgetProposalOperation = new AccountBudgetProposalOperation();
$accountBudgetProposalOperation->setCreate($accountBudgetProposal);
$accountBudgetProposalOperation->setUpdateMask(
  FieldMasks::allSetFieldsOf($accountBudgetProposal)
);

// Send request to Google Ads API (not shown).

Please tell me where im wrong?

**Comment by fiboknacky** [comment]
Can you share your request and response logs?

**Comment by divyeshgajja** [comment]
I am runing code in PHP.
hear is my code.

         $accountBudgetProposal = new AccountBudgetProposal([
              'proposal_type' => AccountBudgetProposalType::UPDATE,
              'account_budget' => $accountBudget->getResourceName(),
              'proposed_spending_limit_micros' => 5000000000]);

            $accountBudgetProposalOperation = new AccountBudgetProposalOperation();
            $accountBudgetProposalOperation->setCreate($accountBudgetProposal);
            $accountBudgetProposalOperation->setUpdateMask(
              FieldMasks::allSetFieldsOf($accountBudgetProposal)
            );

**Comment by divyeshgajja** [comment]
Please share me some currect Example.
i trying all this API exmaple but still not working and also i am not getting any error.

**Comment by fiboknacky** [comment]
The guide I shared is the official one. If you cannot run it, we need request and response logs in order to help troubleshooting.
Without [the logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging), it's difficult to further diagnose the issues.

**Comment by divyeshgajja** [comment]
Hear is my PHP CODE:

	$googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
       $query = 'SELECT account_budget.status, ' . 'account_budget.billing_setup, ' . 'account_budget.approved_spending_limit_micros, ' . 'account_budget.approved_spending_limit_type, ' . 'account_budget.proposed_spending_limit_micros, ' . 'account_budget.proposed_spending_limit_type, ' . 'account_budget.adjusted_spending_limit_micros, ' . 'account_budget.adjusted_spending_limit_type, ' . 'account_budget.approved_start_date_time, ' . 'account_budget.proposed_start_date_time, ' . 'account_budget.approved_end_date_time, ' . 'account_budget.approved_end_time_type,' . 'account_budget.proposed_end_date_time, ' . 'account_budget.proposed_end_time_type ' . 'FROM account_budget’; 

 $stream = $googleAdsServiceClient->search($customerId, $query);

foreach ($stream->iterateAllElements() as $googleAdsRow) {

            $accountBudget = $googleAdsRow->getAccountBudget();
            $accountBudgetProposal = new AccountBudgetProposal([
              'proposal_type' => AccountBudgetProposalType::UPDATE,
              'account_budget' => $accountBudget->getResourceName(),
              'proposed_spending_limit_micros' => 5000000000]);
            $accountBudgetProposalOperation = new AccountBudgetProposalOperation();
            $accountBudgetProposalOperation->setCreate($accountBudgetProposal);
            $accountBudgetProposalOperation->setUpdateMask(
              FieldMasks::allSetFieldsOf($accountBudgetProposal)
            );

}


I am using this example to update current Account Budget .

**Comment by fiboknacky** [comment]
Did you check my [logging guide](https://developers.google.com/google-ads/api/docs/client-libs/php/logging) above? Have you turned it on? Could you please share the logs, not the code?

**Comment by divyeshgajja** [comment]
Hear is my Logs:

2021-12-08 11:41:01 Error: [TypeError] Argument 1 passed to Google\Ads\GoogleAds\Lib\V9\GoogleAdsClientBuilder::withLogger() must be an instance of Psr\Log\LoggerInterface, string given, called in /Applications/MAMP/htdocs/gameadzonewebv3/src/Controller/GoogleapiController.php on line 714 (/Applications/MAMP/htdocs/gameadzonewebv3/plugins/googleadsv9/src/Google/Ads/GoogleAds/Lib/V9/GoogleAdsClientBuilder.php:213)


Please check.

**Comment by fiboknacky** [comment]
The log shows there is an error, which is not related directly to the API itself. 
As I have no visibility into your whole program , could you try debugging `GoogleapiController.php`?
It looks like you don't use the Logger correctly.

**Comment by divyeshgajja** [comment]
Okay.

   ->withLogger('/Applications/MAMP/htdocs/gameadzonewebv3/logs/‘)

I am using this way.
Plese tell me correct way.

**Comment by fiboknacky** [comment]
That function doesn't accept a string. Could you kindly double-check [this section](https://developers.google.com/google-ads/api/docs/client-libs/php/logging#configuring_logging)? 
If you want to create a logger on the fly, see [this function](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/Lib/V9/LoggerFactory.php#L41).

**Comment by fiboknacky** [comment]
Close due to inactivity.
