### ISSUE TITLE
Asynchronious reporting data requests ("GoogleAdsServiceClient->searchAsync()")

### ISSUE THREAD

**Issue by hakimio** [googleads/google-ads-php#701]
**Problem you are trying to solve:**

I would like to be able to download multiple reports in parallel.

**Solution you'd like:**

Right now when you call `GoogleAdsServiceClient->search()` method it in turn calls `GapicClientTrait->getPagedListResponse()` and blocks execution because of [the `wait()` call](https://github.com/googleapis/gax-php/blob/14e5bbd14b41c9602623a70d35e0d88fc8cddddf/src/GapicClientTrait.php#L746) at the end of the method.

I would like to have non-blocking `GoogleAdsServiceClient->searchAsync()` method which would just return `GuzzleHttp\Promise\PromiseInterface` and allow you to choose when to `wait()` for the promise to be resolved.

**Additional context:**

**Comment by PierrickVoulet** [comment]
Hi @hakimio,

Thank you for sending this enhancement request.

The implementation is owned by [gax-php](https://github.com/googleapis/gax-php). Could you please elaborate a bit more on the use cases?

**Comment by hakimio** [comment]
Use case is simple: downloading multiple reports in parallel to cache them in local database.

**Comment by hakimio** [comment]
Proposed simple solution which works:
```php
    public function searchAsync(string $customerId, string $query, array $optionalArgs = []): PromiseInterface
    {
        $request = new SearchGoogleAdsRequest();
        $requestParamHeaders = [];
        $request->setCustomerId($customerId);
        $request->setQuery($query);
        $requestParamHeaders['customer_id'] = $customerId;
        if (isset($optionalArgs['pageToken'])) {
            $request->setPageToken($optionalArgs['pageToken']);
        }

        if (isset($optionalArgs['pageSize'])) {
            $request->setPageSize($optionalArgs['pageSize']);
        }

        if (isset($optionalArgs['validateOnly'])) {
            $request->setValidateOnly($optionalArgs['validateOnly']);
        }

        if (isset($optionalArgs['returnTotalResultsCount'])) {
            $request->setReturnTotalResultsCount($optionalArgs['returnTotalResultsCount']);
        }

        if (isset($optionalArgs['summaryRowSetting'])) {
            $request->setSummaryRowSetting($optionalArgs['summaryRowSetting']);
        }

        $requestParams = new RequestParamsHeaderDescriptor($requestParamHeaders);
        $optionalArgs['headers'] = isset($optionalArgs['headers']) ? array_merge($requestParams->getHeader(), $optionalArgs['headers']) : $requestParams->getHeader();
        
        return $this->startCall('Search', SearchGoogleAdsResponse::class, $optionalArgs, $request);
    }
```

`startCall()` method is from `GapicClientTrait` class.

**Comment by hakimio** [comment]
Closing since sometime around `v21` [`GoogleAdsServiceClient->searchAsync()`](https://github.com/googleads/google-ads-php/blob/3b876a88574a44652ad091da9c731267095b97ea/src/Google/Ads/GoogleAds/V16/Services/Client/GoogleAdsServiceClient.php#L56) method was introduced.
