### ISSUE TITLE
 Call to undefined method Google\Auth\CredentialsLoader::shouldLoadClientCertSource()

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#706]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your client library and Google Ads API versions:**

* Client library version: `v13.0.0`

* Google Ads API version: `V8`

**Your environment:**

================= PHP GENERAL INFORMATION
phpinfo()
PHP Version => 7.4.14

System => Linux ads 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64
Build Date => Jan 13 2021 08:04:06

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*

================= PHP EXTENSION INFORMATION
The PHP Extension grpc is installed: 1.35.0
The PHP Extension protobuf is installed: 3.14.0

**Description of the bug:**
Getting error while try to make click_view report

An uncaught Exception was encountered

Type:        Error
Message:     Call to undefined method Google\Auth\CredentialsLoader::shouldLoadClientCertSource()
Filename:    /vendor/google/gax/src/GapicClientTrait.php
Line Number: 235

Backtrace:
	File: /vendor/google/gax/src/LongRunning/Gapic/OperationsGapicClient.php
	Line: 183
	Function: buildClientOptions

	File: /src/Google/Ads/GoogleAds/Lib/V8/GoogleAdsGapicClientTrait.php
	Line: 77
	Function: __construct

	File:/vendor/google/gax/src/GapicClientTrait.php
	Line: 195
	Function: modifyClientOptions

	File: /src/Google/Ads/GoogleAds/V8/Services/Gapic/GoogleAdsServiceGapicClient.php
	Line: 170
	Function: buildClientOptions

	File: /src/Google/Ads/GoogleAds/Lib/V8/ServiceClientFactoryTrait.php
	Line: 963
	Function: __construct

	File: /GetClickReport.php
	Line: 228
	Function: getGoogleAdsServiceClient

	File: /GetClickReport.php
	Line: 75
	Function: getGCLIDReportMetrics

 
**Anything else we should know about your project / environment:**

**Comment by PierrickVoulet** [comment]
Hi @chiragvels,

This issue seems related to the configuration of your environment.

The method `Google\Auth\CredentialsLoader::shouldLoadClientCertSource()` was introduced with the version [`1.17.0`](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.17.0) of `google/auth` and is used starting with the version [`1.18.0`](https://github.com/googleapis/gax-php/releases/tag/v1.8.0) of `google/gax-php`.

Could you confirm the versions of `google/auth` and `google/gax-php` that are installed our your environment?

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I don’t think that issue with configuration.
I was using same server for other google ads api related functionality which is working fine. I am also able to download other reports.

Where I can see the versions of google/auth and google/gax-php?

**Comment by PierrickVoulet** [comment]
If you  use composer, you could check with `composer show google/auth` and `composer show google/gax`.

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

name     : google/auth
descrip. : Google Auth Library for PHP
keywords : Authentication, google, oauth2
versions : * v1.18.0

name     : google/gax
descrip. : Google API Core for PHP
keywords : google
versions : * v1.10.0

Thanks,

**Comment by PierrickVoulet** [comment]
This looks good to me. This seems to be a bug of `google/gax`, please open a new issue on their [repository](https://github.com/googleapis/gax-php/issues/new?assignees=&labels=&template=bug_report.md)?

**Comment by chiragvels** [comment]
Ok,

Thanks,

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I am still facing issue with only keywordsPlanService

Type:        Error
Message:     Call to undefined method Google\Auth\CredentialsLoader::shouldLoadClientCertSource()
Filename:    /google-ads-php/vendor/google/gax/src/GapicClientTrait.php
Line Number: 235

Backtrace:
	File: /google-ads-php/vendor/google/gax/src/LongRunning/Gapic/OperationsGapicClient.php
	Line: 183
	Function: buildClientOptions

	File: /google-ads-php/src/Google/Ads/GoogleAds/Lib/V10/GoogleAdsGapicClientTrait.php
	Line: 77
	Function: __construct

	File: /google-ads-php/vendor/google/gax/src/GapicClientTrait.php
	Line: 195
	Function: modifyClientOptions

	File: /google-ads-php/src/Google/Ads/GoogleAds/V10/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php
	Line: 180
	Function: buildClientOptions

	File: /google-ads-php/src/Google/Ads/GoogleAds/Lib/V10/ServiceClientFactoryTrait.php
	Line: 897
	Function: __construct


Can you please help me If I have C version of grpc, which is older one 1.35.0. So it will take C version or composer based version?

Thanks,

**Comment by PierrickVoulet** [comment]
The C implementation of grpc ([PECL based](https://pecl.php.net/package/gRPC)) is used if it is installed in addition to the PHP implementation ([composer based](https://packagist.org/packages/grpc/grpc)). It is recommended to use the same version for the C and PHP implementations. To do so, you can check the version installed by composer and install the same version via PECL on your system using `sudo pecl install grpc-<version>`.

Also, not sure if related to your issue but you may want to check [this similar issue](https://github.com/googleapis/gax-php/issues/383).

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

Thanks for the confirmation.

Also, not sure if related to your issue but you may want to check https://github.com/googleapis/gax-php/issues/383.
-> No I am facing issue only while using KeywordPlanIdeaService as of now.

Thanks,

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

And this error only comes when I try to get keywords ideas based on urlseed.

Thanks,

**Comment by PierrickVoulet** [comment]
Hi @chiragvels - Could you provide the code you are using and logs when it works and when it does not. This would help us investigate further.

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

I have enabled logging but not able to generate any log as it not even able to gone past getKeywordPlanIdeaServiceClient
Sample

```
           $keywordPlanIdeaServiceClient = $googleAdsClient->getKeywordPlanIdeaServiceClient();
            // Generate keyword ideas based on the specified parameters.
            $response = $keywordPlanIdeaServiceClient->generateKeywordIdeas(
                    [
                'language' => ResourceNames::forLanguageConstant(1000),
                'customerId' => $customerID,
                'geoTargetConstants' => ResourceNames::forGeoTargetConstant($locationId),
                'keywordPlanNetwork' => KeywordPlanNetwork::GOOGLE_SEARCH,
                'pageSize' => 200,
                'urlSeed' => new UrlSeed(['url' => $pageUrl])
                    ] 
            );
```
But when I use 
> 'keywordSeed' => new KeywordSeed(['keywords' => $keywords])

Instead 

> 'urlSeed' => new UrlSeed(['url' => $pageUrl])

It will provide keywordsIdea.

Thanks

**Comment by PierrickVoulet** [comment]
I tried both on my side and got no issues, it looks like it is specific to your environment. I am using PHP `8.0`, gRPC `1.45.0` and Protobuf `3.20.1` (with [extensions installed](https://github.com/googleads/google-ads-php#requirements)).
