### ISSUE TITLE
google_ads_php.ini not found but it does exists

### ISSUE THREAD

**Issue by LucasGorgal** [googleads/google-ads-php#707]
**Your client library and Google Ads API versions:**

* Client library version: `v13.0.0`

* Google Ads API version: `V8`

**Your environment:** Digital Ocean Droplet - Ubuntu 20.04 (LTS) x64

```
================= PHP GENERAL INFORMATION
phpinfo()
PHP Version => 7.4.3

System => Linux ubuntu-s-1vcpu-1gb-sfo3-01 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64
Build Date => Nov 25 2021 23:16:22
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php/7.4/cli
Loaded Configuration File => /etc/php/7.4/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.4/cli/conf.d
Additional .ini files parsed => /etc/php/7.4/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.4/cli/conf.d/10-opcache.ini,
/etc/php/7.4/cli/conf.d/10-pdo.ini,
/etc/php/7.4/cli/conf.d/15-xml.ini,
/etc/php/7.4/cli/conf.d/20-bcmath.ini,
/etc/php/7.4/cli/conf.d/20-bz2.ini,
/etc/php/7.4/cli/conf.d/20-calendar.ini,
/etc/php/7.4/cli/conf.d/20-ctype.ini,
/etc/php/7.4/cli/conf.d/20-curl.ini,
/etc/php/7.4/cli/conf.d/20-dom.ini,
/etc/php/7.4/cli/conf.d/20-exif.ini,
/etc/php/7.4/cli/conf.d/20-ffi.ini,
/etc/php/7.4/cli/conf.d/20-fileinfo.ini,
/etc/php/7.4/cli/conf.d/20-ftp.ini,
/etc/php/7.4/cli/conf.d/20-gd.ini,
/etc/php/7.4/cli/conf.d/20-gettext.ini,
/etc/php/7.4/cli/conf.d/20-iconv.ini,
/etc/php/7.4/cli/conf.d/20-intl.ini,
/etc/php/7.4/cli/conf.d/20-json.ini,
/etc/php/7.4/cli/conf.d/20-ldap.ini,
/etc/php/7.4/cli/conf.d/20-mbstring.ini,
/etc/php/7.4/cli/conf.d/20-mysqli.ini,
/etc/php/7.4/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.4/cli/conf.d/20-phar.ini,
/etc/php/7.4/cli/conf.d/20-posix.ini,
/etc/php/7.4/cli/conf.d/20-readline.ini,
/etc/php/7.4/cli/conf.d/20-shmop.ini,
/etc/php/7.4/cli/conf.d/20-simplexml.ini,
/etc/php/7.4/cli/conf.d/20-soap.ini,
/etc/php/7.4/cli/conf.d/20-sockets.ini,
/etc/php/7.4/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.4/cli/conf.d/20-sysvsem.ini,
/etc/php/7.4/cli/conf.d/20-sysvshm.ini,
/etc/php/7.4/cli/conf.d/20-tokenizer.ini,
/etc/php/7.4/cli/conf.d/20-xmlreader.ini,
/etc/php/7.4/cli/conf.d/20-xmlrpc.ini,
/etc/php/7.4/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.4/cli/conf.d/20-xsl.ini,
/etc/php/7.4/cli/conf.d/20-zip.ini

PHP API => 20190902
PHP Extension => 20190902
Zend Extension => 320190902
Zend Extension Build => API320190902,NTS
PHP Extension Build => API20190902,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => available, disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, compress.bzip2, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
================= PHP EXTENSION INFORMATION
The PHP Extension grpc is installed: 1.39.0
The PHP Extension protobuf is installed: 3.17.3
```

**Description of the bug:**
Google Ads PHP works correct from cli from root. However, I connected the API to the Apache. I seted fromFile option in oAuth loader: fromFile('/root/google_ads_php.ini').

However, it won't work.

If I use the command _cat /root/google_ads_php.ini_ it correctly shows the file and the permission is 777.

**Steps to reproduce:**

I don't know how to reproduce this. I guess installing an Apache instance and using the demo script fo keywords referring to the .ini file.

**Expected behavior:**
The ini file being corrected loaded and the script working correctly just as the CLI.

**Request/Response Logs:**

`Fatal error: Uncaught InvalidArgumentException: Config file not found as specified: '/root/google_ads_php.ini'. Home directory could not be located so it was not searched. in /home/root/report/google-ads-php/src/Google/Ads/GoogleAds/Lib/ConfigurationLoader.php:72 Stack trace: #0 /home/root/report/google-ads-php/src/Google/Ads/GoogleAds/Lib/AbstractGoogleAdsBuilder.php(57): Google\Ads\GoogleAds\Lib\ConfigurationLoader->fromFile()`

 
**Anything else we should know about your project / environment:**
No

**Comment by PierrickVoulet** [comment]
Hi @LucasGorgal,

Your Apache may not have access to `/root/`, could you try putting the configuration file under the document root of the website instead of `/root/`?

To workaround you could use other methods of configuration such as [dynamic configuration](https://developers.google.com/google-ads/api/docs/client-libs/php/configuration#dynamic_configuration) or [environment variables](https://developers.google.com/google-ads/api/docs/client-libs/php/configuration#configuration_environment_variables).

**Comment by LucasGorgal** [comment]
Great, thank you so much! Using dynamic configuration did work!

Now it shows another err, do I put it here or create another issue report?

`Fatal error: Uncaught BadMethodCallException: Streaming calls are not supported while using the REST transport. in /home/root/report/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php:137 Stack trace: #0 /home/root/report/google-ads-php/vendor/google/gax/src/Transport/HttpUnaryTransportTrait.php(63): Google\ApiCore\Transport\RestTransport->throwUnsupportedException() #1 /home/root/report/google-ads-php/vendor/google/gax/src/GapicClientTrait.php(521): Google\ApiCore\Transport\RestTransport->startServerStreamingCall() #2 /home/root/report/google-ads-php/vendor/google/gax/src/Middleware/CredentialsWrapperMiddleware.php(61): Google\Ads\GoogleAds\V8\Services\Gapic\GoogleAdsServiceGapicClient->Google\ApiCore\{closure}() #3 /home/root/report/google-ads-php/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\ApiCore\Middleware\CredentialsWrapperMiddleware->__invoke() #4 /home/root/report/google-ads-php/vendor/google/gax/src/Middleware/RetryMiddleware.php(85): Google\ApiCore\Middleware\FixedHeaderMiddleware->__invoke() #5 /home/root/report/google-ads-php/vendor/google/gax/src/Middleware/OptionsFilterMiddleware.php(63): Google\ApiCore\Middleware\RetryMiddleware->__invoke() #6 /home/root/report/google-ads-php/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\ApiCore\Middleware\OptionsFilterMiddleware->__invoke() #7 /home/root/report/google-ads-php/src/Google/Ads/GoogleAds/Lib/V8/ServerStreamingGoogleAdsExceptionMiddleware.php(61): Google\ApiCore\Middleware\FixedHeaderMiddleware->__invoke() #8 /home/root/report/google-ads-php/src/Google/Ads/GoogleAds/Lib/V8/ServerStreamingGoogleAdsResponseMetadataCallable.php(40): Google\Ads\GoogleAds\Lib\V8\ServerStreamingGoogleAdsExceptionMiddleware->__invoke() #9 /home/root/report/google-ads-php/vendor/google/gax/src/GapicClientTrait.php(496): Google\Ads\GoogleAds\Lib\V8\ServerStreamingGoogleAdsResponseMetadataCallable->__invoke() #10 /home/root/report/google-ads-php/src/Google/Ads/GoogleAds/V8/Services/Gapic/GoogleAdsServiceGapicClient.php(523): Google\Ads\GoogleAds\V8\Services\Gapic\GoogleAdsServiceGapicClient->startCall() #11`

**Comment by PierrickVoulet** [comment]
> Great, thank you so much! Using dynamic configuration did work!
> 
> Now it shows another err, do I put it here or create another issue report?

It looks like you are trying to use `GoogleAdsService.SearchStream` with `rest` transport which isn't compatible. Please either [switch to `grpc` transport](https://developers.google.com/google-ads/api/docs/client-libs/php/transport) or use [`GoogleAdsService.Search`](https://developers.google.com/google-ads/api/docs/reporting/streaming).

**Comment by LucasGorgal** [comment]
Thank you so much for your answer! I thought it was enabled on default.

It works now :)
