### ISSUE TITLE
Add detailed demographic criteriaId Adgroup level

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/google-ads-php#708]
I tried using the code below to add detailed demographic criteriaId but it's not working, could you please help to resolve,

$adGroupResourceName = ResourceNames::forAdGroup($customerId, $adgroup_id);

$AdGroupCriterion = new AdGroupCriterion(['ad_group' => $adGroupResourceName,

'user_interest' => new UserInterestInfo(['user_interest_category'=>'customers/67X61XXX/detailedDemographics/3008'])

]);

$operations = [new AdGroupCriterionOperation(['create' => $AdGroupCriterion])];

$adGroupCriterionServiceClient = $googleAdsClient->getAdGroupCriterionServiceClient();

$response = $adGroupCriterionServiceClient->mutateAdGroupCriteria($customerId,$operations);

**Comment by fiboknacky** [comment]
Could you provide more details, e.g., error messages or logs?

**Comment by Vijaysinh** [comment]
Request: 
{"customerId":"6716104374","operations":[{"create":{"adGroup":"customers/6716104374/adGroups/134004505329","userInterest":{"userInterestCategory":"customers/6716104374/detailedDemographics/3008"}}}]}

Response
-------
Headers: {
    "request-id": "vX_QzcNFSRLaqTycgIdQZQ",
    "date": "Fri, 24 Dec 2021 12:04:25 GMT",
    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"requestError":"RESOURCE_NAME_MALFORMED"},"message":"Resource name 'customers/6716104374/detailedDemographics/3008' is malformed: expected 'customers/{customer_id}/userInterests/{user_interest_id}'.","location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"user_interest"},{"fieldName":"user_interest_category"}]}}],"requestId":"vX_QzcNFSRLaqTycgIdQZQ"}

**Comment by Vijaysinh** [comment]
its showing I have to pass user_interest_id but, I want to add detailedDemographic id at adgroupLevel also demographic criteriaId (3008) , I got from detailed_demographic report.

**Comment by Vijaysinh** [comment]
I want to add this data as per screenshot

![image](https://user-images.githubusercontent.com/6183730/147353400-4dc8368a-1b9a-4544-9f5a-787b09f599c5.png)

**Comment by Vijaysinh** [comment]
@fiboknacky could you please update on this?

**Comment by fiboknacky** [comment]
As a basic rule for using the classes in this library, you have to use the resource name of the class you're creating.
So, if you create a [UserInterestInfo](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V9/Common/UserInterestInfo.php), you cannot specify the resource name of the detailed demographic. You need to use the resource name of the `UserInterestInfo`.

Usually, if a criterion type can be targeted, it should appear as a part of one-of field ([`criterion`](https://developers.google.com/google-ads/api/reference/rpc/v9/AdGroupCriterion?hl=en#criterion)).
It looks like that the detailed demographic isn't available there yet.
You can request this feature in the [Google Ads API forum](https://groups.google.com/g/adwords-api).
