### ISSUE TITLE
Can v201809 Google adwords API be used for migration of the Extensions from Feed Based to be Asset Based

### ISSUE THREAD

**Issue by shobhathorve2022** [googleads/google-ads-php#710]
I just have one quick question, we are using the Google Adwords API v201809. Can we switch to use AssetBasedOperation using this version(v201809) of Google Adwords API or do we need to switch to v7/v8/v9. Really confused, please help.

If v201809 can be used, can someone please guide how.

Lots of Thanks,
Shhobha

**Comment by fiboknacky** [comment]
The AdWords API will be sunset soon in [April this year](https://ads-developers.googleblog.com/2021/04/upgrade-to-google-ads-api-from-adwords.html) and is replaced by the Google Ads API.
v201809 was the last version of the AdWords API, so you cannot use any new features in that API, including the assets.

Please check out [this blog post](https://ads-developers.googleblog.com/2021/04/upgrade-to-google-ads-api-from-adwords.html) and [the Migration guide](https://developers.google.com/google-ads/api/docs/migration/features) and start migration soon.
If you need help, feel free to reach out to us via this repository's issue tracker (for the library-related issues) and [the Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) for other general API questions.

Best,
Knack
