### ISSUE TITLE
REST API Get request to generate KeywordPlanHistoricalMetrics in PHP 

### ISSUE THREAD

**Issue by MOSTAFAEZZAT** [googleads/google-ads-php#711]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

I want to use REST API of Google Ads API by GET request to generate Historical Metrics for keyword.
 all i just need is to get the historical metrics for a word through Rest Interface with Google Ads API. 
I have a conversation on Google Ads API forum and still didn't get solution 
```
         $keyword= "Digital Maketing";
         $ch =curl_init("https://googleads.googleapis.com/v9/customers/(8519781266)/keywordPlans/(1):generateHistoricalMetrics" );
        
        curl_setopt($ch, CURLOPT_HEADER, true) ;
        curl_setopt($ch, CURLOPT_POSTFIELDS, $keyword); 
        curl_setopt($ch, CURLOPT_POSTFIELDS, true); 
        $respose = curl_exec($ch);
        print_r( $respose);
```

When I run this code it prints this error 

```
HTTP/2 401 www-authenticate: Bearer realm="https://accounts.google.com/" vary: X-Origin vary: Referer vary: Origin,Accept-Encoding content-type: application/json; charset=UTF-8 date: Wed, 29 Dec 2021 12:21:11 GMT server: ESF cache-control: private x-xss-protection: 0 x-frame-options: SAMEORIGIN x-content-type-options: nosniff alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43" accept-ranges: none { "error": { "code": 401, "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "status": "UNAUTHENTICATED", "details": [ { "@type": "type.googleapis.com/google.rpc.ErrorInfo", "reason": "CREDENTIALS_MISSING", "domain": "googleapis.com", "metadata": { "method": "google.ads.googleads.v9.services.KeywordPlanService.GenerateHistoricalMetrics", "service": "googleads.googleapis.com" } } ] } } 1

```

**Comment by fiboknacky** [comment]
Could you please share the link on the Google Ads API forum that you discuss as well?
As your topic is not related to this library, we should continue discussing that on the Google Ads API forum to ensure the best visibility to the users.

**Comment by MOSTAFAEZZAT** [comment]
Thanks for responding. 
After I did the Curl PHP Code I got an Issue in OAuth 2 access token `{ "error": { "code": 401, "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "status": "UNAUTHENTICATED" } }` 
It's on this conversation [Google Ads with Rest Interface error Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.](https://groups.google.com/g/adwords-api/c/ux_3SR_3nmI/m/rcSY1jLYDwAJ?hl=en) I'm waiting for respond also but I did everything as it was in the docs 

this php curl code 
```
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://googleads.googleapis.com/v9/customers/(8519781266):generateKeywordIdeas');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\n\"keywordSeed\": {\n    \"keywords\": [\n    \"cofee\"\n  ]\n  }\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Login-Customer-Id: (2260416591)';
$headers[] = 'Developer-Token: (z2sb0uyekDzkMbiyNpAImg';
$headers[] = 'Authorization: Bearer (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)';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
print_r($result);
curl_close($ch);
```

**Comment by MOSTAFAEZZAT** [comment]
I'm also trying to use the Google Ads API library itself I installed grpc and protobuf etc.. and i'm just waiting to figure out the problem of the AOuth token.
May I ask if google provides public token just for test?

**Comment by fiboknacky** [comment]
First, please don't put your developer token in here or anywhere. It works like a password that you should keep to yourself.

> May I ask if google provides public token just for test?

We don't have that kind of token. You need to follow the normal OAuth steps.

I saw the topic you started. The agent already asked you for your reply 3 days ago. They can help you debug why you get the OAuth error. Could you please reply and continue your conversation there?

As this is not related to this library, I'll close this issue for now.
Feel free to start a new one if you have library-specific issues.
