### ISSUE TITLE
Authentication of the request failed

### ISSUE THREAD

**Issue by zhangfeixiao** [googleads/google-ads-php#712]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
![c684ebc11b2e44c68f24338f4dbe0ca](https://user-images.githubusercontent.com/38904664/148476132-4300a9e6-2c6b-4868-8574-2dcd07fd90d0.png)

Hello,The developer token in the file is access_ Token?
https://developers.google.cn/google-ads/api/docs/first-call/get-campaigns

**Comment by fiboknacky** [comment]
No, to get the developer token, you need to follow [this guide](https://developers.google.com/google-ads/api/docs/first-call/dev-token).
As it looks like the question is related to the Google Ads API in general, please reach out to the experts on [the Google Ads API forum](https://groups.google.com/g/adwords-api). Feel free to get back to this repository if you have library-specific issues.
