### ISSUE TITLE
$adGroupCriterion->setFinalUrls([]); Not Working set final url to empty

### ISSUE THREAD

**Issue by evaldasgudavicius** [googleads/google-ads-php#713]
Hello,

Client library version: V9

Description of the bug: 12.1.0

---------

The problem is, that the function to set keyword final URL to empty NOT WORKING.

The code:

![image](https://user-images.githubusercontent.com/97511653/148913133-8776162e-d9ed-450e-b9a5-cd4db1ce3ca5.png)

The response is successful, but this "setFinalUrls([]);" does not remove the final URL from the keyword.

If I set not empty URL like setFinalUrls(['https://example.com']); it works and does the job.

-----------

Please check this issue and let me know how to set the final URL to empty properly.

Thanks!

**Comment by PierrickVoulet** [comment]
Hi @evaldasgudavicius,

This is a known limitation of the utility method `FieldMasks::allSetFieldsOf`, see #487 for details.

As a workaround, you can manually set the path `final_urls` in the `FieldMasks` instead of relying on the utility method `FieldMasks::allSetFieldsOf` alone.

Here is how it looks like:

```php
$adGroupCriterionOperation = new AdGroupCriterionOperation();
$adGroupCriterionOperation->setUpdate($adGroupCriterion);
$adGroupCriterionOperation->setUpdateMask(new FieldMask(['paths' => ['final_urls']]));
```

**Comment by evaldasgudavicius** [comment]
Thanks, Pierrick!

This works!

Can I ask you one more?

Could you please share the link where I can find all the list of available paths?

And how should I use this field mask if I want to set status and set the final URL in the same operation as in the example?

![image](https://user-images.githubusercontent.com/97511653/148952884-73371eef-f1f3-4046-9448-d121f1e2ef6a.png)

**Comment by PierrickVoulet** [comment]
Thanks for confirming!

The paths are always based on the fields of the `AdGroupCriterion` type in your case. You can find a quite exhaustive list of those fields in the [API reference documentation](https://developers.google.com/google-ads/api/fields/v9/ad_group_criterion).

In the case of status, you should be able to add [`status`](https://developers.google.com/google-ads/api/fields/v9/ad_group_criterion#ad_group_criterion.status) to the list:

```php
$adGroupCriterionOperation->setUpdateMask(new FieldMask(['paths' => ['final_urls', 'status']]));
```

**Comment by evaldasgudavicius** [comment]
Thanks, Pierrick!

You've resolved my problem :)

**Comment by evaldasgudavicius** [comment]
One more quick question about the same topic.

What if I set two paths (new FieldMask(['paths' => ['status', 'final_urls'])), but in some cases i will change only status, but not url or only final_urls, but not status.

Is there something wrong with that?

**Comment by PierrickVoulet** [comment]
> One more quick question about the same topic.
> 
> What if I set two paths (new FieldMask(['paths' => ['status', 'final_urls'])), but in some cases i will change only status, but not url or only final_urls, but not status.
> 
> Is there something wrong with that?

This can lead to some board effects. You should only set the paths that you want to update in the fields mask of each request.
