### ISSUE TITLE
Creating RSA - collection_size_error TOO_MANY

### ISSUE THREAD

**Issue by evaldasgudavicius** [googleads/google-ads-php#714]
Client library version: V9
Google Ads API version: 12.1.0

Hello,

I'm creating RSA from an example -> https://developers.google.com/google-ads/api/docs/samples/add-responsive-search-ad

The problem is, that if I use more than 4 headlines, I'm getting an error collection_size_error.

If the number of headlines is < 5, everything is ok.

I'm attaching the PrintScreen with my code.

Also, sharing example request-id -> v4jXrghb9LzFyQUKV_EFrA

I have tried every variant with a pinning line.

Pin all headlines, pin some headlines, not to pin at all.

How could I resolve this problem?

$headlines = [
    ['line' => 'Test Headline 1'],
    ['line' => 'Test Headline 2'],
    ['line' => 'Test Headline 3'],
    ['line' => 'Test Headline 4'],
    ['line' => 'Test Headline 5']
];
$descriptions = [
    ['line' => 'Buy your tickets now'],
    ['line' => 'Visit the Red Planet']
];

$headlinesToCreate = [];
foreach($headlines as $headline) {
    $headlineText = $headline['line'];
    $adTextAsset = new AdTextAsset();
    $adTextAsset->setText($headlineText);
    $headlinesToCreate[] = $adTextAsset;
}

$descriptionsToCreate = [];
foreach($descriptions as $description) {
    $descriptionText = $description['line'];
    $adTextAsset = new AdTextAsset();
    $adTextAsset->setText($descriptionText);
    $descriptionsToCreate[] = $adTextAsset;
}

$responsiveSearchAdInfo = new ResponsiveSearchAdInfo();
$responsiveSearchAdInfo->setHeadlines($headlinesToCreate);
$responsiveSearchAdInfo->setDescriptions($headlinesToCreate);

$ad = new Ad();
$ad->setResponsiveSearchAd($responsiveSearchAdInfo);
$ad->setFinalUrls([$finalURL]);

$adGroupAd = new AdGroupAd();
$adGroupAd->setAdGroup($adGroupResourceName);
$adGroupAd->setStatus(AdGroupAdStatus::ENABLED);
$adGroupAd->setAd($ad);

$adGroupAdOperation = new AdGroupAdOperation();
$adGroupAdOperation->setCreate($adGroupAd);

$adGroupAdServiceClient = $googleAdsClient->getAdGroupAdServiceClient();
$response = $adGroupAdServiceClient->mutateAdGroupAds($accountID, [$adGroupAdOperation]);

**Comment by fiboknacky** [comment]
> $responsiveSearchAdInfo->setDescriptions($headlinesToCreate);

You seem to provide the headlines to descriptions, which has a limit of 4, as indicated in [this article](https://support.google.com/google-ads/answer/7684791).

**Comment by evaldasgudavicius** [comment]
OMG, such a fail.

Thank you very much!
