### ISSUE TITLE
PHP Fatal error when running GetCampaigns example

### ISSUE THREAD

**Issue by will621** [googleads/google-ads-php#719]
Hi there,

I'm currently upgrading from the adwords api to google ads api (so have pre-existing auth details), as a first step I've pulled down the repo independently from our project.  I've followed the https://github.com/googleads/google-ads-php#readme (installed grpc protbuf via pecl, etc), but am running into an issue when running the example.

php examples/BasicOperations/GetCampaigns.php --customerId <REDACTED>

I'm getting the following error back:

➜  google-ads-php git:(main) ✗ php examples/BasicOperations/GetCampaigns.php --customerId <REDACTED>

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Google\ApiCore\Transport\Grpc\ServerStreamingCallWrapper::__construct() must be an instance of Grpc\ServerStreamingCall, instance of Google\Ads\GoogleAds\Lib\V9\GoogleAdsLoggingServerStreamingCall given, called in /google-ads-php/vendor/google/gax/src/Transport/GrpcTransport.php on line 208 and defined in /google-ads-php/vendor/google/gax/src/Transport/Grpc/ServerStreamingCallWrapper.php:49

(There is more of a stack trace which I can send if needed)

Not sure if helpful but if I edit the GetCampaigns.php code and use `search` instead of `searchStream` the campaigns are returned successfully (I want to use searchStream though!)

macOS Monterey
PHP 7.4.27
pecl grpc 1.43.0
pecl protobuf 3.19.3

Composer hasn't been touched since cloned (and I ran composer install rather than update):
"require": {
    "php": ">=7.4",
    "google/gax": "^1.7.0",
    "grpc/grpc": "^1.36.0",
    "google/protobuf": "^3.18.0",
    "monolog/monolog": "^1.26 || ^2.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^9.5",
    "squizlabs/php_codesniffer": "^3.5",
    "ext-bcmath": "*",
    "ext-grpc": "*",
    "ext-protobuf": "*",
    "ulrichsg/getopt-php": "^3.4",
    "react/http": "^1.2.0",
    "composer/composer": "^2.0"
  },
  

composer.lock file has:
          "name": "google/gax",
            "version": "v1.11.1",
            
                       "name": "grpc/grpc",
            "version": "1.42.0",
            
                        "name": "google/protobuf",
            "version": "v3.19.3",

**Comment by PierrickVoulet** [comment]
I was able to replicate with `gax-php` versions `1.11.0` and `1.11.1` but not with `1.10.0` and `1.11.2`. This issue seems to be fixed [here](https://github.com/googleapis/gax-php/pull/362).

Could you upgrade your `gax-php` dependency to the latest version `1.11.2` if it is not done already and let us know if that helps?

**Comment by will621** [comment]
Hi @PierrickVoulet yep that did the trick, thanks for the speedy reply.

**Comment by PierrickVoulet** [comment]
Thanks @will621 for confirming.
