### ISSUE TITLE
User doesn't have permission to access customer Error

### ISSUE THREAD

**Issue by Improbus42** [googleads/google-ads-php#721]
Hello! When i run GetCampaigns.php with my customer id i have an error : 
```
Status code: 7
Details: The caller does not have permission
Failure: {"errors":[{"errorCode":{"authorizationError":"USER_PERMISSION_DENIED"},"message":"User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"}]
```
How can i fix this? In script on Adwords APi all works fine. Please help!

**Comment by PierrickVoulet** [comment]
Hi @Improbus42 - This question is specific to Google Ads API (not the PHP library), please contact the dedicated [support](https://developers.google.com/google-ads/api/support).
