### ISSUE TITLE
Laravel Sample App - Class 'Google\Ads\GoogleAds\Lib\V9\GoogleAdsClientBuilder' not found

### ISSUE THREAD

**Issue by will621** [googleads/google-ads-php#723]
* Client library version: `v13.0.0`
* Google Ads API version: `V9`

macOS Monterey
PHP 7.4.27
pecl grpc 1.43.0
pecl protobuf 3.19.3

When running the Laravel Sample app and getting campaign details "Class 'Google\Ads\GoogleAds\Lib\V9\GoogleAdsClientBuilder' not found" error occurs

The composer.json file with the laravel sample app is referencing         
"googleads/google-ads-php": "^12.0", but the code is referencing V9 classes (which I'm thinking aren't there for 12.1.0)

To fix I just had to upgrade to v13.0.0 by running 
`composer require googleads/google-ads-php
`

So I think the LaravelSampleApp composer.json (and lock) needs to be updated to
        "googleads/google-ads-php": "^13.0", 

https://github.com/googleads/google-ads-php/blob/v13.0.0/examples/LaravelSampleApp/composer.json#L13

**Comment by PierrickVoulet** [comment]
Hi @will621 - Thank you for reporting this bug and suggesting a solution. I sent #724, this should avoid this type of issues in the future.
