### ISSUE TITLE
zteckjob 

### ISSUE THREAD

**Issue by Ayse1974** [googleads/google-ads-php#725]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Problem you are trying to solve:**

**Solution you'd like:**

**Alternatives you've considered:**

**Additional context:**

**Comment by PierrickVoulet** [comment]
Closing this issue because it was created without any content. Feel free to comment to provide more information.

**Comment by Ayse1974** [comment]
> Closing this issue because it was created without any content. Feel free to comment to provide more information.

Hmm! Okay

**Comment by PierrickVoulet** [comment]
@Ayse1974 I reversed the title of this issue because it is completely off-topic and related to advertising. I am locking the conversion because it is not a real issue.
