### ISSUE TITLE
How to get keywords stats

### ISSUE THREAD

**Issue by jaekunchoi** [googleads/google-ads-php#730]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
In Adwords API we were able to pass list of keywords and got stats (monthly avg, cpc, competition, historical volumes etc.) but how can we do this for Ads API? I just want to pass about 700 keywords and get that data not generate any related keywords

**Comment by PierrickVoulet** [comment]
Hi @jaekunchoi - This question is related to Google Ads API usage, not this library. Please contact the [Google Ads API support](https://developers.google.com/google-ads/api/support), they are better suited to answer.
