### ISSUE TITLE
Get value of Labels

### ISSUE THREAD

**Issue by fil79** [googleads/google-ads-php#731]
Hi

i am trying to get all labels of a customer, here it is my code

` $query = '  SELECT customer_client.id, customer_client.descriptive_name, customer_client.applied_labels,
                    customer_client.client_customer
                    FROM customer_client
                  ';

        $response =
            $googleAdsServiceClient->search($customerId, $query);

        foreach ($response->iterateAllElements() as $googleAdsRow) {
            /** @var GoogleAdsRow $googleAdsRow */
            
            $customer = $googleAdsRow->getCustomerClient();
            $customerId = $customer->getId();
            $customerName = $customer->getDescriptiveName();
            $customerLabels = $customer->getAppliedLabels();

            var_dump($customerId);
            var_dump($customer);
            var_dump($customerLabels);

            
        }`

the result of $customerLabels is object(google\protobuf\internal\repeatedField)#. How i can ge the values inside. I really can t find in documentation

Thanks in advance

**Comment by fiboknacky** [comment]
You can use `foreach()` to iterate over its members:

```php
foreach ($customerLabels as $customerLabel) {
    // Do something.
}
```
