### ISSUE TITLE
How can we have one single request with multiple mutate operations?

### ISSUE THREAD

**Issue by jaekunchoi** [googleads/google-ads-php#732]
I was looking at this example and it seems it requests multiple requests rather than aggregating multiple mutate operations in a single request.
https://github.com/googleads/google-ads-php/blob/2a7e23d246c18b36918de34fb7a73bbf4a571e2c/examples/Planning/AddKeywordPlan.php#L117-L144

How can I stop mutate requests and group them into one request instead?

**Comment by PierrickVoulet** [comment]
Hi @jaekunchoi - You can find more information about the different mutate options in this [article](https://developers.google.com/google-ads/api/docs/mutating/overview). It's not specific to this library but to the Google Ads API, please contact their dedicated [support](https://developers.google.com/google-ads/api/support) if you have any follow up questions about these features.
