### ISSUE TITLE
"Getting started" guide does not work with web applications

### ISSUE THREAD

**Issue by treyvanes** [googleads/google-ads-php#733]
This is a very simple issue which can be explained in two steps:

1. Your "Getting started" guide tells us to run `AuthenticateInDesktopApplication` to set up `google_ads_php.ini`. If you are developing a web application, this won't work as it is the wrong application type. The error received from Google is `It is not allowed for the WEB client type`.
2. If you try to change to use the `AuthenticateInWebApplication` example instead, the URL generated by the example is invalid and you cannot authenticate using this URL. For example, it always wants me to authenticate using `127.0.0.1:37723/oauth2callback`, but my web application is on the internet and is not accessible via `127.0.0.1:37723/oauth2callback`.

I hope the documentation can be fixed to include instructions for web applications.

Thanks for maintaining this library.

Cheers

**Comment by fiboknacky** [comment]
Hello,

`AuthenticateInDesktopApplication` is as you can infer from the name (and also in the file comment), it's meant for the offline (Desktop application) flow.

As stated in the [comment](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/AuthenticateInWebApplication.php#L35) of `AuthenticateInWebApplication`, the code example will start a basic local web server, so what you describe works as intended. We never intend that example to run on the Internet.

They serve as a basic example to help you get an idea of how the OAuth2 flow can be implemented.
If you're developing a web application by yourself, you need to ensure that you pass [all the necessary information](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/AuthenticateInWebApplication.php#L78-L91), and supply a correct redirect URL for your application.

Finally, please also check [this section](https://developers.google.com/google-ads/api/docs/oauth/cloud-project?hl=en#choose_an_app_type) to see if you really need a web application flow. In some cases, the desktop app flow is already enough.

**Comment by treyvanes** [comment]
Thanks for your reply.

In the instructions for setting up your OAuth2 credentials, you tell us to run AuthenticateInDesktopApplication and to copy the output to google_ads_php.ini.

Based on your reply it is clear this documentation is incorrect.

It would be worth fixing the documentation instead of dismissing my concerns because I didn't see a comment on line 35 in one of your files. Try to use Striple as an example, there's a reason people enjoy using that API.
