### ISSUE TITLE
Generating Keywords with Rest Rest API using curl PHP

### ISSUE THREAD

**Issue by MOSTAFAEZZAT** [googleads/google-ads-php#734]
Hello I want to generate keywordsIdeas and Historical Keywords Mretics through curl php with Rest I have been following with Google Ads API forum also but I get Errors with Curl Command However My Access token works normally with other command such as 
```
C:\Users\MostafaEzzat>curl -f --request GET "https://googleads.googleapis.com/v9/customers:listAccessibleCustomers" \ --header "Content-Type: application/json" \ --header "developer-token: REDACTED" \ --header "Authorization: Bearer REDACTED" \
{
  "resourceNames": [
    "customers/8519781266",
    "customers/2260416591",
    "customers/3084026203",
    "customers/2897861276",
    "customers/6210187694",
    "customers/3242362947"
  ]
}
```

I searched for past conversation I found this code 
      ```
 $curl = curl_init();
                curl_setopt_array($curl, array(
                CURLOPT_URL => "https://googleads.googleapis.com/v9/customers/8519781266:generateKeywordIdeas",
            
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_ENCODING => "",
                CURLOPT_MAXREDIRS => 10,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                CURLOPT_CUSTOMREQUEST => "POST",
                CURLOPT_POSTFIELDS =>"{
                    'geoTargetConstants': ['USA','Canada'],
                    'includeAdultKeywords': 'false',
                    'pageToken': '1',
                    'pageSize': '1000',
                    'keywordPlanNetwork': 'GOOGLE_SEARCH',
                    'keywordAnnotation': ['KEYWORD_CONCEPT'],
                    'aggregateMetrics': 'DEVICE',
                    'language': 'English',
                     
                }",
                CURLOPT_HTTPHEADER => array(
                    "Content-Type: application/json",
                    "developer-token: REDACTED",
                    "login-customer-id: 2260416591",
                    "Authorization: Bearer REDACTED"
            
                    ),
                ));
                $response = curl_exec($curl);
                
                curl_close($curl);
                echo "CURLllll" ;
                var_dump($response);
```
When I run it I get this Error `So what's the right formula to generate KeywordsIdeas through Curl PHP` Thanks in advance
 `"{ "error": { "code": 400, "message": "Invalid value at 'aggregate_metrics' (type.googleapis.com/google.ads.googleads.v9.common.KeywordPlanAggregateMetrics), \"DEVICE\"", "status": "INVALID_ARGUMENT", "details": [ { "@type": "type.googleapis.com/google.rpc.BadRequest", "fieldViolations": [ { "field": "aggregate_metrics", "description": "Invalid value at 'aggregate_metrics' (type.googleapis.com/google.ads.googleads.v9.common.KeywordPlanAggregateMetrics), \"DEVICE\"" } ] } ] } } `

**Comment by fiboknacky** [comment]
First, please be reminded to _not_ post your **developer token** and **refresh token** on the public forum.
They're your private credentials and can be used in a wrong way.

Regarding the use of REST and curl, as it's not related to the client library, the Google Ads API forum would be the best to discuss if you wish to use REST to submit your query.
As for the one you shared here, I found that you've supplied a wrong data type to `aggregateMetrics`.

It has a type of [KeywordPlanAggregateMetrics](https://developers.google.com/google-ads/api/rest/reference/rest/v9/KeywordPlanAggregateMetrics), so you should provide an object of that class with an array of `aggregateMetricTypes` inside.
