### ISSUE TITLE
MutateAdGroupCriterionLabels

### ISSUE THREAD

**Issue by fil79** [googleads/google-ads-php#736]
Hi

i am trying to mutate keyword labels with googleAds API. 
https://developers.google.com/google-ads/api/reference/rpc/v7/MutateAdGroupCriterionLabelsRequest

Is there any code example to show how to do this operation?

Thanks

**Comment by PierrickVoulet** [comment]
Hi @fil79 - The [closest example we currently have](https://github.com/googleads/google-ads-php/blob/main/examples/CampaignManagement/AddCampaignLabels.php) is for campaign labels, it should be fairly close to ad group criterion labels.
