### ISSUE TITLE
Examples for asset-based DSA

### ISSUE THREAD

**Issue by SeriousJ55** [googleads/google-ads-php#738]
Are there examples about asset-based DSA?

You only give examples for feed-based DSA that will be deprecated on April 27, 2022:
https://github.com/googleads/google-ads-php/blob/main/examples/AdvancedOperations/AddDynamicPageFeed.php

**Comment by PierrickVoulet** [comment]
Hi @SeriousJ55 - Thank you for the feedback! We are working on it, we hope to provide one with the next release of the library (it should be pretty soon).

**Comment by fiboknacky** [comment]
[The example](https://github.com/googleads/google-ads-php/blob/main/examples/AdvancedOperations/AddDynamicPageFeedAsset.php) is now available in [v14.0.0](https://github.com/googleads/google-ads-php/releases/tag/v14.0.0).
