### ISSUE TITLE
How to delete all keyword plans?

### ISSUE THREAD

**Issue by jaekunchoi** [googleads/google-ads-php#739]
Sorry another question:
Is there a way to delete all keyword plans in the account?
Any example would be appreciated!

**Comment by PierrickVoulet** [comment]
Hi @jaekunchoi - You can refer to the code example [RemoveCampaign](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/RemoveCampaign.php#L116) that demonstrates how to send a request with operation(s) to remove campaign(s). You could replicate the logic to remove KeywordPlans instead (see [KeywordPlanService.MutateKeywordPlans](https://developers.google.com/google-ads/api/reference/rpc/v10/KeywordPlanService#mutatekeywordplans), [MutateKeywordPlansRequest](https://developers.google.com/google-ads/api/reference/rpc/v10/MutateKeywordPlansRequest), [KeywordPlanOperation](https://developers.google.com/google-ads/api/reference/rpc/v10/KeywordPlanOperation)).

**Comment by jaekunchoi** [comment]
Thanks for the response but how can I remove all keyword plans that the customer has without having to lookup individual keyword plan?

**Comment by PierrickVoulet** [comment]
Not sure. The [Google Ads API support team](https://developers.google.com/google-ads/api/support) is best suited to answer this type of questions, please contact them.

If you have any follow up questions that are related to this library though, do not hesitate to contact us again.
