### ISSUE TITLE
Calls assets are not returned

### ISSUE THREAD

**Issue by xiaawan** [googleads/google-ads-php#746]
Hello,

I am using following query and results are not returned from the API. Also, I don't get any error. 

I am using v10
---------------------------------------------------
SELECT campaign_asset.asset, campaign.id, campaign.name, asset.id,
                asset.resource_name, 
                asset.call_asset.country_code, asset.call_asset.phone_number from campaign_asset
                WHERE campaign_asset.field_type = "CALL" ORDER BY campaign.name ASC

--------------------------------------------------------------------

Can anyone help me what I am doing wrong here?

**Comment by PierrickVoulet** [comment]
Hi @xiaawan - This question is specific to the Google Ads API, not this library. Please contact the [Google Ads API support](https://developers.google.com/google-ads/api/support) team, they are the best suited to answer and will help you.
