### ISSUE TITLE
Web app authorization problem

### ISSUE THREAD

**Issue by LaurentSEO** [googleads/google-ads-php#749]
Hi all,

I'm trying to use Google Ads API for the first time with this documentation: https://developers.google.com/google-ads/api/docs/client-libs/php/oauth-web?hl=en

AuthenticateInWebApplication.php give an URL and the doc says "visit the following URL", so I copy it in my browser.
I could validate the authorization, but I was redirected on http://127.0.0.1:44807/oauth2callback, so to my own computer where oauth2callback doesn't exists. And this URL doesn't exists neither in the client library.

I don't understand the overall process yet, so I'm trying to stupidly follow the documentation :-)

Could someone help me?

Thanks
Best regards

**Comment by PierrickVoulet** [comment]
Hi @LaurentSEO,

Most projects use OAuth Desktop, not OAuth Web. It is recommend to use OAuth Desktop when there are no specific reasons to use OAuth Web.

This question is not strictly related to this library, please contact the [support team of Google Ads API](https://developers.google.com/google-ads/api/support). They are the best suited to answer your questions about the OAuth flows. In the meantime, I thought I would point you to the guide in the Google Ads API [documentation](https://developers.google.com/google-ads/api/docs/oauth/overview) in case you did not have the chance to take a look at it just yet.

Thanks,

**Comment by LaurentSEO** [comment]
Hi Pierrick,
Thanks!
I began to contact the API support, but they said it was a client library problem and I should contact its authors...
Best regards Laurent
Laurent

**Comment by PierrickVoulet** [comment]
Did you posted the question on the public forum? If you did, could you point us to it?

**Comment by LaurentSEO** [comment]
Yes :
https://groups.google.com/g/adwords-api/c/z1MvNZ0tWK8
