### ISSUE TITLE
Unable to setup logging

### ISSUE THREAD

**Issue by michaelk1975** [googleads/google-ads-php#751]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your client library and Google Ads API versions:**

* Client library version: `v14.0.0`

* Google Ads API version: `V10`

**Your environment:**

**Description of the bug:**

I'm trying to enable logging:
Added  the following to google_ads_php.ini:

[LOGGING]
logFilePath = my path
logLevel = “DEBUG"

Also performed 'chmod -R 777' on directory containing the log file.
But after running a request, the log file was empty.

**Steps to reproduce:**

**Expected behavior:**

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by PierrickVoulet** [comment]
Hi @michaelk1975,

We need more information about your environment to investigate.

Please provide the output generated by our complementary script: https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php.

Alternatively, please provide with the following pieces of information:

* The PHP version: Run `php -v`.
* The name and version of the operating system: Run `php -r 'print php_uname();'`.
* Whether the PHP Extension `protobuf` is used or not: Run `php -r 'print phpversion("protobuf");'`.
* Whether the PHP Extension `grpc` is used or not: Run `php -r 'print phpversion("grpc");'`.
* The type of transport being used (`grpc` or `rest`): See https://developers.google.com/google-ads/api/docs/client-libs/php/transport.

**Comment by michaelk1975** [comment]
Hi @PierrickVoulet ,
Sorry, I thought I provided it.
See below:

PHP version: HP 7.4.18 (cli) (built: May  3 2021 11:26:48) ( NTS )
The name and version of the operating system:  Linux saas-staging-161-20 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64
Protobuf command line returns nothing.
GRPC: 1.38.0
Type of transport: tried to specify both transport = "grpc" and transport = "rest" in google_ads_php.ini. When GRPC is sepcified, error is returned, so I suppose we are using rest.

**Comment by PierrickVoulet** [comment]
Thanks for providing the additional information. I think you are experiencing the same issue as https://github.com/googleads/google-ads-php/issues/414 so I am closing this issue. Feel free to comment here if you think it is a different issue.

**Comment by michaelk1975** [comment]
Thank you @PierrickVoulet ,

But grpc is installed in my case. 
"php -i | grep grpc" returns:
grpc
grpc support => enabled
grpc module version => 1.38.0
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value

I wonder what is missing so...
When I'm setting "transport=grpc" in google_ads_php.ini, I'm getting the following error:
"gRPC support has been requested but required dependencies have not been found. For details on how to install the gRPC extension please see https://cloud.google.com/php/grpc"

**Comment by PierrickVoulet** [comment]
Could you confirm that you added the line `extension=grpc.so` to the `php.ini` file?

**Comment by michaelk1975** [comment]
Yes, extension=grpc.so is enabled.
After I enabled it I started to get another error:
"gRPC support has been requested but required dependencies have not been found. For details on how to install the gRPC extension please see https://cloud.google.com/php/grpc"

Protobuf is in composer.json and is installed:

composer info | grep protobuf

returns:

google/protobuf                      v3.19.4   proto library for PHP

**Comment by PierrickVoulet** [comment]
I still suspect a misconfiguration. Could you execute the following to make sure your system picks a valid configuration?

```php
<?php
  echo extension_loaded('grpc') ? 'yes' : 'no';
  echo extension_loaded('protobuf') ? 'yes' : 'no';
?>
```

**Comment by michaelk1975** [comment]
Getting "no" and "no"
But according to error ("gRPC support has been requested but required dependencies have not been found") it seems like grpc is recognized, but some dependency is missing.

**Comment by michaelk1975** [comment]
Hi Pierrick,
I wonder what could cause grpc and protobuf to not be loaded... Both are returned when I'm running "php -m" command - I believe that it means that both extensions are installed properly. Please advise, what can I do (or check) to enable logging?

**Comment by PierrickVoulet** [comment]
> Hi Pierrick, I wonder what could cause grpc and protobuf to not be loaded... Both are returned when I'm running "php -m" command - I believe that it means that both extensions are installed properly. Please advise, what can I do (or check) to enable logging?

Difficult to say without having access to the environments. If you have multiple PHPs installed on the machine you may want to double check that the one you execute is the one where you installed and configured the `grpc` and `protobuf` extensions.
