### ISSUE TITLE
ENUM numbers to names 

### ISSUE THREAD

**Issue by pienx** [googleads/google-ads-php#754]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

Hi,

I would like to know how to get names instead of integer values when I select for example the Asset Type or an Ad Type and so on.

Here is my query as en example:
$query = "SELECT ad_group.name, ad_group_ad.ad.type FROM ad_group_ad WHERE campaign.advertising_channel_type = 'SEARCH' AND ad_group.status = 'ENABLED'";

I have a variable let's say: $adType = $googleAdsRow->getAdGroupAd()->getAd()->getType();

And I would like to echo not and integer buth the actual ad type (responsive search ad etc.)

Same for an extension
$query = 'SELECT asset.type FROM asset';
$asset = $googleAdsRow->getAsset()->getType();

Thanks a lot for your help!

Peter

**Comment by PierrickVoulet** [comment]
Hi @pienx - You can use helper functions for this. [Here](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/GetExpandedTextAds.php#L135) is an example with an ad group ad status.
