### ISSUE TITLE
Asset Type Enum to name

### ISSUE THREAD

**Issue by pienx** [googleads/google-ads-php#755]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

Hi there,

I have posted a question regarding the Asset types that return integers and I have seen the example regarding the Ad Group Ad Status [here](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/GetExpandedTextAds.php#L135) but I still can't get the TEXT value of an Asset Type with this helper:

AssetType::name($googleAdsRow->getAsset()->getType())

I have an error saying the Class does not exist.

How can I get the text value please and do we have a liste of these helper functions because I really don't get it :/

Thank you for your help!

**Comment by PierrickVoulet** [comment]
Hi @pienx,

You need to use the instruction below before calling `AssetType::name($googleAdsRow->getAsset()->getType())`.

```php
use Google\Ads\Googleads\V10\Enums\AssetTypeEnum\AssetType;
```

**Note:** You will need to change `V10` depending on the version you are using (could be `V7`, `V8`, `V9` or `V10`).

Thanks,
