### ISSUE TITLE
Can't retrieve campaign targeted languages

### ISSUE THREAD

**Issue by pienx** [googleads/google-ads-php#757]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

Hi,

I am trying to retrieve the targeted languages of my campaigns [like here](https://ibb.co/JFf2mfq).
It is the selected languages in the campaign paramètres.

 I would like to display campaign CAMPAIGN_NAME targets SELECTED_LANGUAGES_IN_PARAMETERS

I am trying with this query : 
SELECT language_constant.name, campaign.name FROM campaign_criterion WHERE campaign.advertising_channel_type = 'SEARCH'

and with:
$campaignName = $googleAdsRow->getCampaign()->getName();
$languages = $googleAdsRow->getLanguageConstant()->getName();

I get the languages of only 1 campaign and then I always have a fatal error of Call to a member function getName() on null.

I tried in many ways but I can't figure out and I also tried with SELECT ... FROM language_constant but in this case I can't get the campaign name from the GAQL query builder...

Could you help me please ?

Thank you very much !

**Comment by Kenimartonia** [comment]
OK thanks
