### ISSUE TITLE
 Fatal error: Uncaught Error: Class "Google\Ads\GoogleAds\Examples\Utils\ArgumentParser" not found in GetCampaigns.php

### ISSUE THREAD

**Issue by publish-web** [googleads/google-ads-php#760]
Hi everyone,

I'm facing an issue with Ads API. When I call GetCampaigns.php, I'm get this error :

Fatal error: Uncaught Error: Class "Google\Ads\GoogleAds\Examples\Utils\ArgumentParser" not found in /var/www/html/GetCampaigns.php:31 Stack trace: #0 /var/www/html/GetCampaigns.php(107): Google\Ads\GoogleAds\Examples\BasicOperations\GetCampaigns::main() #1 {main} thrown in /var/www/html/GetCampaigns.php on line 31

But it works well in command line with :
php examples/BasicOperations/GetCampaigns.php --customerId <YOUR_CUSTOMER_ID>

Anyone knows why ?

Thank you!

* Client library version: `v10`
* Google Ads API version: `v14.0.0`
 Ubuntu / PHP 8.0

**Comment by Kenimartonia** [comment]
Ok thanks and best regards

**Comment by PierrickVoulet** [comment]
Hi @publish-web,

The file you are reusing is an example that was developed to execute from command line only. To reuse its content in the context of your web application you will need to adapt it because of the development sources and dependencies it uses.

If you are interested by a similar example running as a web application, you can take a look at the [Laravel sample application](https://github.com/googleads/google-ads-php/tree/main/examples/LaravelSampleApp).

Thanks,

**Comment by publish-web** [comment]
Hi @PierrickVoulet

Thanks for your answer. I don't use Laravel but a custom web application. I couldn't find any example by following the link you gave me, sorry.

I currently use the Adwords API and want to migrate to the Ads API.

Is there some examples running as a web application ?

Thanks :)

**Comment by PierrickVoulet** [comment]
The only web application example we have is the [LaravelSampleApp](https://github.com/googleads/google-ads-php/tree/main/examples/LaravelSampleApp), you may want to check how the [controller](https://github.com/googleads/google-ads-php/blob/main/examples/LaravelSampleApp/app/Http/Controllers/GoogleAdsApiController.php) is implemented to learn how to use this library in this context.

To help you get started, here is a minimalist code example for your convenience. If should run successfully in your application if you already added this library as a dependency. It does the same thing as the code example `GetCampaigns` but feel free to change it to your convenience:

```php
use Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder;
use Google\Ads\GoogleAds\Lib\OAuth2TokenBuilder;

/** @var int $customerId Change this value to the customer ID to request campaigns for */
$customerId = null;
/** Change this value to the path of the Google Ads configuration file to use */
$googleAdsIniFilepath = '/path/to/google_ads_php.ini';

$oAuth2Credential = (new OAuth2TokenBuilder())
    ->fromFile($googleAdsIniFilepath)
    ->build();
$googleAdsClient = (new GoogleAdsClientBuilder())
    ->fromFile()
    ->withOAuth2Credential($oAuth2Credential)
    ->build();

$query = 'SELECT campaign.id, campaign.name FROM campaign ORDER BY campaign.id';
$googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
$stream = $googleAdsServiceClient->searchStream($customerId, $query);
foreach ($stream->iterateAllElements() as $googleAdsRow) {
    printf(
        "Campaign with ID %d and name '%s' was found.%s",
        $googleAdsRow->getCampaign()->getId(),
        $googleAdsRow->getCampaign()->getName(),
        PHP_EOL
    );
}
```

**Comment by PierrickVoulet** [comment]
Il est difficile de déterminer ce qui pourrait ne pas fonctionner sur votre configuration sans y avoir un accès direct. Autant que je sache, les étapes d'installation doivent être exactement les mêmes que celles que vous avez utilisées pour la bibliothèque d'AdWords.

Je ne pense pas que ce problème soit spécifique à notre bibliothèque, mais n'hésitez pas à nous faire savoir si vous trouvez quelque chose que nous faisons mal et nous vous aiderons!

**Comment by publish-web** [comment]
J'ai fini par trouver... En fait la librairie n'était pas bien installée via composer. Il fallait lancer la commande "composer require googleads/google-ads-php" pour qu'elle figure bien dans composer.json notamment.

Maintenant cela fonctionne !

Sauf erreur de ma part cela ne figure pas dans le "Getting started" de cette doc : https://github.com/googleads/google-ads-php (je précise que je ne suis pas très familiarisé avec l'utilisation de composer, ceci explique peut-être cela ^^)

En tout cas merci malgré tout pour votre aide ;)

**Comment by PierrickVoulet** [comment]
Merci d'avoir confirmé ce qui a résolu le problème ! Nous garderons un œil sur cela et nous modifierons la documentation si d'autres personnes rencontrent ce problème à l'avenir.
