### ISSUE TITLE
V14.0.0 Google\Ads\GoogleAds\Examples\Migration\RunExamples not working, dependency missing

### ISSUE THREAD

**Issue by clicks-meuser** [googleads/google-ads-php#761]
**Your client library and Google Ads API versions:**

* Client library version: `v10.0.0` -lib V10

* Google Ads API version: `v14.0.0`

**Your environment:**

* PHP 7.4.26 (cli) (built: Dec  2 2021 14:25:17) ( NTS )
* Linux application.local 5.15.19-2-rt29-MANJARO
* no protobuf extension
* no grpc extension
* no transport yet

**Description of the bug:**

the README.md tells to run composer install with a setup of requiring
* google-ads-php:^5.0.0
* googleads-php-lib:^41.0.0

google-ads-php/examples/Migration/RunExamplse.php requires
Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder which is not available in google-ads-php:^5.0.0

if i use v14.0.0 instead the RunExamples.php follow up is requiring
Google\Ads\GoogleAds\Examples\Utils\Helper which is missing in v14.0.0

**Steps to reproduce:**

run composer install in google-ads-php/examples/Migration like the README.md tells you
follow up with composer dump-autoload -o
fill in the credentials in the RunExamples.php file
execute RunExamples.php with `php RunExamples.php`

**Expected behavior:**

at least the required files should be available or the documentation should tell which version to use

**Request/Response Logs:**

With google-ads-php:v14.0.0

php RunExamples.php 

Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\Examples\Utils\Helper' not found in /var/www/html/web/google-ads-php/examples/Migration/CampaignManagement/CreateCompleteCampaignAdWordsApiOnly.php on line 118

Error: Class 'Google\Ads\GoogleAds\Examples\Utils\Helper' not found in /var/www/html/web/google-ads-php/examples/Migration/CampaignManagement/CreateCompleteCampaignAdWordsApiOnly.php on line 118

with google-ads-php:^v5.0.0

php RunExamples.php 

Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder' not found in /var/www/html/web/google-ads-php/examples/Migration/RunExamples.php on line 75

Error: Class 'Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder' not found in /var/www/html/web/google-ads-php/examples/Migration/RunExamples.php on line 75

**Comment by PierrickVoulet** [comment]
Hi @clicks-meuser and thank you for reporting this.

The PRs #762 and #763 should fix the issue, you can give it a try if you want.

**Comment by PierrickVoulet** [comment]
Both PRs were merged on the branch `main` so it should be fixed. Feel free to reopen this issue if you are still encountering issues.
