### ISSUE TITLE
Cannot select metrics top_impression_percentage in Ads API, but can select TopImpressionPercentage in AdWords API. Why?

### ISSUE THREAD

**Issue by giv13** [googleads/google-ads-php#765]
**Your client library and Google Ads API versions:**

* Client library version: `v14.0.0`

* Google Ads API version: `V10`

**Your environment:** PHP

**Your question:**

When I try to run the query `SELECT segments.date, metrics.cost_micros, metrics.impressions, metrics.clicks, metrics.ctr, metrics.average_cpc, metrics.top_impression_percentage FROM customer WHERE segments.date BETWEEN 20220221 AND 20220227`, I get an error `Cannot select or filter on the following metrics: 'top_impression_percentage'(could not support requested resources: 'CUSTOMER'), since metric is incompatible with the resource in the FROM clause or other selected segmenting resources.`. I'm currently transitioning from the AdWords API to the Ads API and I see that in the old API I could get the `TopImpressionPercentage` in the `ACCOUNT_PERFORMANCE_REPORT`. Why was this feature removed in the new API?

**Comment by PierrickVoulet** [comment]
Hi @giv13 - Your question is specific to the API (not this library). Please contact the [Google Ads API support](https://developers.google.com/google-ads/api/support), they will help.
