### ISSUE TITLE
How to remove tracking_url_template from a campaign

### ISSUE THREAD

**Issue by maicomevoi** [googleads/google-ads-php#766]
I have already asked in the Google Ads API forum and they told me to write here.

I tried it passing this arguments to fieldMask:
1.) 'tracking_url_template' => ""
2.) 'tracking_url_template' => null
but neither work.
How i can do this?

this is my example code:
        $resourceName = ResourceNames::forCampaign($client_customer_id, $camp->id_campaign);

        $campaign = new Campaign([
            'resource_name' => $resourceName,
            'tracking_url_template' => ""
        ]);

        $campaignOperation = new CampaignOperation();
        $campaignOperation->setRemove($campaign);
        $campaignOperation->setUpdateMask(FieldMasks::allSetFieldsOf($campaign));

        $campaignServiceClient = $googleAdsClient->getCampaignServiceClient();

        $response = $campaignServiceClient->mutateCampaigns(
            $client_customer_id,
            [$campaignOperation]
        );

Based on the code I wrote you could you tell me exactly how to remove the tracking url template?
Maybe a code example (template) to always use, then I adapt it to my code.
Also which methods to use and which instances?

Regards, Cristiano.

**Comment by PierrickVoulet** [comment]
Hi @maicomevoi - I think your issue is similar to another one we [answered](https://github.com/googleads/google-ads-php/issues/713#issuecomment-1009918882) in the past. Could you take a look and let us know if that does not help?

**Comment by maicomevoi** [comment]
Yes I'll try asap, I'll let you know if I can.
Thanks for the reply.

**Comment by maicomevoi** [comment]
Thank you very much, it work perfectly with the solution that you have mentioned.

In my opinion, it would be handy if in the future there was the possibility to pass a null or empty value to "remove" a field from the resource in question.

Thanks again for the help.
