### ISSUE TITLE
GenerateKeywordIdeaResult not return the keyword correctly

### ISSUE THREAD

**Issue by ziat1988** [googleads/google-ads-php#767]
In order to get the volume search by a keyword, I go with KeywordPlanIdeaServiceClient.
The idea is to get only the first result and ignore all other results as the ideas. This is fine with many cases. The problem is when I try with this keyword: "restaurant Français FREJUS", my function returns the volume of another keyword : "restaurant italien frejus" with volume = 390 as first result. 

This is not good for me. All I want is it gives me the 0 as in the old API before
What suprise me, is for some other keyword like "restaurant Méditérranéen FREJUS" it gives me correctly the keyword with volume=0

Is there any simple way to check in the result that volume comes with the "idea", not the keyword itself?

My implement in PHP:
```php
$requestOptionalArgs['keywordSeed'] = new KeywordSeed(['keywords' => ["restaurant Français FREJUS"]]);

        $keywordPlanIdeaServiceClient = $this->googleAdsClient->getKeywordPlanIdeaServiceClient();
        $response = $keywordPlanIdeaServiceClient->generateKeywordIdeas(
            [
                'pageSize'=>1, // only need the first result
                'language' => ResourceNames::forLanguageConstant("1002"), // code language french
                'customerId' => $this->clientCustomerId,
                KeywordPlanNetwork::GOOGLE_SEARCH
         
            ] + $requestOptionalArgs
        );
  $page = $response->getPage();
 foreach ($page->getIterator() as $key=>$result){
     // $result with "restaurant italien frejus" !?
  }
```
Thanks a lot

**Comment by fiboknacky** [comment]
As this is related with the API result rather than the client library itself, please post your question on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
