### ISSUE TITLE
Class EstimateKeywordTraffic google-ads-php

### ISSUE THREAD

**Issue by mnk85** [googleads/google-ads-php#771]
Hello All  !

I do the migration from The AdWords API to the Google Ads API.

I ask the dev forum for find the "new way" to use the class "EstimateKeywordTraffic"and i get this way "Generate Forecast Metrics".

so i follow the process and adapt the code to my project ( i use Laravel 6 ).

Now when i try to do my call of the "runExample" function (renamed to runkeywordplan in my code), i get :
Too few arguments to function Google\\Ads\\GoogleAds\\Lib\\V10\\GoogleAdsClient::__construct(), 0 passed in C:\\wamp64\\www\\app\\app\\Services\\EstimateKeywordTraffic3.php on line 348 and exactly 1 expected"  

Function :
```
    public static function main($data) {
        $config = base_path() . '/google_ads_php.ini';
        
        // Generate a refreshable OAuth2 credential for authentication.
        $oAuth2Credential = (new OAuth2TokenBuilder())
            ->fromFile($config)
            ->build();
        
        // Construct a Google Ads client configured from a properties file and the
        // OAuth2 credentials above.
        $googleAdsClient = (new GoogleAdsClientBuilder())
            ->fromFile($config)
            ->withOAuth2Credential($oAuth2Credential)
            ->build();
        
        return self::runkeywordplan(new GoogleAdsClient(), $googleAdsClient, $data);
      
    }
```
In my controller i call --> $results = EstimateKeywordTraffic3::main($data);

Do you know where is my mistake ?
For me it's very different of the precedent class and i need to do 2 things. First, change the code with the new class. Second adapt the code with my actual projet (Function in laravel 6)

Thanks in advance

**Comment by fiboknacky** [comment]
`GoogleAdsClient` in this library isn't meant to be constructed directly.
It looks like you build a new `GoogleAdsClient` correctly:

```php
        $googleAdsClient = (new GoogleAdsClientBuilder())
            ->fromFile($config)
            ->withOAuth2Credential($oAuth2Credential)
            ->build();
```

But you don't use it in:

```php
        return self::runkeywordplan(new GoogleAdsClient(), $googleAdsClient, $data);
```

So, in short, you need to change the above code to use the previously created `$googleAdsClient`.

I'd recommend reading the [README](https://github.com/googleads/google-ads-php/blob/main/README.md) and browse some code examples to get an idea of the library.
It's not super different from the old [SOAP library](https://github.com/googleads/googleads-php-lib), but that way, you may be able to ramp up more quickly.

**Comment by mnk85** [comment]
Thanks @fiboknacky . Clear and efficient.
Now i get a new error, i didn't understand why.
``` message: "Class 'App\Services\KeywordPlan' not found"` ```

`<?php

namespace App\Services;

use GetOpt\GetOpt;

use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSession;

use Google\Ads\GoogleAds\Lib\V10\GoogleAdsServerStreamDecorator;
use Google\Ads\GoogleAds\V10\Errors\GoogleAdsError;
use Google\Ads\GoogleAds\V10\Services\GoogleAdsRow;
use Google\ApiCore\ApiException;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\Ads\GoogleAds\Lib\OAuth2TokenBuilder;
use Google\Ads\GoogleAds\Lib\V10\GoogleAdsClient;
use Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder;
use Google\Ads\GoogleAds\Lib\V10\GoogleAdsException;

class EstimateKeywordTraffic3
{
    private static $customerId = 'mynumber';

// ******* File number 1 AddKeywordPlan.php
// Doc --> https://developers.google.com/google-ads/api/docs/keyword-planning/generate-forecast-metrics

public static function runkeywordplan(GoogleAdsClient $googleAdsClient, int $customerId)
{
    
    $keywordPlanResource = self::createKeywordPlan(
        $googleAdsClient,
        $customerId
    );

    $planCampaignResource = self::createKeywordPlanCampaign(
        $googleAdsClient,
        $customerId,
        $keywordPlanResource
    );

    $planAdGroupResource = self::createKeywordPlanAdGroup(
        $googleAdsClient,
        $customerId,
        $planCampaignResource
    );

    self::createKeywordPlanAdGroupKeywords(
        $googleAdsClient,
        $customerId,
        $planAdGroupResource
    );

    self::createKeywordPlanNegativeCampaignKeywords(
        $googleAdsClient,
        $customerId,
        $planCampaignResource
    );
}

/**
 * Creates a keyword plan.
 *
 * @param GoogleAdsClient $googleAdsClient the Google Ads API client
 * @param int $customerId the customer ID
 * @return string the newly created keyword plan resource
 */
private static function createKeywordPlan(
    GoogleAdsClient $googleAdsClient,
    int $customerId
) {
    // Creates a keyword plan.
    $keywordPlan = new KeywordPlan([
        'name' => 'Keyword plan for traffic estimate #' . Helper::getPrintableDatetime(),
        'forecast_period' => new KeywordPlanForecastPeriod([
            'date_interval' => KeywordPlanForecastInterval::NEXT_QUARTER
        ])
    ]);

    // Creates a keyword plan operation.
    $keywordPlanOperation = new KeywordPlanOperation();
    $keywordPlanOperation->setCreate($keywordPlan);

    // Issues a mutate request to add the keyword plan.
    $keywordPlanServiceClient = $googleAdsClient->getKeywordPlanServiceClient();
    $response = $keywordPlanServiceClient->mutateKeywordPlans(
        $customerId,
        [$keywordPlanOperation]
    );

    $resourceName = $response->getResults()[0]->getResourceName();
    printf("Created keyword plan: '%s'%s", $resourceName, PHP_EOL);

    return $resourceName;
}

/**
 * Creates the campaign for the keyword plan.
 *
 * @param GoogleAdsClient $googleAdsClient the Google Ads API client
 * @param int $customerId the customer ID
 * @param string $keywordPlanResource the keyword plan resource
 * @return string the newly created campaign resource
 */
private static function createKeywordPlanCampaign(
    GoogleAdsClient $googleAdsClient,
    int $customerId,
    string $keywordPlanResource
) {
    // Creates a keyword plan campaign.
    $keywordPlanCampaign = new KeywordPlanCampaign([
        'name' => 'Keyword plan campaign #' . Helper::getPrintableDatetime(),
        'cpc_bid_micros' => 1000000,
        'keyword_plan_network' => KeywordPlanNetwork::GOOGLE_SEARCH,
        'keyword_plan' => $keywordPlanResource,
    ]);

    // See https://developers.google.com/adwords/api/docs/appendix/geotargeting
    // for the list of geo target IDs.
    $keywordPlanCampaign->setGeoTargets([
        new KeywordPlanGeoTarget([
            'geo_target_constant' => ResourceNames::forGeoTargetConstant(2840) // USA
        ])
    ]);

    // See https://developers.google.com/adwords/api/docs/appendix/codes-formats#languages
    // for the list of language criteria IDs.
    // Set English as a language constant.
    $keywordPlanCampaign->setLanguageConstants([ResourceNames::forLanguageConstant(1000)]);

    // Creates a keyword plan campaign operation.
    $keywordPlanCampaignOperation = new KeywordPlanCampaignOperation();
    $keywordPlanCampaignOperation->setCreate($keywordPlanCampaign);

    $keywordPlanCampaignServiceClient =
        $googleAdsClient->getKeywordPlanCampaignServiceClient();
    $response = $keywordPlanCampaignServiceClient->mutateKeywordPlanCampaigns(
        $customerId,
        [$keywordPlanCampaignOperation]
    );

    $planCampaignResource = $response->getResults()[0]->getResourceName();
    printf("Created campaign for keyword plan: '%s'%s", $planCampaignResource, PHP_EOL);

    return $planCampaignResource;
}

/**
 * Creates the ad group for the keyword plan.
 *
 * @param GoogleAdsClient $googleAdsClient the Google Ads API client
 * @param int $customerId the customer ID
 * @param string $planCampaignResource the resource name of the campaign under which the
 *     ad group is created
 * @return string the newly created ad group resource
 */

private static function createKeywordPlanAdGroup(
    GoogleAdsClient $googleAdsClient,
    int $customerId,
    string $planCampaignResource
) {
    // Creates a keyword plan ad group.
    $keywordPlanAdGroup = new KeywordPlanAdGroup([
        'name' => 'Keyword plan ad group #' . Helper::getPrintableDatetime(),
        'cpc_bid_micros' => 2500000,
        'keyword_plan_campaign' => $planCampaignResource
    ]);

    // Creates a keyword plan ad group operation.
    $keywordPlanAdGroupOperation = new KeywordPlanAdGroupOperation();
    $keywordPlanAdGroupOperation->setCreate($keywordPlanAdGroup);

    $keywordPlanAdGroupServiceClient = $googleAdsClient->getKeywordPlanAdGroupServiceClient();
    $response = $keywordPlanAdGroupServiceClient->mutateKeywordPlanAdGroups(
        $customerId,
        [$keywordPlanAdGroupOperation]
    );

    $planAdGroupResource = $response->getResults()[0]->getResourceName();
    printf("Created ad group for keyword plan: '%s'%s", $planAdGroupResource, PHP_EOL);

    return $planAdGroupResource;
}

/**
 * Creates ad group keywords for the keyword plan.
 *
 * @param GoogleAdsClient $googleAdsClient the Google Ads API client
 * @param int $customerId the customer ID
 * @param string $planAdGroupResource the resource name of the ad group under which the
 *     keywords are created
 */
private static function createKeywordPlanAdGroupKeywords(
    GoogleAdsClient $googleAdsClient,
    int $customerId,
    string $planAdGroupResource
) {
    // Creates the ad group keywords for the keyword plan.
    $keywordPlanAdGroupKeyword1 = new KeywordPlanAdGroupKeyword([
        'text' => 'mars cruise',
        'cpc_bid_micros' => 2000000,
        'match_type' => KeywordMatchType::BROAD,
        'keyword_plan_ad_group' => $planAdGroupResource
    ]);

    $keywordPlanAdGroupKeyword2 = new KeywordPlanAdGroupKeyword([
        'text' => 'cheap cruise',
        'cpc_bid_micros' => 15000000,
        'match_type' => KeywordMatchType::PHRASE,
        'keyword_plan_ad_group' => $planAdGroupResource
    ]);

    $keywordPlanAdGroupKeyword3 = new KeywordPlanAdGroupKeyword([
        'text' => 'jupiter cruise',
        'cpc_bid_micros' => 1990000,
        'match_type' => KeywordMatchType::EXACT,
        'keyword_plan_ad_group' => $planAdGroupResource
    ]);

    $keywordPlanAdGroupKeywords =
        [$keywordPlanAdGroupKeyword1, $keywordPlanAdGroupKeyword2, $keywordPlanAdGroupKeyword3];

    // Creates an array of keyword plan ad group keyword operations.
    $keywordPlanAdGroupKeywordOperations = [];

    foreach ($keywordPlanAdGroupKeywords as $keyword) {
        $keywordPlanAdGroupKeywordOperation = new KeywordPlanAdGroupKeywordOperation();
        $keywordPlanAdGroupKeywordOperation->setCreate($keyword);
        $keywordPlanAdGroupKeywordOperations[] = $keywordPlanAdGroupKeywordOperation;
    }

    $keywordPlanAdGroupKeywordServiceClient =
        $googleAdsClient->getKeywordPlanAdGroupKeywordServiceClient();

    // Adds the keyword plan ad group keywords.
    $response = $keywordPlanAdGroupKeywordServiceClient->mutateKeywordPlanAdGroupKeywords(
        $customerId,
        $keywordPlanAdGroupKeywordOperations
    );

    /** @var KeywordPlanAdGroupKeyword $result */
    foreach ($response->getResults() as $result) {
        printf(
            "Created ad group keyword for keyword plan: '%s'%s",
            $result->getResourceName(),
            PHP_EOL
        );
    }
}

/**
 * Creates negative campaign keywords for the keyword plan.
 *
 * @param GoogleAdsClient $googleAdsClient the Google Ads API client
 * @param int $customerId the customer ID
 * @param string $planCampaignResource the resource name of the campaign under which
 *     the keywords are created
 */
private static function createKeywordPlanNegativeCampaignKeywords(
    GoogleAdsClient $googleAdsClient,
    int $customerId,
    string $planCampaignResource
) {
    // Creates a negative campaign keyword for the keyword plan.
    $keywordPlanCampaignKeyword = new KeywordPlanCampaignKeyword([
        'text' => 'moon walk',
        'match_type' => KeywordMatchType::BROAD,
        'keyword_plan_campaign' => $planCampaignResource,
        'negative' => true
    ]);

    $keywordPlanCampaignKeywordOperation = new KeywordPlanCampaignKeywordOperation();
    $keywordPlanCampaignKeywordOperation->setCreate($keywordPlanCampaignKeyword);

    $keywordPlanCampaignKeywordServiceClient =
        $googleAdsClient->getKeywordPlanCampaignKeywordServiceClient();

    // Adds the negative campaign keyword.
    $response = $keywordPlanCampaignKeywordServiceClient->mutateKeywordPlanCampaignKeywords(
        $customerId,
        [$keywordPlanCampaignKeywordOperation]
    );

    /** @var KeywordPlanCampaignKeyword $result */
    foreach ($response->getResults() as $result) {
        printf(
            "Created negative campaign keyword for keyword plan: '%s'%s",
            $result->getResourceName(),
            PHP_EOL
        );
    }
}   
    //File 2 GenerateForecastMetrics.php
    //Doc--> https://developers.google.com/google-ads/api/docs/keyword-planning/generate-forecast-metrics

    public static function GenerateForecastMetrics(
        GoogleAdsClient $googleAdsClient,
        int $customerId,
        int $keywordPlanId
    ) {
        $keywordPlanServiceClient = $googleAdsClient->getKeywordPlanServiceClient();

        // Issues a request to generate forecast metrics based on the specific keyword plan ID.
        $generateForecastMetricsResponse = $keywordPlanServiceClient->generateForecastMetrics(
            ResourceNames::forKeywordPlan($customerId, $keywordPlanId)
        );

        $i = 0;
        foreach ($generateForecastMetricsResponse->getKeywordForecasts() as $forecast) {
            /** @var KeywordPlanKeywordForecast $forecast */

            $metrics = $forecast->getKeywordForecast();
            printf(
                "%d) Keyword ID: %s%s",
                ++$i,
                $forecast->getKeywordPlanAdGroupKeyword(),
                PHP_EOL
            );
            printf(
                "Estimated daily clicks: %s%s",
                is_null($metrics->getClicks()) ? 'null'
                    : sprintf("%.2f", $metrics->getClicks()),
                PHP_EOL
            );
            printf(
                "Estimated daily impressions: %s%s",
                is_null($metrics->getImpressions())
                    ? 'null' : sprintf("%.2f", $metrics->getImpressions()),
                PHP_EOL
            );
            printf(
                "Estimated average cpc (micros): %s%s",
                is_null($metrics->getAverageCpc()) ? 'null' : $metrics->getAverageCpc(),
                PHP_EOL
            );
        }
    }

    public static function main($data) {
		$config = base_path() . '/google_ads_php.ini';
		
		// Generate a refreshable OAuth2 credential for authentication.
		$oAuth2Credential = (new OAuth2TokenBuilder())
			->fromFile($config)
			->build();
		
		// Construct a Google Ads client configured from a properties file and the
		// OAuth2 credentials above.
		$googleAdsClient = (new GoogleAdsClientBuilder())
			->fromFile($config)
			->withOAuth2Credential($oAuth2Credential)
			->build();
		
		return 
        //self::createKeywordPlan($googleAdsClient, $customerId);
        //self::createKeywordPlanCampaign($googleAdsClient, $customerId, $keywordPlanResource);
        //self::createKeywordPlanAdGroup($googleAdsClient, $customerId, $planCampaignResource);
        //self::createKeywordPlanAdGroupKeywords($googleAdsClient, $customerId, $planAdGroupResource);
        //self::createKeywordPlanNegativeCampaignKeywords($googleAdsClient, $customerId, $planCampaignResource);
        //self::GenerateForecastMetrics($googleAdsClient, $customerId, $keywordPlanId);
        
        self::runkeywordplan($googleAdsClient, self::$customerId);
        
	}

    //FIN DE LA CLASSE EstimateKeywordTraffic3
}`

**Comment by fiboknacky** [comment]
That file is actually drawn from the [code example](https://github.com/googleads/google-ads-php/blob/main/examples/Planning/AddKeywordPlan.php) in this repository.
Please consult that file and ensure you import all classes necessary via the `use` statements.

**Comment by mnk85** [comment]
Thanks again @fiboknacky !

I hope this will be my last question about the changement due to the migration.

Actually i get no error for all the 'AddKeywordPlan.php' file. My problem it's for the next operation "Generate the metrics".
In the exemple, we use "$keywordPlanId" but this variable dosen't exist.

I find another exemple here -->https://github.com/googleads/google-ads-php/blob/main/examples/Planning/GenerateForecastMetrics.php
with this 
```php
private const CUSTOMER_ID = 'INSERT_CUSTOMER_ID_HERE';
private const KEYWORD_PLAN_ID = 'INSERT_KEYWORD_PLAN_ID_HERE';
```

So my question how can i get the "KEYWORD_PLAN_ID"

For remember, this is what i do in my Main Function
```php
return
self::runkeywordplan($googleAdsClient, self::$customerId, $data);
self::GenerateForecastMetrics($googleAdsClient, self::$customerId, $keywordPlanId);
```
Thanks

**Comment by fiboknacky** [comment]
It's in the [file comment](https://github.com/googleads/google-ads-php/blob/main/examples/Planning/GenerateForecastMetrics.php#L36). You need to create a keyword plan first if you don't have one. You can use the **AddKeywordPlan** example to do so.

**Comment by mnk85** [comment]
euh i think i miss something. I already create all this :
![image](https://user-images.githubusercontent.com/42063484/160371091-f3fa59a3-0b6b-451d-9eed-66098a02404d.png)

So is not this ?

**Comment by fiboknacky** [comment]
The Keyword Plan ID is the last part of its [resource name](https://developers.google.com/google-ads/api/rest/design/resource-names?hl=en). 

It looks like you're not familiar much with the API, so I'd highly recommend visiting [this guide](https://developers.google.com/google-ads/api/docs/concepts/overview?hl=en) to get the concepts used in the Google Ads API first.
Feel free to drop a question about the API on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).

**Comment by fiboknacky** [comment]
1) [DateRange](https://developers.google.com/google-ads/api/reference/rpc/v10/DateRange) needs two fields `start_date` and `end_date`. You just need to set two fields like you set fields of other messages (e.g., `forecast_period`). They accept string.

2) `setGeoTargets ` accepts an array of `KeywordPlanGeoTarget` objects. You need to create those objects one by one and add it to an array. Then, assign it to the `setGeoTargets` like `$keywordPlanCampaign->setGeoTargets($arrayOfKeywordPlanGeoTargets)` if `$arrayOfKeywordPlanGeoTargets` is the array of those objects mentioned above.

**Comment by mnk85** [comment]
Hello, using the forecastmetrics with the keywordplan is ok if i use the interval but if i call it with a date range when i call this function it break
public static function GenerateForecastMetrics(
        GoogleAdsClient $googleAdsClient,
        int $customerId,
        int $keywordPlanId
    ) {
        global $keywordPlanId;

        $keywordPlanServiceClient = $googleAdsClient->getKeywordPlanServiceClient();
        
        // Issues a request to generate forecast metrics based on the specific keyword plan ID.
       
        $generateForecastMetricsResponse = $keywordPlanServiceClient->generateForecastMetrics(
            ResourceNames::forKeywordPlan($customerId, $keywordPlanId)
        );
 my customerId and keywordPlanId they are  ok if i create the keywordplan  with the date_interval i get through this call at generateForecastMetrics. and can print all the info from the docs.
but if i create the keywordplan with a date_interval the call to generateForecastMetrics fail. i don't understand could you help me please.
 i share here the pastebin of results and error messages from these two type of call.
the first one using date_interval https://pastebin.com/P9DvLiQY 
the second one with error using a date_range: https://pastebin.com/4xg3iwSS
