### ISSUE TITLE
'examples/AdvancedOperations/AddDisplayUploadAd.php' seems to result into MUTATE_NOT_ALLOWED

### ISSUE THREAD

**Issue by lanthopusx** [googleads/google-ads-php#772]
It seems that when we run 'examples/AdvancedOperations/AddDisplayUploadAd.php', we get a MUTATE_NOT_ALLOWED response.

We first run 'examples/BasicOperations/AddCampaigns.php' and then 'examples/BasicOperations/AddAdGroups.php' then provide generated adgroupid to AddDisplayUploadAd::runExample();

The error is thrown when reaching:
`
$adGroupAdResponse = $adGroupAdServiceClient->mutateAdGroupAds(
            $customerId,
            [$adGroupAdOperation]
        );
`

The following is logged by the exception handlers:

>[2022-03-22T13:58:19.528572+00:00] google-ads.NOTICE: Request
>-------
>Method Name: /google.ads.googleads.v10.services.AdGroupAdService/MutateAdGroupAds
>Host: googleads.googleapis.com
>Headers: {
>    "x-goog-api-client": "gl-php\/8.0.16 gccl\/14.0.0 gapic\/14.0.0 gax\/1.12.0 grpc\/1.42.0 rest\/1.12.0",
>    "x-goog-request-params": "customer_id=[REDACTED_CUSTOMER_ID]",
>    "developer-token": "REDACTED",
>    "login-customer-id": "1496918513"
>}
>Request: 
>{"customerId":"[REDACTED_CUSTOMER_ID]","operations":[{"create":{"status":"PAUSED","adGroup":"customers/[REDACTED_CUSTOMER_ID]/adGroups/133409207223","ad":{"finalUrls":["http://example.com/html5"],"name":"Ad for HTML5","displayUploadAd":{"displayUploadProductType":"HTML5_UPLOAD_AD","mediaBundle":{"asset":"customers/[REDACTED_CUSTOMER_ID]/assets/35514718815"}}}}}]}
>
>Response
>-------
>Headers: {
>    "request-id": "fGIZmZFv1uubPL_cjN7mfw",
>    "date": "Tue, 22 Mar 2022 13:58:15 GMT",
>    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
>}
>
>Fault
>-------
>Status code: 3
>Details: Request contains an invalid argument.
>Failure: {"errors":[{"errorCode":{"mutateError":"MUTATE_NOT_ALLOWED"},"message":"Mutates are not allowed for the requested resource.","location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"ad"}]}}],"requestId":"fGIZmZFv1uubPL_cjN7mfw"} 

When we replace the 'display_upload_ad' node with a valid 'responsive_search_ad' node the ads are created accordingly.

In that example we replaced:
`'display_upload_ad' => new DisplayUploadAdInfo([
                    'display_upload_product_type' => DisplayUploadProductType::HTML5_UPLOAD_AD,
                    'media_bundle' => new AdMediaBundleAsset(['asset' => $adAssetResourceName])
                ])`
with
`'responsive_search_ad' => new ResponsiveSearchAdInfo([
                    'headlines' => [
                        self::createAdTextAsset('headline_1_'),
                        self::createAdTextAsset('headline_2_'),
                        self::createAdTextAsset('headline_3_'),
                    ],
                    'descriptions' => [
                        self::createAdTextAsset('descr' . time()),
                        self::createAdTextAsset('descr2' . time()),
                        self::createAdTextAsset('descr3' . time()),
                    ],
                    'path1' => '',
                    'path2' => ''
                ])`

What are we missing/doing wrong here?

**Comment by PierrickVoulet** [comment]
Hi @lanthopusx - I do not reproduce. Could you double check that the group ID that you are using does actually exist for the customer? This issue seems related to the Google Ads API (not this library) so you should contact their [support](https://developers.google.com/google-ads/api/support), they will help you with this.
