### ISSUE TITLE
Summary Row is not return

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#774]
Your client library and Google Ads API versions:

Client library version: v14.0.0
Google Ads API version: V9
Your environment:
PHP Version => 7.4.14
System => Linux 4.15.0-142-generic https://github.com/googleads/google-ads-php/issues/146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64
The PHP Extension grpc is installed: 1.43.0
The PHP Extension protobuf is installed: 3.19.4

Hi,

I am not getting Summary Row for below query.

> SELECT campaign.name , campaign.status , metrics.clicks , metrics.impressions , metrics.ctr , metrics.conversions , metrics.cost_per_conversion , metrics.view_through_conversions , metrics.average_cpc , metrics.average_cpm , metrics.cost_micros , metrics.conversions_from_interactions_rate , metrics.search_impression_share FROM campaign WHERE metrics.impressions > 0 AND campaign.id IN (19191XX561) AND segments.date BETWEEN '2022-02-21' AND '2022-03-23'

Thanks,

**Comment by PierrickVoulet** [comment]
Hi @chiragvels - Could you provide us with some code to reproduce the failing request and some examples (request IDs or logs)?

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

"requestId": 
1yi5EMRUEbr1dgoohdUpTw
4uBVv5sj0lxTB7xprLW2mg

Code:
```

try {

            $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();

            $query = "SELECT campaign.name , campaign.status , metrics.clicks , metrics.impressions , metrics.ctr , metrics.conversions , metrics.cost_per_conversion , metrics.view_through_conversions , metrics.average_cpc , metrics.average_cpm , metrics.cost_micros , metrics.conversions_from_interactions_rate , metrics.search_impression_share FROM campaign WHERE metrics.impressions > 0 AND campaign.id IN (19191XX561) AND segments.date BETWEEN '2022-02-21' AND '2022-03-23'";
                $options = ['summaryRowSetting' => 3];
            
            $stream = $googleAdsServiceClient->searchStream($customerId, $query, $options);
            
            foreach ($stream->readAll() as $response) {
                   if ($response->hasSummaryRow()) {
                             //Do Response process
                     }
              }
        } catch (GoogleAdsException $googleAdsException) {
            throw $googleAdsException;
        } catch (ApiException $apiException) {
            throw $apiException;
        } 
```
$response->hasSummaryRow() is always getting false;

From Log I can see 2 response for same request: So I think response is wrong.

Log:

> [2022-03-23T22:23:16.302714+05:30] customReport.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v8.services.GoogleAdsService/SearchStream", CustomerId: XXX, RequestId: "4uBVv5sj0lxTB7xprLW2mg", IsFault: 0, FaultMessage: "None"  
> 
> [2022-03-23T22:23:16.303314+05:30] customReport.DEBUG: Request

> 
> -------
> Method Name: /google.ads.googleads.v8.services.GoogleAdsService/SearchStream
> Host: googleads.googleapis.com
> Headers: {
>     "x-goog-api-client": "gl-php\/7.1.33 gccl\/13.0.0 gapic\/13.0.0 gax\/1.11.4 grpc\/1.43.0 rest\/1.11.4",
>     "x-goog-request-params": "customer_id=XXX",
>     "developer-token": "REDACTED"
> }
> Request: 
> {"customerId":"XXX","query":"SELECT campaign.name\n                    , campaign.status\n                    , metrics.clicks\n                    , metrics.impressions\n                    , metrics.ctr\n                    , metrics.conversions\n                    , metrics.cost_per_conversion\n                    , metrics.view_through_conversions\n                    , metrics.average_cpc\n                    , metrics.average_cpm\n                    , metrics.cost_micros\n                    , metrics.conversions_from_interactions_rate\n                    , metrics.search_impression_share \n                FROM \n                    campaign \n                    WHERE metrics.impressions > 0 AND campaign.id IN (19191XX561)   AND segments.date BETWEEN '2022-02-21' AND '2022-03-23'","summaryRowSetting":"SUMMARY_ROW_WITH_RESULTS"}
> 
> Response
> -------
> Headers: {
>     "content-disposition": "attachment",
>     "date": "Wed, 23 Mar 2022 16:53:15 GMT",
>     "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
> }
> Response: 
> {"results":[{"campaign":{"resourceName":"customers/XXX/campaigns/1913XX61","name":"All Seasons Rent All","status":"ENABLED"},"metrics":{"averageCpc":1628459.2881355933,"averageCpm":158755945.14210179,"clicks":"295","conversionsFromInteractionsRate":0.10508474576271186,"conversions":31,"costMicros":"480395490","costPerConversion":15496628.709677419,"ctr":0.097488433575677463,"impressions":"3026","searchImpressionShare":0.099900000000000003,"viewThroughConversions":"0"}}],"fieldMask":"campaign.name,campaign.status,metrics.clicks,metrics.impressions,metrics.ctr,metrics.conversions,metrics.costPerConversion,metrics.viewThroughConversions,metrics.averageCpc,metrics.averageCpm,metrics.costMicros,metrics.conversionsFromInteractionsRate,metrics.searchImpressionShare","requestId":"4uBVv5sj0lxTB7xprLW2mg"} 
> 

> [2022-03-23T22:23:16.303410+05:30] customReport.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v8.services.GoogleAdsService/SearchStream", CustomerId: XXX, RequestId: "4uBVv5sj0lxTB7xprLW2mg", IsFault: 0, FaultMessage: "None"  
> [2022-03-23T22:23:16.303609+05:30] customReport.DEBUG: Request
> -------

> 
> Method Name: /google.ads.googleads.v8.services.GoogleAdsService/SearchStream
> Host: googleads.googleapis.com
> Headers: {
>     "x-goog-api-client": "gl-php\/7.1.33 gccl\/13.0.0 gapic\/13.0.0 gax\/1.11.4 grpc\/1.43.0 rest\/1.11.4",
>     "x-goog-request-params": "customer_id=XXX",
>     "developer-token": "REDACTED"
> }
> Request: 
> {"customerId":"XXX","query":"SELECT campaign.name\n                    , campaign.status\n                    , metrics.clicks\n                    , metrics.impressions\n                    , metrics.ctr\n                    , metrics.conversions\n                    , metrics.cost_per_conversion\n                    , metrics.view_through_conversions\n                    , metrics.average_cpc\n                    , metrics.average_cpm\n                    , metrics.cost_micros\n                    , metrics.conversions_from_interactions_rate\n                    , metrics.search_impression_share \n                FROM \n                    campaign \n                    WHERE metrics.impressions > 0 AND campaign.id IN (19191XX561)   AND segments.date BETWEEN '2022-02-21' AND '2022-03-23'","summaryRowSetting":"SUMMARY_ROW_WITH_RESULTS"}
> 
> Response
> -------
> Headers: {
>     "content-disposition": "attachment",
>     "date": "Wed, 23 Mar 2022 16:53:15 GMT",
>     "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
> }
> Response: 
> {"fieldMask":"campaign.name,campaign.status,metrics.clicks,metrics.impressions,metrics.ctr,metrics.conversions,metrics.costPerConversion,metrics.viewThroughConversions,metrics.averageCpc,metrics.averageCpm,metrics.costMicros,metrics.conversionsFromInteractionsRate,metrics.searchImpressionShare","summaryRow":{"metrics":{"averageCpc":1628459.2881355933,"averageCpm":158755945.14210179,"clicks":"295","conversionsFromInteractionsRate":0.10508474576271186,"conversions":31,"costMicros":"480395490","costPerConversion":15496628.709677419,"ctr":0.097488433575677463,"impressions":"3026","searchImpressionShare":0.099900000000000003,"viewThroughConversions":"0"}},"requestId":"4uBVv5sj0lxTB7xprLW2mg"}  
>
