### ISSUE TITLE
search and searchStream Usage question

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#779]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
Hi,
I have usage question.
1)
Once I use searchStream it will not read again?
For example.
```
try {
            $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
            $options = array('summaryRowSetting' => 3);
            $stream = $googleAdsServiceClient->searchStream($client_id, $query, $options);
            foreach ($stream->readAll() as $response) {
                  foreach ($response->getResults() as $result) {
                                 //This will give results as stream called first time
                                   echo "In Result Set";
                  }
            }
            foreach ($stream->readAll() as $response) {
                  if ($response->hasSummaryRow()) {
// This will not give any results as stream already called 
                                   echo "In Result Summary Set";
                  }
            }
        } catch (GoogleAdsException $googleAdsException) {
            throw $googleAdsException;
        } catch (ApiException $apiException) {
            throw $apiException;
        } 
```

This example will print "In Result Set", but never print **"In Result Summary Set"**
So stream once read it will never read again?

2) How I can get totalNumber of results count using searchStream?

Thanks,

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

No. That answer won’t help. 
As you can see from example I shared. I want to use stream twice.
One to get results and one time for summary row only.
So my question is 
1)once we use stream it was not available for second time to use?
2) I can not see no of records return by search stream. It only possible using search methods only?

Thanks

**Comment by PierrickVoulet** [comment]
In the comment I provided there is an example of how to both get the results and the summary row using a single `readAll` call:

```php
$stream = $googleAdsServiceClient->searchStream($customerId, $query, ['summaryRowSetting' => 3]);
foreach ($stream->readAll() as $response) {
    foreach ($response->getResults() as $result) {
        // Do something with each result
    }
    // Handle the summary row
    if ($response->hasSummaryRow()) {
        print $response->getSummaryRow()->getMetrics()->getClicks();
    }
}
```

1. Correct, it is not available for second time to use.
2. Not sure I understand your question.

**Comment by PierrickVoulet** [comment]
1. You are correct, the only option is to send new requests because there is no way to "reset" the stream.
2. With `searchStream` the only way to know the number of results is to loop through all of them and to increment a counter. This limitation is specific to the Google Ads API, not this library, this is because there is no field `total_results_count` in the [`SearchGoogleAdsStreamResponse`](https://developers.google.com/google-ads/api/reference/rpc/v10/SearchGoogleAdsStreamResponse) like there is in the [`SearchGoogleAdsResponse`](https://developers.google.com/google-ads/api/reference/rpc/v10/SearchGoogleAdsResponse).

**Comment by chiragvels** [comment]
Hi @PierrickVoulet ,

1) I mean read same result again. And not reset. 
2) Ok. Got it.
Thanks.

**Comment by PierrickVoulet** [comment]
1. Got it. I confirm, the only option is to send new requests.
