### ISSUE TITLE
Selecting field from campaign_budget via. campaign

### ISSUE THREAD

**Issue by gries** [googleads/google-ads-php#781]
Hi,
question is similar to this one https://github.com/googleads/google-ads-php/issues/642 

I want to select campaign_budget data linked to a campaign but how do I access the fields in this library?
```php
$query = 'SELECT campaign.name, campaign_budget.name FROM campaign';
$stream = $this->googleClient->getGoogleAdsServiceClient()->search(
    $this->customerId,
    $query,
    ['pageSize' => $this->pageSize]
);

foreach ($stream->getIterator() as $row) {
    // how do i get campaign_budget.name
    $row->getCampaign()->getCampaignBudgetName() // does not exist
    $row->getCampaign()->getCampaignBudget()->getName() // does not work as CampaignBudget is a string
    $row->getCampaign()->serializeToJsonString() // does NOT include campaign_budget.name
}
```

**Comment by PierrickVoulet** [comment]
Hi @gries - You need to use `$row->getCampaignBudget()->getName()` instead of `$row->getCampaign()->getCampaignBudget()->getName()`.

**Comment by gries** [comment]
Hi @PierrickVoulet thank you for the quick reply your solution works perfectly. :+1: :tada:
