### ISSUE TITLE
#782 re (Parser access)

### ISSUE THREAD

**Issue by luckiluf** [googleads/google-ads-php#783]
i re-open an issue cause i don't know why i can't reply to the answer of the issue #782

i have try to copy all files from example located in vendor/googleads/..... into my API, the require with vendor/autoload.php is good but i have the same problem of accessing to Parser whereas is present in example/utils with the right namespace.

for the moment i just want to test GetCampaigns.php using my docker CLI.

Sorry I'm a beginner so a lot of things are unclear to me...

**Comment by luckiluf** [comment]
update :  

I have re-installed the API with packagist and follow the steps from the guide.

I rewrite GetCampaigns in my API and includes class ArgumentParser/Name in this file.

Now its GetOpt class not found and i found it nowhere.

Thanks in advance.

**Comment by PierrickVoulet** [comment]
Hi @luckiluf - Your application needs to require the package `ulrichsg/getopt-php`. We require it as a dev package in this library because it is only used for code examples (see our [composer.json](https://github.com/googleads/google-ads-php/blob/main/composer.json#L18)).
