### ISSUE TITLE
PHP Get First Page Cpc Micros

### ISSUE THREAD

**Issue by mahirsumer** [googleads/google-ads-php#785]
I am using Google Ads API V10 PHP Libray. I'm trying to get the "ad_group_criterion.position_estimates.first_page_cpc_micros," metric. But I am getting null error. Where am I doing wrong?

Sample Query:
SELECT campaign.id, campaign.name, ad_group_criterion.keyword.text, ad_group_criterion.position_estimates.first_page_cpc_micros FROM keyword_view

PHP Sample:
$campaign_id = $googleAdsRow->getCampaign()->getId();
$campaign_name = $googleAdsRow->getCampaign()->getName();
$keyword = $googleAdsRow->getAdGroupCriterion()->getKeyword()->getText();
$first_page_cpc = $googleAdsRow->getAdGroupCriterion()->getPositionEstimates()->getFirstPageCpcMicros();

Error:
Fatal error: Uncaught Error: Call to a member function getFirstPageCpcMicros() on null in...

**Comment by PierrickVoulet** [comment]
Hi @mahirsumer - The query does not return any position estimates. It does not seem to be an issue with this library but the Google Ads API, you should contact their [support](https://developers.google.com/google-ads/api/support) to get help on this.
