### ISSUE TITLE
generateHistoricalMetrics with more than twelve month not work

### ISSUE THREAD

**Issue by FabiOPC84** [googleads/google-ads-php#787]
**Your client library and Google Ads API versions:**

* Client library version: `v14.0.0`

* Google Ads API version: `10`

**Your environment:**

**Description of the bug:**

I am using the APIs with both method: generateKeywordIdeas and generateHistoricalMetrics.
I noticed that only for the generateHistoricalMetrics, the HistoricalMetricsOptions is not considered to expand the date range.
The API always returns twelve months. As you can see inside the request is not set. Is it a bug?
From the documentation it should work for both methods https://developers.google.com/google-ads/api/reference/rpc/v10/GenerateHistoricalMetricsRequest.
No problem with generateKeywordIdeas. 

Part of code

           $historicalMetricsOptions = null;

           $start = new YearMonth(['year' => 2020, 'month' => 5]); //base 0
           $end = new YearMonth(['year' => date('Y'), 'month' => date('m')]);
           $yearMonthRange = new YearMonthRange(['start' => $start, 'end' => $end]);
           $historicalMetricsOptions = new HistoricalMetricsOptions(['year_month_range' => $yearMonthRange]);

           $keywordPlanIdeaServiceClient = $googleAdsClient->getKeywordPlanServiceClient();
           $response = $keywordPlanIdeaServiceClient->generateHistoricalMetrics(
                $keywordPlanResource, [], $historicalMetricsOptions
           );

**Request Logs:**

Method Name: /google.ads.googleads.v10.services.KeywordPlanService/GenerateHistoricalMetrics
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.4.13 gccl\/14.0.0 gapic\/14.0.0 gax\/1.12.0 grpc\/1.43.0 rest\/1.12.0",
    "x-goog-request-params": "keyword_plan=customers%2F******%2FkeywordPlans%2F******",
    "developer-token": "REDACTED"
}
Request: 
{"keywordPlan":"customers\/******\/keywordPlans\/******"}

**Response Logs:**

Headers: {
    "content-disposition": "attachment",
    "request-id": "******",
    "date": "Mon, 11 Apr 2022 10:05:14 GMT",
    "alt-svc": "******"
}
Response: 
{"metrics":[{"searchQuery":"noleggio auto","keywordMetrics":{"avgMonthlySearches":"135000","monthlySearchVolumes":[{"year":"2021","month":"MARCH","monthlySearches":"60500"},{"year":"2021","month":"APRIL","monthlySearches":"90500"},{"year":"2021","month":"MAY","monthlySearches":"165000"},{"year":"2021","month":"JUNE","monthlySearches":"246000"},{"year":"2021","month":"JULY","monthlySearches":"246000"},{"year":"2021","month":"AUGUST","monthlySearches":"201000"},{"year":"2021","month":"SEPTEMBER","monthlySearches":"165000"},{"year":"2021","month":"OCTOBER","monthlySearches":"135000"},{"year":"2021","month":"NOVEMBER","monthlySearches":"110000"},{"year":"2021","month":"DECEMBER","monthlySearches":"110000"},{"year":"2022","month":"JANUARY","monthlySearches":"110000"},{"year":"2022","month":"FEBRUARY","monthlySearches":"135000"}],"competition":"MEDIUM","competitionIndex":"62","lowTopOfPageBidMicros":"406708","highTopOfPageBidMicros":"1459408"}}]}

**Comment by FabiOPC84** [comment]
Hi @fiboknacky 
I had already opened the issues on that forum but Google said it is a problem related to the php library.
Looking the request you can see that historicalMetricsOptions is not sent but is set on my code.
Thanks

**Comment by fiboknacky** [comment]
Could you please share the link to your post?

**Comment by FabiOPC84** [comment]
@fiboknacky https://groups.google.com/g/adwords-api/c/4x4IEiXO298/m/9bo-Wy8cFAAJ
I continued the conversation via email. Here the reply:

"
Hello Fabio,

Thanks for replying back. Please note that our API team only addresses API related issues and concerns. Unfortunately, the existing code changing it’s not on our end to assist you. I would recommend reaching out to their PHP Client Library owner on using this  [PHP issue tracker](https://github.com/googleads/google-ads-php/issues).

However, the [YearMonthRange](https://developers.google.com/google-ads/api/reference/rpc/v10/YearMonthRange) for historical metrics and inclusive of the start and end months. If not specified the searches will be returned for the past 12 months. Searches data is available for the past 4 years. If the search volume is not available for the entire year_month_range provided, the subset of the year month range for which search volume is available will be returned. Hope this information helps.

Best regards,
"

**Comment by fiboknacky** [comment]
OK. You actually uses the method wrongly. Please take a look at [the method signature](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V10/Services/Gapic/KeywordPlanServiceGapicClient.php#L465).

From the signature, you need to specify the historical metric options in an array like this:

```php
       $response = $keywordPlanIdeaServiceClient->generateHistoricalMetrics(
            $keywordPlanResource, ['historicalMetricsOptions' => $historicalMetricsOptions]
       );

```

**Comment by FabiOPC84** [comment]
Thanks a lot @fiboknacky . it works
