### ISSUE TITLE
GoogleAdsException not caching UNAUTHENTICATED accounts with getCustomer service 

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#79]
Hello,

I am writing this post separately as suggested over [here](https://groups.google.com/d/topic/adwords-api/6Y6GHSiNKEA/discussion).
I was getting UNAUTHENTICATED error for a valid customerId when I ran a getCustomer service, which is based on list of account received from ListAllAccounts service.
I have around 20 accounts there which was listed from ListAccesibleCustomers service. I just wanted to list out all the accounts that can be managed by my main MCC account.

To do this process I need to cache the UNAUTHENTICATED error, but seems like GoogleAdsException is not caching those errors.

Code is like this.

       
```
$customerServiceClient = $googleAdsClient->getCustomerServiceClient();
$accessibleCustomers = $customerServiceClient->listAccessibleCustomers();


        foreach ($accessibleCustomers->getResourceNames() as $resourceName) {
            
            try {
                $customer = $customerServiceClient->getCustomer($resourceName);
                $customerId = ($customer->getId() != '') ? $customer->getId()->getValue() : '';
            } catch (GoogleAdsException $e) {
                throw $e;
            }
        }
```

Please note earlier I was able to get all the listed accounts with same code, but now It is not.

```
function getAllCustomers() {
    $customerServiceClient = $googleAdsClient->getCustomerServiceClient();
    $accessibleCustomers = $customerServiceClient->listAccessibleCustomers();
    foreach ($accessibleCustomers->getResourceNames() as $resourceName) {
        $customer = $customerServiceClient->getCustomer($resourceName);
        $customerId = ($customer->getId() != '') ? $customer->getId()->getValue() : '';
        $this->getCustomersFromCustomerId($customerId);
    }
}


function getCustomersFromCustomerId($customerId) {
    $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
    $query = 'SELECT customer_client.resource_name,
                customer_client.client_customer,
                customer_client.level,
                customer_client.hidden,
                customer_client.level
                FROM customer_client';
    $response = $googleAdsServiceClient->search($customerId, $query, ['pageSize' => self::PAGE_SIZE]);
    foreach ($response->iterateAllElements() as $googleAdsRow) {
        printf(
                "Customer ResourceName '%s', isHidden %d, Level %d and clientCustomer '%s' was found.%s", $googleAdsRow->getCustomerClient()->getResourceName(), $googleAdsRow->getCustomerClient()->getHidden()->getValue(), $googleAdsRow->getCustomerClient()->getLevel()->getValue(), $googleAdsRow->getCustomerClient()->getClientCustomer()->getValue(), PHP_EOL
        );
    }
}

```

Thanks,

**Comment by fiboknacky** [comment]
Hello Chirag,

Sorry for this inconvenience.
Based on what you said, do you mean UNAUTHENTICATED is thrown as part of other exception class, not GoogleAdsException? Could you please tell us what it looks like?

The only workaround for now would be trying to catch this exception, until we fix the root cause, i.e., either not returning canceled or drafted accounts from `listAccessibleCustomers()` or having a way for the users to tell what accounts are in those states.

Best,
Knack

**Comment by chiragvels** [comment]
Hello Knack,

I was using try cache as mentioned above, and If any error comes it will still go through all the records and error should be cache.
But instead that the process stopped by giving error as below.
This time I got this error but 4 days back it was UNAUTHENTICATED error.

Google Ads failure details:
	authorization_error: The customer can't be used because it isn't enabled.

Thanks,

**Comment by fiboknacky** [comment]
Could you please give me example CIDs that resulted in that error?
I'll remove the CIDs once I see them.
Alternatively, you could send them to googleadsapi-support@google.com and mention this issue number.

Thank you!

**Comment by chiragvels** [comment]
> Could you please give me example CIDs that resulted in that error?

I have sent the CIDs to email googleadsapi-support@google.com

> I'll remove the CIDs once I see them?
I am not getting here? I can see those CIDs under the MCC account, but through API it is not giving getCustomer service info.

**Comment by fiboknacky** [comment]
> I am not getting here? I can see those CIDs under the MCC account, but through API it is not giving getCustomer service info.

Never mind about this. I just meant that you can send the CIDs here too, but it's much better to send via the email address.

**Comment by fiboknacky** [comment]
Hi Chirag,

Really sorry for the delay. We're all swamped with other urgent tasks at hand.

I've confirmed the CIDs you've sent and cannot reproduce the original error you've got.
All are returned as Google Ads failure now.

Please don't hesitate to let us know if this issue re-occur.

Best,
Knack
