### ISSUE TITLE
AdvertisingChannelType Enum value missing

### ISSUE THREAD

**Issue by bitsbauer** [googleads/google-ads-php#790]
**Your client library and Google Ads API versions:**

* Client library version: `v14.0.0`

* Google Ads API version: `V10`

**Your environment:** -

**Description of the bug:** Enum value for AdvertisingChannelType is missing in this file: src/Google/Ads/GoogleAds/V10/Enums/AdvertisingChannelTypeEnum/AdvertisingChannelType.php

Description page lists a value for DISCOVERY (Discovery campaigns) -> 
https://developers.google.com/google-ads/api/reference/rpc/v10/AdvertisingChannelTypeEnum.AdvertisingChannelType

This value is missing in the file listed above ...

**Steps to reproduce:** -

**Expected behavior:** -

**Request/Response Logs:** -
 
**Anything else we should know about your project / environment:** -

**Comment by fiboknacky** [comment]
We've not released a new version that will include that change yet.
This should be done in a few days.

**Comment by juliorafaelr** [comment]
I got the same issue but for a different file 

Description of the bug: Enum value for AdType is missing in this file: src/Google/Ads/GoogleAds/V10/Enums/AdTypeEnum/AdType.php

`UnexpectedValueException
Enum Google\Ads\GoogleAds\V10\Enums\AdTypeEnum\AdType has no name defined for value 35`

**Comment by fiboknacky** [comment]
Please try the [latest release](https://github.com/googleads/google-ads-php/releases/tag/v15.0.0).
