### ISSUE TITLE
get keyword text from click_view

### ISSUE THREAD

**Issue by Gilakiva3** [googleads/google-ads-php#792]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
i try to get the keyword text but i  dont get the keyword text.
what the function i need to use to see the keyword text ? 
i use $click_view->getKeyword()

  $query =
            "SELECT "
            . "click_view.gclid, "
            . "click_view.keyword, "
            . "click_view.keyword_info.text,"
            . "click_view.keyword_info.match_type,"
            . "ad_group.id,"
            . "ad_group.name,"
            . "campaign.id,"
            . "campaign.name, "
            . "segments.click_type,"
            . "segments.date "
            . "FROM click_view "
            . "WHERE segments.date DURING YESTERDAY and click_view.gclid = '$gclid' "
            . "LIMIT 5";

        $result = [];

        $stream = $googleAdsServiceClient->searchStream(
            $accountId,
            $query
        );

//        print($query.PHP_EOL);

        foreach ($stream->iterateAllElements() as $googleAdsRow) {
            echo 'check' . PHP_EOL;

            /** @var GoogleAdsRow $googleAdsRow */
            $campaign = $googleAdsRow->getCampaign();
            $adGroup = $googleAdsRow->getAdGroup();
            $adGroupCriterion = $googleAdsRow->getAdGroupCriterion();
            $metrics = $googleAdsRow->getMetrics();
            $click_view = $googleAdsRow->getClickView();
            $segments = $googleAdsRow->getSegments();
            $keywordUrl = $click_view->getKeyword();
            $result = [
                $click_view->getKeyword(),
                $click_view->getGclid(),
                $adGroup->getName(),
                $adGroup->getId(),
                $campaign->getName(),
                $segments->getDate()
            ];

            self::log('Google-Ads',"Keyword text  with ".$click_view->getKeyword()."\n"
                . "Gclid  ".$click_view->getGclid()."\n"
                . "AD Group Name -  ".$adGroup->getName()."\n"
                . "AD Group ID - ".$adGroup->getId()."\n"
                . "Campaign Name   ".$campaign->getName()."\n"
                . "Date ".$segments->getDate()."\n");

**Comment by PierrickVoulet** [comment]
Hi @Gilakiva3 - Not all clicks are associated to a keyword (see [documentation](https://developers.google.com/google-ads/api/fields/v10/click_view#click_view.keyword)). This issue is related to Google Ads API usage (not this library), please contact their [support](https://developers.google.com/google-ads/api/support).
