### ISSUE TITLE
OOB deprecation / OAuth2 / This SDK

### ISSUE THREAD

**Issue by marconett** [googleads/google-ads-php#799]
Google recently send us an email with the information that OAuth out-of-band (OOB) flow will be deprecated and "_Our records indicate you have OAuth clients that used the OAuth OOB flow in the past._", linking to the OAuth client that our google-ads-php project is exclusively using.

We are currently using this SDK in version 15.0. To authenticate, I follow the README and use `GenerateUserCredentials.php` to get a refreshToken ONCE on my workstation. I then put this token inside the google_ads_php.ini on my server and use it to access the API via my server-side production application.

The OAuth 2.0-Client-ID I have in my Google Cloud Platform Console is of type "Desktop".

Neither the email I received, nor the [blog post](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html) linked in that email make it clear how this relates to the authentication method used in this SDK and how I need to react (if at all). So far, the Google Ads API support was not able provide a useful answer (https://groups.google.com/u/2/g/adwords-api/c/Vxlig2rTIxU).

I now consider this a problem with this SDK and not the Ads API, as this SDK provides a single way to authenticate with the API ([GenerateUserCredentials](https://github.com/googleads/google-ads-php/blob/HEAD/examples/Authentication/GenerateUserCredentials.php)).

Do I need to change something?

**Comment by PierrickVoulet** [comment]
Hi @marconett - Both the example `GenerateUserCredentials` and the related [guide](https://developers.google.com/google-ads/api/docs/client-libs/php/oauth-web) were recently updated to reflect the OOB flow deprecation. You should be all set if you use these resources.
