### ISSUE TITLE
Where do I get php_protobuf.dll

### ISSUE THREAD

**Issue by tarpindersingh** [googleads/google-ads-php#800]
Where do I get php_protobuf.dll for windows 10.

**Comment by PierrickVoulet** [comment]
Hi @tarpindersingh - This library does not own protobuf. Please check this [GitHub repository](https://github.com/protocolbuffers/protobuf) instead. From there you can rely on the provided [installation instructions](https://github.com/protocolbuffers/protobuf#protobuf-runtime-installation) or [contact the developers for more information](https://github.com/protocolbuffers/protobuf/issues/new/choose).
