### ISSUE TITLE
Get Country,Region and Metro id's or names per campaign id 

### ISSUE THREAD

**Issue by KaustubhDalal** [googleads/google-ads-php#802]
I have some more queries regarding the client library as below :

1. In Daily reporting I am trying to fetch metrics.view_though_conversions, which method should I use to get its value.
- also how can I fetch the value of completed views in the geographic or user location view? 

2. I am able to get all required data with customer ids but now I am going to fetch geographic data like impressions, clicks, conversions, country id, region/state/province id, metro id, or names. 
I have gone through [UserLocationView](https://developers.google.com/google-ads/api/fields/v10/user_location_view) and [Geographic_view](https://developers.google.com/google-ads/api/fields/v10/geographic_view) documentation and tried to make queries to fetch country, region, and metro ids but not getting how to iterate GoogleRows object or which stat functions should I use to get the impression we have getImpression() like that for a country which function should I use to get its value or id.

like below i am using :
foreach ($response->iterateAllElements() as $googleAdsRow) {
                $campaign = $googleAdsRow->getCampaign();
                $adGroup = $googleAdsRow->getAdGroup();
                $adGroupCriterion = $googleAdsRow->getAdGroupCriterion();
                $metrics = $googleAdsRow->getMetrics();

how can I fetch geo data for region and country and metros?

can you please suggest to me an example of how can I iterate query responses in rows?

**Comment by fiboknacky** [comment]
> also how can I fetch the value of completed views in the geographic or user location view?

What do you mean by "value of completed views"?

> I have gone through [UserLocationView](https://developers.google.com/google-ads/api/fields/v10/user_location_view) and [Geographic_view](https://developers.google.com/google-ads/api/fields/v10/geographic_view) documentation and tried to make queries to fetch country, region, and metro ids but not getting how to iterate GoogleRows object or which stat functions should I use to get the impression we have getImpression() like that for a country which function should I use to get its value or id.

We have a [code example](https://github.com/googleads/google-ads-php/blob/main/examples/Reporting/GetKeywordStats.php#L131) for this. You can refer to how to reiterate over Google Ads rows there.

When you call `$metrics = $googleAdsRow->getMetrics();`, `$metrics` should contain all the metrics available from your request, including `view_though_conversions`.

**Comment by fiboknacky** [comment]
Closing due to the inactivity.
