### ISSUE TITLE
PERMISSION_DENIED error with PHP google ads library 

### ISSUE THREAD

**Issue by vysakhgkrishnan** [googleads/google-ads-php#804]
I am using php client library to get the ads data and i have configured all my data/credentials (loginCustomerId,clientId,clientSecret,refreshToken)in the google_ads_php_ini file as per documentation.

But still I am getting the below error.

ApiException was thrown with message '{ "message": "The caller does not have permission", "code": 7, "status": "PERMISSION_DENIED", "details": [ { "@type": "[type.googleapis.com](http://type.googleapis.com/)\/google.ads.googleads.v10.errors.GoogleAdsFailure", "errors": [ { "errorCode": { "authorizationError": "USER_PERMISSION_DENIED" }, "message": "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id'

I have already set the customer id in the ini config file.

should i do anything on the account level?
Thanks in advance.

**Comment by fiboknacky** [comment]
As it's an error from the Google Ads API server, could you please ask in [this forum](https://groups.google.com/g/adwords-api)? Thank you.
