### ISSUE TITLE
Protobuf extension not found error in PHP >= 7.4

### ISSUE THREAD

**Issue by cgvaghela** [googleads/google-ads-php#805]
Hello Guys,

I am trying to get protobuf in google-ads-php.
When I fire this command "composer install / composer update".
It's getting error. I shared screen-shot.
I need all metrics object key.
For Ex: How can I get 'metrics.video_quartile_p25_rate' this one.
video_quartile need protobuf.

Thank you
![protobuf-error](https://user-images.githubusercontent.com/32707767/171183520-3bf1dc72-753a-4ae5-ae38-70c9b8b4556f.png)
![protobuf-lib](https://user-images.githubusercontent.com/32707767/171183528-3c00b5c3-446c-4a4b-9089-96bfab7d7b3b.png)

**Comment by fiboknacky** [comment]
You need a protobuf extension. Please read [this guide](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf) and [Requirements](https://github.com/googleads/google-ads-php#requirements) first.

**Comment by fiboknacky** [comment]
About the specific protobuf extension file, please see #800.
