### ISSUE TITLE
How to get error code instead of code's description

### ISSUE THREAD

**Issue by leolll** [googleads/google-ads-php#809]
In the [HandlePartialFailure.php](https://github.com/googleads/google-ads-php/blob/1378e99f0981b418ec232b01eb55b4529b0a5752/examples/ErrorHandling/HandlePartialFailure.php#L217) example code (line 217) it shows how to get the error message.  How do I get the error code instead?

For example, I can get this error message:
`The click associated with the given identifier or iOS URL parameter is either too old to be imported or occurred outside of the click through lookback window for the specified conversion action.`

But I want this error code: 
`EXPIRED_EVENT `

Example [ConversionUploadError](https://developers.google.com/google-ads/api/reference/rpc/v10/ConversionUploadErrorEnum.ConversionUploadError)

**Comment by PierrickVoulet** [comment]
Hi @leolll - You could use the following instruction to gather the name of the `ConversionUploadError` being returned:

```php
use Google\Ads\GoogleAds\V10\Errors\ConversionUploadErrorEnum\ConversionUploadError;

// ...

ConversionUploadError::name($error->getErrorCode()->getConversionUploadError());
```
