### ISSUE TITLE
The urls fields are empty

### ISSUE THREAD

**Issue by Jejec** [googleads/google-ads-php#813]
Hello,

Please don't close the ticket because it's impossible to reopen which I created initially and didn't deserve such a quick closure.

I actually did not report in my previous post, but I have already contacted google ads support with whom we have carried out several tests and there is no problem on their side. When I make requests directly to the API, so without using the "googleads/google-ads-php" library, I retrieve the urls correctly.

So I'm reposting a copy of my original message.

Hello,

Following the change of library announced by google adwords we used googleads/google-ads-php but we encountered some problems for the recovery of urls. All fields that must contain urls are empty.

ad_group_ad.ad.display_url,
ad_group_ad.ad.final_urls,
ad_group_ad.ad.final_mobile_urls,
ad_group_ad.ad.final_app_urls

However, when we go to the interface, we have many urls. We made requests directly via the ads API and we actually retrieve urls.
We therefore assume that there would be a problem with the library. Perhaps the problem comes from the use of this one.
We make a connection via the following code:

$this->OAuth2 = (new OAuth2TokenBuilder()) ->withClientId($this->getConfigApi('CONFIG_GAPI_CLIENT_ID', $subsidiaryId)) ->withClientSecret($this->getConfigApi('CONFIG_GAPI_CLIENT_SECRET', $subsidiaryId)) ->withRefreshToken($this->getConfigApi('CONFIG_GAPI_REFRESH_TOKEN', $subsidiaryId)) ->build();

Followed by :

(new GoogleAdsClientBuilder()) ->withOAuth2Credential($this->getOAuth2($subsidiaryId)) ->withDeveloperToken($this->getConfigApi('CONFIG_GAPI_DEVELOPER_TOKEN', $subsidiaryId)) ->withLoginCustomerId($this->getConfigApi('CONFIG_GAPI_MCC_GOOGLE_ID', $subsidiaryId)) ->build();

We then perform a request via the getGoogleAdsServiceClient() method then searchStream($googleId, $query).
We list the elements via a foreach and the iterateAllElements() method.

However, we recover all the data except the urls which makes us think of a bug.

Regards,
Jérôme Cauz

**Comment by fiboknacky** [comment]
Could you please share the forum post that you communicated with the Google Ads API support?

**Comment by Jejec** [comment]
Hello,

For Google Ads API support, everything was done by email.

For the code, here it is:

```
public function getOAuth2($subsidiaryId)
{
	if(!$this->OAuth2) {
		$this->OAuth2 = (new OAuth2TokenBuilder())
			->withClientId($this->getConfigApi('CONFIG_GAPI_CLIENT_ID', $subsidiaryId))
			->withClientSecret($this->getConfigApi('CONFIG_GAPI_CLIENT_SECRET', $subsidiaryId))
			->withRefreshToken($this->getConfigApi('CONFIG_GAPI_REFRESH_TOKEN', $subsidiaryId))
			->build();
	}

	return $this->OAuth2;
}


public function getServiceClient($subsidiaryId)
{
	return (new GoogleAdsClientBuilder())
		->withOAuth2Credential($this->getOAuth2($subsidiaryId))
		->withDeveloperToken($this->getConfigApi('CONFIG_GAPI_DEVELOPER_TOKEN', $subsidiaryId))
		->withLoginCustomerId($this->getConfigApi('CONFIG_GAPI_MCC_GOOGLE_ID', $subsidiaryId))
		->build();
}


$query = "
SELECT 
	ad_group_ad.ad.id,
	ad_group_ad.ad.type,
	ad_group_ad.status,
	ad_group_ad.ad.display_url,
	ad_group_ad.ad.final_urls,
	ad_group_ad.ad.final_mobile_urls,
	ad_group_ad.ad.final_app_urls,
	ad_group_ad.ad.text_ad.headline,
	ad_group_ad.ad.text_ad.description1,
	ad_group_ad.ad.text_ad.description2,
	ad_group_ad.ad.call_ad.description1,
	ad_group_ad.ad.call_ad.description2,
	ad_group_ad.ad.expanded_text_ad.description,
	ad_group_ad.ad.expanded_text_ad.description2,
	ad_group_ad.ad.expanded_text_ad.headline_part1,
	ad_group_ad.ad.expanded_text_ad.headline_part2,
	ad_group_ad.ad.expanded_text_ad.headline_part3,
	ad_group_ad.ad.legacy_responsive_display_ad.description,
	ad_group_ad.policy_summary.approval_status,
	ad_group.id,
	metrics.clicks,
	metrics.impressions,
	metrics.cost_micros,
	metrics.conversions,
	metrics.average_cpc,
	campaign.id
FROM ad_group_ad
";

$googleAdsServiceClient = $this->authGoogle->getServiceClient($subsidiaryId)->getGoogleAdsServiceClient();
$stream = $googleAdsServiceClient->searchStream($googleId, $query);

$adGroupAds = [];
/** @var GoogleAdsRow $googleAdsRow */
foreach ($stream->iterateAllElements() as $googleAdsRow) {
	$policyTopicEntriesTab = [];
	$approvalStatus = null;
	if($googleAdsRow->getAdGroupAd()->hasPolicySummary()) {
		$policySummary = $googleAdsRow->getAdGroupAd()->getPolicySummary();
		$approvalStatus = $policySummary->getApprovalStatus();
		if($policySummary->getPolicyTopicEntries()) {
			foreach($policySummary->getPolicyTopicEntries() as $policyTopicEntries) {
				$policyTopicEvidencesTab = [];
				if($policyTopicEntries->getPolicyTopicEvidences()) {
					foreach($policyTopicEntries->getPolicyTopicEvidences() as $policyTopicEvidences) {
						$policyTopicEvidencesTab[] = [
							'policyTopicEvidenceType' => $policyTopicEvidences->getPolicyTopicEvidenceType(),
							'evidenceTextList' => $policyTopicEvidences->getEvidenceTextList()
						];
					}
				}
				$policyTopicEntriesTab[] = [
					'policyTopicName' => $policyTopicEntries->getPolicyTopicName(),
					'policyTopicEvidences' => $policyTopicEvidencesTab
				];
			}
		}
	}

	$adGroupAds[] = [
		'id' => $googleAdsRow->getAdGroupAd()->getAd()->getId(),
		'type' => (in_array('type', $getName)) ? AdTypeEnum\AdType::name($googleAdsRow->getAdGroupAd()->getAd()->getType()) : $googleAdsRow->getAdGroupAd()->getAd()->getType(),
		'status' => (in_array('status', $getName)) ? AdGroupAdStatus::name($googleAdsRow->getAdGroupAd()->getStatus()) : $googleAdsRow->getAdGroupAd()->getStatus(),
		'displayUrl' => $googleAdsRow->getAdGroupAd()->getAd()->getDisplayUrl(),
		'finalUrls' => $googleAdsRow->getAdGroupAd()->getAd()->getFinalUrls(),
		'finalMobileUrls' => $googleAdsRow->getAdGroupAd()->getAd()->getFinalMobileUrls(),
		'finalAppUrls' => $googleAdsRow->getAdGroupAd()->getAd()->getFinalAppUrls(),
		'textAdHeadline' => $googleAdsRow->getAdGroupAd()->getAd()->hasTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getTextAd()->getHeadline() : '',
		'textAdDescription1' => $googleAdsRow->getAdGroupAd()->getAd()->hasTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getTextAd()->getDescription1() : '',
		'textAdDescription2' => $googleAdsRow->getAdGroupAd()->getAd()->hasTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getTextAd()->getDescription2() : '',
		'callAdDescription1' => $googleAdsRow->getAdGroupAd()->getAd()->hasCallAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getCallAd()->getDescription1() : '',
		'callAdDescription2' => $googleAdsRow->getAdGroupAd()->getAd()->hasCallAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getCallAd()->getDescription2() : '',
		'expandedTextAdDescription' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getDescription() : '',
		'expandedTextAdDescription2' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getDescription2() : '',
		'expandedTextAdHeadlinePart1' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getHeadlinePart1() : '',
		'expandedTextAdHeadlinePart2' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getHeadlinePart2() : '',
		'expandedTextAdHeadlinePart3' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getHeadlinePart3() : '',
		'legacyResponsiveDisplayAdDescription' => $googleAdsRow->getAdGroupAd()->getAd()->hasLegacyResponsiveDisplayAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getLegacyResponsiveDisplayAd()->getDescription() : '',
		'policySummary' => [
			'approvalStatus' => $approvalStatus,
			'policyTopicEntries' => $policyTopicEntriesTab
		],
		'adGroupId' => $googleAdsRow->getAdGroup()->getId(),
		'clicks' => $googleAdsRow->getMetrics()->getClicks(),
		'impressions' => $googleAdsRow->getMetrics()->getImpressions(),
		'costMicros' => $googleAdsRow->getMetrics()->getCostMicros(),
		'conversions' => $googleAdsRow->getMetrics()->getConversions(),
		'averageCpc' => $googleAdsRow->getMetrics()->getAverageCpc(),
		'campaignId' => $googleAdsRow->getCampaign()->getId()
	];
}
```


Sorry for the unreadable display, but cannot get it to display the code correctly.

Regards,

**Comment by Jejec** [comment]
The subject of emails with the google ADS API (googleadsapi-support@google.com) was "[API ADS] The urls fields are empty".  
There is a reference in the emails, maybe it can help:
ref:_00D1U1174p._5004Q2bdTka:ref

Thank you

**Comment by fiboknacky** [comment]
Could you share the latest request ID that you get from running [your code](https://github.com/googleads/google-ads-php/issues/813#issuecomment-1157375829)?
The one that you shared with the API support team seems to be a different request and I couldn't find the related one.
Thanks.

**Comment by Jejec** [comment]
Hello,

I resubmitted the query with the logs. Here is the information related to the request:
[2022-06-20T08:26:09.155767+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v9.services.GoogleAdsService/SearchStream", CustomerId: 7232342501, RequestId: "9_N2mgVyyEEZO67niirmYw", IsFault: 0, FaultMessage: "None"  

Thank you

**Comment by fiboknacky** [comment]
What I can see from the request ID that you shared is that your request contains no queries. It looks like the query you mentioned above wasn't sent with the `GoogleAdsSearchStream` request.
Could you double check if the log is correct?

**Comment by Jejec** [comment]
Hello,

I did, however, get a response with data. I redid the query here is the log:
[2022-06-22T08:12:52.893971+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v9.services.GoogleAdsService/SearchStream", CustomerId: 7232342501, RequestId: "upzR6u-bHqPb504wMoowwA", IsFault: 0, FaultMessage: "None"  


The code is exactly as provided above.
```php
$googleAdsServiceClient = $this->authGoogle->getServiceClient($subsidiaryId)->getGoogleAdsServiceClient();
$stream = $googleAdsServiceClient->searchStream($googleId, $query);
```

Just the getServiceClient function which is modified for the display of logs here it is:
```php
public function getServiceClient($subsidiaryId)
  {
          $loggerFactory = new LoggerFactory();
          $logger = $loggerFactory->createLogger(
              'google-ads',
              APP_PATH.'/Services/logging.log',
              Logger::DEBUG
          );

          return (new GoogleAdsClientBuilder())
              ->withOAuth2Credential($this->getOAuth2($subsidiaryId))
              ->withDeveloperToken($this->getConfigApi('CONFIG_GAPI_DEVELOPER_TOKEN', $subsidiaryId))
              ->withLoginCustomerId($this->getConfigApi('CONFIG_GAPI_MCC_GOOGLE_ID', $subsidiaryId))
              ->withLogger($logger)
              ->build();
  }
```

**Comment by fiboknacky** [comment]
Could you share what's in `APP_PATH.'/Services/logging.log'` for this particular request? Thanks.

**Comment by fiboknacky** [comment]
Could you also share what's in the `[LOGGING]` section of your [`google_ads_php.ini`](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/google_ads_php.ini) (if exists) too?

**Comment by Jejec** [comment]
No problem. I'll try that on Tuesday 5th and let you know.

**Comment by Jejec** [comment]
Hello,

Here are the logs with the search method.

```
[2022-07-05T08:31:48.689324+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v9.services.GoogleAdsService/Search", CustomerId: 7232342501, RequestId: "DcswSsftUVA1GI0E6lTTRg", IsFault: 0, FaultMessage: "None"  
```

**Comment by fiboknacky** [comment]
Sorry for taking long time. I successfully fetched your log response in the server and it looked fine.
I also impersonate your account (customerId `7232342501`), use your code in the original post, and successfully retrieved final URLs.

In the original post, you didn't show how you print your URLs. Could you show how you do that and why you think they're empty?

**Comment by fiboknacky** [comment]
What do you do after the below lines?

```php
adGroupAds[] = [
		'id' => $googleAdsRow->getAdGroupAd()->getAd()->getId(),
		'type' => (in_array('type', $getName)) ? AdTypeEnum\AdType::name($googleAdsRow->getAdGroupAd()->getAd()->getType()) : $googleAdsRow->getAdGroupAd()->getAd()->getType(),
		'status' => (in_array('status', $getName)) ? AdGroupAdStatus::name($googleAdsRow->getAdGroupAd()->getStatus()) : $googleAdsRow->getAdGroupAd()->getStatus(),
		'displayUrl' => $googleAdsRow->getAdGroupAd()->getAd()->getDisplayUrl(),
		'finalUrls' => $googleAdsRow->getAdGroupAd()->getAd()->getFinalUrls(),
		'finalMobileUrls' => $googleAdsRow->getAdGroupAd()->getAd()->getFinalMobileUrls(),
		'finalAppUrls' => $googleAdsRow->getAdGroupAd()->getAd()->getFinalAppUrls(),
		'textAdHeadline' => $googleAdsRow->getAdGroupAd()->getAd()->hasTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getTextAd()->getHeadline() : '',
		'textAdDescription1' => $googleAdsRow->getAdGroupAd()->getAd()->hasTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getTextAd()->getDescription1() : '',
		'textAdDescription2' => $googleAdsRow->getAdGroupAd()->getAd()->hasTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getTextAd()->getDescription2() : '',
		'callAdDescription1' => $googleAdsRow->getAdGroupAd()->getAd()->hasCallAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getCallAd()->getDescription1() : '',
		'callAdDescription2' => $googleAdsRow->getAdGroupAd()->getAd()->hasCallAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getCallAd()->getDescription2() : '',
		'expandedTextAdDescription' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getDescription() : '',
		'expandedTextAdDescription2' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getDescription2() : '',
		'expandedTextAdHeadlinePart1' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getHeadlinePart1() : '',
		'expandedTextAdHeadlinePart2' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getHeadlinePart2() : '',
		'expandedTextAdHeadlinePart3' => $googleAdsRow->getAdGroupAd()->getAd()->hasExpandedTextAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getExpandedTextAd()->getHeadlinePart3() : '',
		'legacyResponsiveDisplayAdDescription' => $googleAdsRow->getAdGroupAd()->getAd()->hasLegacyResponsiveDisplayAd() ? $googleAdsRow->getAdGroupAd()->getAd()->getLegacyResponsiveDisplayAd()->getDescription() : '',
		'policySummary' => [
			'approvalStatus' => $approvalStatus,
			'policyTopicEntries' => $policyTopicEntriesTab
		],
		'adGroupId' => $googleAdsRow->getAdGroup()->getId(),
		'clicks' => $googleAdsRow->getMetrics()->getClicks(),
		'impressions' => $googleAdsRow->getMetrics()->getImpressions(),
		'costMicros' => $googleAdsRow->getMetrics()->getCostMicros(),
		'conversions' => $googleAdsRow->getMetrics()->getConversions(),
		'averageCpc' => $googleAdsRow->getMetrics()->getAverageCpc(),
		'campaignId' => $googleAdsRow->getCampaign()->getId()
	];
```

**Comment by Jejec** [comment]
Nothing in particular. I return the data. Here is the line:

```php
return $this->response->setStatusCode(200)->setJsonContent($adGroupAds);
```

**Comment by fiboknacky** [comment]
I really have no idea here either because your code works perfectly on my computer (even with your account).
Even if you use `var_dump` or `print`, no URLs are printed at all? I just wonder if there is a bug with `setJsonContent`.

**Comment by Jejec** [comment]
Even if I display the result of $adGroupAds via a var_dump I don't have a url so I don't think the setJsonContent function is causing a problem.

**Comment by fiboknacky** [comment]
What fields did you select? What happened when you select only `ad_group_ad.ad.id,` and `ad_group_ad.ad.display_url`?

**Comment by JCauz** [comment]
Hello,

I did the test with just the 2 fields you are asking for, but still nothing.
Here is the log:

```
[2022-07-27T09:40:00.661625+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v9.services.GoogleAdsService/SearchStream", CustomerId: 7232342501, RequestId: "vaNHwByyccc1tC-umVPidw", IsFault: 0, FaultMessage: "None"  
```

**Comment by fiboknacky** [comment]
Could you try with `search` instead? Unfortunately, I cannot see the internal log when using `searchStream`.
And let's get down into a detail. What ad group ID and ad group ad ID are you fetching now? Can you add a filter to scope them into one ad group ad that you know it contains URLs?
Instead of using `var_dump`, please use a PHP `print command instead, since sometimes `var_dump` doesn't work well with the messages created by protobuf, unfortunately.

**Comment by JCauz** [comment]
Hello,

I performed the query with search. Here are the logs:

```
[2022-08-03T07:17:15.724359+00:00] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v9.services.GoogleAdsService/Search", CustomerId: 7232342501, RequestId: "3YABeu-fxWNnuxyi2m53kw", IsFault: 0, FaultMessage: "None"  
```

I didn't make any condition on a group ad id because I don't necessarily know the ids of those who have urls but most should have them anyway.

I also used a print_r but still nothing.

**Comment by fiboknacky** [comment]
Thanks for providing the request ID.
I assume your query is `SELECT ad_group.id, ad_group_ad.ad.id, ad_group_ad.ad.display_url FROM ad_group_ad ORDER BY ad_group.id`, right?

I checked your customer ID 723-234-2501 and found that all ads are an [expanded text ad](https://developers.google.com/google-ads/api/docs/ads/expanded-text-ads), which doesn't contain any display URL at first.
The expanded text ad calculates the display URL by combining expanded descriptions and and URL customization.
That's why you don't see it returned in `ad_group_ad.ad.display_url`.

I mark this issue closed, since it seems not an issue of the library anymore. Feel free to reach out to [the Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) for further help about the API in general.
