### ISSUE TITLE
Clearing Maximize Bidding strategy cpc - Removing cpc bid

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/google-ads-php#815]
As per the google, ads document To remove a bid, update its field back to null.

I am trying to remove CPC bid for the campaign which is having Maximize clicks bidding with cpc.

        $campaign = new Campaign([
            'resource_name' => ResourceNames::forCampaign($customerId, $campaignId),
            'status' => $status == 'paused' ? CampaignStatus::PAUSED : CampaignStatus::ENABLED,
        ]);

        $updateMask = new Campaign([
            'resource_name' => ResourceNames::forCampaign($customerId, $campaignId),
            'status' => $status == 'paused' ? CampaignStatus::PAUSED : CampaignStatus::ENABLED,
            'target_spend'=>new TargetSpend(["cpc_bid_ceiling_micros"=>null]),
        ]);

        $campaignOperation = new CampaignOperation();
        $campaignOperation->setUpdate($campaign);
        $campaignOperation->setUpdateMask(FieldMasks::allSetFieldsOf($updateMask));
        $campaignServiceClient = $googleAdsClient->getCampaignServiceClient();

If I pass as null then I am getting this error, 

request.CRITICAL: Uncaught PHP Exception Exception: "Cannot convert '' to integer" at /vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V9/Common/TargetSpend.php line 61 {"exception":"[object] (Exception(code: 0): Cannot convert '' to integer at /var/www/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V9/Common/TargetSpend.php:61)"} []

Could you please let me know the correct way?

**Comment by PierrickVoulet** [comment]
Hi @Vijaysinh  - I think your issue is similar to another one we https://github.com/googleads/google-ads-php/issues/713#issuecomment-1009918882 in the past. Could you take a look and let us know if that does not help?

**Comment by Vijaysinh** [comment]
@PierrickVoulet I tried with 
```
$campaignOperation->setUpdateMask(new FieldMask(['paths' => ['target_spend']]));
```
Its giving me error : field_error:The field cannot be cleared.

after that I tried below,
```
$campaignOperation->setUpdateMask(new FieldMask(['paths' => ['cpc_bid_ceiling_micros']]));
```
Its giving me this error : field_mask_error:The field mask contained an invalid field: 'cpc_bid_ceiling_micros'.

Could you please let me know what I am doing wrong here? I wanted to clear cpcbid.

**Comment by Vijaysinh** [comment]
@PierrickVoulet it worked after changing to this
``` $campaignOperation->setUpdateMask(new FieldMask(['paths' => ['target_spend.cpc_bid_ceiling_micros']]));
```

**Comment by PierrickVoulet** [comment]
Thank you for confirming and for the feedback. We will upgrade our [guide](https://developers.google.com/google-ads/api/docs/client-libs/php/fieldmasks) soon to help with that.
