### ISSUE TITLE
Restore monolog/monolog:v1.26 compatibility 

### ISSUE THREAD

**Issue by jroenf** [googleads/google-ads-php#816]
**Problem you are trying to solve:**
Php client library for Google Ads V15.1 supports Google Ads API V11. We want to use it. Unfortunately, version V15.1 also dropped support for monolog/monolog:V1.26. Monolog 2 or 3 is required. This is in conflict with the monolog/monolog:v1.26 version we use. Updating monolog is not easy for us, we use symfony/symfony:v4.4 (still supported), that version lists monolog 2 (and 3) as a conflict.

**Solution you'd like:**
Use Google Ads API 11 through the php client library with support for monolog/monolog:V1.26.

**Alternatives you've considered:**
Upgrading symfony major version also solves the issue. We will do that before supports ends (> 1 year). But is is too much work now to get started with Performance Max campaigns fast.

**Additional context:**
We want to use the new AssetSource of Performance Max Assets. Only available in V11 of the Google Ads Api.

**Comment by fiboknacky** [comment]
@jroenf I didn't realize that Monolog 2 is listed as a conflict of Symfony v4.4.
I'll bring back that soon to the main branch, but I'll need some time to release a new version.
Does that work for you?

**Comment by fiboknacky** [comment]
We're aiming to make a release based on `main` in around two weeks.

**Comment by Vijaysinh** [comment]
![GoogleAds](https://user-images.githubusercontent.com/6183730/177555455-8aea7ecb-7b06-4211-adec-e1044d218df2.PNG)
Currently getting this error as per attached screenshot

**Comment by fiboknacky** [comment]
Yes, because `15.1.0` still supports only two versions. If you want to use it now, please specify `dev-main` instead of `15.1.0`.

**Comment by Vijaysinh** [comment]
@fiboknacky That worked fine, thank you so much.

**Comment by jroenf** [comment]
@fiboknacky thank you for solving this issue. You helped us very much. We are now using v16.0 and are implementing our use of AssetSource for Performance Max Assets. 🙏

**Comment by fiboknacky** [comment]
Glad that it's helpful to you. :) Please feel free us know if you have any issues in the future.
