### ISSUE TITLE
Obtaining a refresh token with the GenerateUserCredentials.php 

### ISSUE THREAD

**Issue by MaximeCertain** [googleads/google-ads-php#820]
Hello,

I am trying to consume this library with the desktop app flow way.

I obtained my client Id and Client Secret with the https://console.cloud.google.com

Then, to obtain the refresh token I followed this doc : https://developers.google.com/google-ads/api/docs/client-libs/php/oauth-web
and installed your library with the docker way. 
Then when I run 
`php examples/Authentication/GenerateUserCredentials.php`
in the container and enter my clientId and client secretId i am getting an url with a consent screen. 
After clicking on continue in the consent screen i am getting this connection error when redirecting in the redirect_uri generated by your program :
![image](https://user-images.githubusercontent.com/44211757/174967962-77e64a36-4791-4d6e-a106-74df25ca9f6f.png)

Can you help me to obtain a refresh token to use your library ? 
Thanks

**Comment by fiboknacky** [comment]
> I obtained my client Id and Client Secret with the https://console.cloud.google.com/

First, could you please confirm that your client ID has a **type** as **Desktop**?

And because refresh token isn't needed to be fetched very often, you may do this on your local machine instead of Docker.

**Comment by MaximeCertain** [comment]
> First, could you please confirm that your client ID has a **type** as **Desktop**?

Hello, 
Yes my client Id is created with a type as Desktop.

**Comment by fiboknacky** [comment]
Could you please try running this on your local machine? Usually, it should work without configuring any more settings.
I actually don't know what's in the screenshot, but I guess it looks like the connection is refused in the container.
That's the part I'm not sure if there is any setting in Docker that would prevent you from doing that.

**Comment by MaximeCertain** [comment]
Thanks,  

I have try in local and indeed it works better with the redirect_uri, I could obtain my refresh token. 

But, when running a request with your library I have a DEVELOPER_TOKEN_NOT_APPROVED 

`    "message": "The caller does not have permission",
    "code": 7,
    "status": "PERMISSION_DENIED",
    "details": [
        {
            "@type": "type.googleapis.com\/google.ads.googleads.v10.errors.GoogleAdsFailure",
            "errors": [
                {
                    "errorCode": {
                        "authorizationError": "DEVELOPER_TOKEN_NOT_APPROVED"
                    },
                    "message": "The developer token is not approved. Non-approved developer tokens can only be used with test accounts."
                }
            ],`

Whereas my google ads is already already a test account, do you have any idea ? 

Thanks

**Comment by fiboknacky** [comment]
For `DEVELOPER_TOKEN_NOT_APPROVED`, please contact the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api). They'll guide you through the process. Thanks.
