### ISSUE TITLE
How to get Image Urls/Text for Responsive Display Ads

### ISSUE THREAD

**Issue by mdworkin21** [googleads/google-ads-php#823]
Hello,

I'm trying to pull a report for Ads, and I'm having difficulty getting URLs and text for image and headline assets. I'm able to get the resource names for them, but have been unable to pull actual image urls and the actual headlines. 

I've tried a few of approaches and have been scouring the php library but can't seem to find what I need. 

1. `$googleAdsRow->getAdGroupAd()->getAd()->getImageAd()` - Returns null
1.a. The `getImageAd` method is supposed to return an` ImageAdInfo` object that has a `getImageUrl` method on it, but since `ImageAdInfo` is null, I cant' use it.
2. `$googleAdsRow->getAdGroupAd()->getAd()->getResponsiveDisplayAd()` returns (I believe) repeated field
2.a Iterate over return from 2 and use `getAsset()`, returns resource name. I'm not sure what to do with this in order to get what I need.

I've faced similar issues with text ads.

_So a few questions_:
i. Is what I'm trying to do possible? (seems like it should be)
ii. What do I need to do?

Thanks for your help!

Best,
Matt

**Comment by PierrickVoulet** [comment]
Hi @mdworkin21 - Could you provide the [GAQL](https://developers.google.com/google-ads/api/docs/query/overview) queries you are using in your requests that lead to this behavior?

**Comment by mdworkin21** [comment]
hey @PierrickVoulet thanks for getting back to me. 

Sure, here's the GAQL. 

For context, I'm trying to pull a "performance" report for ads, where we get some metrics (e.g. cost) for a particular ad, as well as important ad properties, like image URLs, headlines, etc. for the previous day.

```
SELECT 
campaign.id,ad_group.id,
campaign.advertising_channel_type,
ad_group_ad.ad.responsive_display_ad.marketing_images,
ad_group_ad.ad.responsive_display_ad.square_marketing_images,
ad_group_ad.ad.responsive_display_ad.headlines,
ad_group_ad.ad.responsive_display_ad.descriptions,
ad_group_ad.ad.responsive_display_ad.long_headline,
segments.date,
metrics.average_cpc,
metrics.cost_micros,
metrics.impressions,
metrics.clicks,
metrics.ctr,
metrics.conversions
FROM ad_group_ad 
WHERE segments.date = '2022-06-21' AND ad_group_ad.ad.type = RESPONSIVE_DISPLAY_AD AND metrics.cost_micros > 0 
ORDER BY segments.date
```

Please let me know what else would be helpful for you to see.

**Comment by PierrickVoulet** [comment]
For questions that are related to the Google Ads API, you should contact the dedicated [support](https://developers.google.com/google-ads/api/support). For questions that are strictly related to this library (usage, bugs, feedback), feel free to contact us. In this particular case, the questions are related to building Google Ads API requests that retrieve some information you need.

`$googleAdsRow->getAdGroupAd()->getAd()->getImageAd()` should not return `null` anymore because you selected `ad_group_ad.ad.image_ad.image_url` so you should be able to use `getImageUrl `.

**Comment by mdworkin21** [comment]
I added the line, and tried the above code but it looks like `null` is still being returned. I guess this is an API problem? I'll reach back out to them. Thanks for your help.

**Comment by PierrickVoulet** [comment]
> I added the line, and tried the above code but it looks like `null` is still being returned. I guess this is an API problem? I'll reach back out to them. Thanks for your help.

Could be an expected behavior (there is no data to return) or a bug. If you provide the Google Ads API support with the request and response logs they will be able to confirm and advise. Feel free to reopen this issue if it turns out that this library is misbehaving and we will take a look.
