### ISSUE TITLE
Uploading offline click conversion with ads test account 

### ISSUE THREAD

**Issue by MaximeCertain** [googleads/google-ads-php#824]
Hello, 

When I run my offline upload click conversion program , I  have this message :

`Partial failures occurred: 'The click or call is owned by a customer account that the uploading customer does not manage., at conversions[0].gclid'.`

I created the gclid with a production google ads account, 
whereas I used a google ads test account to test in local.

​Is it possible to test the offline upload click conversion with a test account ?
If not , can we create gclid with a test account ?

Thanks to you.

**Comment by fiboknacky** [comment]
Since the question is related to the Google Ads API, please post your question on [the Google Ads API forum](https://groups.google.com/g/adwords-api). Thank you.
