### ISSUE TITLE
Create campaign with geo-targeting

### ISSUE THREAD

**Issue by MiqueasDM** [googleads/google-ads-php#826]
Hi everyone, 

I would like to modify the example file that is in Basicoperations called Addcampaigns to add geographical segmentation as the user chooses.

The user introduces a country and the campaign is created with the target location in that place.

Thank you

**Comment by PierrickVoulet** [comment]
Hi @MiqueasDM, This [other example](https://github.com/googleads/google-ads-php/blob/main/examples/Targeting/AddCampaignTargetingCriteria.php) about campaign targeting could potentially help you achieve that.

**Comment by PierrickVoulet** [comment]
Closing the issue due to inactivity.
