### ISSUE TITLE
Uploading offline click conversion  have an "This customer does not have an import conversion action that matches the conversion action provided.," error message

### ISSUE THREAD

**Issue by MaximeCertain** [googleads/google-ads-php#831]
Hello I am trying to upload offline conversion click 

To perform the test of my program in my local machine,  I take a gclid generated in my production website  and save the gclid in my internal CRM database for the associate user.

Then I am trying in my upload offline conversion program to upload this gclid ( and a custom variable with) to the conversion action which was created few years ago

Here is my program :

![image](https://user-images.githubusercontent.com/44211757/177734689-96f15061-615f-479a-a1f6-1238b72d9ba0.png)

This program results on a 
`This customer does not have an import conversion action that matches the conversion action provided., at conversions[0].conversion_action
`
Error message 

But when i run a conversion action query with the same customer id that I am using in my program 

![image](https://user-images.githubusercontent.com/44211757/177734931-6b1f3569-7957-4c9d-81bc-56e6a5b0a66d.png)

I have a result and retrieve the conversion action that I am trying to use 

SO I don't know how to face this issue ?

Thanks

**Comment by fiboknacky** [comment]
The issue is more about the conversion action settings. Could you please post on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)? Thanks.
