### ISSUE TITLE
failed to connect to Google Ads API

### ISSUE THREAD

**Issue by sososbl** [googleads/google-ads-php#837]
Hi,

We failed to connect to Google Ads API since 07/18/2022 at around 5 p.m..

Please see below job log for reference.

Request: 
{"customerId":"**********","query":"SELECT metrics.all_conversions, \r\n                            metrics.all_conversions_value, \r\n                            metrics.clicks, \r\n                            metrics.cost_micros, \r\n                            metrics.all_conversions_from_interactions_rate, \r\n                            metrics.ctr, \r\n                            metrics.impressions, \r\n                            ad_group.id, \r\n                            ad_group.name, \r\n                            ad_group.cpc_bid_micros, \r\n                            campaign.id \r\n                    FROM ad_group \r\n                    WHERE ad_group.status=ENABLED \r\n                    AND segments.date BETWEEN '2022-04-20' AND '2022-07-19' and campaign.id = 17076130278","pageSize":10000}

Response
-------
Headers: []

Fault
-------
Status code: 14
Details: failed to connect to all addresses
Failure: {}  
[2022-07-19T02:20:55.592099-04:00] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v10.services.GoogleAdsService/Search", CustomerId: **********, RequestId: "", IsFault: 1, FaultMessage: "None"

We are using php for all of our API requests and all the requests to the Google Ads API are throwing this error:

Fault
-------
Status code: 14
Details: failed to connect to all addresses

Nothing has changed from our side when the errors start to happen. We notice that there is a new verision v11. Do we have to update the version from v10 to v11? We've contacted google before and they ask us to contact the client library authors as they are better equipped to provide support on this topic. Please kindly look into this issue and let us know how to fix the errors as soon as possible. Thank you very much.

**Comment by fiboknacky** [comment]
We don't see any errors on our end. Everything works fine. Is there any chance that your network connectivity has issues?
Do you use the library inside a Docker or any servers?

**Comment by sososbl** [comment]
We've tried another server and are able to connect to Google Ads API now. Thank you.
