### ISSUE TITLE
Migration from googleads-php-lib to google-ads-php

### ISSUE THREAD

**Issue by shellysajudev** [googleads/google-ads-php#839]
I'm trying to update this functionality to the new library.

`(new AdWordsSessionBuilder())
->withDeveloperToken('xxxxxx')
->withUserAgent(UserAgent::DEFAULT)
->withOAuth2Credential($oauth2);  `

But I can't find AdWordsSessionBuilder class in the new library. Could you please help me out in trying to migrate to the new library.
I'm using V6 API.

**Comment by fiboknacky** [comment]
First, v6 is already sunset. Please use the latest version, which is v11 now.
Although some concepts are shared, this library is fundamentally different from `googleads-php-lib`. 
I highly recommend going through all sections in [README](https://github.com/googleads/google-ads-php#getting-started) first.

Then, you can browse code examples, such [GetCampaigns](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/GetCampaigns.php) and learn how to create relevant objects in this library.

To briefly answer your question now, in this library, the equivalent class is called `GoogleAdsBuilder`. You can see how to use it [here](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/GetCampaigns.php#L53).
