### ISSUE TITLE
How to make Batch Processing?

### ISSUE THREAD

**Issue by sera527** [googleads/google-ads-php#84]
Please give example.

**Comment by fiboknacky** [comment]
We're preparing an example and will available probably in early June.

**Comment by zacintosh** [comment]
Is there any update on this?

**Comment by fiboknacky** [comment]
Unfortunately, it's got extended a bit probably by next week.
The example is already ready, but you probably cannot run [it](https://github.com/googleads/google-ads-php/blob/master/examples/CampaignManagement/AddCompleteCampaignsUsingMutateJob.php) yet.

Please keep an eye on our [blog announcement](https://ads-developers.googleblog.com/) too. We'll also announce there.

**Comment by fiboknacky** [comment]
Currently, the batch processing is still not generally available. As always, please keep an eye on [our blog](https://ads-developers.googleblog.com) for any new releases.
I'm going to close this issue as there is no work needing to be done in this library.
