### ISSUE TITLE
Problem with either the documentation or the implementation of /google-ads-php/examples/Authentication/GenerateUserCredentials.php

### ISSUE THREAD

**Issue by marcobat** [googleads/google-ads-php#840]
I have attempted using this example to generate a refresh token.
The first issue that I ran into is that the script doesn't requests a redirect url and defaults to what it can gather from the local machine, in my case an IP Address, which is not a valid redirect url.
I have changed/modified the lines that define the redirect url like this:

        print 'Enter your redirect url here: ';
        $redirectUrl = trim(fgets(STDIN)); 

With this modification i can now get a valid redirect url.
I can then manually enter it into a browser, login with the proper credentials and provide access.

However, i then ran into a second issue, the script, for what i understand, should eventually provide a refresh token, instead it hangs and never finishes the process (i stopped waiting after a few minutes)

**Comment by fiboknacky** [comment]
Hi,

What application type (web or desktop) do you use?
If you use web, you need to add the following "http://127.0.0.1" to the "Authorized redirect URIs" list in your Google Cloud Console project too.

As for the code, it creates a redirect URL in [this line](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L88).
The program should prompt you to log into Google account in [this line](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L172).

**Comment by marcobat** [comment]
Hi,
the application type i use is web but http://127.0.0.1 is not a valid url and the address that [this line](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L88) returns is not http://127.0.0.1 but the actual IP of the server (which is behind a firewall anyway).

The program does provide a usable redirect URL  (If I modify it to input redirect URL myself). 

I can then login into google using it and give the proper authorization, however my understanding is that the script should then continue and provide me with the refresh token, instead it hangs there.

**Comment by fiboknacky** [comment]
That's interesting because it's defined at [this line](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L63), so it should be http://127.0.0.1.

Could you run it locally?

**Comment by marcobat** [comment]
Hi,
yes, if i ran it on my local machine it would return http://127.0.0.1/ (I actually didn't try but I bet it would).

But the problem still remains, the redirect url is ultimately generated [here](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L88), maybe there could be a check, if the redirect url is different than 127.0.0.1 and it is an IP address (i'm not allowed to specify the redirect url as an IP Address) the script could prompt for a valid redirect url (just a suggestion to solve what probably is a edge case like mine).

However ultimately the main issue is that I can't get the refresh token out of this process, once i validate with my google account i receive the redirect url i provided with appended ?code-xxx&state=xxx&more_tags values (which i guess would be used to generate the refresh token), how do I get the actual refresh token? (I got it by manually using https://developers.google.com/oauthplayground/, but it would be great to be able to get it via this script).

**Comment by fiboknacky** [comment]
> once i validate with my google  account i receive the redirect url i provided with appended ?code-xxx&state=xxx&more_tags values (which i guess would be used to generate the refresh token)

The normal flow would be that you follow the authentication flow, you put the authorization code in the textbox (the URI that you mentioned appended with some query parameters), and the browser will [show a message to ask you to check the result in the console](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L164).

> But the problem still remains, the redirect url is ultimately generated [here](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L88), maybe there could be a check, if the redirect url is different than 127.0.0.1 and it is an IP address (i'm not allowed to specify the redirect url as an IP Address) the script could prompt for a valid redirect url (just a suggestion to solve what probably is a edge case like mine).

That would be a good workaround if it resolves your issue.
However, from the fact that you still cannot get the refresh token, I doubt that it would really resolve your issue.
There might be some settings in the server that prevents you from achieving this.

> (I got it by manually using https://developers.google.com/oauthplayground/, but it would be great to be able to get it via this script).

Provided that getting refresh tokens doesn't need to be done on a regular basis. Could you consider running this on your local machine instead of the servers?
Although it may not be exactly the same reason, but that's why we put a caveat in [the file comment](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/GenerateUserCredentials.php#L36).

**Comment by marcobat** [comment]
Yes, very good caveat :)
I'm sure running it on my local machine would work
