### ISSUE TITLE
v17.0.0 update of the FieldMasks utility causes undefined method error

### ISSUE THREAD

**Issue by geropeter** [googleads/google-ads-php#844]
**Your client library and Google Ads API versions:**

* Client library version: `v17.0.0`

* Google Ads API version: `V11`

**Your environment:**

* The PHP version: 7.4.18
* The name and version of the operating system: Ubuntu 4.4.0-210-generic
* Whether the PHP Extension `protobuf` is used or not: 3.19.4
* Whether the PHP Extension `grpc` is used or not: 1.26.0
* The type of transport being used (`grpc` or `rest`): grpc

**Description of the bug:**

By updating headline or description assets of RSAs using a batch job an error was shown pointing towards the FieldMasks utility:

Call to undefined method Google\Protobuf\FieldDescriptor::getRealContainingOneof() in /vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/FieldMasks.phpat line 259

**Steps to reproduce:**

Update a line in the headline or description asset of an RSA, the error always started when FieldMasks utility was called:

$adOperation->setUpdateMask(FieldMasks::allSetFieldsOf($ad));

**Expected behavior:**

**Request/Response Logs:**
 
**Anything else we should know about your project / environment:**

**Comment by fiboknacky** [comment]
Could you update your protobuf's version to `3.21.5` first? Thanks.

**Comment by leongersen** [comment]
I ran into this too when upgrading, upgrading the protobuf extension is the fix here.

Maybe the SDK can check the minimum required version of the extension? `"google/protobuf": "^3.21.5"` is required in `composer.json`, but there is no validation that a compatible version of the extension is installed.

https://github.com/protocolbuffers/protobuf/releases/tag/v21.5

**Comment by fiboknacky** [comment]
Thanks @leongersen.
We have an open feature request here: #406.

**Comment by geropeter** [comment]
I have updated protobuf's version to 3.21.5 and grpc to 1.42.0, the error unfortunately still persists. Confirmed on a single RSA with only one headline being updated ( number and content of the other headlines and descriptions and the contents of path1/2 and final url fields would not change )

**Comment by fiboknacky** [comment]
Do you use the C implementation or PHP implementation?
[That version](https://github.com/protocolbuffers/protobuf/releases/tag/v21.5) should already contain the method `getRealContainingOneof`. I just confirmed that it worked for both C and PHP implementations.

**Comment by geropeter** [comment]
I use the PHP implementation, and found the function there too. If I revert back to V16.0.0 of the Google Ads API, the update runs, there are no errors.

**Comment by fiboknacky** [comment]
That's really strange. If the function is there, it shouldn't throw an error like that.
I just confirmed using the PHP implementation but didn't find any errors.
What does it look like in your `composer.lock`? Could you try removing it and the `protobuf` directory in `vendor` and reinstall it again?

**Comment by geropeter** [comment]
Thanks @fiboknacky, I've done as you suggested, and it is working again.

**Comment by geropeter** [comment]
@fiboknacky I've closed the issue too soon, I've experienced the same error after upgrading then reinstalling protobuf with composer. If I revert back to V16.0.0 of the Google Ads API, the batch job runs without errors.

**Comment by fiboknacky** [comment]
So, you can see that function in the protobuf code under `vendor`, right?
Could you share your code that triggers that error here too please?

**Comment by sksoft22** [comment]
How to add extension like "extension=grpc" for protobuf.so, just putting the DLL file?

**Comment by fiboknacky** [comment]
@sksoft22  Can you follow [this wiki](https://github.com/chobie/php-protocolbuffers/wiki/Tutorial)?

**Comment by geropeter** [comment]
@fiboknacky The protobuf php module was enabled, this was the source of the conflict. After disabling it everything is working again as expected.
If someone encounters the same issue, I got the idea from this ticket / article: https://github.com/aliyun/aliyun-tablestore-php-sdk/issues/9
