### ISSUE TITLE
Logger LogLevel is not align with PSR-3-logger-interface

### ISSUE THREAD

**Issue by BartStep** [googleads/google-ads-php#849]
Logger LogLevel is not compatible with PSR-3-logger-interface. 
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#5-psrlogloglevel

When error level is passing to LoggerInterface it has capital letter instead of lowercase: 
Ex: `DEBUG` instead of `debug`

https://github.com/googleads/google-ads-php/blob/f66ce0876ded6ed5ae028a6ed23bc552854cdcbb/src/Google/Ads/GoogleAds/Lib/V11/GoogleAdsCallLogger.php#L203

**Comment by fiboknacky** [comment]
Fixed with [v20.1.0](https://github.com/googleads/google-ads-php/releases/tag/v20.1.0)
