### ISSUE TITLE
Google\AdsApi\Common\OAuth2TokenBuilder' not found in 

### ISSUE THREAD

**Issue by fabianamanu** [googleads/google-ads-php#85]
I'm sorry for the English

created an index.php to display my reports plus I am with the following error Fatal error: Uncaught Error: Class 'Google \ AdsApi \ Common \ OAuth2TokenBuilder'
![erro](https://user-images.githubusercontent.com/12700210/58096211-efd6cf80-7baa-11e9-8f14-3099db42cc04.png)

**Comment by Raibaz** [comment]
Hi, 

How did you import the Google Ads client library? Are you using composer? And if so, did you run `composer install` to get all the required dependencies?

Also, your screenshot seems to indicate that you are actually using the AdWords API, so you may want to open your issue in [its repo](https://github.com/googleads/googleads-php-lib).

**Comment by fabianamanu** [comment]
ola  eu importei pelo link https://github.com/googleads/googleads-php-lib  instalei o composer  sim  fiz tudo que estava na documentação r

**Comment by fabianamanu** [comment]
I asked the question where you are indicating me but I do not respond, I am new in api, and I need to generate reports of my accounts

**Comment by fiboknacky** [comment]
I'm closing this issue because it's not related to this library. Please catch up with [this issue](https://github.com/googleads/googleads-php-lib/issues/589) instead.
