### ISSUE TITLE
block-ip

### ISSUE THREAD

**Issue by AnthonyL71** [googleads/google-ads-php#854]
Hello,

I want to use google-ads-php to block ips on campaigns, and unblock them too. Could you tell me which file in examples I could do this? 

thank you

Anthony

**Comment by fiboknacky** [comment]
Hello Anthony,

We don't have an example for that. The closest one would be [UpdateCampaignCriterionBidModifier](https://github.com/googleads/google-ads-php/blob/main/examples/CampaignManagement/UpdateCampaignCriterionBidModifier.php), but you need to change from `setUpdate` to `setCreate`.

In summary, you need to create [IpBlockInfo](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V12/Common/IpBlockInfo.php) first.
Then, create a new [CampaignCriterion](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V12/Resources/CampaignCriterion.php) and call [`setIpBlock`](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V12/Resources/CampaignCriterion.php#L1010) to set the `IpBlockInfo` created previously.
