### ISSUE TITLE
How can i get The targeted Locations For a campaign

### ISSUE THREAD

**Issue by mohammadsiabbouforwork** [googleads/google-ads-php#855]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
 Hey,

I'm trying to retrieve the targeted locations for an exact campaign based on its id but I couldn't find the way.
I was wondering if anyone could help with a code example, please.

I  appreciate any help you can provide.

**Comment by fiboknacky** [comment]
Since your question seems to be related to the usage of the Google Ads API in general, could you please post your question in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)? Thanks.
