### ISSUE TITLE
Run file by browser

### ISSUE THREAD

**Issue by AnthonyL71** [googleads/google-ads-php#856]
Hello,

I manage to use google-ads-php very well, however when I want to run:

php -q google-ads-php/examples/AdvancedOperations/AddAppCampaign.php

It works fine, but if I want to run it with my web browser: http://localhost/google-ads-php/examples/AdvancedOperations/AddAppCampaign.php it shows me a blank page and nothing happens. Could you help me please? 

Thanks

**Comment by fiboknacky** [comment]
As stated in [Step 5 of Getting Started](https://github.com/googleads/google-ads-php#getting-started), the examples are meant to be run on the command prompt. If you wish to use it on web browser, you have to refer to the code examples and implement them on your selected web application.
