### ISSUE TITLE
Performance degradation for get/searches compared to AdWords

### ISSUE THREAD

**Issue by wihl** [googleads/google-ads-php#86]
(this is a tracking bug)

Using the get_ad_groups example, with 152k results and page sizes of 4000, 7000, and 10000, results in a performance degradation compared to both AdWords and other languages.

For comparable tests in other languages of AdWords vs. Google Ads API:

- Java is approximately 50% slower 
- Python 2 is approximately 20% slower

whereas PHP is approximately 500% slower. It also gets worse with larger page sizes whereas the other languages improve with larger page sizes. This merits deeper investigation. 

See @PierrickVoulet for details of the query and associated CIDs

**Comment by fiboknacky** [comment]
Will touch base with Pierrick for the details separately.

**Comment by chiragvels** [comment]
hi @fiboknacky ,

Is there any progress to issue?



Thanks,

**Comment by fiboknacky** [comment]
We're actively working on it.

**Comment by PierrickVoulet** [comment]
Quick update: the performance degradation is mainly coming from the API (server side) and we found a few areas of improvement on the client lib side:

* API: it has been [reverted back to Beta](https://ads-developers.googleblog.com/2019/07/google-ads-api-returning-to-beta.html) to address this really issue. As more updates become available, they will be shared on the [Developer Blog](https://ads-developers.googleblog.com/)
* Client lib: we are working on it and will continue keeping you posted as progress is made

**Comment by PierrickVoulet** [comment]
The PHP implementation of Protobuf is the main performance issue on the client library side: the C implementation of Protobuf is multiple times faster.

So we now clarify the two options and recommend to use the C implementation when possible: #158 and #162.

There is more work to be done on the API side but that's not related to the client library so I am closing this issue.
