### ISSUE TITLE
GetCustomer Function Is No Longer Available in V12

### ISSUE THREAD

**Issue by masabni** [googleads/google-ads-php#860]
Hi, I was using the 12.1.0 version of the package (V9 in the namespace), but now I got response form google api saying
"Version v9 is deprecated. Requests to this version will be blocked." so I updated the package to 17.1 (V12 in the namespace) and now the getCustomer function in CustomerServiceClient is gone.
So, how can I get the customer info by its resource name in the new version?

**Comment by fiboknacky** [comment]
That's intended. It was removed since v10. Please see [this section](https://developers.google.com/google-ads/api/docs/concepts/changing-objects#inspecting_objects_with_get_deprecated) for details.
