### ISSUE TITLE
get Uncaught TypeError: Argument 1 passed to Google\Ads\GoogleAds\Util\FieldMasks::getDescriptorForMessage() must be an instance of Google\Protobuf\Internal\Message, instance of Google\Protobuf\Internal\RepeatedField given

### ISSUE THREAD

**Issue by n00bik** [googleads/google-ads-php#861]
Hello,
I have got
Uncaught TypeError: Argument 1 passed to Google\Ads\GoogleAds\Util\FieldMasks::getDescriptorForMessage() must be an instance of Google\Protobuf\Internal\Message, instance of Google\Protobuf\Internal\RepeatedField given

Use
"googleads/google-ads-php": "^17.1"
Google Ads API version: V12

Composer.json:
`
{
    "require": {
        "phpmailer/phpmailer": "^6.0",
        "smi2/phpclickhouse": "^1.4",
        "phpseclib/phpseclib": "^3.0",
        "firebase/php-jwt": "^6.0",
        "google/apiclient": "^2.0",
        "google/protobuf": "^3.21",
        "googleads/google-ads-php": "^17.1"
    }
}
`

My stack:
PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:30) ( NTS Visual C++ 2017 x64 )
Windows NT S83861 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
Command php -r 'print phpversion("protobuf");' - return nothing
command php -r 'print phpversion("grpc"); - return nothing

Customer id = 3718943174

Thank you in advance for your help

**Comment by fiboknacky** [comment]
What code did you run to generate this error?

**Comment by n00bik** [comment]
> What code did you run to generate this error?

Hello
I use [this ](https://github.com/googleads/google-ads-php/blob/main/examples/AccountManagement/GetChangeDetails.php) code from example folder

**Comment by fiboknacky** [comment]
Thanks for reporting this. I have a fix under review in #868.
