### ISSUE TITLE
Is there an easy way to get a resource based on the resourcename? There must be an easy way, but cannot find it.

### ISSUE THREAD

**Issue by lambertbeekhuis** [googleads/google-ads-php#862]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

**Comment by fiboknacky** [comment]
Since your question is more related to the Google Ads API in general, please post your question on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api). Thank you.
