### ISSUE TITLE
Easy to way get an AdGroupAd (on resourcename?) and modify it

### ISSUE THREAD

**Issue by lambertbeekhuis** [googleads/google-ads-php#863]
Hi,
What is the way to fetch an AdGroupAd (e..g on resourcename), in my case a DiscoveryCarouselAdInfo,
change the DiscoveryCarouselCardAssets and save it again.

**Comment by fiboknacky** [comment]
https://groups.google.com/forum/?nomobile=true#!forum/adwords-api
