### ISSUE TITLE
Editing 'cards' on: Ad ->DiscoveryCarouselAdInfo -> AdDiscoveryCarouselCardAsset -> Asset -> DiscoveryImageAsset

### ISSUE THREAD

**Issue by lambertbeekhuis** [googleads/google-ads-php#864]
How to change the ad by adding or removing 'cards' (as stored in a new AdDiscoveryCardAsset).

I see the example for Campaigns https://developers.google.com/google-ads/api/samples/update-campaign.

But how to handle a new AdDiscoveryCarouselCardAsset, without chaging DiscoveryCarouselAdInfo?

Remove the original Ad and make a new one (how to remove), or change the exiting Ad? (and how?)

Hope someone can help!

**Comment by fiboknacky** [comment]
Could you ask this on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) first? There are experts on the forum that will help answer your question, which is related to the API usage. 

Feel free to get back to us if it's related to the PHP client library.
