### ISSUE TITLE
Get request info after making a call

### ISSUE THREAD

**Issue by ujwaldhakal** [googleads/google-ads-php#865]
**This is just a question not bug !**
**Your client library and Google Ads API versions:**

* Client library version: `v17`

* Google Ads API version: `10`

**Your environment:**

I am using alpine Linux

I am using GRPC as transport to make calls for `uploadingClickConversion`. I have logger in place as well. Whenever I request something I get logs like 

```
/** @var UploadClickConversionsResponse $response */
            $response = $conversionUploadService->uploadClickConversions(
                $customerId,
                $clickConversions,
                true
            );
```

`Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v10.services.ConversionUploadService/UploadClickConversions", CustomerId: xxxxxx, RequestId: "xxxxxxx", IsFault: 0, FaultMessage: "None" [] []`

Everything is working as expected but I am looking for possible ways to get `RequestId` from my request instead of waiting for the logs.   
Is there any way to get `requestId` after making a request?

**Comment by fiboknacky** [comment]
You can pass the option `'withResponseMetadata'` to the method you call like this:

```php
[$response, $status] = $conversionUploadService->uploadClickConversions(
    $customerId,
    $clickConversions,
    true,
    ['withResponseMetadata' => true]
);
```

(Note that the method will return an array now. The first member is a response like before. The second member is a status)

`$status` will contain an array like this:

```
object(Google\Ads\GoogleAds\Lib\V12\GoogleAdsResponseMetadata)#51 (1) {
  ["metadata":"Google\Ads\GoogleAds\Lib\V12\GoogleAdsResponseMetadata":private]=>
  array(17) {
    ["content-disposition"]=>
    array(1) {
      [0]=>
      string(10) "attachment"
    }
    ["request-id"]=>
    array(1) {
      [0]=>
      string(22) "REQUEST_ID"
    }
    ...
}
```

Then, you can extract the request ID from it like [this](https://github.com/googleads/google-ads-php/blob/5fb1df4f9c3e4108a413d749ca8ea7244225c747/src/Google/Ads/GoogleAds/Lib/V12/GoogleAdsResponseMetadata.php#L57). The request ID is in an array with the key 'request-id'.

**Comment by ujwaldhakal** [comment]
Would it be helpful if we could document these?

**Comment by fiboknacky** [comment]
Yep, I plan to do so. Thanks for your suggestion.

**Comment by fiboknacky** [comment]
The tip is now available at [Response Metadata](https://developers.google.com/google-ads/api/docs/client-libs/php/response-metadata).

**Comment by ujwaldhakal** [comment]
Thanks, This is very helpful @fiboknacky
