### ISSUE TITLE
"Error occurred during parsing: Unexpected wire type."

### ISSUE THREAD

**Issue by rdeveloper1925** [googleads/google-ads-php#867]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your client library and Google Ads API versions:**

* Client library version: `v12.1`

* Google Ads API version: `V12`

**Your environment:**

PHP 7.3.33 (cli) (built: Oct 24 2022 07:42:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33, Copyright (c) 1999-2018, by Zend Technologies

**Description of the bug:**
I am trying to use [List accessible customers](https://developers.google.com/google-ads/api/samples/list-accessible-customers) code snippet from the documentation, however i run into an error "Error occurred during parsing: Unexpected wire type." at the point of initializing the `$googleadsclient`:
`$googleAdsClient = (new GoogleAdsClientBuilder())->fromFile()
            ->withOAuth2Credential($oAuth2Credential)
            ->build();`

**Steps to reproduce:**
Try to list accessible customers using the code snippet at https://developers.google.com/google-ads/api/samples/list-accessible-customers

**Expected behavior:**
To List the resource names for the customers that the authenticating user has access to.

**Comment by fiboknacky** [comment]
Could you please share what protobuf version you use?
