### ISSUE TITLE
How to update Ads API v10 to V12

### ISSUE THREAD

**Issue by publish-web** [googleads/google-ads-php#872]
Hi,

I'm using Ads API v10 but I need to update for V12 before February 1st.

I run "composer update" but still doesn't have "V12" folder in vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds
What is the instruction ?

I'm beginner with usage of composer...

Thank you!

**Comment by fiboknacky** [comment]
The easiest way would be removing the `vendor/googleads/google-ads-php/` directory and run the command again. Could you please try?

**Comment by publish-web** [comment]
Thanks for your answer! I removed the vendor/googleads/google-ads-php/ directory and run these commands :

- git clone https://github.com/googleads/google-ads-php.git
- cd google-ads-php
- sudo composer install

The directory "google-ads-php" has been added in /home/ubuntu/ but not in vendor/googleads/

What is the problem? Am I missed a command line?

Thank you

**Comment by fiboknacky** [comment]
The steps you followed are for trying our code examples, but if you'd like to use this library as your project's dependency, it  should be:

* Change to your project directory
* Run `composer require googleads/google-ads-php`

It should install the main branch of this library to your `vendor/`.

**Comment by publish-web** [comment]
It works! Thanks so much for your help!

Have a good day :)
