### ISSUE TITLE
The error of Login Customer Id when creating the campaign budget

### ISSUE THREAD

**Issue by ujas-prom** [googleads/google-ads-php#876]
Hello Team,

I have a problem with `login-customer-id` with the below versions of the library,

**My client library and Google Ads API versions:**

* Client library version: `v17.1.0`

* Google Ads API version: `V12`

I already mentioned my account manager's customer id in the `google_adsapi.ini` file as the below variable which developer token I used,
`loginCustomerId = "2215293344"`

**Note: Already my manager accounts have basic access to developer tokens.**

Now, I create a campaign budget for my client, I passed his Google Ads account customer Id and its showed me the error below,

`Google\ApiCore\ApiException {#13541
  #message: """
    {
        "message": "The caller does not have permission",
        "code": 7,
        "status": "PERMISSION_DENIED",
        "details": [
            {
                "@type": "type.googleapis.com\/google.ads.googleads.v12.errors.GoogleAdsFailure",
                "errors": [
                    {
                        "errorCode": {
                            "authorizationError": "USER_PERMISSION_DENIED"
                        },
                        "message": "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https:\/\/developers.google.com\/google-ads\/api\/docs\/concepts\/call-structure#cid"
                    }
                ],
                "requestId": "r8gurevOJcJjN8XrnFX9Gg"
            }
        ]
    }`

Also, I build my `GoogleAdsClientBuilder` with pass manual login customer id as the below and checked with that to create a campaign budget but still, same issues occur,

`$oAuth2Configuration = (new ConfigurationLoader())->fromFile($storagepath);
$oAuth2Credential = (new OAuth2TokenBuilder())->from($oAuth2Configuration)->build();
$googleAdsClient = (new GoogleAdsClientBuilder())
                    ->from($oAuth2Configuration)
                    ->withOAuth2Credential($oAuth2Credential)
                    ->withLoginCustomerId(2215293344)
                    ->build();`

I have integrated the below code for **create campaign budget**,
`$uniqId = uniqid();
  $budget = new CampaignBudget([
      'name' => 'Interplanetary Cruise Budget #' . $uniqId,
      'delivery_method' => BudgetDeliveryMethod::STANDARD,
      'amount_micros' => $amount * 1000000
  ]);
  $campaignBudgetOperation = new CampaignBudgetOperation();
  $campaignBudgetOperation->setCreate($budget);
  $campaignBudgetServiceClient = $googleAdsClient->getCampaignBudgetServiceClient();
  $response = $campaignBudgetServiceClient->mutateCampaignBudgets(
      $customerId,
      [$campaignBudgetOperation]
  );
  $createdBudget = $response->getResults()[0];`

Note: I passed my client's Google Ads account customer Id into $customerId.

**Comment by fiboknacky** [comment]
Since the issue is related to the API in general, could you please ask on the [Google Ads API forum](https://groups.google.com/g/adwords-api)? There'll be our experts helping you shortly.
