### ISSUE TITLE
Error after composer

### ISSUE THREAD

**Issue by andreaboccaforno** [googleads/google-ads-php#877]
Hello to all,
i have run all project via ssh, but after when i open a file, i have this error:

Parse error: syntax error, unexpected identifier "Level" file online 32.

Someone can help me?

**Comment by fiboknacky** [comment]
Could you tell us more? What project you're running? What's the code of the file you're trying to open?
Did you follow the steps [here](https://github.com/googleads/google-ads-php#getting-started) to get started?
