### ISSUE TITLE
How to upgrade the version?

### ISSUE THREAD

**Issue by anilerogul** [googleads/google-ads-php#882]
Hello all,

I use v10 now and it's deprecated today so I get **"response >>> Request with ID 'xxx' has failed. Google Ads failure details: request_error: Version v10 is deprecated. Requests to this version will be blocked."** this error when I send a request to API. 

I don't know how to upgrade the version to v12 or v13. Do I just have to replace composer.json and run composer install or is there something else to do? I searched a lot for this but couldn't find a solution. 

https://developers.google.com/google-ads/api/docs/upgrade this link is not useful for me.

Can anyone please help me? Thanks in advance for your help.

**Comment by fiboknacky** [comment]
Could you tell me more how you installed this library for your project?

**Comment by anilerogul** [comment]
Actually I did not install it, another software developer working in the company installed it, but he is not working here at the moment. My guess, he has installed it as described in the readme file (https://github.com/googleads/google-ads-php/blob/main/README.md), using composer.

**Comment by fiboknacky** [comment]
Thanks for the context. Could you at least how you use this library with your project like how it's put under your project's root directory?

**Comment by anilerogul** [comment]
We use the library's functions as an API. We send requests to make changes on Google Ads side. Then making changes according to responses on our side. It's not in root directory, it has own directory. As I know, we used composer install command to put it under its own directory.

I will run `composer update`, thanks again.
