### ISSUE TITLE
Root composer.json requires PHP extension ext-protobuf * but it is missing from your system. Install or enable PHP's protobuf extension.

### ISSUE THREAD

**Issue by suhailansari2019** [googleads/google-ads-php#883]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**
Not able to run composer insall show me the error mention above I try to install the protobuf extention but not able to solve my issue can you please help me in this?

**Comment by fiboknacky** [comment]
How did you try to install protobuf and what was the error message when you did so?

**Comment by fiboknacky** [comment]
Closed due to inactivity.
