### ISSUE TITLE
Changing request behavior with "Request contains an invalid argument." exception

### ISSUE THREAD

**Issue by irigney** [googleads/google-ads-php#884]
**Your client library and Google Ads API versions:**

* Client library version: `v10.0.0`

* Google Ads API version: `V10`

**Your environment:**
PHP 8.0.26 (cli) (built: Dec  5 2022 21:59:43) ( NTS )
Linux debianserver 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13)
3.19.4
1.39.0

**Your question:**

Hello, I have some problem with API
I'm creating googleAdsClient in this way
$oAuth2Credential = (new OAuth2TokenBuilder())
	->fromFile($file)
	->withClientId($clientId)
	->withClientSecret($clientSecret)
	->withRefreshToken($refreshToken)
	-> build();
$googleAdsClient = (new GoogleAdsClientBuilder())
	->withDeveloperToken($devToken)
	->withOAuth2Credential($oAuth2Credential)
	->build();
And after that i`m trying to achieve accessibleCustomers
$customerServiceClient = $googleAdsClient->getCustomerServiceClient();
$accessibleCustomers = $customerServiceClient->listAccessibleCustomers(); 
And at some point, such exception appears:
  Google\ApiCore\ApiException: {
      "message": ,
      "code": 3,
      "status": "INVALID_ARGUMENT",
      "details": [
          {
              "@type": "google.ads.googleads.v10.errors.googleadsfailure-bin",
              "data": "Unknown Binary Data>"
          },
          {
              "@type": "grpc-status-details-bin",
              "data": "Unknown Binary Data>"
          },
          {
              "@type": "request-id",
              "data": "pVh0lCVpoArEABvURws8iA"
          }
      ]
  }
But after some attempts it works with return of:
Google\Ads\GoogleAds\V10\Services\ListAccessibleCustomersResponse Object
I have the same mistake for different request, but this request is the simplest
Here is the request-id for the similar error, maybe it will be helpfull: FeJLsSn7aBgzZ8zC4A3O8g
I will be very grateful for your help
Thank you for your time.

 
**Anything else we should know about your project / environment:**

**Comment by fiboknacky** [comment]
v10 of Google Ads API is [already sunset](https://ads-developers.googleblog.com/2023/01/google-ads-api-v10-sunset-reminder.html). Please migrate to the [latest version](https://developers.google.com/google-ads/api/docs/release-notes#v13) as soon as possible.
You can check the sunset schedule [here](https://developers.google.com/google-ads/api/docs/sunset-dates#timetable).
