### ISSUE TITLE
All requests returned '400 Bad Request'

### ISSUE THREAD

**Issue by lait1989** [googleads/google-ads-php#885]
Hi! I want to get campaigns from google ads. I created a file google_ads_php.ini in my homepath with credentials, i saw that credentials when debug request in phpstorm. 

Request
`php google-ads-php\examples\AccountManagement\GetAccountHierarchy.php`

Return
`PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}`

Credentials are correct and worked with version 10 of google ads api, but not it is not supported and i try to use it with 13 version.

**Comment by fiboknacky** [comment]
Could you try regenerating a new refresh token? 
Since the issue is likely to be related to the OAuth settings, if the issue persists, could you seek help in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)? Thanks.

**Comment by fiboknacky** [comment]
Closed due to inactivity.
