### ISSUE TITLE
Unable to call to undefined method getRealContainingOneof

### ISSUE THREAD

**Issue by Albertopipo** [googleads/google-ads-php#891]
While trying to update our version of the google-ads-php library to the latest version, v19, we've been facing a problem with the classes in the vendor library that we haven't been able to solve.
Basically, whenever we try to use the FieldMasks utility, more specifically its allSetFieldsOf() static function, we get the following error:

Attempted to call an undefined method named "getRealContainingOneof" of class "Google\Protobuf\FieldDescriptor".

Which is to say, it is as if the class FieldDescriptor didn't contain the getRealContainingOneof() method, except the method appears to be implemented in the class. We considered the possibility that it might be a namespace issue of the class FieldDescriptor, but as far as we can tell, the class methods that return simple types (getName and such) are functional - it's only the methods that would return a Protobuf type message that fail.

If it helps, these are the current versions of the related vendor libraries we're running:

PHP 8.0
Symfony 5.2.14
Google Ads Api V13
Google ads php 19.0.9
Google protobuf 3.22.2

**Comment by fiboknacky** [comment]
Could you please tell me more what [protobuf implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf) (C or PHP) do you use?
Does it happen when you run a basic example like [UpdateCampaign](https://github.com/googleads/google-ads-php/blob/main/examples/BasicOperations/UpdateCampaign.php) too?

**Comment by fiboknacky** [comment]
Could you please share your code to reproduce, then? Thanks.

**Comment by sergey178** [comment]
+ Same problem
Fatal error: Uncaught Error: Call to undefined method Google\Protobuf\FieldDescriptor::getRealContainingOneof() in
protobuf - 3.20.1
PHP Version 7.4.28

$adOperation = new AdOperation();
$adOperation->setUpdate($ad);
$adOperation->setUpdateMask(FieldMasks::allSetFieldsOf($ad));

**Comment by Albertopipo** [comment]
Hello, 
Is there any news regarding this issue?
Thanks

**Comment by fiboknacky** [comment]
Sorry for keeping you waiting.
I tried it with protobuf 3.22.3 but couldn't reproduce your reported issue when using the code in [your comment above](https://github.com/googleads/google-ads-php/issues/891#issuecomment-1504985139).

Can you try upgrading to 3.22.3 first? To be 100% sure, you can remove the protobuf directories in `vendor/` first. Then, after upgrading, check your `composer.lock` to be sure that it's 3.22.3.
If your problem still persists, could you share what the code of `FieldDescriptor` in your `vendor/` looks like?

Apart from that, some of your other dependencies or projects may fix your protobuf to the older versions than that, or have their own protobuf versions that can silently overwrite the version you think you're using too. You may double-check if that's the case.

**Comment by sergey178** [comment]
> Sorry for keeping you waiting. I tried it with protobuf 3.22.3 but couldn't reproduce your reported issue when using the code in [your comment above](https://github.com/googleads/google-ads-php/issues/891#issuecomment-1504985139).
> 
> Can you try upgrading to 3.22.3 first? To be 100% sure, you can remove the protobuf directories in `vendor/` first. Then, after upgrading, check your `composer.lock` to be sure that it's 3.22.3. If your problem still persists, could you share what the code of `FieldDescriptor` in your `vendor/` looks like?
> 
> Apart from that, some of your other dependencies or projects may fix your protobuf to the older versions than that, or have their own protobuf versions that can silently overwrite the version you think you're using too. You may double-check if that's the case.

It helped me. Thanks.

**Comment by Albertopipo** [comment]
Hello,
I tried to upgrado to protobuf's 3.22.3 and the problem still persists. I even tried deleting the whole vendor and installing it again.
My FieldDescriptor's code is the following:

As you will see, it contains the getRealContainingOneof mentioned previously, but FieldMasks.php has trouble finding it.

<?php

// Protocol Buffers - Google's data interchange format
// Copyright 2017 Google Inc.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

namespace Google\Protobuf;

use Google\Protobuf\Internal\GetPublicDescriptorTrait;
use Google\Protobuf\Internal\GPBType;

class FieldDescriptor
{
    use GetPublicDescriptorTrait;

    /** @var  \Google\Protobuf\Internal\FieldDescriptor $internal_desc */
    private $internal_desc;

    /**
     * @internal
     */
    public function __construct($internal_desc)
    {
        $this->internal_desc = $internal_desc;
    }

    /**
     * @return string Field name
     */
    public function getName()
    {
        return $this->internal_desc->getName();
    }

    /**
     * @return int Protobuf field number
     */
    public function getNumber()
    {
        return $this->internal_desc->getNumber();
    }

    /**
     * @return int
     */
    public function getLabel()
    {
        return $this->internal_desc->getLabel();
    }

    /**
     * @return int
     */
    public function getType()
    {
        return $this->internal_desc->getType();
    }

    /**
     * @return OneofDescriptor
     */
    public function getContainingOneof()
    {
        return $this->getPublicDescriptor($this->internal_desc->getContainingOneof());
    }

    /**
     * Gets the field's containing oneof, only if non-synthetic.
     *
     * @return null|OneofDescriptor
     */
    public function getRealContainingOneof()
    {
        return $this->getPublicDescriptor($this->internal_desc->getRealContainingOneof());
    }

    /**
     * @return boolean
     */
    public function hasOptionalKeyword()
    {
        return $this->internal_desc->hasOptionalKeyword();
    }

    /**
     * @return Descriptor Returns a descriptor for the field type if the field type is a message, otherwise throws \Exception
     * @throws \Exception
     */
    public function getMessageType()
    {
        if ($this->getType() == GPBType::MESSAGE) {
            return $this->getPublicDescriptor($this->internal_desc->getMessageType());
        } else {
            throw new \Exception("Cannot get message type for non-message field '" . $this->getName() . "'");
        }
    }

    /**
     * @return EnumDescriptor Returns an enum descriptor if the field type is an enum, otherwise throws \Exception
     * @throws \Exception
     */
    public function getEnumType()
    {
        if ($this->getType() == GPBType::ENUM) {
            return $this->getPublicDescriptor($this->internal_desc->getEnumType());
        } else {
            throw new \Exception("Cannot get enum type for non-enum field '" . $this->getName() . "'");
        }
    }

    /**
     * @return boolean
     */
    public function isMap()
    {
        return $this->internal_desc->isMap();
    }
}

**Comment by fiboknacky** [comment]
Hmm... Do you use any IDEs? What happens when you trace the `getRealContainingOneof` method? Does it link to a correct file?

**Comment by Albertopipo** [comment]
Hello, 

After updating the Google Ad's api version it seems that we had some mix between C's and PHP's implementation and we had both  'working' at the same time. We deleted the C version completely and now it seems to work.

Thanks for your time and sorry for all the trouble.

**Comment by fiboknacky** [comment]
That's what I thought that there might be a mix between implementations. Sorry that I didn't think of this early. Anyway, I'm happy that you could resolve the issue.
