### ISSUE TITLE
getAuthorizationHeaderCallback must with params authHttpHandler

### ISSUE THREAD

**Issue by hhniao** [googleads/google-ads-php#898]
when i cant access googleapis, i need proxy for it.
in this file vendor/google/gax/src/CredentialsWrapper.php:212
`return $credentialsFetcher->updateMetadata([], $audience);`
i need change it to:
`return $credentialsFetcher->updateMetadata([], $audience, $authHttpHandler);`

**Comment by fiboknacky** [comment]
That part belongs to `gax-php`. Could you please [file a request on that repository](https://github.com/googleapis/gax-php/issues/new/choose) instead?
