### ISSUE TITLE
LinkedCustomerId header is not set when using GoogleAdsClientBuilder

### ISSUE THREAD

**Issue by heyhsieh** [googleads/google-ads-php#902]
* Client library version: `19.1.0`

* Google Ads API version: `13`

**Description of the bug:**
The linked customer id header is not sent when it is configured via the GoogleAdsClientBuilder. Calling withLinkedCustomerId will set the linkedCustomerId property in the builder. However the headers are set by the addFixedHeaderMiddleware method in GoogleAdsGapicClientTrait, which sets the developer token and login customer id headers but doesn't account for the linked customer id [LINK](https://github.com/googleads/google-ads-php/blob/1a45e844d224638f7ff1bb15b0a05331540df3e1/src/Google/Ads/GoogleAds/Lib/V13/GoogleAdsGapicClientTrait.php#L87).

I found a similar issue that was reported for login-customer-id [LINK](https://github.com/googleads/google-ads-php/issues/25).

**Comment by fiboknacky** [comment]
Fixed with [v20.1.0](https://github.com/googleads/google-ads-php/releases/tag/v20.1.0)
