### ISSUE TITLE
api end points to get all conversion action 

### ISSUE THREAD

**Issue by skant2111** [googleads/google-ads-php#903]
I am searching for the google ads api which can give me all conversion action for the specific ads account.

example : 
url = https://googleads.googleapis.com/v12/customers/['customer_id']/conversionActions
method = GET

**Comment by skant2111** [comment]
question

**Comment by fiboknacky** [comment]
Your question is related to the Google Ads API product, so please ask on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api). Thank you.

**Comment by skant2111** [comment]
Thanks @fiboknacky
