### ISSUE TITLE
Capitalxtends.com

### ISSUE THREAD

**Issue by Capitalxtends** [googleads/google-ads-php#904]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Problem you are trying to solve:**

**Solution you'd like:**

**Alternatives you've considered:**

**Additional context:**

**Comment by fiboknacky** [comment]
Looks like this was created by mistake, so I close it.
