### ISSUE TITLE
v19.0.0 GRPC resulting in status code 14, 403 Forbidden in some requests to API V13

### ISSUE THREAD

**Issue by jeffersoncechinel** [googleads/google-ads-php#917]
**Your client library and Google Ads API versions:**

* Client library version: `v19.0.0`

* Google Ads API version: `V13`

**Your environment:**

* The PHP version: 7.4.21.
* The name and version of the operating system: Linux 5.15.0-72-generic Ubuntu SMP x86_64.
* Whether the PHP Extension `protobuf` is used or not: 3.22.1.
* Whether the PHP Extension `grpc` is used or not: 1.53.0.
* The type of transport being used (`grpc` or `rest`): grpc

**Description of the bug:** Most of the time, my requests go through, but occasionally, my requests to the Google ADS API V13 are blocked with just a Status code 14 and a 403 forbidden code. The reasons for the blockage are never indicated. A thread in Google Ads API Forum is already created as seen here: https://groups.google.com/g/adwords-api/c/dY7sIBHq9h4 but the API's guys could not identify the problem on their side and suggested to contact the library owner.

**Steps to reproduce:** I could not reproduce the problem. It happens sometimes with no particular reason.

**Expected behavior:** The expected behavior is the request to go through or at least show an explanation for the error response. 

**Request/Response Logs:** Since its a HTTP error this is the only logs I have:

```
[2023-06-14T16:58:33.129510-04:00] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v13.services.GoogleAdsService/Search", CustomerId: ****, RequestId: "", IsFault: 1, FaultMessage: "None"
[2023-06-14T16:58:33.129848-04:00] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v13.services.GoogleAdsService/Search
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.4.21 gccl\/19.0.0 gapic\/19.0.0 gax\/1.19.0 grpc\/1.53.0 rest\/1.19.0 pb\/3.22.1+c",
    "x-goog-request-params": "customer_id=****",
    "developer-token": "REDACTED",
    "login-customer-id": "****"
}
Request:
{"customerId":"****","query":"SELECT \n            ad_group_criterion.criterion_id,\n            ad_group.id,\n            segments.date,\n            metrics.clicks,\n            metrics.impressions,\n            metrics.average_cpc,\n            metrics.cost_micros,\n            metrics.historical_quality_score,\n            ad_group_criterion.position_estimates.first_page_cpc_micros            \n            FROM keyword_view\n            WHERE segments.date BETWEEN '2023-06-14' AND '2023-06-14'\n                AND metrics.impressions > 0"}

Response
-------
Headers: []

Fault
-------
Status code: 14
Details: 403:Forbidden
Failure: {}
```
The problem is not specific for the google.ads.googleads.v13.services.GoogleAdsService/Search method, it occurs on other methods as well.

Thank you.

**Comment by fiboknacky** [comment]
It seems the issue is intermittently occurring? Do you see any patterns of the issue, like the time of the day? Does it occur with any types of query when using GoogleSearch?

In addition, do you use a proxy? That can also be a cause too.

**Comment by jeffersoncechinel** [comment]
Yes it is intermittently occurring. I don't see any patterns, it happens in different times of day. I can confirm it is happening with different queries in GoogleAdsService/Search. My application is running in a Kubernetes cluster with no proxy or any type of egress.

Just to give you some more background. I have workers than run in parallel requesting different types of queries in GoogleAdsService/Search. At first I thought that could be a rate limiting issue but the error response does not not mention anything related to rate limiting. Perhaps the library is not treating rate limiting well from the API so it gives a different error response to the user? It is just a thought.

**Comment by fiboknacky** [comment]
> Just to give you some more background. I have workers than run in parallel requesting different types of queries in GoogleAdsService/Search. At first I thought that could be a rate limiting issue but the error response does not mention anything related to rate limiting. Perhaps the library is not treating rate limiting well from the API so it gives a different error response to the user? It is just a thought.

That's a possible cause. Unfortunately, the server may not always return the exact rate limiting error back. The forbidden error is something I occasionally see, although it's not quite often.

**Comment by Sanchit33** [comment]
it seems that credentials might be incorrect or the data that you queried might not be present at that instance, I might be naive so sorry in advance! just wanted to help if it counts.

**Comment by jeffersoncechinel** [comment]
Hi there! I managed to make it work. I had to add a delay for the jobs and it seems to have fixed the problem. Strange thing is that it was never needed before and also the API's guys did not find or mention anything related to rate limiting. I will close this issue for now. Thank you very much for you help!
