### ISSUE TITLE
No result - GenerateKeywordForecastMetricsRequest V14

### ISSUE THREAD

**Issue by mnk85** [googleads/google-ads-php#918]
Hey all , 

i try to use the new "GenerateKeywordForecastMetricsRequest" with the **V14 Library**. But impossible to get **any result**... Below i show you all my steps. I do a mistake ?

Actualy "$requestGenerateKeywordForecastMetrics" print nothing. At the end i try too something like :
"$service_forecastresponse = $googleAdsClient->generateKeywordForecastMetrics($requestGenerateKeywordForecastMetrics);"
but "generateKeywordForecastMetrics" don't exist in "googleAdsClient"

**Comment by fiboknacky** [comment]
It seems you're new to the Google Ads API. I'd recommend you go through [some examples](https://github.com/googleads/google-ads-php/blob/main/examples/) first to get the idea of how to use it.
In short, for your case, you cannot just create `GenerateKeywordForecastMetricsRequest` and expect that it'll return something. You need to send the request to the API server first and process the returned response.

We're planning to add an example of using `GenerateKeywordForecastMetrics` soon, but we have no ETAs yet. The closest one is [GenerateKeywordIdeas](https://github.com/googleads/google-ads-php/blob/main/examples/Planning/GenerateKeywordIdeas.php).

**Comment by mnk85** [comment]
Im not new but yes i write the full code without any exemple (not yet available ). 

Is not possible to give me the way of my error? or i am so far of what i need to do ?

If i to far, maybe make a very basic simple exemple ( they can help a lot of people waiting for official examples) with the step like i do in my code (Step 1 : X call, step 2; call V class, ...)

Thanks for your time
PS: not only me looking for that in the dev forum

**Comment by fiboknacky** [comment]
The closest example is [GenerateKeywordIdeas](https://github.com/googleads/google-ads-php/blob/main/examples/Planning/GenerateKeywordIdeas.php).
Could you please check that example first? The steps are pretty much the same.

The main difference is that you need to call `generateKeywordForecastMetrics` instead of `generateKeywordIdeas`.

**Comment by mnk85** [comment]
I try right now something like :
`
$requestGenerateKeywordForecastMetrics = new GenerateKeywordForecastMetricsRequest();
$requestGenerateKeywordForecastMetrics->setCustomerId($customerId);
$requestGenerateKeywordForecastMetrics->setForecastPeriod($a);
$requestGenerateKeywordForecastMetrics->setCampaign($campaigntoforecast);

**$forecast_query = $googleAdsClient->generateKeywordForecastMetrics($requestGenerateKeywordForecastMetrics);**
`
But i get "Call to undefined method Google\\Ads\\GoogleAds\\Lib\\V14\\GoogleAdsClient::generateKeywordForecastMetrics()"

It's why i think i made a mistake in the "basic" call, not the parameters.

**Comment by mnk85** [comment]
You tell me to first create "KeywordPlanIdeaService" like :
```
$keywordPlanIdeaServiceClient = $googleAdsClient->getKeywordPlanIdeaServiceClient();
```
But when i read the [documentation](https://developers.google.com/google-ads/api/docs/keyword-planning/generate-forecast-metrics#php), they say :

To generate forecast metrics, complete these steps:

**1 -** Construct a campaign that you want to forecast [CampaignToForecast](https://developers.google.com/google-ads/api/reference/rpc/v14/CampaignToForecast).
Like i do in my first comment ( where i set all the parameters)

**2 -** Call [KeywordPlanIdeaService.GenerateKeywordForecastMetrics] **with that CampaignToForecast** and any other parameters, such as forecast_period.

Where i did 
```
$requestGenerateKeywordForecastMetrics = new GenerateKeywordForecastMetricsRequest();
$requestGenerateKeywordForecastMetrics->setCustomerId($customerId);
$requestGenerateKeywordForecastMetrics->setForecastPeriod($a);
$requestGenerateKeywordForecastMetrics->setCampaign($campaigntoforecast);
```

I know what i did is wrong ( is not working so ...), i read 4 times your exemples ( the close one [GenerateKeywordIdeas])
And im confused because is not like the documentation so im still stuck.

**Comment by fiboknacky** [comment]
Sorry but the example is on the way. It may not be ready soon. I'll help you as much as I can now.

Let me share a tip in case you wish to do coding by your own.
Whenever you use a new class, you should probably see the code first.
In this case, I recommend you to use `KeywordPlanIdeaServiceClient`, right?

What you have to do is to search for that class on this repository.
You'll see that it's [here](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/KeywordPlanIdeaServiceClient.php), which links to the core class [`KeywordPlanIdeaServiceGapicClient`]
(https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php).

In [`KeywordPlanIdeaServiceGapicClient`]
(https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php), you can see that the method that you should use is `generateKeywordForecastMetrics`. It has the following signature:

```php
public function generateKeywordForecastMetrics($campaign, array $optionalArgs = [])
```

So, you need to pass `$campaignToForecast`  as the first argument to the method, NOT in an array.
And in the PHP document above it, you can see that other information like `$customerId` should go into an array.

So, a correct version should be:

```php
$keywordPlanIdeaServiceClient = $googleAdsClient->getKeywordPlanIdeaServiceClient();
$response = $keywordPlanIdeaServiceClient->generateKeywordForecastMetrics(
    $campaigntoforecast,
    ['customerId' => $customerId, 'forecastPeriod' => $daterange]
);
```

Note that the key in the array is case-sensitive. You should spell exactly as it says in the code, not with a capital letter.
Finally, I'd recommend naming a variable in a readable way.
In your code you name `$googleAdsClient->getKeywordPlanIdeaServiceClient();` as `requestGenerateKeywordForecastMetrics`. This could be confusing and less readable in the future.
You're getting a service client, so let's name it `$keywordPlanIdeaServiceClient`.

**Comment by mnk85** [comment]
Thanks @fiboknacky !
**This is a real answer :)**

For now i get the error below. For testing i **only put the "required" settings** to the campaign to eliminate the possibility but still this error. I don't know if it's a bug or still me. 

"message": "{\n    \"message\": \"Request contains an invalid argument.\",\n    \"code\": 3,\n    \"status\": \"INVALID_ARGUMENT\",\n    \"details\": [\n        {\n            \"@type\": \"google.ads.googleads.v14.errors.googleadsfailure-bin\",\n            \"data\": \"<Unknown Binary Data>\"\n        },\n        {\n            \"@type\": \"grpc-status-details-bin\",\n            \"data\": \"<Unknown Binary Data>\"\n        },\n        {\n            \"@type\": \"request-id\",\n            \"data\": \"bsUqQ0BFHXYR1Bz-cYz4HQ\"\n        }\n    ]\n}",

**Comment by mnk85** [comment]
Just if you can give the way for print the result. I get the good return in the log file but i didn't find the way to print the result.
Is not like (with the adaption needed clickThroughRate, impressions, ... ) :
```
 foreach ($response->iterateAllElements() as $result) {
            /** @var GenerateKeywordIdeaResult $result */
            // Note that the competition printed below is enum value.
            // For example, a value of 2 will be returned when the competition is 'LOW'.
            // A mapping of enum names to values can be found at KeywordPlanCompetitionLevel.php.
            printf(
                "Keyword idea text '%s' has %d average monthly searches and competition as %d.%s",
                $result->getText(),
                is_null($result->getKeywordIdeaMetrics()) ?
                    0 : $result->getKeywordIdeaMetrics()->getAvgMonthlySearches(),
                is_null($result->getKeywordIdeaMetrics()) ?
                    0 : $result->getKeywordIdeaMetrics()->getCompetition(),
                PHP_EOL
            );
        }
        ```

**Comment by fiboknacky** [comment]
About [this comment](https://github.com/googleads/google-ads-php/issues/918#issuecomment-1600863293), what did you get in the log file? (Make sure to redact sensitive information please)

**Comment by mnk85** [comment]
Method Name: /google.ads.googleads.v14.services.KeywordPlanIdeaService/GenerateKeywordForecastMetrics
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.4.33 gccl\/19.2.0 gapic\/19.2.0 gax\/1.19.1 grpc\/1.41.0 rest\/1.19.1 pb\/+n",
    "x-goog-request-params": "customer_id=MYCUSTOMERID",
    "developer-token": "REDACTED",
    "login-customer-id": "MYCUSTOMERID"
}
Request: 
{"customerId":"MYCUSTOMERID","forecastPeriod":{"startDate":"2023-06-22","endDate":"2023-09-19"},"campaign":{"languageConstants":["languageConstants\/1002"],"geoModifiers":[{"geoTargetConstant":"geoTargetConstants\/2250"}],"keywordPlanNetwork":"GOOGLE_SEARCH","biddingStrategy":{"maximizeClicksBiddingStrategy":{"dailyTargetSpendMicros":"31500000"}},"adGroups":[{"biddableKeywords":[{"keyword":{"text":"rent a car","matchType":"BROAD"}}]}]}}

Response
-------
Headers: {
    "content-disposition": "attachment",
    "request-id": "hVXNGKqZMrl0zqTC8cavOA",
    "date": "Wed, 21 Jun 2023 13:37:03 GMT",
    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
}
Response: 
{"campaignForecastMetrics":{"impressions":97137.8046875,"clickThroughRate":0.1738574355840683,"averageCpcMicros":"167869","clicks":16888.12890625,"costMicros":"2835000090","conversions":1888.0377197265625,"conversionRate":0.11179673671722412,"averageCpaMicros":"1501559"}}

**Comment by fiboknacky** [comment]
Could you check the code? What's the returned type of [`generateKeywordForecastMetrics`](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php#L277)
If you follow that you'll be able to see what method you should use.

Hint: See [this line](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php#L273).

**Comment by mnk85** [comment]
You mean i need to use the class "GenerateKeywordForecastMetricsResponse" for print the result of [generateKeywordForecastMetrics] ?

It's look like "GenerateKeywordForecastMetricsResponse" already use "GenerateKeywordForecastMetricsResponse" on his object return.

return $this->startCall('GenerateKeywordForecastMetrics', GenerateKeywordForecastMetricsResponse::class, $optionalArgs, $request)->wait();

**Comment by fiboknacky** [comment]
> You mean i need to use the class "GenerateKeywordForecastMetricsResponse" for print the result of [generateKeywordForecastMetrics] ?

Yes.

> You mean i need to use the class "GenerateKeywordForecastMetricsResponse" for print the result of [generateKeywordForecastMetrics] ?
> It's look like "GenerateKeywordForecastMetricsResponse" already use "GenerateKeywordForecastMetricsResponse" on his object return.
> return $this->startCall('GenerateKeywordForecastMetrics', GenerateKeywordForecastMetricsResponse::class, $optionalArgs, $request)->wait();

Nope. It seems you misunderstand how to read the generated code.
Please focus on the line that I mentioned above. This is the same for all other methods that you may use in the future.

**Comment by mnk85** [comment]
"misunderstand how to read the generated code." Correct :D
 Is why i ask you the way before the official exemple.

 I already do a lot without exemple. Now i just need to understand how to get the results , it's the end but you want me to think again, I understand :D

**Comment by mnk85** [comment]
I still didn't find the good way for get the result ...
This is not working:
```
 print_r($forecastresponse->getCampaignForecastMetrics()->getClickThroughRate());
```
 This show all the object  "print_r($forecastresponse"

**Comment by fiboknacky** [comment]
What do you mean by "show all the object"?

**Comment by mnk85** [comment]
i want to print all the result like :
```
$forecastresponse = $forecastquery->generateKeywordForecastMetrics(
                $campaigntoforecast,
                [
                'customerId' => $customerId,
                'forecastPeriod' => $date_range
                ]
        );
         foreach ($forecastresponse->getCampaignForecastMetrics() as $forecast) {
 echo "Impressions: " . $forecast->getImpressions() . "\n";
            echo "Clicks: "  . $forecast->getClicks() . "\n";
            echo "Cost: " . $forecast->getCostMicros() . "\n";
            echo "Conversions: " . $forecast->getConversions() . "\n";
            echo "getClickThroughRate" . $forecast->getClickThroughRate() . "\n";
        ```

**Comment by fiboknacky** [comment]
Again, please read [the code](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/GenerateKeywordForecastMetricsResponse.php#L44). I know the name could be confusing, but it's not an array. It's an object of `KeywordForecastMetrics`.

**Comment by fiboknacky** [comment]
Yes, you're right that it shouldn't have a loop.
So, do you mean the code below fails? If so, can you share the error message?

```php
$metrics = $forecastresponse->getCampaignForecastMetrics();
echo "Impressions: " . $metrics->getImpressions() . "\n";
echo "Click-through rate: " . $metrics->getClickThroughRate() . "\n";
```

**Comment by mnk85** [comment]
It's OK , i find this before but i think we can get the cost per keyword like before.
Apparently this is no longer possible, we only have the data for the campaign
