### ISSUE TITLE
Similar problem as with v1_2 release 

### ISSUE THREAD

**Issue by MaksTech** [googleads/google-ads-php#92]
So this issue is somewhat similar to #66.

For this to make sense, the logic goes like this:

First, we have method to take an actual value of Conversions metric.. `getConversionsValue()`
https://github.com/googleads/google-ads-php/blob/a64b0066b4aae086b39866a89a9013d44fbe2d46/src/Google/Ads/GoogleAds/V1/Common/Metrics.php#L3926-L3929

You might know that there's Conversions Value metric and in the last release this similarity made a mess, well this time this is not such an extreme problem but it creates a problem when we're willing to get a value of Conversions Value metric...
https://github.com/googleads/google-ads-php/blob/a64b0066b4aae086b39866a89a9013d44fbe2d46/src/Google/Ads/GoogleAds/V1/Common/Metrics.php#L3757-L3760
It means that `getConversionsValueValue()` method will try a `getValue()` method on a `getConversionsValue()` method, which is another metric, first and secondly, the previous method already returns value with `getValue()` method.

I really hope this makes sense. And this is not the only case, there are other similar metrics that do conflict just like this.

**Comment by Raibaz** [comment]
Yep, it does make sense, thanks a lot for spotting this.

(And BTW, thanks a lot also for the answers you've been giving lately on other issues on this client library, you've been very helpful!)

We're currently working on a conclusive solution for this issue, what we released now is just a temporary fix; we may be doing an intermediate release, with a better temporary fix between the one we just did and the next API release, where we hope this will be fixed.

**Comment by MaksTech** [comment]
Thank you, it means a lot! Helping others makes learning process a lot easier, so it's a win-win situation :)

When approximately is gonna be the next release?

**Comment by Raibaz** [comment]
Just to give you an update; we are moving forward with a longer-term solution that will prevent issues like this from happening in future releases.

As I was mentioning in my previous comment, we may still do an intermediate release with a temporary and not perfect (but still better than the current situation) fix to have broken API requests like the one mentioned in #105 working, but we are working to have this solved with a satisfying developer experience.

**Comment by Raibaz** [comment]
This has been fixed by V2.0.0.
