### ISSUE TITLE
Incorrect parameter name- -Travel/AddPerformanceMaxForTravelGoalsCampaign.php

### ISSUE THREAD

**Issue by mehdiwihp** [googleads/google-ads-php#921]
* Client library version: `v19.2.0` 

* Google Ads API version: `V14`

Hi

There is an error in the example for adding Performance Max campaign : 

https://github.com/googleads/google-ads-php/blob/2ae4c1b81bb4792e4711dcf150faddba80e9bdf0/examples/Travel/AddPerformanceMaxForTravelGoalsCampaign.php#L305

https://github.com/googleads/google-ads-php/blob/2ae4c1b81bb4792e4711dcf150faddba80e9bdf0/examples/Travel/AddPerformanceMaxForTravelGoalsCampaign.php#L291-L310

The parameter should be **placeIds** instead of  **placeId**

Thanks

**Comment by fiboknacky** [comment]
Thanks for reporting. We'll fix this soon. 
Feel free to submit a pull request if you have time too.

**Comment by fiboknacky** [comment]
Fixed with [v20.1.0](https://github.com/googleads/google-ads-php/releases/tag/v20.1.0)
