### ISSUE TITLE
Revert LGTM! I think we should consider moving to a `handlers` variables name in another issue or something.

### ISSUE THREAD

**Issue by Marketsoption** [googleads/google-ads-php#924]
Revert LGTM! I think we should consider moving to a `handlers` variables name in another issue or something.

_Originally posted by @iuioiua in https://github.com/denoland/fresh/pull/1396#pullrequestreview-1510292765_

**Comment by Marketsoption** [comment]
> Revert LGTM! I think we should consider moving to a `handlers` variables name in another issue or something.
> 
> _Originally posted by @iuioiua in https://github.com/denoland/fresh/pull/1396#pullrequestreview-1510292765_

**Comment by iuioiua** [comment]
This is spam.
