### ISSUE TITLE
Fatal error:  "using installed/web application flow" but we want to use service account flow

### ISSUE THREAD

**Issue by theainz27** [googleads/google-ads-php#926]
Hi,

I get this error after setting up the library and trying to run the suggested test call:

php examples/BasicOperations/GetCampaigns.php --customerId myCustomerID

Fatal error: "All of 'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/web application flow. in..."

But we are wanting to use the service auth method by sending the info below in the ini file:

; For service account flow.
jsonKeyFilePath = "***************************************"
scopes = "https://www.googleapis.com/auth/adwords"
impersonatedEmail = "***********************************************"

etc

Is there some other setting in the ini file or request command or elsewhere that instructs the library to use the service account flow?

All the help we can find relates to the refreshToken method and issues around that.

Thanks

**Comment by fiboknacky** [comment]
There is only on `.ini` file used in this library.
So, you didn't change any values in the ini file, and you're sure that it's read by the library correctly?

**Comment by theainz27** [comment]
Hi, thanks for the reply. We edited the file, and originally had errors from it not being found. Once that was overcome then the file appeared to be read and we got this error stating it was using the wrong flow.
Is there a way to confirm that we read the correct file? I think we overcame the path problem by putting the file where the application was looking as we didnt have access to change the path definition of the file location.
So perhaps the wrong file is read. I will investigate.
Can you confirm there is no flag to tell the application to use the service account, and that it will use it if it gets service account credentials? If so then we are reading the wrong file?
Thanks.

**Comment by fiboknacky** [comment]
The mode is inferred by the settings you put in the ini file. It's validated [here](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/Lib/OAuth2TokenBuilder.php#L189).

**Comment by theainz27** [comment]
Great, thanks for confirming, we must have issues with the reading of the ini.

**Comment by theainz27** [comment]
Closing assuming issue is our end with ini.
