### ISSUE TITLE
how to add members to CrmBasedUserList

### ISSUE THREAD

**Issue by charliexiong** [googleads/google-ads-php#93]
In the old adwords api, the members can be added to the list by creating members with emails, like below
        // Create operation to add members to the user list based on email
        // addresses.
        $mutateMembersOperations = [];
        $mutateMembersOperation = new MutateMembersOperation();
        $operand = new MutateMembersOperand();
        $operand->setUserListId($userList->getId());

        $members = [];
        // Hash normalized email addresses based on SHA-256 hashing algorithm.
        foreach ($emails as $email) {
            $memberByEmail = new Member();
            $memberByEmail->setHashedEmail(self::normalizeAndHash($email));
            $members[] = $memberByEmail;
        }
        // Add members to the operand and add the operation to the list.
        $operand->setMembersList($members);
        $mutateMembersOperation->setOperand($operand);
        $mutateMembersOperation->setOperator(Operator::ADD);
        $mutateMembersOperations[] = $mutateMembersOperation;

        // Add members to the user list based on email addresses.
        $result = $userListService->mutateMembers($mutateMembersOperations);

There seems no similar functions to add new members to CrmBasedUserList with CRM emails in the new google ads api.

**Comment by Raibaz** [comment]
Hi,

What you say is correct, adding members to a CrmBasedUserList is not currently supported by the Google Ads API.

I'll reopen this issue if I have any further informations about if or when it will be supported, but for now I don't have a timeline for this feature, so I'm closing it.
