### ISSUE TITLE
AddAppCampaign.php error in mutateCampaigns

### ISSUE THREAD

**Issue by RoyBellingan** [googleads/google-ads-php#938]
Using  v20.1.0 https://github.com/googleads/google-ads-php/tree/v20.1.0
This example fails here https://github.com/googleads/google-ads-php/blob/main/examples/AdvancedOperations/AddAppCampaign.php#L272 
with the error that at least 2 parameter are now needed. the fix is to use
```
        $response = $campaignServiceClient->mutateCampaigns(
            $customerId, [$campaignOperation]
        );
```

**Comment by fiboknacky** [comment]
Can you try running `composer update` to upgrade the `gax-php` dependency?

**Comment by RoyBellingan** [comment]
Ok I will try asap

**Comment by RoyBellingan** [comment]
But the signature of the function is
    public function mutateCampaigns($customerId, $operations, array $optionalArgs = [])

Btw updated, and still in error

**Comment by fiboknacky** [comment]
For your information, we've rolled out two versions of source code. The latest version is called [GAPIC v2](https://developers.devsite.corp.google.com/google-ads/api/docs/client-libs/php/gapic#gapicv2).

By default, all examples [now use GAPIC v2](https://github.com/googleads/google-ads-php/blob/main/examples/AdvancedOperations/AddAppCampaign.php#L100). 
If you run examples without changing anything, they should use GAPIC v2.

GAPIC v2 clients are located at `src/Google/Ads/GoogleAds/V14/Services/Client/`.
Following all the references, you can see that GAPIC v2 [`mutateCampaigns()`](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/Client/BaseClient/CampaignServiceBaseClient.php#L415) accepts only one required parameter, which is a [`MutateCampaignRequest`](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V14/Services/MutateCampaignsRequest.php).

**Comment by RoyBellingan** [comment]
I was not aware of this new addiction, but I think the code should handle better those error while such big transition in is progress. Thank you for the assistance.

**Comment by fiboknacky** [comment]
The code examples are just an example and it's supposed to run as is. 
If we roll out breaking changes in `src/`, we surely will handle the errors.
The GAPIC v2 source code should be transparent for you too, i.e., if you [don't turn it on deliberately](https://github.com/googleads/google-ads-php/blob/main/examples/Authentication/google_ads_php.ini#L62), it should not affect your code.

If you find that it affects you in any ways, please let us know.
I'll close this issue for now.
