### ISSUE TITLE
Example AddGmailAd.php doesn't work return MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE

### ISSUE THREAD

**Issue by dpereiraegoi** [googleads/google-ads-php#94]
Hi,

When try execute the addGmailAd.php no examples/AdvancedOperations, return the follow error. I download the images and de mime_type are correct.

Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"type"}]}},{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":1},{"fieldName":"create"},{"fieldName":"type"}]}}]}

**Comment by PierrickVoulet** [comment]
Hi,

I just gave a try and it worked without any issue on my side. Did you change anything in the code before running it?

**Comment by dpereiraegoi** [comment]
Hi

No. Only add the customer_id and ad_group_id...

**Comment by PierrickVoulet** [comment]
I am still trying to reproduce. Could you please provide more information about your environment (network, proxy or not, PHP version, hardware, OS, etc)?

**Comment by dpereiraegoi** [comment]
Macbook pro 13'' i5 - MacOS Mojave - 10.14.5N
Wifi network
No proxy
PHP 7.1.23

**Comment by PierrickVoulet** [comment]
Thank you for sharing, I will give another try on my side.

In the meantime:
- Could you try running the code example [UploadImage](https://github.com/googleads/google-ads-php/blob/master/examples/Misc/UploadImage.php)?
- Could you try running the code example AddGmailAd removing the lines where the 'mime_type' attributes are set [here](https://github.com/googleads/google-ads-php/blob/master/examples/AdvancedOperations/AddGmailAd.php#L141) and [here](https://github.com/googleads/google-ads-php/blob/master/examples/AdvancedOperations/AddGmailAd.php#L155).

**Comment by dpereiraegoi** [comment]
**UploadImage.php**

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"type"}]}}]}  

**AddGmailAd.php**

ault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"type"}]}},{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":1},{"fieldName":"create"},{"fieldName":"type"}]}}]}

**Comment by PierrickVoulet** [comment]
Unfortunately I am still not able to reproduce this behavior so I need to ask your help again, could you provide us with the entire logs for each of these tests with the requests IDs?

**Comment by dpereiraegoi** [comment]
**AddGmailAd.php** 
[2019-05-29 12:59:11] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v1.services.MediaFileService/MutateMediaFiles", ClientCustomerId: 3304251648, RequestId: "8_4Z1lOULRJrtpglYIPELQ", IsFault: 1, FaultMessage: "["The MediaType does not match the actual media object's type.","The MediaType does not match the actual media object's type."]"  
[2019-05-29 12:59:11] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v1.services.MediaFileService/MutateMediaFiles
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.1.23 gapic\/ gax\/0.38.0 grpc\/1.20.0",
    "x-goog-request-params": "customer_id=3304251648",
    "developer-token": "REDACTED",
    "login-customer-id": "6152647662"
}
Request: {"customerId":"3304251648","operations":[{"create":{"type":"IMAGE"}},{"create":{"type":"IMAGE"}}]}

Response
-------
Headers: {
    "request-id": "8_4Z1lOULRJrtpglYIPELQ",
    "date": "Wed, 29 May 2019 12:59:11 GMT",
    "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"type"}]}},{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":1},{"fieldName":"create"},{"fieldName":"type"}]}}]}  
Request with ID '8_4Z1lOULRJrtpglYIPELQ' has failed.
Google Ads failure details:
        media_file_error: The MediaType does not match the actual media object's type.
        media_file_error: The MediaType does not match the actual media object's type.
MacBook-Pro-de-admin:AdvancedOperations dpereira$ 
MacBook-Pro-de-admin:AdvancedOperations dpereira$ 
MacBook-Pro-de-admin:AdvancedOperations dpereira$ 
MacBook-Pro-de-admin:AdvancedOperations dpereira$ php AddGmailAd.php 
[2019-05-29 13:11:08] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v1.services.MediaFileService/MutateMediaFiles", ClientCustomerId: 3304251648, RequestId: "4e8NoZXZ3NNMtrP3l46U9w", IsFault: 1, FaultMessage: "["The MediaType does not match the actual media object's type.","The MediaType does not match the actual media object's type."]"  
[2019-05-29 13:11:08] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v1.services.MediaFileService/MutateMediaFiles
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.1.23 gapic\/ gax\/0.38.0 grpc\/1.20.0",
    "x-goog-request-params": "customer_id=3304251648",
    "developer-token": "REDACTED",
    "login-customer-id": "6152647662"
}
Request: {"customerId":"3304251648","operations":[{"create":{"type":"IMAGE"}},{"create":{"type":"IMAGE"}}]}

Response
-------
Headers: {
    "request-id": "4e8NoZXZ3NNMtrP3l46U9w",
    "date": "Wed, 29 May 2019 13:11:08 GMT",
    "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"type"}]}},{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":1},{"fieldName":"create"},{"fieldName":"type"}]}}]}  
Request with ID '4e8NoZXZ3NNMtrP3l46U9w' has failed.
Google Ads failure details:
        media_file_error: The MediaType does not match the actual media object's type.
        media_file_error: The MediaType does not match the actual media object's type.

**UploadImage.php**

[2019-05-29 13:09:43] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v1.services.MediaFileService/MutateMediaFiles", ClientCustomerId: 3304251648, RequestId: "GfQnR_H5yVJ30rTP5Q-HLg", IsFault: 1, FaultMessage: "["The MediaType does not match the actual media object's type."]"  
[2019-05-29 13:09:43] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v1.services.MediaFileService/MutateMediaFiles
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.1.23 gapic\/ gax\/0.38.0 grpc\/1.20.0",
    "x-goog-request-params": "customer_id=3304251648",
    "developer-token": "REDACTED",
    "login-customer-id": "6152647662"
}
Request: {"customerId":"3304251648","operations":[{"create":{"type":"IMAGE","sourceUrl":"https://goo.gl/3b9Wfh","name":"Ad Image"}}]}

Response
-------
Headers: {
    "request-id": "GfQnR_H5yVJ30rTP5Q-HLg",
    "date": "Wed, 29 May 2019 13:09:43 GMT",
    "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"mediaFileError":"MEDIA_TYPE_DOES_NOT_MATCH_MEDIA_FILE_TYPE"},"message":"The MediaType does not match the actual media object's type.","trigger":{"stringValue":""},"location":{"fieldPathElements":[{"fieldName":"operations","index":0},{"fieldName":"create"},{"fieldName":"type"}]}}]}  
Request with ID 'GfQnR_H5yVJ30rTP5Q-HLg' has failed.
Google Ads failure details:
        media_file_error: The MediaType does not match the actual media object's type.

**Comment by PierrickVoulet** [comment]
Thank you for sharing all this. I eventually reproduced the issue today switching my environment to the C implementation of the gRPC/Protobuf.

Could you confirm if the gRPC PHP extension you are using is managed by PECL (C implementation) or Composer (PHP native implementation)?

**Comment by dpereiraegoi** [comment]
The extensions installed are:

extension=grpc.so
extension=protobuf.so

Installed packages, channel pecl.php.net:
=========================================
Package  Version State
grpc     1.20.0  stable
protobuf 3.7.1   stable

**Comment by PierrickVoulet** [comment]
Alright, could you:
- Remove `extension=protobuf.so` from your php.ini
- Update the dependencies using Composer (run `composer update` from the root directory of the repository)
- Run the code examples

**Comment by dpereiraegoi** [comment]
Works!! Thanks ;)
