### ISSUE TITLE
Where to place google_ads_php.ini configuration file in the server live project ?

### ISSUE THREAD

**Issue by khushal21** [googleads/google-ads-php#949]
Hello everyone,
I am creating an application to view the campaign data using Google ads PHP client library. In localhost the code is working fine and also showing required result. But when I hosted project on server various error where found due to the mismatch in path of google_ads_php.ini config file. Error are below

```
PHP Fatal error:  Uncaught InvalidArgumentException: Config file not found as specified: 'https://domainname.in/google-ads-php/google_ads_php.ini'. Home directory could not be located so it was not searched. in /home1/folder/public_html/domain_name.in/google-ads-php/src/Google/Ads/GoogleAds/Lib/ConfigurationLoader.php:72
Stack trace:
#0 /home1/folder/public_html/domain_name.in/google-ads-php/src/Google/Ads/GoogleAds/Lib/AbstractGoogleAdsBuilder.php(57): Google\Ads\GoogleAds\Lib\ConfigurationLoader->fromFile('https://domain...')
#1 /home1/folder/public_html/domainname.in/google-ads-php/GetCampaigns.php(52): Google\Ads\GoogleAds\Lib\AbstractGoogleAdsBuilder->fromFile('https://domainname...')
#2 /home1/folder/public_html/domainname.in/ga-get-campaign.php(13): Google\Ads\GoogleAds\Examples\BasicOperations\GetCampaigns::main()
#3 {main}
  thrown in /home1/folder/public_html/domainname.in/google-ads-php/src/Google/Ads/GoogleAds/Lib/ConfigurationLoader.php on line 72
```

Please help me find that how can i solve this error on server ?

**Comment by fiboknacky** [comment]
The logic is [here](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/Util/EnvironmentalVariables.php#L36).
To find your home directory, you can start by running `getenv('HOME')`. 
Once you know the home directory, you can just put your `google_ads_php.ini` there without setting anything special.
