### ISSUE TITLE
ListAccessibleCustomers send only one result

### ISSUE THREAD

**Issue by whyjonii06** [googleads/google-ads-php#95]
Hi,

With my MCC i try to get the List Accessible Customers (all of customers linked to my MCC).
But, i have only one result and it's the ID of my MCC.

**Comment by MaksTech** [comment]
[ListAccessibleCustomers](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#google.ads.googleads.v1.services.CustomerService.ListAccessibleCustomers) does not return customers linked to MCC acount but only Google Ads accounts that are linked to your "personal" Google account. You can check those (or "that" in your case) by clicking on your account picture in upper right corner in Google Ads. 

If you want to get linked customers to MCC account, you will have to do [Query search](https://developers.google.com/google-ads/api/docs/query/overview) from [CustomerClient](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.CustomerClient) resource.

Here's my query:
```sql
SELECT
    customer_client.resource_name,
    customer_client.level,
    customer_client.hidden
FROM
    customer_client
WHERE
    customer_client.hidden != TRUE
ORDER BY
    customer_client.level ASC
LIMIT
    1000
```

If you want to get more details, like Descriptive name of all those customers, you will have to do a query on each of those retrieved Customers that you just got from request. And here's the way I do it:

```sql
SELECT
    customer.currency_code,
    customer.descriptive_name,
    customer.time_zone,
    customer.manager
FROM
    customer
ORDER BY
    customer.descriptive_name DESC
LIMIT
    100
```

Hope this helps! :)

**Comment by Raibaz** [comment]
Also note that you can filter out manager accounts in the second query by filtering it like this:
```sql
    SELECT
        customer.currency_code,
        customer.descriptive_name,
        customer.time_zone,
        customer.manager
    FROM
        customer
    WHERE
        customer.manager = false
    LIMIT
        100
```

This way you don't have to rely on exception catching to filter results.

**Comment by chiragvels** [comment]
Hi @Raibaz,

We cant do any filtering using PHP Ads API, It is there under the doc that this metrics are filterable but we cant get result If we use like this

```
SELECT
                            customer_client.resource_name,
                            customer_client.client_customer,
                            customer_client.hidden,
                            customer_client.level
                        FROM
                           customer_client'
WHERE customer.test_account != TRUE';
```

**Comment by Raibaz** [comment]
What errors are you getting? Also note that your GAQL query has a couple of syntax errors, which may be causing your issue.

**Comment by chiragvels** [comment]
Hello @Raibaz ,

Here is the forum post where Mike is also able to reproduce the same error.
https://groups.google.com/forum/#!msg/adwords-api/LAW0JsNwpP0/504PF5cuBQAJ

The error is :

> 
> Response
> -------
> Headers: {
>     "request-id": "oG8syN-JVV_9qDOQCb2e-w",
>     "date": "Wed, 05 Jun 2019 06:53:07 GMT",
>     "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""
> }
> 
> Fault
> -------
> Status code: 13
> Details: Internal error encountered.
> Failure: {}  



Thanks,

**Comment by Raibaz** [comment]
Yep i also noticed it's a bug with the API that occurs when filtering on customer.test_account.

I'll close this issue for now as it's no longer related to the client library.
