### ISSUE TITLE
Update issues v12 to lastest

### ISSUE THREAD

**Issue by publish-web** [googleads/google-ads-php#953]
* Client library version: `v17.1`
* Google Ads API version: `V12`

Ubuntu 21.10

Hi,

I have some issues when I try to update google-ads-php.

Here is what I do :

- remove the vendor/googleads/google-ads-php/ directory

- git clone https://github.com/googleads/google-ads-php.git
- cd google-ads-php
- composer require googleads/google-ads-php

And I have this error :

> Using version ^21.0 for googleads/google-ads-php
> Root package 'googleads/google-ads-php' cannot require itself in its composer.json

Can you help me please ?

Thank you!

**Comment by fiboknacky** [comment]
You don't need to remove the `google-ads-php` directory.
Instead, what you should is just running `composer update` from your project directory.

As the error message describes, you're requiring the library inside itself, which is wrong.

**Comment by publish-web** [comment]
Thanks for your answer!

This is what I've done following your advice :

- cd google-ads-php
- composer update

But it returns :

> Nothing to install, update or remove

In the composer.json file, I can see "17.1" and this my current library version :
```
{
    "require": {
        "grpc/grpc": "^1.38",
        "google/protobuf": "^3.17",
        "googleads/google-ads-php": "^17.1"
    }
}
```
But I'm trying to update to 21.0, should I edit this file manually?

**Comment by fiboknacky** [comment]
Nope. Please don't cd into the `google-ads-php` folder.
You should do this at your own project directory (the parent of `vendor`)

**Comment by publish-web** [comment]
I finished to figure it out on my own, it works now! Thanks for your help!
