### ISSUE TITLE
Where are the Reporting examples?

### ISSUE THREAD

**Issue by Globerada** [googleads/google-ads-php#954]
Hi team.

Why you have removed all the examples from Reporting?

There were deleted on this commit: https://github.com/googleads/google-ads-php/pull/950

Also, [404 here on the docs](https://developers.google.com/google-ads/api/samples/get-keyword-stats?hl=es-419)

**Comment by MrVlad001** [comment]
same question

**Comment by AnashOommen** [comment]
Hi, please refer to https://github.com/googleads/google-ads-php/blob/8372d9f7551240e70fbe569a12d7e12f8fe0c324/examples/BasicOperations/GetKeywords.php for now. We are in the middle of a code example + guide rework.

**Comment by fiboknacky** [comment]
As the question is answered, I close this issue for now.
