### ISSUE TITLE
Data from the predefined reports

### ISSUE THREAD

**Issue by MrVlad001** [googleads/google-ads-php#955]
Hello is it possible to get a data from the predefined reports like on screenshot. 

![image](https://github.com/googleads/google-ads-php/assets/5904699/75540122-b07d-481d-979e-b3a54d4afe5b)

I can't find similar examples, thanks

**Comment by fiboknacky** [comment]
Your question is related to the Google Ads API in general.
Could you please ask on [the Google Ads API forum](https://groups.google.com/forum/?nomobile=true&pli=1#!forum/adwords-api)? Thanks.
