### ISSUE TITLE
How do I get data in catch block?

### ISSUE THREAD

**Issue by 0x1881** [googleads/google-ads-php#960]
I'm currently using mutate operations and performing mutate operations on ad groups. While in the try-catch block, how can I access the data when the error is caught?

### Ex: 
`try {
    // mutate operations
} catch (ApiException $apiException) {
    printf(
        "ApiException was thrown with message '%s'.%s",
        $apiException->getMessage(),
        PHP_EOL
    );
}`

**Comment by fiboknacky** [comment]
What "data" do you want to retrieve? 
All you can access is what's available as a public method in [this class](https://github.com/googleapis/gax-php/blob/main/src/ApiException.php).
