### ISSUE TITLE
GetAdGroupSimulation example

### ISSUE THREAD

**Issue by dpereiraegoi** [googleads/google-ads-php#97]
Hi,
Can create an example for simulations?

I try to obtain ad group simulation but return an error.

https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.AdGroupSimulation

Method Name: /google.ads.googleads.v1.services.AdGroupSimulationService/GetAdGroupSimulation
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.1.23 gapic\/ gax\/0.38.0 grpc\/1.20.0",
    "x-goog-request-params": "resource_name=customers\/2503074041\/adGroupSimulations\/70859416557~BID_MODIFIER~DEFAULT~2019-05-01~2019-12-12",
    "developer-token": "REDACTED",
    "login-customer-id": "6152647662"
}
Request: {"resourceName":"customers/2503074041/adGroupSimulations/70859416557~BID_MODIFIER~DEFAULT~2019-05-01~2019-12-12"}

Response
-------
Headers: {
    "request-id": "upuKOcv5n45Ex7e0hvfqIg",
    "date": "Mon, 27 May 2019 13:42:45 GMT",
    "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""
}

Fault
-------
Status code: 5
Details: Requested entity was not found.
Failure: {"errors":[{"errorCode":{"requestError":"BAD_RESOURCE_ID"},"message":"'2019-05-01' part of the resource name is invalid."}]}  
Request with ID 'upuKOcv5n45Ex7e0hvfqIg' has failed.
Google Ads failure details:
        request_error: '2019-05-01' part of the resource name is invalid.

**Comment by Raibaz** [comment]
Hi, can you please paste the code block that you use to request the ad group simulation?

The resource name in your logs seems a bit weird but i'm not sure if it's because of an issue with copying and pasting the logs or with how you are trying to retrieve the ad group simulations.
