### ISSUE TITLE
Micros gets rounded and causes API error

### ISSUE THREAD

**Issue by mdworkin21** [googleads/google-ads-php#977]
**Your client library and Google Ads API versions:**

* Client library version: `18.0.0`

* Google Ads API version: `13`

**Your environment:**

<span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">================= PHP GENERAL INFORMATION</span><div class="center" style="text-align: center; color: rgb(34, 34, 34); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
PHP Version 8.1.26

</div><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">================= PHP EXTENSION INFORMATION The PHP Extension grpc is installed: 1.44.0 The PHP Extension protobuf is installed: 3.19.4</span>

**Description of the bug:**
Recently I've been getting the following error when trying to update target_cpa_micros: `currencyError":"VALUE_NOT_MULTIPLE_OF_BILLABLE_UNIT` What seems to be happening is that the int is slightly rounded down, which changes it to a non-billable unit. Here's an example. I pass 2070000 but in the API logs it shows: 2069999, causing the error. 

**Steps to reproduce:**
This doesn't happen every time, just sporadically. It's hard to tell, but I think it only happens when the micros passed in has an odd number before the rest of the zeros.

**Expected behavior:**
Expected behavior is that it doesn't change the micros at all, and the update goes through.

**Request/Response Logs:**

![Screenshot 2023-12-19 at 9 47 45 AM](https://github.com/googleads/google-ads-php/assets/32579329/32d8962f-c02c-4305-ae4a-1a6a6c6e4698)

 
**Anything else we should know about your project / environment:**

**Comment by fiboknacky** [comment]
Hello there,

> This doesn't happen every time, just sporadically. It's hard to tell, but I think it only happens when the micros passed in has an odd number before the rest of the zeros.

So, is it possible to reproduce the issue using this condition? 
And what environment are you using? Linux, Windows, or Mac?

**Comment by mdworkin21** [comment]
Hi, thanks for getting back to me. We have a Linux environment.

When I said it doesn't happen everytime, I should have clarified, it doesn't happen every time we try to update a tcpa. We have been successfully doing that for a while, but this error is somewhat new. You can try to reproduce it by passing 2070000 as the target_cpa_micros, or 2030000. Those have been frequently causing issues for us.

**Comment by fiboknacky** [comment]
I'm using the same set of extension versions, but unfortunately, I couldn't reproduce the issue after several trials.

**Comment by mdworkin21** [comment]
Hmm, ok, thank you for looking into it. Could there maybe be a problem with large integers getting rounded for some reason?

**Comment by mdworkin21** [comment]
This seems to have stopped happening, though I'm not sure why (since we didn't change anything). In any case, I think we can close this.

**Comment by fiboknacky** [comment]
Thanks for sharing!
