### ISSUE TITLE
ResourceNames class missing entities

### ISSUE THREAD

**Issue by projectyang** [googleads/google-ads-php#98]
Noticed [ResourceNames.php](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Util/V1/ResourceNames.php) is currently missing entities. (e.g. ExtensionFeedItemServiceClient)

Happy to volunteer and finish adding the rest.

**Comment by Raibaz** [comment]
Hi, thanks for spotting this: yes we are aware that the ResourceNames class is far from complete and it lacks functions for several resources, so if you could send a PR adding the ones you need we'd really appreciate it :)

**Comment by Raibaz** [comment]
Fixed by #100.
