### ISSUE TITLE
membership_life_span cannot be set for FlexibleRuleUserList

### ISSUE THREAD

**Issue by laurachevalier4** [googleads/google-ads-php#980]
`membership_life_span` cannot be set for `FlexibleRuleUserList`. We should update the `add_flexible_rule_user_list` example to remove the line that sets this to 365, as this value is ignored for this type of user list. This value is set to a default value of 540 for `FlexibleRuleUserList` regardless of user-provided value. This is a special case that doesn't apply to other list types, so no need to update other examples.

**Comment by ephbaum** [comment]
I don't think this right. It seems that the API _should_ allow this update according to [documentation](https://developers.google.com/google-ads/api/reference/rpc/v15/UserList#membership_life_span). I believe this is actually a bug in the API that needs to be addressed upstream.

**Comment by laurachevalier4** [comment]
Hey @ephbaum! Unfortunately the documentation needs to be updated as well – I've been in talks with the team to make that happen, after confirming that this behavior is intended. The docs should state that `membership_life_span` will be ignored for `logical_user_lists` and [`rule_based_user_lists`](https://developers.google.com/google-ads/api/reference/rpc/v15/RuleBasedUserListInfo), and automatically set to the [maximum membership duration](https://support.google.com/google-ads/answer/2472738) (540 days). Any exclusion logic is handled by the [rules](https://developers.google.com/google-ads/api/reference/rpc/v15/FlexibleRuleUserListInfo#exclusive_operands[]) themselves.

In the UI for rule-based user lists, what you see is values set through inclusion and exclusion rules. For example, in the [screenshot shared in issue #969](https://github.com/googleads/google-ads-php/issues/969#issue-1984122312), the way you would set the value seen under the "Exclude..." header is to set `lookback_window_days` on the [exclusive operands](https://developers.google.com/google-ads/api/reference/rpc/v15/FlexibleRuleUserListInfo#exclusive_operands[]). In the code example, that would mean updating [this line](https://github.com/googleads/google-ads-php/blob/main/examples/Remarketing/AddFlexibleRuleUserList.php#L154) similar to how it's done for the inclusive operands.  I achieve the following 
![image](https://github.com/googleads/google-ads-php/assets/15260006/5685502d-a5f7-448e-91bf-8c2df3cb3784)
by updating the exclusive operand code to:
```
'exclusive_operands' => [
                new FlexibleRuleOperandInfo(['rule' => $userVisitedSite3RuleInfo]),
                'lookback_window_days' => 365
            ]
```
