### ISSUE TITLE
phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.1.25) does not satisfy that requirement.

### ISSUE THREAD

**Issue by Enkirch** [googleads/google-ads-php#988]
Hi, 
when I clone the whole thing here and do "composer install", I get the following message.

`phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.1.25) does not satisfy that requirement.`

Why is PHP 8 not ok now, since the whole thing should only run on PHP 8.1 from March?

**Comment by fiboknacky** [comment]
You probably need to upgrade your `phpunit`. From the error message, it looks like those versions require `^7.1`, which caps the PHP version to only 7.x. Later versions of `phpunit` seem to specify the same as this library, e.g., `>=8.0`, which allows any version larger than `8.0`, for example.
