### ISSUE TITLE
Hi Google support,

### ISSUE THREAD

**Issue by sathyaswetha** [googleads/google-ads-php#992]
![Screenshot from 2024-02-01 16-35-19](https://github.com/googleads/google-ads-php/assets/47313773/7edfed59-5ff4-4eee-8d3c-10fe21d36c9d)
We are developing an integration where we are using the following code to fetch the "Accessible List of customers" and we have
a UI where we list these customers (accounts). But the code is giving onlty the ID as resourceName response. The id would not make
for a good UI experience while our customers select the account. So could yoh help us with how we must frame the code to get the
expected response.

**Comment by fiboknacky** [comment]
Closing as the solution is provided.
